# -*- coding: utf-8 -*-
# -*- mode: python; python-indent-offset: 4 -*-
#
# Based on "Betongteknisk ordlista: Svensk-engelsk", Betongrapport 17-2012, TNC 103
#          "Glossary of Concrete Terms: Swedish-English"
#
# ISBN: 780171961037
#
#
# 2026-05-28
#
# G. Q. Maguire Jr.
#
# Notes:
# 
#
# Abbreviations used:
#  CEFR   Common European Framework of Reference for Languages: Learning, teaching, assessment.
#  POS    Part Of Speech
betongteknisk_words={
    # Delmaterial till betong
    'aluminacement': {'C2': 'Noun', 'n': 'Alumina cement (or high-alumina cement)'},
    'anläggningscement': {'C2': 'Noun', 'n': 'Civil engineering cement (or infrastructure cement)'},
    'bascement': {'C2': 'Noun', 'n': 'Basic/Standard cement (specifically Portland-limestone or Portland-fly ash cement)'},
    'bindemedel': {'C2': 'Noun', 'n': 'Binder (or binding agent)'},
    'bindetid': {'C2': 'Noun', 'n': 'Setting time'},
    'bindning': {'B2': 'Noun', 'n': 'Setting (or binding)'},
    'blandcement': {'C2': 'Noun', 'n': 'Blended cement (or composite cement)'},
    'bränd skiffer': {'C2': 'Noun phrase', 'n': 'Burnt shale'},
    'bulkcement': {'C2': 'Noun', 'n': 'Bulk cement'},
    'byggcement': {'C2': 'Noun', 'n': 'Construction cement'},
    'CEM I': {'C2': 'Acronym', 'n': 'Pure Portland cement'},
    'CEM II': {'C2': 'Acronym', 'n': 'Portland-composite cement'},
    'CEM III': {'C2': 'Acronym', 'n': 'Blast furnace slag cement'},
    'CEM IV': {'C2': 'Acronym', 'n': 'Pozzolanic cement'},
    'CEM V': {'C2': 'Acronym', 'n': 'Composite cement'},
    'cement': {'B1': 'Noun', 'n': 'Cement'},
    'cementhållfasthet': {'C2': 'Noun', 'n': 'Cement strength'},
    'cementklinker': {'C2': 'Noun', 'n': 'Cement clinker'},
    'cementpasta': {'C2': 'Noun', 'n': 'Cement paste'},
    'cementtillsats': {'C2': 'Noun', 'n': 'Cement additive (or admixture)'},
    'cementtyp': {'C2': 'Noun', 'n': 'Cement type'},
    'falsk bindning': {'C2': 'Noun phrase', 'n': 'False set'},
    'falsk snabbbindning': {'C2': 'Noun phrase', 'n': 'Severe false set'},
    'granulerad masugnsslagg': {'C2': 'Noun phrase', 'n': 'Granulated blast furnace slag (GGBS)'},
    'huvudbeståndsdel': {'C2': 'Noun', 'n': 'Main constituent'},
    'hydrationsvärme': {'C2': 'Noun', 'n': 'Heat of hydration'},
    'hydratiserat cement': {'C2': 'Noun phrase', 'n': 'Hydrated cement'},
    'hydrauliskt bindemedel': {'C2': 'Noun phrase', 'n': 'Hydraulic binder'},
    'hållfasthetsklass': {'C2': 'Noun', 'n': 'Strength class'},
    'hårdnande': {'C1': 'Noun, Present Participle', 'n': 'Hardening'},
    'injekteringscement': {'C2': 'Noun', 'n': 'Grouting cement'},
    'kalciumaluminatcement': {'C2': 'Noun', 'n': 'Calcium aluminate cement'},
    'kalkrik flygaska': {'C2': 'Noun phrase', 'n': 'High-calcium fly ash'},
    'kalksten': {'C1': 'Noun', 'n': 'Limestone'},
    'karbonatisering': {'C2': 'Noun', 'n': 'Carbonation'},
    'kiselrik flygaska': {'C2': 'Noun phrase', 'n': 'Siliceous fly ash'},
    'kompositcement': {'C2', 'Noun', 'n': 'Composite cement'},
    'kromareduktion': {'C2': 'Noun', 'n': 'Chromium reduction'},
    'LA': {'C2': 'Acronym', 'n': 'Low Alkali'},
    'Le Chatelier-provning': {'C2': 'Proper Noun, Technical Test Name'},
    'LH': {'C2': 'Acronym', 'n': 'Low Heat'},
    'LH-cement': {'C2': 'Noun', 'n': 'Low Heat cement'},
    'låg värmeutveckling': {'C2': 'Noun phrase', 'n': 'Low heat development'},
    'lågalkaliskt': {'C1': 'Adjective', 'n': 'Low-alkali'},
    'långsamt hårdnande cement': {'C2': 'Noun phrase', 'n': 'Slow-hardening cement'},
    'malfinhet': {'C2': 'Noun', 'n': 'Fineness of grinding'},
    'MH': {'C2': 'Acronym', 'n': 'Modrate Heat'},
    'mikrocement': {'C2': 'Noun', 'n': 'Microcement'},
    'mindre beståndsdel': {'C2': 'Noun phrase', 'n': 'Minor constituent'},
    'moderat värmeutveckling': {'C2': 'Noun phrase', 'n': 'Moderate heat development'},
    'mucement': {'C2': 'Noun', 'n': 'Masonry cement'},
    'normhållfasthet': {'C2': 'Noun', 'n': 'Standard strength'},
    'portlandcementklinker': {'C2': 'Noun', 'n': 'Portland cement clinker'},
    'puzzolan': {'C2': 'Noun', 'n': 'Pozzolan'},
    'puzzolanskt material': {'C2': 'Noun phrase', 'n': 'Pozzolanic material'},
    'sammansatt portlandcement': {'C2': 'Noun phrase', 'n': 'Portland-composite cement'},
    'SH-cement': {'C2': 'Acronym', 'n': 'Rapid Hardening cement'},
    'silikastoft': {'C2': 'Noun', 'n': 'Silica fume (or silica dust)'},
    'slaggcement': {'C2': 'Noun', 'n': 'Slag cement'},
    'smältcement': {'C2': 'Noun', 'n': ' Fused cement (another name for Alumina cement)'},
    'snabbcement': {'C2': 'Noun', 'n': 'Fast-setting cement'},
    'snabbhårdnande cement': {'C2': 'Noun phrase', 'n': 'Rapid-hardening cement'},
    'specifik yta': {'C2': 'Noun phrase', 'n': 'Specific surface area (typically Blaine fineness)'},
    'SR': {'C2': 'Acronym', 'n': 'Sulfate Resistant'},
    'sulfatresistent cement': {'C2': 'Noun', 'n': 'Sulfate-resistant cement'},
    'säckcement': {'C2': 'Noun', 'n': 'Bagged cement'},
    'tidig hållfasthet': {'C2': 'Noun phrase', 'n': 'Early strength'},
    'Vicat-apparat': {'C2': 'Proper Noun, Equipment Name', 'n': 'Vicat apparatus'},
    'vitcement': {'C2': 'Noun', 'n': 'White cement'},
    'volymbeständighet': {'C2': 'Noun', 'n': 'Soundness (or volume stability)'},
    'värmeutveckling': {'C1': 'Noun', 'n': 'Heat development'},

    # Ballast för betongtillverkning
    'ballast': {'C2': 'Noun', 'n': 'Aggregate'},
    'filler': {'C2': 'Noun', 'n': 'Filler'},
    'fin ballast': {'C2': 'Noun phrase', 'n': 'Fine aggregate'},
    'finhetsmodul': {'C2': 'Noun', 'n': 'Fineness modulus'},
    'finmaterial': {'C2': 'Noun', 'n': 'Fine material (or fines)'},
    'flisighetindex': {'C2': 'Noun', 'n': 'Flakiness index'},
    'fraktion': {'C1': 'Noun', 'n': 'Fraction'},
    'grov ballast': {'C2': 'Noun phrase', 'n': 'Coarse aggregate'},
    'hyttsten': {'C2': 'Noun', 'n': 'Air-cooled blast-furnace slag'},
    'industriellt framställd balast': {'C2': 'Noun phrase', 'n': 'Manufactured aggregate'},
    'korndensitet': {'C2': 'Noun', 'n': 'Particle density'},
    'kornform': {'C2': 'Noun', 'n': 'Particle shape'},
    'kornfraktion': {'C2': 'Noun', 'n': 'Particle fraction'},
    'kornfördelning': {'C2': 'Noun', 'n': 'Particle size distribution'},
    'kornkurva': {'C2': 'Noun', 'n': 'Grading curve (or particle size curve)'},
    'kornstorlek': {'C2': 'Noun', 'n': 'Grain size (or particle size)'},
    'kornstorleksfördelning': {'C2': 'Noun', 'n': 'Grain size distribution'},
    'krosstyegrad': {'C2': 'Noun', 'n': 'Crushed particle ratio (or degree of crushing)'},
    'LT-index': {'C2': 'Noun', 'n': 'Length-thickness index'},
    'lättballast': {'C2': 'Noun', 'n': 'Lightweight aggregate'},
    'lättklinker': {'C2': 'Noun', 'n': 'Expanded clay aggregate'},
    'makadam': {'B2': 'Noun', 'n': 'Crushed stone (or macadam)'},
    'naturlig ballast': {'C2': 'Noun phrase', 'n': 'Natural aggregate'},
    'partiklelsprång': {'C2': 'Noun', 'n': 'Particle gap (or gap-grading indicator)'},
    'smatagen ballast': {'C2': 'Noun phrase', 'n': 'Pit-run aggregate (or pit-extracted aggregate)'},
    'sortering': {'B2': 'Noun', 'n': 'Grading (or sorting)'},
    'stenmjöl': {'B2': 'Noun', 'n': 'Rock dust (or stone dust)'},
    'tung ballast': {'C2': 'Noun phrase', 'n': 'Heavyweight aggregate'},
    'ungstorkad korndensitet': {'C2': 'Noun phrase', 'n': 'Oven-dried particle density'},
    'underkorn': {'C2': 'Noun', 'n': 'Undersize particles'},
    'återvunnen ballast': {'C2': 'Noun phrase', 'n': 'Recycled aggregate'},
    'överkorn': {'C2': 'Noun', 'n': 'Oversize particles'},

    # Vatten för betongtillverkning
    'hårdhet': {'B2': 'Noun', 'n': 'Hardness'},
    'hårt vatten': {'B1': 'Noun phrase', 'n': 'Hard water'},
    'medelhårt vatten': {'B2': 'Noun phrase', 'n': 'Moderately hard water'},
    'mjuk vatten': {'B1': 'Noun phrase', 'n': 'Soft water'},
    'återvunnet vatten': {'C2': 'Noun phrase', 'n': 'Recycled water'},

    # Tillsatsmedel till betong
    'accelerande tillsatsmedel': {'C2': 'Noun phrase', 'n': 'Accelerating admixture'},
    'antiutvaskningdmedel': {'C2': 'Noun', 'n': 'Anti-washout admixture'},
    'AUV-tillsatsmedel': {'C2': 'Noun', 'n': 'Anti-washout admixture (AUV-admixture)'},
    'expanderande tillsatsmedel': {'C2': 'Noun phrase', 'n': 'Expanding admixture'},
    'flyttillsatsmedel': {'C2': 'Noun', 'n': 'Superplasticizing admixture'},
    'fryspunktsnande tillsatsmedel': {'C2': 'Noun phrase', 'n': 'Freezing-point depressing admixture'},
    'inhibitor mot rost': {'C2': 'Noun phrase', 'n': 'Corrosion inhibitor'},
    'krympkompenserande tillsatsmedel': {'C2': 'Noun phrase', 'n': 'Shrinkage-compensating admixture'},
    'krympreducerande tillsatsmedel': {'C2': 'Noun phrase', 'n': 'Shrinkage-reducing admixture'},
    'luftportbildande tillsatsmedel': {'C2': 'Noun phrase', 'n': 'Air-entraining admixture'},
    'plasticerare': {'C2': 'Noun', 'n': 'Plasticizer (Water-reducing admixture)'},
    'retarderand tillsatsmedel': {'C2': 'Noun phrase', 'n': 'Retarding admixture'},
    'skumbildande tillsatsmedel': {'C2': 'Noun phrase', 'n': 'Foaming admixture'},
    'sprutbetongaccelerator': {'C2': 'Noun', 'n': 'Shotcrete accelerator'},
    'stabiliserande tillsatsmedel': {'C2': 'Noun phrase', 'n': 'Stabilizing admixture'},
    'superplasticerare': {'C2': 'Noun', 'n': 'Superplasticizer (High-range water reducer)'},
    'tillsatsmedel': {'C2': 'Noun', 'n': 'Admixture'},
    'tätande tillsatsmedel': {'C2': 'Noun phrase', 'n': 'Water-resisting (or permeability-reducing) admixture'},
    'vattenruderande tillsatsmedel': {'C2': 'Noun phrase', 'n': 'Water-reducing admixture'},

    # Tillsatsmaterial
    'aktivitersindex': {'C2': 'Noun', 'n': 'Activity index'},
    'bränd skiffer': {'C2': 'Noun phrase', 'n': 'Burnt shale'},
    'effektivitetsfaktor': {'C2': 'Noun', 'n': 'Efficiency factor (k-value)'},
    'flyaska': {'C2': 'Noun', 'n': 'Fly ash'},
    'glasfiller': {'C2': 'Noun', 'n': 'Glass filler'},
    'granulerad masugnsslagg': {'C2': 'Noun phrase', 'n': 'Granulated blast-furnace slag'},
    'kalkstenfiller': {'C2': 'Noun', 'n': 'Limestone filler'},
    'metakaolin': {'C2': 'Noun', 'n': 'Metakaolin'},
    'puzolan': {'C2': 'Noun', 'n': 'Pozzolan'},
    'silikaslurry': {'C2': 'Noun', 'n': 'Silica slurry'},
    'silikastoft': {'C2': 'Noun', 'n': 'Silica fume'},
    'tillsatsmaterial': {'C2': 'Noun', 'n': 'Addition (Supplementary cementitious material)'},
    'tillsatsmaterial av typ I': {'C2': 'Noun phrase', 'n': 'Type I addition (Nearly inert material)'},
    'tillsatsmaterial av typ II': {'C2': 'Noun phrase', 'n': 'Type II addition (Pozzolanic or latent hydraulic material)'},

    # Armering
    ## Allmänt
    'amering': {'C2': 'Noun', 'n': 'Reinforcement (Armering)'},
    'ameringsrea': {'C2': 'Noun', 'n': 'Reinforcement area (Armeringsarea)'},
    'ameringsbeteckning': {'C2': 'Noun', 'n': 'Reinforcement designation'},
    'ameringsstål': {'C2': 'Noun', 'n': 'Reinforcing steel'},
    'ameringsstång': {'C2': 'Noun', 'n': 'Reinforcing bar (Rebar)'},
    'ameringstråd': {'C2': 'Noun', 'n': 'Reinforcement wire'},
    'bockbarhet': {'C2': 'Noun', 'n': 'Bendability'},
    'kallbearbetat ameringsstål': {'C2': 'Noun phrase', 'n': 'Cold-worked reinforcing steel'},
    'kolekvivalent': {'C2': 'Noun', 'n': 'Carbon equivalent'},
    'rostfritt stål': {'B1': 'Noun phrase', 'n': 'Stainless steel'},
    'varmvalsat ameringsstål': {'C2': 'Noun phrase', 'n': 'Hot-rolled reinforcing steel'},
    'ythårdad amering': {'C2': 'Noun phrase', 'n': 'Surface-hardened reinforcement'},
    'åldring': {'C1': 'Noun', 'n': 'Aging'},


    ## Slakarmering
    'armeringsbalk': {'C2': 'Noun', 'n': 'Reinforcement beam (Spacer rail)'},
    'armeringsenhet': {'C2': 'Noun', 'n': 'Reinforcement unit'},
    'armeringsförråd': {'C2': 'Noun', 'n': 'Reinforcement storage'},
    'armeringsinnehåll': {'C2': 'Noun', 'n': 'Reinforcement content (Ratio)'},
    'armeringskorg': {'C2': 'Noun', 'n': 'Reinforcement cage'},
    'armeringsmatta': {'C2': 'Noun', 'n': 'Reinforcement mat (Mesh sheet)'},
    'armeringsmängd': {'C2': 'Noun', 'n': 'Reinforcement quantity'},
    'armeringsnät': {'C2': 'Noun', 'n': 'Reinforcement mesh (Welded wire fabric)'},
    'armeringsring': {'C2': 'Noun', 'n': 'Reinforcement ring'},
    'armeringsritning': {'C2': 'Noun', 'n': 'Reinforcement drawing'},
    'armeringsrulle': {'C2': 'Noun', 'n': 'Roll reinforcement'},
    'armeringsskarv': {'C2': 'Noun', 'n': 'Reinforcement splice (joint)'},
    'armeringsspecifikation': {'C2': 'Noun', 'n': 'Reinforcement specification (Bar schedule)'},
    'armeringsstation': {'C2': 'Noun', 'n': 'Reinforcement bending/assembly station'},
    'armeringsstege': {'C2': 'Noun', 'n': 'Reinforcement ladder'},
    'armeringsverkstad': {'C2': 'Noun', 'n': 'Reinforcement fabrication shop'},
    'bockdorn': {'C2': 'Noun', 'n': 'Bending mandrel'},
    'bockning': {'C2': 'Noun', 'n': 'Bending'},
    'bockningsmaskin': {'C2': 'Noun', 'n': 'Bending machine'},
    'bockningsnyckel': {'C2': 'Noun', 'n': 'Bending iron (Bending wrench/hickey)'},
    'bockningsradie': {'C2': 'Noun', 'n': 'Bending radius'},
    'buntad armering': {'C2': 'Noun phrase', 'n': 'Bundled reinforcement'},
    'bygel': {'B2': 'Noun', 'n': 'Stirrup (link/tie)'},
    'bygelavstånd': {'C2': 'Noun', 'n': 'Stirrup spacing'},
    'coil': {'C2': 'Noun', 'n': 'Coil (of rebar or wire)'},
    'distansbock': {'C2': 'Noun', 'n': 'Spacer chair (Continuous support spacer)'},
    'distansbygel': {'C2': 'Noun', 'n': 'Spacer stirrup'},
    'distanshållare': {'C2': 'Noun', 'n': 'Spacer (Bar chair)'},
    'distansring': {'C2': 'Noun', 'n': 'Spacer ring'},
    'dragarmering': {'C2': 'Noun', 'n': 'Tensile reinforcement'},
    'förankring': {'C1': 'Noun', 'n': 'Anchorage'},
    'förankringslängd': {'C2': 'Noun', 'n': 'Anchorage length (Development length)'},
    'förbindelsestege': {'C2': 'Noun', 'n': 'Connection ladder (Tie ladder)'},
    'huvudarmering': {'C2': 'Noun', 'n': 'Main reinforcement'},
    'ILF': {'C2': 'Noun', 'n': 'ILF (Inläggningsfärdig armering / Ready-to-install reinforcement)'},
    'inläggningsfärdig armering': {'C2': 'Noun phrase', 'n': 'Ready-to-install reinforcement (Prefab rebar)'},
    'kallbockning': {'C2': 'Noun', 'n': 'Cold bending'},
    'kamstång': {'C2': 'Noun', 'n': 'Deformed bar (Rebar with ribs)'},
    'korsarmering': {'C2': 'Noun', 'n': 'Two-way reinforcement'},
    'kvalitetsmärkning': {'C2': 'Noun', 'n': 'Quality marking (Grade identification)'},
    'laskskarv': {'C2': 'Noun', 'n': 'Lap joint (Splicing with lap plates)'},
    'ljus rödvärme': {'C2': 'Noun phrase', 'n': 'Bright red heat (Forging temperature)'},
    'monteringsarmering': {'C2': 'Noun', 'n': 'Assembly reinforcement (Construction rebar)'},
    'najning': {'C2': 'Noun', 'n': 'Tying (Bar tying)'},
    'najningsmaskin': {'C2': 'Noun', 'n': 'Rebar tying tool (automatic gun)'},
    'najomat': {'C2': 'Noun', 'n': 'Automatic rebar tier'},
    'najtråd': {'C2': 'Noun', 'n': 'Tie wire (Binding wire)'},
    'najtång': {'C2': 'Noun', 'n': 'Pliers (Tying nippers)'},
    'nominell diameter': {'C2': 'Noun phrase', 'n': 'Nominal diameter'},
    'omlottskarv': {'C2': 'Noun', 'n': 'Lap splice'},
    'ospänd armering': {'C2': 'Noun phrase', 'n': 'Non-prestressed reinforcement'},
    'profilerad stång': {'C2': 'Noun phrase', 'n': 'Profiled/Deformed bar'},
    'relativ armeringsarea': {'C2': 'Noun phrase', 'n': 'Reinforcement ratio (Relative steel area)'},
    'rullarmering': {'C2': 'Noun', 'n': 'Roll reinforcement'},
    'skarvlängd': {'C2': 'Noun', 'n': 'Splice length (Lap length)'},
    'skjuvarmering': {'C2': 'Noun', 'n': 'Shear reinforcement'},
    'slakarmering': {'C2': 'Noun', 'n': 'Non-prestressed reinforcement (Slack reinforcement)'},
    'slät armeringsstång': {'C2': 'Noun phrase', 'n': 'Plain reinforcing bar'},
    'slät stång': {'C2': 'Noun phrase', 'n': 'Plain bar (Smooth bar)'},
    'spiralbygel': {'C2': 'Noun', 'n': 'Helical stirrup (Spiral reinforcement)'},
    'sprickarmering': {'C2': 'Noun', 'n': 'Crack control reinforcement (Anti-crack steel)'},
    'stumsvetsskarv': {'C2': 'Noun', 'n': 'Butt-welded splice'},
    'tryckarmering': {'C2': 'Noun', 'n': 'Compression reinforcement'},
    'tvärkraftsarmering': {'C2': 'Noun', 'n': 'Shear reinforcement (Transverse reinforcement)'},
    'underkantsarmering': {'C2': 'Noun', 'n': 'Bottom reinforcement (Bottom face rebar)'},
    'varmbockning': {'C2': 'Noun', 'n': 'Hot bending'},
    'ändförankring': {'C2': 'Noun', 'n': 'End anchorage'},
    'ändkrok': {'C2': 'Noun', 'n': 'End hook'},
    'överkantsarmering': {'C2': 'Noun', 'n': 'Top reinforcement (Top face rebar)'},
    'överlappsskarv': {'C2': 'Noun', 'n': 'Overlap splice'},

    ## Spännarmering
    'aktiv förankring': {'C2': 'Noun phrase', 'n': 'Live-end anchorage (Stressing anchorage)'},
    'ankarkropp': {'C2': 'Noun', 'n': 'Anchor body'},
    'ankarplatta': {'C2': 'Noun', 'n': 'Anchor plate'},
    'ankarstycke': {'C2': 'Noun', 'n': 'Anchor head (piece)'},
    'avspänning': {'C1': 'Noun', 'n': 'Relaxation (destressing)'},
    'bågankare': {'C2': 'Noun', 'n': 'Loop anchor'},
    'eftersläppning': {'C2': 'Noun', 'n': 'Draw-in (wedge slip/seating drop)'},
    'efterspänd armering': {'C2': 'Noun phrase', 'n': 'Post-tensioned reinforcement'},
    'efterspänd betong': {'C2': 'Noun phrase', 'n': 'Post-tensioned concrete'},
    'fast förankring': {'C2': 'Noun phrase', 'n': 'Dead-end anchorage (Fixed anchorage)'},
    'foderrör': {'C2': 'Noun', 'n': 'Duct (Sheathing/Sleeve)'},
    'friktionsförlust': {'C2': 'Noun', 'n': 'Friction loss'},
    'förankringsplatta': {'C2': 'Noun', 'n': 'Anchor plate'},
    'förankringsspiral': {'C2': 'Noun', 'n': 'Anchorage zone tendon spiral (Bursting component)'},
    'förespänd armering': {'C2': 'Noun phrase', 'n': 'Pre-tensioned reinforcement'},
    'förespänd betong': {'C2': 'Noun phrase', 'n': 'Pre-tensioned concrete'},
    'förspänd betong': {'C2': 'Noun phrase', 'n': 'Prestressed concrete'},
    'förspänning': {'C2': 'Noun', 'n': 'Prestressing'},
    'gängad förankring': {'C2': 'Noun phrase', 'n': 'Threaded anchorage'},
    'gängförankring': {'C2': 'Noun', 'n': 'Threaded anchorage'},
    'helgängad stång': {'C2': 'Noun phrase', 'n': 'Continuously threaded bar'},
    'Hoyer-effekten': {'C2': 'Proper Noun', 'n': 'Hoyer effect (Wedge effect in pre-tensioning bond)'},
    'kabelrör': {'C2': 'Noun', 'n': 'Tendon duct (Sheath)'},
    'kilförankring': {'C2': 'Noun', 'n': 'Wedge anchorage'},
    'loopförankring': {'C2': 'Noun', 'n': 'Loop anchorage'},
    'låsförlust': {'C2': 'Noun', 'n': 'Anchorage slip loss (Seating loss)'},
    'låsglidning': {'C2': 'Noun', 'n': 'Wedge slip'},
    'mothåll': {'C2': 'Noun', 'n': 'Abutment (Pre-tensioning bed stop)'},
    'nedspänning': {'C2': 'Noun', 'n': 'Release of prestress (De-tensioning)'},
    'passiv förankring': {'C2': 'Noun phrase', 'n': 'Dead-end anchorage (Passive anchorage)'},
    'präglad spänntråd': {'C2': 'Noun phrase', 'n': 'Indented prestressing wire'},
    'rörlig förankring': {'C2': 'Noun phrase', 'n': 'Floating anchorage (Movable anchorage)'},
    'skruvförankring': {'C2': 'Noun', 'n': 'Screw anchorage'},
    'spännarmering': {'C2': 'Noun', 'n': 'Prestressing reinforcement (Tendons)'},
    'spännbetong': {'C2': 'Noun', 'n': 'Prestressed concrete'},
    'spännförlust': {'C2': 'Noun', 'n': 'Loss of prestress'},
    'spännkabel': {'C2': 'Noun', 'n': 'Prestressing tendon (Prestressing cable)'},
    'spännkraft': {'C2': 'Noun', 'n': 'Prestressing force'},
    'spännlina': {'C2': 'Noun', 'n': 'Prestressing strand'},
    'spännlista': {'C2': 'Noun', 'n': 'Stressing schedule (Tendon elongation log)'},
    'spännstång': {'C2': 'Noun', 'n': 'Prestressing bar'},
    'spänntråd': {'C2': 'Noun', 'n': 'Prestressing wire'},
    'stegvis uppspänning': {'C2': 'Noun phrase', 'n': 'Stage prestressing'},
    'trumpet': {'B1': 'Noun', 'n': 'Trumpet (Anchorage transition flare)'},
    'trådankare': {'C2': 'Noun', 'n': 'Wire anchor'},
    'trådavskiljare': {'C2': 'Noun', 'n': 'Wire spacer (Separator)'},
    'trådhuvud': {'C2': 'Noun', 'n': 'Button head (Wire head)'},
    'uppspänning': {'C2': 'Noun', 'n': 'Tensioning (Stressing operation)'},
    'vidhäftningsförankring': {'C2': 'Noun', 'n': 'Bond anchorage'},
    'ändspiral': {'C2': 'Noun', 'n': 'End spiral (Bursting reinforcement)'},
    'överföringslängd': {'C2': 'Noun', 'n': 'Transmission length'},
    'överföringssträcka': {'C2': 'Noun', 'n': 'Transmission length'},


    ## Icke-metallisk armering
    'AFRP': {'C2': 'Noun', 'n': 'Aramid Fiber Reinforced Polymer (AFRP)'},
    'aramidfiber': {'C2': 'Noun', 'n': 'Aramid fiber'},
    'aramidfiberarmerad polymer': {'C2': 'Noun phrase', 'n': 'Aramid fiber reinforced polymer'},
    'aromatisk polyamidfiber': {'C2': 'Noun phrase', 'n': 'Aromatic polyamide fiber'},
    'CFRP': {'C2': 'Noun', 'n': 'Carbon Fiber Reinforced Polymer (CFRP)'},
    'dukvara': {'C2': 'Noun', 'n': 'Fabric product (textile sheet)'},
    'efterhärdning': {'C2': 'Noun', 'n': 'Post-curing'},
    'epoxiharts': {'C2': 'Noun', 'n': 'Epoxy resin'},
    'extrudering': {'C2': 'Noun', 'n': 'Extrusion'},
    'fiber': {'B2': 'Noun', 'n': 'Fiber'},
    'fiberarmerad polymer': {'C2': 'Noun phrase', 'n': 'Fiber reinforced polymer (FRP)'},
    'fiberhybrid': {'C2': 'Noun', 'n': 'Fiber hybrid'},
    'fibernät': {'C2': 'Noun', 'n': 'Fiber mesh'},
    'fibersplittring': {'C2': 'Noun', 'n': 'Fiber fibrillation (splitting)'},
    'fibersprutning': {'C2': 'Noun', 'n': 'Fiber spraying (chopper gun deposition)'},
    'FRP': {'C2': 'Noun', 'n': 'Fiber Reinforced Polymer (FRP)'},
    'FRP-stång': {'C2': 'Noun', 'n': 'FRP bar (FRP rebar)'},
    'FRP-system': {'C2': 'Noun', 'n': 'FRP system'},
    'garn': {'B1': 'Noun', 'n': 'Yarn'},
    'GFRP': {'C2': 'Noun', 'n': 'Glass Fiber Reinforced Polymer (GFRP)'},
    'glasfiber': {'B2': 'Noun', 'n': 'Glass fiber (fiberglass)'},
    'glasfiberarmerad polymer': {'C2': 'Noun phrase', 'n': 'Glass fiber reinforced polymer'},
    'glasomvandlingstemperatur': {'C2': 'Noun', 'n': 'Glass transition temperature'},
    'handuppläggning': {'C2': 'Noun', 'n': 'Hand lay-up'},
    'harts': {'C2': 'Noun', 'n': 'Resin'},
    'hartshalt': {'C2': 'Noun', 'n': 'Resin content'},
    'hartsinnehåll': {'C2': 'Noun', 'n': 'Resin content'},
    'härdare': {'C2': 'Noun', 'n': 'Hardener (curing agent)'},
    'härdning': {'C1': 'Noun', 'n': 'Curing (hardening)'},
    'härdplast': {'C2': 'Noun', 'n': 'Thermosetting plastic (thermoset)'},
    'impregnering': {'C2': 'Noun', 'n': 'Impregnation'},
    'kolfiber': {'B2': 'Noun', 'n': 'Carbon fiber'},
    'kolfiberarmerad polymer': {'C2': 'Noun phrase', 'n': 'Carbon fiber reinforced polymer'},
    'komposit': {'C1': 'Noun', 'n': 'Composite'},
    'kompositmaterial': {'C1': 'Noun', 'n': 'Composite material'},
    'konstfiber': {'C2': 'Noun', 'n': 'Man-made fiber (synthetic fiber)'},
    'kontinuerlig fiberarmering': {'C2': 'Noun phrase', 'n': 'Continuous fiber reinforcement'},
    'krimp': {'C2': 'Noun', 'n': 'Crimp'},
    'laminat': {'C1': 'Noun', 'n': 'Laminate'},
    'matris': {'C2': 'Noun', 'n': 'Matrix'},
    'polyesterharts': {'C2': 'Noun', 'n': 'Polyester resin'},
    'förform': {'C2': 'Noun', 'n': 'Preform (blank)'},
    'prepreg': {'C2': 'Noun', 'n': 'Prepreg (pre-impregnated fibers)'},
    'profildragning': {'C2': 'Noun', 'n': 'Pultrusion'},
    'roving': {'C2': 'Noun', 'n': 'Roving'},
    'sammanfogningsmedel': {'C2': 'Noun', 'n': 'Coupling agent (bonding agent)'},
    'stapelfiber': {'C2': 'Noun', 'n': 'Staple fiber'},
    'strängpressning': {'C2': 'Noun', 'n': 'Extrusion (pultrusion)'},
    'syntetfiber': {'C2': 'Noun', 'n': 'Synthetic fiber'},
    'termoplast': {'C2': 'Noun', 'n': 'Thermoplastic'},
    'tvärbindning': {'C2': 'Noun', 'n': 'Cross-linking'},
    'vinylesterharts': {'C2': 'Noun', 'n': 'Vinyl ester resin'},
    'våtuppläggning': {'C2': 'Noun', 'n': 'Wet lay-up'},

    ## Svetsning av armering
    'brännsvetsning': {'C2': 'Noun', 'n': 'Flash welding'},
    'bågsvetsning': {'C2': 'Noun', 'n': 'Arc welding'},
    'fixeringssvets': {'C2': 'Noun', 'n': 'Tack weld (for fixation)'},
    'häftsvets': {'C2': 'Noun', 'n': 'Tack weld'},
    'korssvets': {'C2': 'Noun', 'n': 'Cross weld (intersection weld)'},
    'laskskarv': {'C2': 'Noun', 'n': 'Lap joint (with splice plates)'},
    'motståndssvetsning': {'C2': 'Noun', 'n': 'Resistance welding'},
    'omlottskarv': {'C2': 'Noun', 'n': 'Lap joint'},
    'smältsvetsning': {'C2': 'Noun', 'n': 'Fusion welding'},
    'stuksvetsning': {'C2': 'Noun', 'n': 'Upset welding'},
    'stumsvetsskarv': {'C2': 'Noun', 'n': 'Butt-welded joint'},
    'svets': {'B2': 'Noun', 'n': 'Weld'},
    'svetsbarhet': {'C2': 'Noun', 'n': 'Weldability'},
    'svetsning': {'B2': 'Noun', 'n': 'Welding'},
    'överlappsskarv': {'C2': 'Noun', 'n': 'Overlap joint (lap splice)'},

    ## Betong och olika typer av betong
    'armerad betong': {'B2': 'Noun phrase', 'n': 'Reinforced concrete'},
    'betong': {'B1': 'Noun', 'n': 'Concrete'},
    'betongmassa': {'C2': 'Noun', 'n': 'Fresh concrete mix (or concrete mass)'},
    'bruk': {'B2': 'Noun', 'n': 'Mortar'},
    'cementbruk': {'C2': 'Noun', 'n': 'Cement mortar'},
    'hålrumsbetong': {'C2': 'Noun', 'n': 'Porous concrete (or no-fines concrete)'},
    'injekteringsbetong': {'C2': 'Noun', 'n': 'Grouting concrete'},
    'konstruktionsbetong': {'C2': 'Noun', 'n': 'Structural concrete'},
    'krympningskompenserad betong': {'C2': 'Noun phrase', 'n': 'Shrinkage-compensating concrete'},
    'lättballastbetong': {'C2': 'Noun', 'n': 'Lightweight aggregate concrete'},
    'lättklinkerbetong': {'C2': 'Noun', 'n': 'Expanded clay aggregate concrete'},
    'normal betong': {'B1': 'Noun phrase', 'n': 'Normal-weight concrete'},
    'polymermodifierad betong': {'C2': 'Noun phrase', 'n': 'Polymer-modified concrete'},
    'sandfri betong': {'C2': 'Noun phrase', 'n': 'Sand-free concrete (or no-fines concrete)'},
    'självkompakterande betong': {'C2': 'Noun phrase', 'n': 'Self-compacting concrete'},
    'självnivellerande betong': {'C2': 'Noun phrase', 'n': 'Self-leveling concrete'},
    'självtorkande betong': {'C2': 'Noun phrase', 'n': 'Self-drying concrete'},
    'SKB': {'C2': 'Noun', 'n': 'SCC (Självkompakterande betong / Self-compacting concrete)'},
    'skumbetong': {'C2': 'Noun', 'n': 'Foam concrete (or aerated concrete)'},
    'snabbtorkande betong': {'C2': 'Noun phrase', 'n': 'Rapid-drying concrete'},
    'stenfyllnadsbetong': {'C2': 'Noun', 'n': 'Cyclopean concrete (or rubble concrete)'},
    'torrbetong': {'C2': 'Noun', 'n': 'Dry-mix concrete'},
    'torrbruk': {'C2': 'Noun', 'n': 'Dry-mix mortar'},
    'tung betong': {'C2': 'Noun phrase', 'n': 'Heavyweight concrete'},
    'vibreringsfri betong': {'C2': 'Noun phrase', 'n': 'Self-compacting (vibration-free) concrete'},

    ## Proportionering av betong
    'betongrecept': {'C2': 'Noun', 'n': 'Concrete mix design (or concrete recipe)'},
    'betongsammansättning': {'C2': 'Noun', 'n': 'Concrete composition'},
    'betongspecifikation': {'C2': 'Noun', 'n': 'Concrete specification'},
    'bindemedelshalt': {'C2': 'Noun', 'n': 'Binder content'},
    'cementhalt': {'C2': 'Noun', 'n': 'Cement content'},
    'cementinnehåll': {'C2': 'Noun', 'n': 'Cement content'},
    'effektiv vattenhalt': {'C2': 'Noun phrase', 'n': 'Effective water content'},
    'ekvivalent vattencementtal': {'C2': 'Noun phrase', 'n': 'Equivalent water-cement ratio'},
    'lufthalt': {'C2': 'Noun', 'n': 'Air content'},
    'matris': {'C2': 'Noun', 'n': 'Matrix'},
    'mikrobruk': {'C2': 'Noun', 'n': 'Micro-mortar'},
    'mikrobruksfas': {'C2': 'Noun', 'n': 'Micro-mortar phase'},
    'pulver': {'A2': 'Noun', 'n': 'Powder'},
    'pulverhalt': {'C2': 'Noun', 'n': 'Powder content'},
    'pulverinnehåll': {'C2': 'Noun', 'n': 'Powder content'},
    'total vattenhalt': {'C2': 'Noun phrase', 'n': 'Total water content'},
    'vattenbindemedelstal': {'C2': 'Noun', 'n': 'Water-binder ratio'},
    'vattencementtal': {'C2': 'Noun', 'n': 'Water-cement ratio'},
    'vattenluftcementtal': {'C2': 'Noun', 'n': 'Water-air-cement ratio'},
    'vattenpulvertal': {'C2': 'Noun', 'n': 'Water-powder ratio'},

    # Förkortningar för proportionering
    'vbt': {'C2': 'Noun', 'n': 'w/b ratio (Vattenbindemedelstal)'},
    'vct': {'C2': 'Noun', 'n': 'w/c ratio (Vattencementtal)'},
    'vlct': {'C2': 'Noun', 'n': 'w/(c+a) ratio (Vattenluftcementtal)'},
    'vpt': {'C2': 'Noun', 'n': 'w/p ratio (Vattenpulvertal)'},

    ## Uppmätning och blandning
    'ballastficka': {'C2': 'Noun', 'n': 'Aggregate hopper (or storage bin)'},
    'ballastsilo': {'C2': 'Noun', 'n': 'Aggregate silo'},
    'betongblandare': {'C2': 'Noun', 'n': 'Concrete mixer'},
    'betongfabrik': {'C2': 'Noun', 'n': 'Concrete plant (or batch plant)'},
    'betongstation': {'C2': 'Noun', 'n': 'Concrete batching station'},
    'blandningstid': {'C2': 'Noun', 'n': 'Mixing time'},
    'byggplatstillverkad betong': {'C2': 'Noun phrase', 'n': 'Site-mixed concrete'},
    'cementsilo': {'C2': 'Noun', 'n': 'Cement silo'},
    'fabriksbetong': {'C2': 'Noun', 'n': 'Ready-mixed concrete'},
    'flödesmätare': {'C2': 'Noun', 'n': 'Flow meter'},
    'frifallsblandare': {'C2': 'Noun', 'n': 'Free-fall mixer (or drum mixer)'},
    'genomströmningsmätare': {'C2': 'Noun', 'n': 'Flow-through meter'},
    'kontinuerlig blandare': {'C2': 'Noun phrase', 'n': 'Continuous mixer'},
    'motströmsblandare': {'C2': 'Noun', 'n': 'Counter-current mixer'},
    'planblandare med fast behållare': {'C2': 'Noun phrase', 'n': 'Pan mixer with fixed pan'},
    'planblandare med roterande behållare': {'C2': 'Noun phrase', 'n': 'Pan mixer with rotating pan'},
    'separat vägning': {'C2': 'Noun phrase', 'n': 'Individual weigh-batching'},
    'summationsvägning': {'C2': 'Noun', 'n': 'Cumulative weigh-batching'},
    'transportblandare': {'C2': 'Noun', 'n': 'Truck mixer'},
    'trumblandare': {'C2': 'Noun', 'n': 'Drum mixer'},
    'tvångsblandare': {'C2': 'Noun', 'n': 'Compulsory mixer (or pan/paddle mixer)'},
    'viktmätning': {'C2': 'Noun', 'n': 'Weight measurement (or weigh-batching)'},
    'volymmätning': {'C2': 'Noun', 'n': 'Volume measurement (or volumetric batching)'},

    ## Betongliknande material
    'autoklaverad lättbetong': {'C2': 'Noun phrase', 'n': 'Autoclaved aerated concrete (AAC)'},
    'betong med ultralätt ballast': {'C2': 'Noun phrase', 'n': 'Ultra-lightweight aggregate concrete'},
    'cementbruksbunden ballast': {'C2': 'Noun phrase', 'n': 'Cement-bound aggregate'},
    'cementbundet grus': {'C2': 'Noun phrase', 'n': 'Cement-bound gravel'},
    'CG': {'C2': 'Noun', 'n': 'CG (Cementbundet grus / Cement-bound gravel)'},
    'gasbetong': {'C2': 'Noun', 'n': 'Gas concrete (or aerated concrete)'},
    'polymerbetong': {'C2': 'Noun', 'n': 'Polymer concrete'},
    'träullsbetong': {'C2': 'Noun', 'n': 'Wood-wool concrete'},

    ## Färsk betong
    'arbetbarhet': {'C2': 'Noun', 'n': 'Workability'},
    'cementhud': {'C2': 'Noun', 'n': 'Laitance (or cement paste skin)'},
    'eftersättning': {'C2': 'Noun', 'n': 'Delayed settlement (or secondary slump)'},
    'flytbarhet': {'C2': 'Noun', 'n': 'Fluidity (or flowability)'},
    'flytförmåga': {'C2': 'Noun', 'n': 'Flowability (or filling ability)'},
    'flytgräns': {'C2': 'Noun', 'n': 'Yield stress (or yield point)'},
    'flytsättmått': {'C2': 'Noun', 'n': 'Slump-flow measurement'},
    'gjutbarhet': {'C2': 'Noun', 'n': 'Castability'},
    'jordfuktig betong': {'C2': 'Noun phrase', 'n': 'Earth-moist concrete (or zero-slump concrete)'},
    'J-ring': {'C2': 'Noun', 'n': 'J-ring (test apparatus for self-compacting concrete)'},
    'kompakterbarhet': {'C2': 'Noun', 'n': 'Compactability'},
    'kompakteringstal': {'C2': 'Noun', 'n': 'Degree of compactability'},
    'komprimerbarhet': {'C2': 'Noun', 'n': 'Compressibility (or compactability)'},
    'komprimeringstal': {'C2': 'Noun', 'n': 'Degree of compaction'},
    'konsistens': {'C1': 'Noun', 'n': 'Consistency'},
    'konsistensförlust': {'C2': 'Noun', 'n': 'Slump loss (or loss of consistency)'},
    'konsistensklass': {'C2': 'Noun', 'n': 'Consistency class'},
    'konsistensmått': {'C2': 'Noun', 'n': 'Consistency measurement'},
    'L-låda': {'C2': 'Noun', 'n': 'L-box (test apparatus for self-compacting concrete)'},
    'passeringsförmåga': {'C2': 'Noun', 'n': 'Passing ability'},
    'plastisk viskositet': {'C2': 'Noun phrase', 'n': 'Plastic viscosity'},
    'separation': {'C1': 'Noun', 'n': 'Segregation'},
    'separationsmotstånd': {'C2': 'Noun', 'n': 'Segregation resistance'},
    'stabilitet': {'C1': 'Noun', 'n': 'Stability'},
    'sättmått': {'C2': 'Noun', 'n': 'Slump measurement'},
    'sättning': {'C1': 'Noun', 'n': 'Slump (or settlement)'},
    't500': {'C2': 'Noun', 'n': 't500 (Slump-flow time measurement)'},
    'tillstyvnadstid': {'C2': 'Noun', 'n': 'Stiffening time'},
    'utbredningsmått': {'C2': 'Noun', 'n': 'Flow table spread measurement'},
    'Vebe-tal': {'C2': 'Noun', 'n': 'Vebe time (or Vebe value)'},
    'viskositet': {'C2': 'Noun', 'n': 'Viscosity'},
    'V-trattvärde': {'C2': 'Noun', 'n': 'V-funnel flow time value'},
    'öppethållandetid': {'C2': 'Noun', 'n': 'Open time (or workable life)'},

    ## Transport till och inom arbetsplats
    'bandtransportör': {'C2': 'Noun', 'n': 'Belt conveyor'},
    'betongbask': {'C2': 'Noun', 'n': 'Concrete bucket (or skip)'},
    'betongdumper': {'C2': 'Noun', 'n': 'Concrete dumper'},
    'betongficka': {'C2': 'Noun', 'n': 'Concrete hopper (receiving hopper)'},
    'betongfördelare': {'C2': 'Noun', 'n': 'Concrete distributor'},
    'betongpump': {'C2': 'Noun', 'n': 'Concrete pump'},
    'betongränna': {'C2': 'Noun', 'n': 'Concrete chute'},
    'fördelarmast': {'C2': 'Noun', 'n': 'Placing boom (distributing mast)'},
    'gjutrör': {'C2': 'Noun', 'n': 'Tremie pipe (or pouring pipe)'},
    'gjutslang': {'C2': 'Noun', 'n': 'Pouring hose'},
    'gjuttratt': {'C2': 'Noun', 'n': 'Pouring funnel (or hopper)'},
    'kabelkran': {'C2': 'Noun', 'n': 'Cableway crane'},
    'mastpump': {'C2': 'Noun', 'n': 'Boom pump (truck-mounted concrete pump)'},
    'mobilkran': {'C2': 'Noun', 'n': 'Mobile crane'},
    'pumparbetsområde': {'C2': 'Noun', 'n': 'Pumping work area (or placement radius)'},
    'pumparbetstryck': {'C2': 'Noun', 'n': 'Pump operating pressure'},
    'pumpmast': {'C2': 'Noun', 'n': 'Placing boom (pump mast)'},
    'pumprör': {'C2': 'Noun', 'n': 'Pump pipe'},
    'pumpslang': {'C2': 'Noun', 'n': 'Pump hose'},
    'roterbil': {'C2': 'Noun', 'n': 'Concrete mixer truck (or transit mixer)'},
    'roterpump': {'C2': 'Noun', 'n': 'Mixer-mounted concrete pump (Pumi)'},
    'rörpump': {'C2': 'Noun', 'n': 'Line pump (stationary pipeline pump)'},
    'smörjsats': {'C2': 'Noun', 'n': 'Priming slurry (or lubricating mix)'},
    'stationär pump': {'C2': 'Noun phrase', 'n': 'Stationary pump (or trailer pump)'},
    'störtrör': {'C2': 'Noun', 'n': 'Drop chute (or tremie tube)'},
    'tornkran': {'C2': 'Noun', 'n': 'Tower crane'},
    'trågbil': {'C2': 'Noun', 'n': 'Open-top concrete dump truck (agitator truck)'},
    'uppmastningshöjd': {'C2': 'Noun', 'n': 'Boom reach height (unfolding height)'},
    'ändslang': {'C2': 'Noun', 'n': 'End hose (or tip hose)'},

    ## Formar för platsgjuten betong
    'avformning': {'C2': 'Noun', 'n': 'Stripping (or formwork removal)'},
    'avstängare': {'C2': 'Noun', 'n': 'Stop-end (or bulkhead)'},
    'balkform': {'C2': 'Noun', 'n': 'Beam formwork'},
    'bindregel': {'C2': 'Noun', 'n': 'Wale (or waler/tie-back rule)'},
    'bjälklagsform': {'C2': 'Noun', 'n': 'Slab formwork (or soffit formwork)'},
    'bockrygg': {'C2': 'Noun', 'n': 'Ledger (or support beam/shoring rail)'},
    'bärlagsform': {'C2': 'Noun', 'n': 'Shoring/deck formwork'},
    'distanshylsa': {'C2': 'Noun', 'n': 'Spacer sleeve'},
    'distanshållare': {'C2': 'Noun', 'n': 'Formwork spacer'},
    'distansrör': {'C2': 'Noun', 'n': 'Spacer tube'},
    'formband': {'C2': 'Noun', 'n': 'Formwork strap (or tie strap)'},
    'formbord': {'C2': 'Noun', 'n': 'Table form (or flying form)'},
    'formbyggnad': {'C2': 'Noun', 'n': 'Formwork construction (or erection)'},
    'formlucka': {'C2': 'Noun', 'n': 'Formwork panel (or shuttering shutter)'},
    'formlås': {'C2': 'Noun', 'n': 'Formwork clamp (or tie lock)'},
    'formolja': {'C2': 'Noun', 'n': 'Formwork oil'},
    'formrivning': {'C2': 'Noun', 'n': 'Stripping formwork (or dismantling)'},
    'formskiva': {'C2': 'Noun', 'n': 'Formwork board (or plywood liner)'},
    'formsläppmedel': {'C2': 'Noun', 'n': 'Form release agent'},
    'formstag': {'C2': 'Noun', 'n': 'Formwork tie (or tie rod)'},
    'formstagsbricka': {'C2': 'Noun', 'n': 'Formwork tie washer'},
    'formstagskil': {'C2': 'Noun', 'n': 'Formwork tie wedge'},
    'formstagsmutter': {'C2': 'Noun', 'n': 'Formwork tie nut'},
    'formstämp': {'C2': 'Noun', 'n': 'Formwork shore (or prop/post)'},
    'formsättning': {'C2': 'Noun', 'n': 'Formwork shuttering (or layout setting)'},
    'formtryck': {'C2': 'Noun', 'n': 'Lateral concrete pressure on formwork'},
    'gjutbrygga': {'C2': 'Noun', 'n': 'Pouring platform (or casting gantry)'},
    'gjutform': {'C2': 'Noun', 'n': 'Mould (or concrete formwork)'},
    'pelarform': {'C2': 'Noun', 'n': 'Column formwork'},
    'slitsform': {'C2': 'Noun', 'n': 'Slip-form (or narrow trench form)'},
    'strukturmatris': {'C2': 'Noun', 'n': 'Formwork liner (or textured matrix)'},
    'ställning': {'B2': 'Noun', 'n': 'Scaffolding (or falsework)'},
    'säkerhetsstämp': {'C2': 'Noun', 'n': 'Safety shore (or reshore)'},
    'ursparningsform': {'C2': 'Noun', 'n': 'Blockout formwork (or cutout box)'},
    'valvform': {'C2': 'Noun', 'n': 'Slab/arch formwork'},
    'väggform': {'C2': 'Noun', 'n': 'Wall formwork'},
    'överhöjning': {'C2': 'Noun', 'n': 'Camber (or pre-elevation)'},

    ## Gjutning och bearbetning av betong
    'avdragen yta': {'C2': 'Noun phrase', 'n': 'Screeded surface'},
    'avdragsbana': {'C2': 'Noun', 'n': 'Screed rail (or guide track)'},
    'avjämnad yta': {'C2': 'Noun phrase', 'n': 'Leveled (or smoothed) surface'},
    'bom': {'C2': 'Noun', 'n': 'Hollow sound (or delamination/void deflection)'},
    'brädriven yta': {'C2': 'Noun phrase', 'n': 'Wood-floated surface'},
    'djupvibrering': {'C2': 'Noun', 'n': 'Internal vibration (or deep consolidation)'},
    'formvibrering': {'C2': 'Noun', 'n': 'External form vibration'},
    'gjutning': {'B2': 'Noun', 'n': 'Casting (or concrete pouring)'},
    'gjutpall': {'C2': 'Noun', 'n': 'Casting platform (or step block)'},
    'glättning': {'C2': 'Noun', 'n': 'Power troweling (or power floating)'},
    'inslamningsbruk': {'C2': 'Noun', 'n': 'Slurry grout (or bonding slurry)'},
    'kompaktering': {'C2': 'Noun', 'n': 'Compaction (or consolidation)'},
    'komprimering': {'C1': 'Noun', 'n': 'Compaction'},
    'lasergjutning': {'C2': 'Noun', 'n': 'Laser-guided concrete placement'},
    'platsgjuten betong': {'C2': 'Noun phrase', 'n': 'Cast-in-place concrete (or in-situ concrete)'},
    'slodning': {'C2': 'Noun', 'n': 'Bull floating'},
    'stavvibrering': {'C2': 'Noun', 'n': 'Internal poker vibration'},
    'stighastighet': {'C2': 'Noun', 'n': 'Rate of rise (or placement rate)'},
    'stålglättning': {'C2': 'Noun', 'n': 'Steel troweling'},
    'vattenbilning': {'C2': 'Noun', 'n': 'Hydrodemolition'},
    'vibrering': {'C2': 'Noun', 'n': 'Vibration'},
    'ytvibrering': {'C2': 'Noun', 'n': 'Surface vibration'},
    'återvibrering': {'C2': 'Noun', 'n': 'Revibration'},
    'övervibrering': {'C2': 'Noun', 'n': 'Over-vibration'},

    ## Redskap och maskiner för bearbetning
    'betongglättare': {'C2': 'Noun', 'n': 'Concrete trowel (or power float)'},
    'bygglaser': {'C2': 'Noun', 'n': 'Construction laser'},
    'fogjärn': {'C2': 'Noun', 'n': 'Jointer tool (or groover)'},
    'formvibrator': {'C2': 'Noun', 'n': 'External form vibrator'},
    'glättningsmaskin': {'C2': 'Noun', 'n': 'Power trowel machine'},
    'lasermottagare': {'C2': 'Noun', 'n': 'Laser receiver'},
    'laserstyrd vibratorbalk': {'C2': 'Noun phrase', 'n': 'Laser-guided screed'},
    'rivbräda': {'C2': 'Noun', 'n': 'Plastering float (or wooden float)'},
    'ribbräda': {'C2': 'Noun', 'n': 'Straightedge rule'},
    'sloda': {'C2': 'Noun', 'n': 'Bull float'},
    'stavvibrator': {'C2': 'Noun', 'n': 'Internal poker vibrator'},
    'stålbräda': {'C2': 'Noun', 'n': 'Steel float (or steel trowel board)'},
    'vibratorbalk': {'C2': 'Noun', 'n': 'Vibrating screed beam'},
    'vibratorbord': {'C2': 'Noun', 'n': 'Vibrating table'},
    'vibratorbrygga': {'C2': 'Noun', 'n': 'Vibrating truss screed'},
    'vibratorsloda': {'C2': 'Noun', 'n': 'Power bull float'},
    'vibrobalk': {'C2': 'Noun', 'n': 'Vibrating beam screed'},
    'vibrostav': {'C2': 'Noun', 'n': 'Vibrating poker (or internal vibrator)'},

    ## Speciella gjutningsmetoder
    'arbetsplan': {'C1': 'Noun', 'n': 'Working platform (or operational execution plan)'},
    'bergförankrad sprutbetong': {'C2': 'Noun phrase', 'n': 'Rock-anchored shotcrete'},
    'betongsprutning': {'C2': 'Noun', 'n': 'Shotcreting (or concrete spraying)'},
    'filterduk': {'C2': 'Noun', 'n': 'Filter fabric (or geotextile)'},
    'formsläpp': {'C2': 'Noun', 'n': 'Form release (or clean mold break)'},
    'gitterbåge': {'C2': 'Noun', 'n': 'Lattice girder arch'},
    'gjutfront': {'C2': 'Noun', 'n': 'Flow front (or advancing concrete edge)'},
    'glidform': {'C2': 'Noun', 'n': 'Slip-form'},
    'glidformslyftare': {'C2': 'Noun', 'n': 'Slip-form jack'},
    'glidformsok': {'C2': 'Noun', 'n': 'Slip-form yoke'},
    'hängställning': {'C2': 'Noun', 'n': 'Suspended scaffolding'},
    'injektering': {'C2': 'Noun', 'n': 'Grouting (or injection filling)'},
    'injekteringsbruk': {'C2': 'Noun', 'n': 'Grout mix (or injection mortar)'},
    'insprutat drän': {'C2': 'Noun phrase', 'n': 'Drilled injection drain'},
    'jordinjektering': {'C2': 'Noun', 'n': 'Soil grouting (or compaction grouting)'},
    'klätterform': {'C2': 'Noun', 'n': 'Climbing formwork'},
    'klätterstång': {'C2': 'Noun', 'n': 'Climbing rod'},
    'klätterstångsskarvning': {'C2': 'Noun', 'n': 'Climbing rod splicing'},
    'lyftutrustning': {'C2': 'Noun', 'n': 'Lifting equipment'},
    'robotsprutning': {'C2': 'Noun', 'n': 'Robotic shotcrete spraying'},
    'rör för undervattensgjutning': {'C2': 'Noun phrase', 'n': 'Tremie pipe for underwater casting'},
    'sprickinjektering': {'C2': 'Noun', 'n': 'Crack injection'},
    'sprutbetong': {'C2': 'Noun', 'n': 'Shotcrete (or sprayed concrete)'},
    'sprutbetongbåge': {'C2': 'Noun', 'n': 'Shotcrete arch lining'},
    'sprutbetongvalv': {'C2': 'Noun', 'n': 'Shotcrete canopy (or vault lining)'},
    'sprutpåslag': {'C2': 'Noun', 'n': 'Shotcrete layer blow (or spray pass)'},
    'spännkabelinjektering': {'C2': 'Noun', 'n': 'Post-tensioning tendon duct grouting'},
    'sänkpropp': {'C2': 'Noun', 'n': 'Drop plug (or underwater placement tremie plug)'},
    'torrsprutning': {'C2': 'Noun', 'n': 'Dry-mix shotcreting'},
    'underduk': {'C2': 'Noun', 'n': 'Bottom textile matrix sheet'},
    'undervattensbetong': {'C2': 'Noun', 'n': 'Underwater concrete'},
    'undervattensgjutning': {'C2': 'Noun', 'n': 'Underwater concrete casting'},
    'utbredningsmått': {'C2': 'Noun', 'n': 'Flow table spread'},
    'vakuumbehandling': {'C2': 'Noun', 'n': 'Vacuum dewatering treatment'},
    'vakuumbetong': {'C2': 'Noun', 'n': 'Vacuum dewatered concrete'},
    'vakuumkomprimering': {'C2': 'Noun', 'n': 'Vacuum consolidation'},
    'vakuummatta': {'C2': 'Noun', 'n': 'Vacuum dewatering mat'},
    'vattengenomslag': {'C2': 'Noun', 'n': 'Water penetration (or seepage break)'},
    'våtsprutning': {'C2': 'Noun', 'n': 'Wet-mix shotcreting'},
    'återslag': {'C2': 'Noun', 'n': 'Rebound (shotcrete kickback material)'},

    ## Härdning
    'adiabatisk härdning': {'C2': 'Noun phrase', 'n': 'Adiabatic curing'},
    'autoklavering': {'C2': 'Noun', 'n': 'Autoclaving (or high-pressure steam curing)'},
    'autoklavkammare': {'C2': 'Noun', 'n': 'Autoclave chamber'},
    'avsvalningsperiod': {'C2': 'Noun', 'n': 'Cooling period'},
    'betongtemperatur': {'C2': 'Noun', 'n': 'Concrete temperature'},
    'dimsprutning': {'C2': 'Noun', 'n': 'Fog spraying (or misting)'},
    'efterhärdning': {'C2': 'Noun', 'n': 'Post-curing'},
    'elektrohärdning': {'C2': 'Noun', 'n': 'Electrical curing'},
    'folietäckning': {'C2': 'Noun', 'n': 'Plastic sheeting cover'},
    'frostskada': {'C2': 'Noun', 'n': 'Frost damage'},
    'frysskada': {'C2': 'Noun', 'n': 'Freezing injury (or frost action damage)'},
    'fukthärdning': {'C2': 'Noun', 'n': 'Moist curing (or wet curing)'},
    'förlagringsperiod': {'C2': 'Noun', 'n': 'Pre-steaming period (or delay period before curing)'},
    'härdkammare': {'C2': 'Noun', 'n': 'Curing chamber'},
    'härdning': {'C1': 'Noun', 'n': 'Curing'},
    'härdningscykel': {'C2': 'Noun', 'n': 'Curing cycle'},
    'härdningsklass': {'C2': 'Noun', 'n': 'Curing class'},
    'härdningstemperatur': {'C2': 'Noun', 'n': 'Curing temperature'},
    'härdningstid': {'C2': 'Noun', 'n': 'Curing time'},
    'isolerhärdning': {'C2': 'Noun', 'n': 'Insulated curing'},
    'kall väderlek': {'B1': 'Noun phrase', 'n': 'Cold weather conditions'},
    'kylrör': {'C2': 'Noun', 'n': 'Cooling pipe'},
    'kylslingor': {'C2': 'Noun', 'n': 'Cooling coils'},
    'lufthärdning': {'C2': 'Noun', 'n': 'Air curing'},
    'membranhärdare': {'C2': 'Noun', 'n': 'Curing compound (liquid membrane)'},
    'membranhärdning': {'C2': 'Noun', 'n': 'Membrane curing'},
    'membranhärdningsvätska': {'C2': 'Noun', 'n': 'Liquid membrane-forming curing compound'},
    'mognadsgrad': {'C2': 'Noun', 'n': 'Maturity (or degree of maturity)'},
    'resistor': {'C2': 'Noun', 'n': 'Resistor (heating element)'},
    'temperaturchock': {'C2': 'Noun', 'n': 'Thermal shock'},
    'uppvärmningsperiod': {'C2': 'Noun', 'n': 'Heating-up period'},
    'varm väderlek': {'B1': 'Noun phrase', 'n': 'Hot weather conditions'},
    'vattning': {'B2': 'Noun', 'n': 'Watering (or ponding/wetting)'},
    'vintergjutning': {'C2': 'Noun', 'n': 'Winter concreting'},
    'värmehärdning': {'C2': 'Noun', 'n': 'Heat curing (or accelerated thermal curing)'},
    'ånghärdning': {'C2': 'Noun', 'n': 'Steam curing'},

    ## Hårdnad betongs terminologi
    'arbetskurva': {'C2': 'Noun', 'n': 'Stress-strain curve (or constitutive curve)'},
    'avformningshållfasthet': {'C2': 'Noun', 'n': 'Stripping strength (or early handling strength)'},
    'avnötningshållfasthet': {'C2': 'Noun', 'n': 'Abrasion resistance strength'},
    'cylinderhållfasthet': {'C2': 'Noun', 'n': 'Cylinder compressive strength'},
    'exponeringsklass': {'C2': 'Noun', 'n': 'Exposure class'},
    'formrivningshållfasthet': {'C2': 'Noun', 'n': 'Formwork removal strength'},
    'hållfasthetsklass': {'C2': 'Noun', 'n': 'Strength class'},
    'hårdnad betong': {'C2': 'Noun phrase', 'n': 'Hardened concrete'},
    'korttidshållfasthet': {'C2': 'Noun', 'n': 'Short-term strength'},
    'krympspricka': {'C2': 'Noun', 'n': 'Shrinkage crack'},
    'kubhållfasthet': {'C2': 'Noun', 'n': 'Cube compressive strength'},
    'livslängdsklass': {'C2': 'Noun', 'n': 'Design working life class'},
    'långtidshållfasthet': {'C2': 'Noun', 'n': 'Long-term strength'},
    'nötningshållfasthet': {'C2': 'Noun', 'n': 'Wear resistance (or abrasion strength)'},
    'prägling': {'C2': 'Noun', 'n': 'Stamping (or texturing/embossing)'},
    'självläkning': {'C2': 'Noun', 'n': 'Autogenous healing (or self-healing)'},
    'skjuvhållfasthet': {'C2': 'Noun', 'n': 'Shear strength'},
    'spjälkningshållfasthet': {'C2': 'Noun', 'n': 'Splitting tensile strength'},
    'spräckhållfasthet': {'C2': 'Noun', 'n': 'Splitting strength'},
    'sättspricka': {'C2': 'Noun', 'n': 'Settlement crack'},
    'utförandeklass': {'C2': 'Noun', 'n': 'Execution class'},
    'vatteninträngningsdjup': {'C2': 'Noun', 'n': 'Depth of water penetration'},
    'ytspjälkning': {'C2': 'Noun', 'n': 'Spalling (or surface scaling)'},

    ## Egenskapsbegrepp
    '0,2-gräns': {'C2': 'Noun', 'n': '0.2% proof stress (or yield strength limit)'},
    'absorberad fukt': {'C2': 'Noun phrase', 'n': 'Absorbed moisture'},
    'adsorberad fukt': {'C2': 'Noun phrase', 'n': 'Adsorbed moisture'},
    'autogen krympning': {'C2': 'Noun phrase', 'n': 'Autogenous shrinkage'},
    'bruksskede': {'C2': 'Noun', 'n': 'Service stage (or operational life phase)'},
    'byggskede': {'C2': 'Noun', 'n': 'Construction stage'},
    'byggvarudeklaration': {'C2': 'Noun', 'n': 'Environmental product declaration (EPD) for building products'},
    'täckskikt': {'C2': 'Noun', 'n': 'Concrete cover (or protective layer thickness)'},
    'underarmerat tvärsnitt': {'C2': 'Noun phrase', 'n': 'Under-reinforced cross-section'},
    'undergjutning': {'C2': 'Noun', 'n': 'Under-grouting (or underpinning/bedding grout)'},
    'upphängningsarmering': {'C2': 'Noun', 'n': 'Suspension reinforcement (or hanger reinforcement)'},
    'vot': {'C2': 'Noun', 'n': 'Haunch (or bracket support element)'},
    'vridarmering': {'C2': 'Noun', 'n': 'Torsional reinforcement'},
    'vridspricka': {'C2': 'Noun', 'n': 'Torsional crack'},
    'överarmerat tvärsnitt': {'C2': 'Noun phrase', 'n': 'Over-reinforced cross-section'},

    ## Betongvaror
    'basmått': {'C2': 'Noun', 'n': 'Basic size (or reference dimension)'},
    'betongelement': {'C2': 'Noun', 'n': 'Precast concrete element'},
    'betongvara': {'C2': 'Noun', 'n': 'Concrete product'},
    'byggmått': {'C2': 'Noun', 'n': 'Coordinating size (or structural grid size)'},
    'byggplatstolerans': {'C2': 'Noun', 'n': 'Site tolerance'},
    'direktavformning': {'C2': 'Noun', 'n': 'Immediate stripping (or immediate demoulding)'},
    'fabrikstillverkat betongelement': {'C2': 'Noun phrase', 'n': 'Factory-precast concrete element'},
    'falsrör': {'C2': 'Noun', 'n': 'Rebated joint pipe (or ogee joint pipe)'},
    'gjutbord': {'C2': 'Noun', 'n': 'Casting table'},
    'gjutbädd': {'C2': 'Noun', 'n': 'Casting bed'},
    'gjuthall': {'C2': 'Noun', 'n': 'Precast casting shop (or casting bay)'},
    'hålbjälklag': {'C2': 'Noun', 'n': 'Hollow-core floor slab system'},
    'håldäck': {'C2': 'Noun', 'n': 'Hollow-core slab'},
    'härdningsutrymme': {'C2': 'Noun', 'n': 'Curing room (or curing enclosure space)'},
    'ingjutningsgods': {'C2': 'Noun', 'n': 'Cast-in items (or inserts / embedded parts)'},
    'isolerblock': {'C2': 'Noun', 'n': 'Insulated masonry block'},
    'långbäddsmetod': {'C2': 'Noun', 'n': 'Long-bed method'},
    'långlinjemetod': {'C2': 'Noun', 'n': 'Long-line casting method'},
    'monteringstolerans': {'C2': 'Noun', 'n': 'Erection tolerance (or installation tolerance)'},
    'muffrör': {'C2': 'Noun', 'n': 'Socket pipe (or bell-and-spigot pipe)'},
    'murblock': {'C2': 'Noun', 'n': 'Concrete masonry block'},
    'plattbärlagselement': {'C2': 'Noun', 'n': 'Precast lattice-girder slab element (filigree floor panel)'},
    'sandwichelement': {'C2': 'Noun', 'n': 'Sandwich panel (insulated precast wall panel)'},
    'skalväggselement': {'C2': 'Noun', 'n': 'Precast twin-wall element (or lattice-girder shell wall)'},
    'tillverkningsmått': {'C2': 'Noun', 'n': 'Manufacturing size (or work size dimension)'},
    'tillverkningstolerans': {'C2': 'Noun', 'n': 'Manufacturing tolerance'},
    'torrpressning': {'C2': 'Noun', 'n': 'Dry pressing'},
    'utsättningstolerans': {'C2': 'Noun', 'n': 'Setting-out tolerance'},
    'våtpressning': {'C2': 'Noun', 'n': 'Wet pressing'},
    'övergångsrör': {'C2': 'Noun', 'n': 'Adapter pipe (or transition pipe)'},


    ## Betongytor
    'behuggning': {'C2': 'Noun', 'n': 'Bush-hammering (or scutching)'},
    'betongintarsia': {'C2': 'Noun', 'n': 'Concrete intarsia (or inlaid concrete artwork)'},
    'direkt friläggning': {'C2': 'Noun phrase', 'n': 'Direct aggregate exposure'},
    'djup friläggning': {'C2': 'Noun phrase', 'n': 'Deep aggregate exposure'},
    'filtning': {'C2': 'Noun', 'n': 'Felt floating'},
    'finslipning': {'C2': 'Noun', 'n': 'Fine grinding (or polishing)'},
    'frilagd ballast': {'C2': 'Noun phrase', 'n': 'Exposed aggregate'},
    'friläggning': {'C2': 'Noun', 'n': 'Aggregate exposure'},
    'glättning': {'C2': 'Noun', 'n': 'Power troweling'},
    'grafisk betong': {'C2': 'Noun phrase', 'n': 'Graphic concrete'},
    'grovslipning': {'C2': 'Noun', 'n': 'Coarse grinding'},
    'grund friläggning': {'C2': 'Noun phrase', 'n': 'Shallow aggregate exposure'},
    'indirekt friläggning': {'C2': 'Noun phrase', 'n': 'Indirect aggregate exposure (via retarders)'},
    'kalkutfällning': {'C2': 'Noun', 'n': 'Efflorescence (or lime leaching)'},
    'medeldjup friläggning': {'C2': 'Noun phrase', 'n': 'Medium aggregate exposure'},
    'sandblästring': {'C2': 'Noun', 'n': 'Sandblasting'},
    'ströpplad yta': {'C2': 'Noun phrase', 'n': 'Stippled surface (or plaster-look texture finish)'},
    'stålglättad yta': {'C2': 'Noun phrase', 'n': 'Steel-troweled surface'},
    'stålglättning': {'C2': 'Noun', 'n': 'Steel troweling'},
    'syratvättning': {'C2': 'Noun', 'n': 'Acid etching (or acid washing)'},
    'terrazzo': {'C2': 'Noun', 'n': 'Terrazzo'},
    'ytballast': {'C2': 'Noun', 'n': 'Surface aggregate (or face mix)'},
    'ytsats': {'C2': 'Noun', 'n': 'Topping mix (or wearing course overlay)'},

    ## Fiberbetong
    'bollbildning': {'C2': 'Noun', 'n': 'Fiber balling'},
    'ekvivalent fiberdiameter': {'C2': 'Noun phrase', 'n': 'Equivalent fiber diameter'},
    'fiber': {'B2': 'Noun', 'n': 'Fiber'},
    'fiberbetong': {'C2': 'Noun', 'n': 'Fiber-reinforced concrete (FRC)'},
    'fiberdiameter': {'C2': 'Noun', 'n': 'Fiber diameter'},
    'fiberfaktor': {'C2': 'Noun', 'n': 'Fiber factor'},
    'fiberhalt': {'C2': 'Noun', 'n': 'Fiber content'},
    'fiberinnehåll': {'C2': 'Noun', 'n': 'Fiber content'},
    'fiberorientering': {'C2': 'Noun', 'n': 'Fiber orientation'},
    'mikrofiber': {'C2': 'Noun', 'n': 'Microfiber'},
    'nedkrossningsprov': {'C2': 'Noun', 'n': 'Crushing test (for fiber verification)'},
    'profilerad fiber': {'C2': 'Noun phrase', 'n': 'Deformed fiber (or crimped/hooked fiber)'},
    'residualhållfasthet': {'C2': 'Noun', 'n': 'Residual strength (or post-crack strength)'},
    'residualhållfasthetsfaktor': {'C2': 'Noun', 'n': 'Residual strength factor'},
    'SIFCON': {'C2': 'Noun', 'n': 'SIFCON (Slurry Infiltrated Fiber Concrete)'},
    'slankhet': {'C2': 'Noun', 'n': 'Aspect ratio (or slenderness of fiber)'},
    'sprickfördelande fiberbetong': {'C2': 'Noun phrase', 'n': 'Crack-distributing fiber concrete'},
    'sprickhämmande fiberbetong': {'C2': 'Noun phrase', 'n': 'Crack-controlling fiber concrete'},
    'stålfiber': {'C2': 'Noun', 'n': 'Steel fiber'},
    'töjningshårdnande fiberbetong': {'C2': 'Noun phrase', 'n': 'Strain-hardening fiber-reinforced concrete (SHCC)'},
    'utvaskningsprov': {'C2': 'Noun', 'n': 'Wash-out test'},
    'vidhäftningsfaktor': {'C2': 'Noun', 'n': 'Bond factor (or adhesion coefficient)'},
    'ändförankring': {'C2': 'Noun', 'n': 'End anchorage (or hooked fiber end)'},

    ## Fogar
    'anslutningskonstruktion': {'C2': 'Noun', 'n': 'Adjacent structure (or connection assembly)'},
    'arbetsfog': {'C2': 'Noun', 'n': 'Construction joint (or day joint)'},
    'dilatationsfog': {'C2': 'Noun', 'n': 'Expansion joint (or dilatation joint)'},
    'dymlad fog': {'C2': 'Noun phrase', 'n': 'Doweled joint'},
    'dymling': {'C2': 'Noun', 'n': 'Dowel bar'},
    'expansionsfog': {'C2': 'Noun', 'n': 'Expansion joint'},
    'fogarrangemang': {'C2': 'Noun', 'n': 'Joint layout (or joint arrangement)'},
    'fogavstånd': {'C2': 'Noun', 'n': 'Joint spacing'},
    'fogfyllnad': {'C2': 'Noun', 'n': 'Joint filler'},
    'fogfyllning': {'C2': 'Noun', 'n': 'Joint sealing operation (or filler material)'},
    'foglist': {'C2': 'Noun', 'n': 'Joint fillet strip (or chamfer strip)'},
    'fogmassa': {'C2': 'Noun', 'n': 'Joint sealant'},
    'fogspricka': {'C2': 'Noun', 'n': 'Joint crack (or crack induced at joint)'},
    'förankringsstång': {'C2': 'Noun', 'n': 'Tie bar (or anchor rod)'},
    'isolationsfog': {'C2': 'Noun', 'n': 'Isolation joint'},
    'konstruktionsfog': {'C2': 'Noun', 'n': 'Construction joint'},
    'kontraktionsfog': {'C2': 'Noun', 'n': 'Contraction joint (or control joint)'},
    'längsgående fog': {'C2': 'Noun phrase', 'n': 'Longitudinal joint'},
    'rörelsefog': {'C2': 'Noun', 'n': 'Movement joint (or isolation/expansion joint)'},
    'sprickanvisning': {'C2': 'Noun', 'n': 'Crack inducer (or weakened plane joint slot)'},
    'tvärgående fog': {'C2': 'Noun phrase', 'n': 'Transverse joint'},
    'vägrensfog': {'C2': 'Noun', 'n': 'Shoulder joint'},

    ## Industrigolv, betongvägar och markbetong
    'avjämningsmassa': {'C2': 'Noun', 'n': 'Self-leveling screed compound (or underlayment)'},
    'belagd väg': {'C2': 'Noun phrase', 'n': 'Paved road'},
    'betongbeläggning': {'C2': 'Noun', 'n': 'Concrete pavement (or concrete surfacing)'},
    'betongutläggare': {'C2': 'Noun', 'n': 'Concrete paver machine (or slipform paver)'},
    'betongväg': {'C2': 'Noun', 'n': 'Concrete road'},
    'betongöverbyggnad': {'C2': 'Noun', 'n': 'Concrete pavement superstructure (or road crust)'},
    'bundet bärlager': {'C2': 'Noun phrase', 'n': 'Bound base course'},
    'bundet slitlager': {'C2': 'Noun phrase', 'n': 'Bound wearing course'},
    'bäddmodul': {'C2': 'Noun', 'n': 'Modulus of subgrade reaction (k-value)'},
    'BÖ': {'C2': 'Noun', 'n': 'BÖ (Betongöverbyggnad / Concrete pavement superstructure)'},
    'CBÖ': {'C2': 'Noun', 'n': 'CBÖ (Cementbitumenöverbyggnad / Cement-bitumen composite pavement structure)'},
    'cementbitumenöverbyggnad': {'C2': 'Noun', 'n': 'Cement-bitumen composite pavement structure'},
    'dammbindare': {'C2': 'Noun', 'n': 'Dust binder (or surface sealer/hardener)'},
    'differenskrympning': {'C2': 'Noun', 'n': 'Differential shrinkage'},
    'etsning': {'C2': 'Noun', 'n': 'Etching'},
    'flytande golv': {'C2': 'Noun phrase', 'n': 'Floating floor (or isolated slab overlay)'},
    'förvattning': {'C2': 'Noun', 'n': 'Pre-wetting (or pre-soaking the subgrade)'},
    'glidformsläggare': {'C2': 'Noun', 'n': 'Slipform paver machine'},
    'glidskikt': {'C2': 'Noun', 'n': 'Slip membrane (or separation layer/slip sheet)'},
    'hårdbetong': {'C2': 'Noun', 'n': 'Heavy-duty concrete (or iron-aggregate topping/hard concrete)'},
    'häftlimning': {'C2': 'Noun', 'n': 'Adhesive bonding (or contact gluing)'},
    'kantresning': {'C2': 'Noun', 'n': 'Slab curling (or corner warping)'},
    'kombinationsarmering': {'C2': 'Noun', 'n': 'Combination reinforcement (e.g., mesh + steel fibers)'},
    'krymprörelse': {'C2': 'Noun', 'n': 'Shrinkage movement'},
    'limmad pågjutning': {'C2': 'Noun phrase', 'n': 'Bonded concrete topping (or bonded overlay)'},
    'markbetong': {'C2': 'Noun', 'n': 'External concrete paving (or slab-on-grade hardscaping)'},
    'motgjutningsyta': {'C2': 'Noun', 'n': 'Joint interface surface (or interface against existing pour)'},
    'mönstermall': {'C2': 'Noun', 'n': 'Stamping template (or texture mat stencil)'},
    'mönstrad markbetong': {'C2': 'Noun phrase', 'n': 'Stamped concrete (or patterned textured concrete)'},
    'planavjämnare': {'C2': 'Noun', 'n': 'Floor leveler (or straightedge screeder tool)'},
    'platsgjuten markbetong': {'C2': 'Noun phrase', 'n': 'Cast-in-place external paving'},
    'platta på mark': {'C2': 'Noun phrase', 'n': 'Slab-on-grade (or slab-on-ground)'},
    'pågjutning': {'C2': 'Noun', 'n': 'Concrete topping (or screed overlay)'},
    'pålunderstödd platta': {'C2': 'Noun phrase', 'n': 'Pile-supported slab'},
    'råhet': {'C2': 'Noun', 'n': 'Roughness (or macroscopic surface texture)'},
    'spårbildning': {'C2': 'Noun', 'n': 'Rutting'},
    'stabilisering': {'C1': 'Noun', 'n': 'Stabilization (soil or subgrade modification)'},
    'styv överbyggnad': {'C2': 'Noun phrase', 'n': 'Rigid pavement superstructure'},
    'superfloor': {'C2': 'Noun', 'n': 'Superfloor (polished architectural concrete floor)'},
    'urslag': {'C2': 'Noun', 'n': 'Aggregate pop-out (or edge plucking damage)'},
    'vidhäftningsbruk': {'C2': 'Noun', 'n': 'Bonding mortar (or structural adhesion grout)'},
    'våtlimning': {'C2': 'Noun', 'n': 'Wet-bonding'},
    'vått-i-vått-gjutning': {'C2': 'Noun phrase', 'n': 'Wet-on-wet casting (monolithic multi-layer casting)'},
    'ytråhet': {'C2': 'Noun', 'n': 'Surface roughness'},
    'ytslipat betonggolv': {'C2': 'Noun phrase', 'n': 'Ground and polished concrete floor'},
    'överbyggnad': {'C2': 'Noun', 'n': 'Pavement structure (or pavement superstructure/crust)'},
}

# some additions I made
betongteknisk_words_extended={
    'strosad yta': {'C2': 'Noun phrase', 'n': 'Broomed surface (or textured finish)'},

    # Hållbarhet och Miljö (Sustainability & Environment)
    'klimatförbättrad betong': {'C2': 'Noun phrase', 'n': 'Climate-improved concrete (Low-carbon concrete)'},
    'miljövarudeklaration': {'C2': 'Noun', 'n': 'Environmental Product Declaration (EPD)'},
    'återbrukad betong': {'C2': 'Noun phrase', 'n': 'Reused concrete'},
    'koldioxidavtryck': {'C1': 'Noun', 'n': 'Carbon footprint'},
    'grön betong': {'C2': 'Noun phrase', 'n': 'Green concrete (Eco-concrete)'},

    # Konstruktionsdelar - Anläggning & Bro (Structural Elements - Civil & Bridge)
    'brobana': {'C2': 'Noun', 'n': 'Bridge deck'},
    'farbana': {'C2': 'Noun', 'n': 'Carriageway (or roadway on bridge)'},
    'farbaneplatta': {'C2': 'Noun', 'n': 'Bridge deck slab'},
    'fundament': {'C1': 'Noun', 'n': 'Foundation'},
    'grundplatta': {'C2': 'Noun', 'n': 'Foundation slab (or raft foundation)'},
    'kantbalk': {'C2': 'Noun', 'n': 'Edge beam'},
    'landfäste': {'C2': 'Noun', 'n': 'Abutment (Bridge abutment)'},
    'murkrön': {'C2': 'Noun', 'n': 'Wall coping (or crown)'},
    'pålplatta': {'C2': 'Noun', 'n': 'Pile cap (or pile slab)'},
    'stödmur': {'C2': 'Noun', 'n': 'Retaining wall'},
    'vingmur': {'C2': 'Noun', 'n': 'Wing wall'},
    'överbyggnad': {'C2': 'Noun', 'n': 'Superstructure'},
    'underbyggnad': {'C2': 'Noun', 'n': 'Substructure'},

    # Prefabricerade element (Additional Precast Elements)
    'balkongplatta': {'C2': 'Noun', 'n': 'Balcony slab'},
    'filigranbjälklag': {'C2': 'Noun', 'n': 'Filigree slab (Lattice girder slab)'},
    'massivvägg': {'C2': 'Noun', 'n': 'Solid wall element'},
    'sockelelement': {'C2': 'Noun', 'n': 'Plinth element (or socket element)'},
    'trappelement': {'C2': 'Noun', 'n': 'Stair element (Precast stair)'},

    # Beständighet och Egenskaper (Durability & Properties)
    'beständighet': {'C2': 'Noun', 'n': 'Durability'},
    'frostbeständighet': {'C2': 'Noun', 'n': 'Frost resistance'},
    'kloridinträngning': {'C2': 'Noun', 'n': 'Chloride ingress'},
    'saltfrostbeständighet': {'C2': 'Noun', 'n': 'Salt-frost resistance (Scaling resistance)'},
    'sprickvidd': {'C2': 'Noun', 'n': 'Crack width'},
    'vattentäthet': {'C2': 'Noun', 'n': 'Watertightness'},
    'alkalisilikareaktion': {'C2': 'Noun', 'n': 'Alkali-silica reaction (ASR)'},
    'armeringskorrosion': {'C2': 'Noun', 'n': 'Reinforcement corrosion'},

    # Provning och Kontroll (Testing & Control)
    'mottagningskontroll': {'C2': 'Noun', 'n': 'Reception control (Acceptance inspection)'},
    'oförstörande provning': {'C2': 'Noun phrase', 'n': 'Non-destructive testing (NDT)'},
    'provkropp': {'C2': 'Noun', 'n': 'Test specimen'},
    'provtryckning': {'C2': 'Noun', 'n': 'Pressure testing'},
    'referensprov': {'C2': 'Noun', 'n': 'Reference sample'},

    # Renovering och Underhåll (Repair & Maintenance)
    'betongrenovering': {'C2': 'Noun', 'n': 'Concrete repair'},
    'bila': {'C2': 'Verb', 'n': 'Chip (or jackhammer/demolish)'},
    'bomknackning': {'C2': 'Noun', 'n': 'Hammer tapping (to detect delamination)'},
    'rostskyddsmålning': {'C2': 'Noun', 'n': 'Anti-rust painting (of reinforcement)'},
    'ytskydd': {'C2': 'Noun', 'n': 'Surface protection (Coating)'},

    # Standarder och Dokumentation (Standards & Documentation)
    'AMA': {'C2': 'Proper Noun', 'n': 'AMA (General Material and Workmanship Specifications)'},
    'bygghandling': {'C2': 'Noun', 'n': 'Construction document'},
    'K-ritning': {'C2': 'Noun', 'n': 'Structural drawing'},


}
