# -*- coding: utf-8 -*-
# -*- mode: python; python-indent-offset: 4 -*-
#
# Some acronyms from courses and theses in EECS
#
# on 2024-04-26 the merged words and corrected abstracts were separated out into their own files
#
# on 2024-06-23 put the acronyms into this file
#
# 2024-06-23
#
# G. Q. Maguire Jr.
#
# well_known_acronyms_list is a list of acronym_:entries
#   The list structure has been used becuase there can be many different
#   means for a given acronym.
#
# Each acronym_:entry is a list and has the form:
#  acronym, expanded_form, extras_dict
#
#  Note that the optional extras_dict can contain the following keys and values:
#   's': list of sources
#           each source is s string, typeically of the form: 'diva2:ddddddd'
#   'cefr': string containing a CEFR level, such as 'B2'
#

# consider adding support for these
well_known_acronyms_list=[
    # the following are from CBH
    ['AAS','atomic absorption spectroscopy'],
    ['AC', 'activated Carbon', {'s': 'diva2:827212'}],
    ['ADRD', 'Alzheimer’s disease and related dementias'],
    ['AED', 'automated external defibrillator'],
    ['APTES', '3-aminopropyl)triethoxysilane'],
    ['AR', 'Augmented Reality'],
    ['ATAC-seq', 'Assay for transposase-accessible chromatin with sequencing'],
    ['ATRP','atom transfer radical polymerization'],
    ['Arthro-CT', 'Arthrogram Computed Tomography'],
    ['BA', 'Biological age'],
    ['BIM', 'Building Information Modeling'],
    ['BioSilk','recombinant spider silk'],
    ['BIS', 'baninformationssystemet', {'cefr': 'B2'}],
    ['bLG', 'Bovine β-lactoglobulin protein'],
    ['CBP', 'Consolidated Bioprocessing'],
    ['CBP','consolidated bioprocessing'],
    ['CCS', 'Carbon capture and storage'],
    ['CDF','cumulative distribution function'],
    ['CDK8', 'Cyclin-dependent kinase 8'],
    ['CFUs', 'Colony Forming Units'],
    ['CGE','Capillary Gel Electrophoresis'],
    ['CMR', 'Cardiac Magnetic Resonance Imaging'],
    ['CMR', 'Cardiovascular Magnetic Resonance Imaging'],
    ['CNF', 'Cellulose nanofibrils'],
    ['CNN', 'Convolutional Neural Network'],
    ['CNR', 'Contrast-to-noise ratio'],
    ['CSD', 'Cardiac State Diagram'],
    ['CT', 'Computed tomography'],
    ['CT', 'computed tomography'],
    ['CVD','cardiovascular disease'],
    ['CZE','Capillary Zone Electrophoresis'],
    ['ChIP-seq', 'chromatin immunoprecipitation'],
    ['DARPins', 'Designed ankyrin repeat proteins'],
    ['DFT','Discrete Fourier Transform'],
    ['DLP','digital light processing'],
    ['DOSY', 'Diffusion Ordered Spectroscopy'],
    ['DPMS', 'dolicholphosphate mannosesynthase', {'s': 'diva2:1219274'}],
    ['DSC', 'Differential scanning calorimetry'],
    ['DSP', 'digital signal processing'],
    ['ECG', 'Electrocardiography', {'cefr': 'B2'}],
    ['EDI','Electronic data interchange', {'cefr': 'B2'}],
    ['EDIFACT', 'United Nations rules for Electronic Data Interchange for Administration, Commerce and Transport', {'cefr': 'B2'}],
    ['EIS',    'Electrochemical impedance spectroscopy', {'cefr': 'C1'}],
    ['ELF', 'Extremely Low Frequency', {'cefr': 'B2'}],
    ['EMC','electromagnetic compatibility'],
    ['EMV','Visa and Mastercard', {'cefr': 'A2'}],
    ['EMV','Europay, Mastercard, and Visa', {'cefr': 'A2'}],
    ['ESO','epoxidized soybean oil'],
    ['ESR', 'Equivalent Serie Resistance', {'cefr': 'B2'}], 
    ['ETL', 'Extract, Transform and Load'],
    ['Euro NCAP', 'European New Car Assessment Programme'],
    ['EVs', 'electric vehicles'],
    ['FIGP','Formed in Place Gaskets', {'cefr': 'C1'}],
    ['FFT','Fast Fourier Transform'],
    ['FEM','Finite Element Method'],
    ['FEM','Finite Element Modeling'],
    ['FTIR', 'Fourier Transform Infra-Red'],
    ['GLME', 'Ganoderma lucidum methanolic extract'],
    ['GMBS', 'N-γ-maleimidobutyryl-oxysuccinimide ester'],
    ['GO','Gene Ontology'],
    ['GWAS','genome-wide association study'],
    ['HBM','Human Body Models'],
    ['HD','Homeostatic Dysregulation', {'cefr': 'C1'}],
    ['HGVs','Heavy Goods Vehicles', {'cefr': 'B2'}],
    ['HTO','human technology organization'],
    ['HUD','Head-Up Display', {'cefr': 'B2'}],
    ['ICP','Iterative Closest Point', {'cefr': 'C2'}],
    ['IDE','Integrated development environment', {'cefr': 'B2'}],
    ['IDS','Intrusion Detection System', {'cefr': 'B2'}],
    ['IFCB', 'Imaging FlowCytobot', {'cefr': 'B2', 's': 'diva2:1774747'}],
    ['IGFs','insulin-like growth factors'],
    ['IIoT','Industrial Internet of Things'],
    ['IMU','inertial Measurement Unit'],
    ['ISD','In Source-Decay', {'cefr': 'C1'}],
    ['ISTD', 'Intern standard', {'s': 'diva2:1859260'}],
    ['IoT','Internet of Things', {'cefr': 'A2'}],
    ['KDM','Klemera Doubal Method', {'cefr': 'C1'}],
    ['LCA','Life Cycle Analysis', {'cefr': 'A1'}],
    ['LCC', 'lignin carbohydrate complex'],
    ['LCNF','Lignocellulose nanofibers', {'cefr': 'B2'}],
    ['LED', 'Light Emitting Diode', {'cefr': 'B1'}],
    ['LHC', 'Linde-Hampson cycle'],
    ['LLM','Large Language Model', {'cefr': 'B2'}],
    ['LTO','Lithium-titanate battery', {'cefr': 'B2'}],
    ['MAH','Medicinteknisk apparatur i hemmet'],
    ['MALDI-ToF-MS', 'Matrix-Assisted Laser Desorption/Ionization Time-of Flight Mass Spectrometry'],
    ['MIA','Membership Inference Attack', {'cefr': 'C1'}],
    ['ML','Machine Learning'],
    ['MLCC', 'Multi-layer capacitor'],
    ['MOM', 'Message-oriented middleware', {'s': 'diva2:1473908'}],
    ['MPTES', 'mercaptopropyltriethoxysilane'],
    ['MRI','Magnetic Resonance Imaging'],
    ['MSCs', 'Mesenchymal stromal cells', {'s': 'diva2:1454998'}],
    ['NFC','Near Field Communication', {'cefr': 'C1'}],
    ['NLP', 'Natural Language Processing'],
    ['NMR','Nuclear Magnetic Resonance', {'cefr': 'B2'}],
    ['NOM','natural organic matter'],
    ['NTP', 'Network Time Protocol'],
    ['OC', 'Object Controllers', {'s': 'diva2:1562805'}],
    ['OCR','Optical Character Recognition', {'cefr': 'B2'}],
    ['OFTP','Odette File Transfer Protocol'],
    ['OBT','One Big Table'],
    ['OCP','Open circuit potential'],
    ['OU', 'Optical Unit'],
    ['PAT','process analytical technologies'],
    ['PCA','Principal  Component Analysis', {'cefr': 'C1'}],
    ['PCB','printed circuit board'],
    ['PEMFC','Proton exchange membrane fuel cell', {'cefr': 'C1'}],
    ['PHB', 'Poly(3-hydroxybutyrate)'],
    ['PHR', 'Personal Health Record'],
    ['PIC','Preinitiation complex', {'cefr': 'C2'}],
    ['PLA','Polylactide'],
    ['PLGF','Placental growth factor', {'cefr': 'C1'}],
    ['PLS','Partial Least Square Projection'],
    ['PME','pectinesterase'],
    ['POS','Point Of Sale', {'cefr': 'B2'}],
    ['PRO-seq','Precision nuclear run-on sequencing'],
    ['PTE','Particle-templated emulsification'],
    ['PZT','piezoelectric'],
    ['QoE','Quality of Experience', {'cefr': 'B2'}],
    ['R,L,C', 'Resistor, Inductor, and Capacitor'],
    ['RAB','Rotating Algal Biofilm', {'cefr': 'C1'}],
    ['RAP', 'reclaimed asphalt pavement'],
    ['REM', 'rapid eye movement', {'cefr': 'C1'}],
    ['RGB', 'red, green, blue'],
    ['SHM','Structural health monitoring', {'cefr': 'C1'}],
    ['SIMDIS','Simulated Distillation', {'cefr': 'B2'}],
    ['SIS', 'Swedish Institute for Standards'],
    ['SOC','sense of coherence'],
    ['SPI','soy protein isolate'],
    ['SWIG','Sector Wise Golden-angle', {'cefr': 'C1'}],
    ['TATO', 'triazine-trione', {'s': 'diva2:1361820'}],
    ['TBI', 'Traumatic brain injury', {'cefr': 'C1'}],
    ['TBI','Traumatic Brain Injury'],
    ['TBP', 'True Boiling Point)'],
    ['TEC', 'thiol-ene coupling', {'s': 'diva2:1361820'}],
    ['TEC/TYC', 'thiol-ene coupling/thiol-yne coupling', {'s': 'diva2:1361820'}],
    ['THUMS', 'Total HUman Model for Safety'],
    ['TKIs', 'tyrosine kinase inhibitors'],
    ['TYC', 'thiol-yne coupling', {'s': 'diva2:1361820'}],
    ['TVI','Tissue Velocity Imaging'],
    ['T_1','Longitudinal relaxation time1'],
    ['UI','User Interface', {'cefr': 'A2'}],
    ['UN/EDIFACT', 'United Nations rules for Electronic Data Interchange for Administration, Commerce and Transport', {'cefr': 'B2'}],
    ['UWB','Ultra-Wideband Radar', {'cefr': 'C1'}],
    ['UX','User Experience', {'cefr': 'A2'}],
    ['WPI','Whey protein isolate', {'cefr': 'B2'}],
    ['cMRF', 'Cardiac Magnetic Resonance Fingerprinting'],
    ['dbt', 'Data Build Tool'],
    ['mAbs','Monoclonal Antibodies'],
    ['mMSCs', 'mouse mesenchymal stem cells', {'s': 'diva2:1266796'}],
    ['GDPR', 'General Data Protection Regulation'],
    ['SCA', 'Spinocerebellar ataxia'],
    ['AD', 'Atopic dermatitis'],
    ['CSF', 'cerebrospinal fluid'],
    ['SBA', 'suspension bead array'],
    ['SLC17A6', 'Solute Carrier Family 17 Member 6'],
    ['MAP1A', 'Microtubule Associated Protein 1A'],
    ['MAP2', 'Microtubule Associated Protein 2'],
    ['TSE', 'twin-s crew extruder', {'s': 'diva2:1136064'}],
    ['SBMA', '[2-(methacryloyloxy)ethyl] dimethyl-(3-sulfopropyl)</p><p>ammonium hydroxide', {'s': 'diva2:1175545'}],
    ['pDADMAC', 'diallydimethylammoinium chloride', {'s': 'diva2:1876747'}],
    ['MMT', 'montmorillonite clay', {'s': 'diva2:1876747'}],
    ['DBCO', 'dibenzocyclooctyne', {'s': ''}],
    ['CTAB', 'cationic surfactant cetyltrimethylammonium bromide', {'s': 'diva2:418821'}],
    ['SOS', 'anionic surfactant sodium octyl sulfate', {'s': 'diva2:418821'}], 
    ['TKA', 'total knee arthroplasty', {'s': 'diva2:1115012'}],
    ['DWR', 'Durable water repellents', {'s': 'diva2:1520202'}],
    ['HBD', 'histone-binding domain'],    
    ['SI-ROP', 'surface initiated-Ring Opening Polymerisation', {'s': 'diva2:1787126'}],
    ['AffiMabs', 'antibody-Affibody fusion proteins', {'s': 'diva2:801899'}],
    ['FcRn', 'Fc receptor', {'s': 'diva2:801899'}],
    ['HLA', 'Human Leukocyte Antingen', {'s': 'diva2:853824'}],
    ['MHC', 'Major Histocompatibillity Complex', {'s': 'diva2:853824'}],
    ['SSO', 'Sequence-specific oligonucleotie', {'s': 'diva2:853824'}],
    ['SSP', 'Sequence-specific priming', {'s': 'diva2:853824'}],
    ['SBT', 'Sequenced-based typing', {'s': 'diva2:853824'}],
    ['NGS', 'Next Generation Sequencing', {'s': 'diva2:853824'}],
    ['hpT', 'hours post transfection', {'s': 'diva2:1621933'}],
    ['HA', 'hyaluronic acid', {'s': 'diva2:1438811'}],
    ['PAH', 'polyallylamine hydrochloride', {'s': 'diva2:1438811'}],
    ['WTP', 'willingness to pay', {'s': 'diva2:1519525'}],
    ['NPV', 'net present value', {'s': 'diva2:1519525'}],
    ['PBP', 'payback period', {'s': 'diva2:1519525'}],
    ['LCOM', 'levelized cost of methane', {'s': 'diva2:1519525'}],
    ['MP', 'marginal profit', {'s': 'diva2:1519525'}],
    ['SNG', 'synthetic methane', {'s': 'diva2:1519525'}],
    ['NG', 'natural gas', {'s': 'diva2:1519525'}],
    ['HARM', 'Hand Arm Risk Assessment Method', {'s': 'diva2:537187'}],
    ['PVP-PCL', 'Polyvinyl pyrrolidone-Polycaprolactone', {'s': 'diva2:720734'}],
    ['PLA-PVP', 'Poly lactide-Polyvinyl pyrrolidone', {'s': 'diva2:720734'}],
    ['MBAs' 'Martian Brine Analogues'],
    ['DOE', 'Design of Experiments', {'s': 'diva2:852451'}],
    ['LiBOB', 'lithium bis(oxalato)borate', {'s': 'diva2:1577131'}],
    ['TFEB', 'Transcription factor EB', {'s': 'diva2:1586242'}],
    ['SPPS', 'Solid-Phase Peptide Sythesis', {'s': 'diva2:744725'}],
    ['PCCAs', 'Phase Changing Contrast Agents', {'s': 'diva2:1325213'}],
    ['MOSIC', 'Monoclonal StoichiometrIC', {'s': 'diva2:855825'}],
    ['CVC', 'central venous catheterization', {'s': 'diva2:1086147'}],
    ['LCO', 'luminescent</p><p>conjugated oligothiophene', {'s': 'diva2:1145272'}],
    

]
