# -*- coding: utf-8 -*-
# -*- mode: python; python-indent-offset: 4 -*-
#
# Some useful dicts and lists - for Bosnian
#
#
# 2026-02-27
#
# G. Q. Maguire Jr.
#
#
# Abbreviations used:
#  CEFR   Common European Framework of Reference for Languages: Learning, teaching, assessment.
#  POS    Part Of Speech
#
# This file contains several dicts and lists - these contain 'word' entries, but a 'word' can actually be a string of several words.
#
# Lists have been used when there can be multiple entries for the same 'word' and where there is not CEFR and POS information.
#
#
# Each dict's structure is:
# dict_name = {
#    entry,
#    entry,
# }
# Each entry is a 'word': CEFR_POS_dict
#
# a CEFR_POS_dict entry is a dict with the keys being CEFR levels (A1, A2, B1, B2, C1, C2, XX, and NA)
# followed by a string that contains comma separated POS
#
# The code 'XX' is used for an unknown CEFR level, while NA is for use when no level is applicable:
# 
# 
common_bosnian_words={
    'sažetak': {'A2': 'Noun', 'n': 'Summary or Abstract; a concise overview of the research findings and methodology'},
    'zamaranje': {'B2': 'Noun', 'n': 'Fatigue; the progressive structural damage that occurs when a material is subjected to cyclic loading'},
    'korozija': {'B1': 'Noun', 'n': 'Corrosion; the degradation of a metal due to chemical or electrochemical reactions with its environment'},
    'mehaničkih osobina': {'B2': 'Noun (Plural)', 'n': 'Mechanical properties; characteristics such as strength, elasticity, and ductility'},
    'nakupljanja oštećenja': {'C1': 'Noun, Phrase', 'n': 'Accumulation of damage; the gradual buildup of micro-defects leading to final failure'},
    'cikličkog mehaničkog opterećenja': {'C1': 'Noun, Phrase', 'n': 'Cyclic mechanical loading; repeated application of stress or strain over time'},
    'mehaničkih havarija': {'B2': 'Noun (Plural)', 'n': 'Mechanical failures or breakdowns; significant structural collapses or malfunctions'},
    'degradacije strukture': {'B2': 'Noun', 'n': 'Structural degradation; the process by which a system or material loses its integrity over time'},
    'korozionog zamaranja': {'C1': 'Noun', 'n': 'Corrosion fatigue; the combined effect of cyclic stress and a corrosive environment which accelerates crack growth'},
    'radnim uvjetima': {'B1': 'Noun (Plural)', 'n': 'Operating conditions; the specific environmental factors (temperature, pressure, chemistry) a component faces'},
    'nuklearnih reaktora': {'B2': 'Noun (Plural)', 'n': 'Nuclear reactors; systems used to initiate and control a self-sustained nuclear chain reaction'},
    'lahkovodnih reaktora': {'C1': 'Noun (Plural)', 'n': 'Light water reactors (LWR); a type of thermal-neutron reactor that uses normal water as a coolant and neutron moderator'},
    'prediktivnim modelima': {'C1': 'Noun (Plural)', 'n': 'Predictive models; mathematical frameworks used to forecast the future behavior or lifespan of a material'},
    'nehrđajućeg čelika 304L': {'B2': 'Noun', 'n': '304L stainless steel; a low-carbon austenitic steel known for its corrosion resistance and weldability'},
    'karakterizacija': {'C1': 'Noun', 'n': 'Characterization; the process of measuring and determining the physical and chemical properties of a material'},
    'testovi zatezanje': {'B2': 'Noun (Plural)', 'n': 'Tensile tests; experimental procedures to determine how a material reacts under axial stretching'},
    'rasta pukotina': {'C1': 'Noun', 'n': 'Crack growth; the physical advancement of a crack tip through a material cross-section'},
    'izotropno ponašanje': {'C1': 'Noun', 'n': 'Isotropic behavior; having physical properties that are identical in all directions'},
    'šupljim uzorcima': {'B2': 'Noun (Plural)', 'n': 'Hollow specimens; test samples with a central cavity, often used to simulate pipes or specialized stress states'},
    'padom napona': {'C1': 'Noun, Phrase', 'n': 'Voltage drop; specifically referring here to the Direct Current Potential Drop (DCPD) technique for monitoring crack size'},
    'iniciranja pukotina': {'C1': 'Noun', 'n': 'Crack initiation; the very first stage of fatigue where a microscopic crack begins to form'},
    'amplitudama deformacije': {'C1': 'Noun (Plural)', 'n': 'Strain amplitudes; the magnitude of cyclic stretching or compression applied to a specimen'},
    'ravni smicanja': {'C1': 'Noun (Plural)', 'n': 'Shear planes; the specific atomic planes along which sliding occurs during plastic deformation'},
    'kristalnim zrnima': {'C1': 'Noun (Plural)', 'n': 'Crystalline grains; individual crystals within a polycrystalline metal structure'},
    'konstitutivni model': {'C1': 'Noun', 'n': 'Constitutive model; a mathematical relation describing the stress-strain behavior of a specific material'},
    'kristalnoj plastičnosti': {'C1': 'Noun', 'n': 'Crystal plasticity; a theory that models the deformation of metals based on slip systems within individual grains'},
    'kalibrirani': {'B2': 'Adjective', 'n': 'Calibrated; adjusted against known experimental data to ensure model accuracy'},
    'produženje radnog vijeka': {'B2': 'Noun', 'n': 'Life extension; the process of safely operating a component beyond its original design lifespan'},

    'predstavljaju': {'B1': 'Verb', 'n': 'Represent; to serve as or be the equivalent of (e.g., fatigue and corrosion represent two dominant mechanisms)'},
    'dominantna': {'B2': 'Adjective', 'n': 'Dominant; the primary or most influential factors in a process'},
    'mehanizma': {'B2': 'Noun', 'n': 'Mechanisms; the fundamental physical or chemical processes behind a change'},
    'prouzrokuju': {'B2': 'Verb', 'n': 'Cause; to be the reason for a change in mechanical properties'},
    'promjenu': {'B1': 'Noun', 'n': 'Change; an alteration in the state or properties of a material'},
    'strukturnih': {'B2': 'Adjective', 'n': 'Structural; relating to the load-bearing parts of a system'},
    'materijala': {'A1': 'Noun', 'n': 'Materials; the substances used to construct engineering components'},
    'nastaje': {'B1': 'Verb', 'n': 'Arises/Occurs; the starting point of a phenomenon like fatigue'},
    'rezultat': {'A2': 'Noun', 'n': 'Result; the outcome of progressive damage accumulation'},
    'progresivnog': {'B2': 'Adjective', 'n': 'Progressive; happening gradually over a period of time'},
    'uslijed': {'B2': 'Preposition', 'n': 'Due to/As a result of; indicating the cause of damage'},
    'procjenjuje': {'B2': 'Verb', 'n': 'Estimated; the calculated or projected frequency of mechanical failures'},
    'izazvana': {'B1': 'Adjective', 'n': 'Induced/Caused by; referring to corrosion triggered by chemical reactions'},
    'hemijskim': {'A2': 'Adjective', 'n': 'Chemical; relating to interactions at the molecular level'},
    'elektrohemijskim': {'C1': 'Adjective', 'n': 'Electrochemical; involving the exchange of electrons between a metal and its environment'},
    'reakcijama': {'B1': 'Noun (Plural)', 'n': 'Reactions; the specific chemical interactions with the surroundings'},
    'okolinom': {'B1': 'Noun', 'n': 'Environment/Surroundings; the medium (like water) surrounding a component'},
    'dovodi': {'B1': 'Verb', 'n': 'Leads to; resulting in material loss or structural degradation'},
    'gubitka': {'B2': 'Noun', 'n': 'Loss; the reduction of material mass due to corrosion'},
    'godišnji': {'B1': 'Adjective', 'n': 'Annual; the yearly economic impact of material degradation'},
    'trošak': {'B1': 'Noun', 'n': 'Cost; the financial burden of corrosion on a national GDP'},
    'kombinuju': {'B1': 'Verb', 'n': 'Combine; when two distinct phenomena act simultaneously'},
    'slučaju': {'B1': 'Noun', 'n': 'Case; a specific instance or scenario, such as corrosion fatigue'},
    'proces': {'A2': 'Noun', 'n': 'Process; the series of steps in material degradation'},
    'značajno': {'B2': 'Adverb', 'n': 'Significantly; to a great or important degree'},
    'ubrzava': {'B2': 'Verb', 'n': 'Accelerates; increasing the speed of the failure process'},
    'posebno': {'B1': 'Adverb', 'n': 'Especially/Particularly; highlighting critical components in harsh conditions'},
    'kritično': {'B2': 'Adjective', 'n': 'Critical; a state or condition that is decisive or dangerous'},
    'inženjerske': {'B2': 'Adjective', 'n': 'Engineering; relating to the design and building of complex systems'},
    'komponente': {'B1': 'Noun (Plural)', 'n': 'Components; individual parts of a larger machine or structure'},
    'rade': {'A1': 'Verb', 'n': 'Work/Operate; the functioning of systems in heavy conditions'},
    'teškim': {'B1': 'Adjective', 'n': 'Heavy/Harsh; extreme operating environments like marine settings'},
    'pomorske': {'B2': 'Adjective', 'n': 'Marine; relating to sea-based constructions and environments'},
    'konstrukcije': {'B2': 'Noun (Plural)', 'n': 'Constructions; physical structures like offshore platforms or ships'},
    'zrakoplovni': {'B2': 'Adjective', 'n': 'Aerospace/Aviation; relating to aircraft and flight systems'},
    'sistemi': {'B1': 'Noun (Plural)', 'n': 'Systems; complex organized assemblies of components'},
    'industrijska': {'B1': 'Adjective', 'n': 'Industrial; relating to manufacturing or factory environments'},
    'okruženja': {'B1': 'Noun (Plural)', 'n': 'Environments; the surrounding conditions of a system'},
    'kontekstu': {'B2': 'Noun', 'n': 'Context; the circumstances that form the setting for an event'},
    'globalnog': {'B2': 'Adjective', 'n': 'Global; relating to the entire world and the fossil-free transition'},
    'prelaska': {'B2': 'Noun', 'n': 'Transition/Passage; the move toward a society without fossil fuels'},
    'društvu': {'B1': 'Noun', 'n': 'Society; the community of people living together'},
    'fosilnih': {'B2': 'Adjective', 'n': 'Fossil; relating to fuels like coal or oil'},
    'goriva': {'B1': 'Noun', 'n': 'Fuels; substances burned to provide energy'},
    'siguran': {'B1': 'Adjective', 'n': 'Safe; reliable operation without risk to humans'},
    'dugotrajan': {'B2': 'Adjective', 'n': 'Long-lasting; the extended operation of nuclear reactors'},
    'postojećih': {'B2': 'Adjective', 'n': 'Existing; currently available or functioning systems'},
    'ključan': {'B2': 'Adjective', 'n': 'Key/Crucial; essential for satisfying energy needs'},
    'zadovoljavanje': {'B2': 'Noun, Gerund', 'n': 'Satisfying; meeting the growing demand for energy'},
    'rastućih': {'B2': 'Adjective', 'n': 'Growing; the increasing need for reliable energy sources'},
    'energetskih': {'B1': 'Adjective', 'n': 'Energy; relating to power and fuel requirements'},
    'potreba': {'B1': 'Noun (Plural)', 'n': 'Needs; the requirements of a modern society'},
    'vijeka': {'B2': 'Noun', 'n': 'Life/Lifespan; the total time a reactor is in operation'},
    'ugrožavanje': {'B2': 'Noun, Gerund', 'n': 'Endangering; putting human safety at risk'},
    'ljudske': {'B1': 'Adjective', 'n': 'Human; relating to people and their safety'},
    'sigurnosti': {'B1': 'Noun', 'n': 'Safety; the state of being protected from danger'},
    'široko': {'B1': 'Adverb', 'n': 'Widely; recognized across the globe as a key step'},
    'prepoznato': {'B2': 'Adjective', 'n': 'Recognized; accepted as an important part of the transition'},
    'korak': {'A2': 'Noun', 'n': 'Step; an action or stage in a larger process'},
    'tranziciji': {'B2': 'Noun', 'n': 'Transition; the change from one state to another'},
    'naglašava': {'B2': 'Verb', 'n': 'Emphasizes; highlighting the need for accurate models'},
    'potrebu': {'B1': 'Noun', 'n': 'Need; the requirement for predictive capabilities'},
    'tačnim': {'B2': 'Adjective', 'n': 'Accurate; precise and correct measurements or models'},
    'obuhvatiti': {'B2': 'Verb', 'n': 'Encompass/Capture; to include all aspects of a complex interaction'},
    'složenu': {'B2': 'Adjective', 'n': 'Complex; consisting of many interconnected parts'},
    'interakcije': {'B2': 'Noun (Plural)', 'n': 'Interactions; the mutual influence between fatigue and corrosion'},
    'vodi': {'A1': 'Noun', 'n': 'Water; the primary coolant and corrosive medium in an LWR'},
    'provedena': {'B1': 'Adjective', 'n': 'Conducted; performed experiments or characterizations'},
    'zraku': {'A2': 'Noun', 'n': 'Air; the baseline environment for mechanical testing'},
    'sobnoj': {'B1': 'Adjective', 'n': 'Room; typically referring to room temperature (approx. 20-25°C)'},
    'temperaturi': {'B1': 'Noun', 'n': 'Temperature; a critical variable in material performance'},
    'uključivalo': {'B1': 'Verb', 'n': 'Included; containing various types of fatigue and crack tests'},
    'pravca': {'B1': 'Noun', 'n': 'Direction; refers to the longitudinal or transverse orientation of the material'},
    'uzdužnom': {'B2': 'Adjective', 'n': 'Longitudinal; the direction parallel to the main axis or rolling direction'},
    'poprečnom': {'B2': 'Adjective', 'n': 'Transverse; the direction perpendicular to the main axis'},
    'pokazali': {'B1': 'Verb', 'n': 'Showed/Demonstrated; the results indicated specific behaviors'},
    'smanjene': {'B1': 'Adjective', 'n': 'Reduced; lowered performance levels at high temperatures'},
    'performanse': {'B2': 'Noun (Plural)', 'n': 'Performance; the functional capabilities of the steel'},
    'povišenim': {'B2': 'Adjective', 'n': 'Elevated; temperatures higher than the standard baseline'},
    'poslužili': {'B2': 'Verb', 'n': 'Served; the results acted as a foundation for further testing'},
    'osnova': {'B2': 'Noun', 'n': 'Basis/Foundation; the starting point for investigating corrosion fatigue'},
    'ispitivanje': {'B2': 'Noun, Gerund', 'n': 'Examination/Testing; the systematic investigation of material behavior'},
    'istraživanje': {'B2': 'Noun, Gerund', 'n': 'Research; the study of mechanical-electrochemical degradation'},
    'simuliranoj': {'B2': 'Adjective', 'n': 'Simulated; artificial environment mimicking actual BWR water'},
    'ključnog': {'B2': 'Adjective', 'n': 'Boiling (specifically "voda ključnog reaktora" refers to Boiling Water Reactor - BWR)'},
    'tehnika': {'B1': 'Noun', 'n': 'Technique; a specific method like DCPD used for monitoring'},
    'istosmijernog': {'C1': 'Adjective', 'n': 'Direct current (DC); relating to the electric signal used in crack monitoring'},
    'električnog': {'B1': 'Adjective', 'n': 'Electric; involving electricity or electric signals'},
    'signala': {'B1': 'Noun', 'n': 'Signal; the data stream used to track crack initiation'},
    'korištena': {'B1': 'Adjective', 'n': 'Used; applied in a specific situation (in-situ)'},
    'praćenje': {'B2': 'Noun, Gerund', 'n': 'Monitoring; the continuous observation of crack progress'},
    'potencijal': {'B2': 'Noun', 'n': 'Potential; the electrochemical voltage measured against a reference'},
    'mjerent': {'B1': 'Adjective', 'n': 'Measured; the value determined by the reference electrode'},
    'referentnom': {'B2': 'Adjective', 'n': 'Reference; a standard against which other values are compared'},
    'elektrodom': {'C1': 'Noun', 'n': 'Electrode; a conductor used to establish electrical contact with the water'},
    'smanjenje': {'B1': 'Noun', 'n': 'Reduction; the decrease in fatigue life when exposed to water'},
    'trajnosti': {'B2': 'Noun', 'n': 'Durability/Lifespan; the number of cycles a material lasts before failure'},
    'poređenju': {'B1': 'Noun', 'n': 'Comparison; evaluating performance in water versus air'},
    'naročito': {'B2': 'Adverb', 'n': 'Particularly/Notably; especially evident at low strain levels'},
    'niskim': {'B1': 'Adjective', 'n': 'Low; referring to small magnitudes of deformation'},
    'metalografske': {'C1': 'Adjective', 'n': 'Metallographic; relating to the study of the physical structure of metals'},
    'mikrostrukturne': {'C1': 'Adjective', 'n': 'Microstructural; the small-scale structure of a material visible under a microscope'},
    'analize': {'B1': 'Noun (Plural)', 'n': 'Analyses; the detailed examination of grains and slip systems'},
    'prvenstveno': {'B2': 'Adverb', 'n': 'Primarily; occurring mostly along specific shear planes'},
    'događa': {'B1': 'Verb', 'n': 'Happens/Occurs; the formation of cracks in favorable grains'},
    'uzduž': {'B1': 'Preposition', 'n': 'Along; the path following specific slip directions'},
    'povoljno': {'B2': 'Adverb', 'n': 'Favorably; orientations that make it easier for the material to slip'},
    'orijentisane': {'B2': 'Adjective', 'n': 'Oriented; the geometric alignment of grains relative to the load'},
    'klizanje': {'B2': 'Noun, Gerund', 'n': 'Slip/Sliding; the movement of crystal planes against each other'},
    'lokalni': {'B1': 'Adjective', 'n': 'Local; occurring in a specific, limited area'},
    'lom': {'B2': 'Noun', 'n': 'Break/Fracture; the rupture of the oxide film on the metal surface'},
    'oksidnog': {'C1': 'Adjective', 'n': 'Oxide; relating to the thin layer of corrosion products on the surface'},
    'filma': {'B1': 'Noun', 'n': 'Film; the protective layer that breaks and reforms (repassivates)'},
    'repasivizaciju': {'C1': 'Noun', 'n': 'Repassivation; the process where a broken oxide layer heals itself'},
    'zapažanja': {'B2': 'Noun (Plural)', 'n': 'Observations; the insights gained from microscopic study'},
    'podržavaju': {'B1': 'Verb', 'n': 'Support; the evidence backs up a specific mechanism'},
    'mehanizam': {'B2': 'Noun', 'n': 'Mechanism; the physical explanation for anodic dissolution'},
    'anodnog': {'C1': 'Adjective', 'n': 'Anodic; relating to the anode where oxidation and dissolution occur'},
    'rastvaranja': {'C1': 'Noun, Gerund', 'n': 'Dissolution; the process of metal ions dissolving into the water'},
    'jasnu': {'B1': 'Adjective', 'n': 'Clear; an obvious connection between strain and crack density'},
    'povezanost': {'B2': 'Noun', 'n': 'Connection/Correlation; the link between different experimental variables'},
    'gustine': {'B2': 'Noun', 'n': 'Density; the number of surface cracks per unit area'},
    'površinskih': {'B1': 'Adjective', 'n': 'Surface; cracks that originate and are visible on the outside of the material'},
    'osnovnu': {'B1': 'Adjective', 'n': 'Basic/Fundamental; referring to experimental insights as a base for modeling'},
    'eksperimentalnih': {'B2': 'Adjective', 'n': 'Experimental; derived from lab tests rather than theory'},
    'uvida': {'B2': 'Noun', 'n': 'Insights; the understanding gained from the data'},
    'razvijen': {'B1': 'Adjective', 'n': 'Developed; a model created for a specific simulation goal'},
    'zasnovan': {'B1': 'Adjective', 'n': 'Based; built upon the principles of crystal plasticity'},
    'ciljem': {'B2': 'Noun', 'n': 'Goal/Aim; the objective of simulating coupled processes'},
    'simulacije': {'B2': 'Noun (Plural)', 'n': 'Simulations; computer-based recreations of physical processes'},
    'spregnutih': {'C1': 'Adjective', 'n': 'Coupled; two processes (mechanical and chemical) that influence each other'},
    'procesa': {'A2': 'Noun (Plural)', 'n': 'Processes; the sequence of events leading to failure'},
    'vode': {'B1': 'Verb', 'n': 'Lead; mechanisms that result in the initiation of cracks'},
    'implementiran': {'B2': 'Adjective', 'n': 'Implemented; built into a software environment like Abaqus'},
    'pomoću': {'B1': 'Preposition', 'n': 'Using/By means of; using a UMAT subroutine for the code'},
    'potprograma': {'C1': 'Noun', 'n': 'Subroutine; a specialized piece of code used to extend simulation software'},
    'fenomenološki': {'C1': 'Adjective', 'n': 'Phenomenological; based on observed behaviors rather than fundamental laws'},
    'okvir': {'B2': 'Noun', 'n': 'Framework; the theoretical structure of the model'},
    'zakonom': {'B1': 'Noun', 'n': 'Law/Rule; specifically the damage law used in the model'},
    'oštećenja': {'B1': 'Noun', 'n': 'Damage; the internal degradation tracked by the software'},
    'baziranom': {'B1': 'Adjective', 'n': 'Based; relying on Gutman’s interaction theories'},
    'teoriji': {'B1': 'Noun', 'n': 'Theory; the scientific explanation for mechanical-electrochemical behavior'},
    'prema': {'A2': 'Preposition', 'n': 'According to; following the work of a specific scientist'},
    'parametri': {'B1': 'Noun (Plural)', 'n': 'Parameters; the numerical constants that define the model'},
    'podataka': {'B1': 'Noun', 'n': 'Data; the evidence used for calibration'},
    'izvedene': {'B1': 'Adjective', 'n': 'Carried out/Performed; the simulations conducted on the specimen cross-section'},
    'reprezentativnom': {'C1': 'Adjective', 'n': 'Representative; a small section that accurately reflects the whole material'},
    'presjeku': {'B2': 'Noun', 'n': 'Cross-section; the internal view of the specimen'},
    'uspješno': {'B1': 'Adverb', 'n': 'Successfully; describing the model’s ability to capture key features'},
    'opisuje': {'B1': 'Verb', 'n': 'Describes; explaining or representing experimental characteristics'},
    'ključne': {'B1': 'Adjective', 'n': 'Key/Crucial; the most important features of the experiment'},
    'uključujući': {'B1': 'Preposition', 'n': 'Including; covering aspects like damage localization'},
    'lokalizaciju': {'C1': 'Noun', 'n': 'Localization; the concentration of damage in specific areas'},
    'orientiranim': {'B2': 'Adjective', 'n': 'Oriented; grains positioned in a way that encourages damage'},
    'predviđeni': {'B2': 'Adjective', 'n': 'Predicted; the calculated number of cycles before failure'},
    'broj': {'A1': 'Noun', 'n': 'Number; the count of cycles until crack initiation'},
    'ciklusa': {'B1': 'Noun (Plural)', 'n': 'Cycles; repeated loading events in a fatigue test'},
    'slaže': {'B1': 'Verb', 'n': 'Agrees/Matches; the model predictions align with the lab results'},
    'više': {'A1': 'Adverb', 'n': 'Multiple/More; testing at several different strain levels'},
    'kombinovani': {'B1': 'Adjective', 'n': 'Combined; the mixture of experimental and numerical work'},
    'program': {'A1': 'Noun', 'n': 'Program; the organized plan of experimental activities'},
    'numerički': {'B2': 'Adjective', 'n': 'Numerical; computer-based math and simulation methods'},
    'disertaciji': {'C1': 'Noun', 'n': 'Dissertation; the formal thesis presenting the doctoral research'},
    'unapređuju': {'B2': 'Verb', 'n': 'Improve/Advance; enhancing the ability to predict failure'},
    'sposobnost': {'B1': 'Noun', 'n': 'Ability/Capability; the power to forecast crack initiation'},
    'predviđanja': {'B2': 'Noun, Gerund', 'n': 'Predicting; the act of forecasting future failure events'},
    'nuklearnim': {'B1': 'Adjective', 'n': 'Nuclear; relating to environments inside a power plant'},
    'rad': {'A1': 'Noun', 'n': 'Work/Research; the contribution made by this dissertation'},
    'doprinosi': {'B2': 'Verb', 'n': 'Contributes; adding to the reliability of reactor components'},
    'pouzdanom': {'B2': 'Adjective', 'n': 'Reliable; trustworthy operation and life extension'},
    'postavlja': {'B1': 'Verb', 'n': 'Sets/Lays; establishing the foundation for future studies'},
    'temelje': {'B1': 'Noun (Plural)', 'n': 'Foundations; the basis for upcoming research on environment interactions'},
    'buduća': {'A2': 'Adjective', 'n': 'Future; studies that will follow this work'},
    'istraživanja': {'B1': 'Noun (Plural)', 'n': 'Research/Studies; further investigations into complex material behavior'},
    'složenija': {'B2': 'Adjective', 'n': 'More complex; future work involving even more variables'},
    'ključne riječi': {'B1': 'Noun (Plural)', 'n': 'Keywords; the most significant terms used to index the research'},
    'lahkovodni': {'C1': 'Adjective', 'n': 'Light-water; see "lahkovodnih reaktora"'},
    'mehaničko-elektrohemijska': {'C1': 'Adjective', 'n': 'Mechanical-electrochemical; relating to the coupled interaction of force and chemistry'},

    'zamaranja': {'B2': 'Noun (Genitive)', 'n': 'Of fatigue; the process of material weakening under cyclic loads'},
    'pukotina': {'B2': 'Noun (Genitive, Plural)', 'n': 'Of cracks; referring to the gaps or fractures forming in the steel'},
    'corsci': {'C1': 'Noun, Artifact', 'n': 'Likely an abbreviation or scan error for "Corrosion Science", a leading journal in material degradation'},
    'kao': {'A1': 'Conjunction', 'n': 'As / Like; used for comparisons (e.g., as in the case of corrosion)'},
    'korozionog': {'B2': 'Adjective', 'n': 'Corrosive / Of corrosion; describing the nature of the fatigue or environment'},
    'korrosionsutmattning': {'C1': 'Noun (Swedish)', 'n': 'Corrosion fatigue; the Swedish equivalent of "koroziono zamaranje"'},
    'ijfatigue': {'C1': 'Proper Noun', 'n': 'International Journal of Fatigue; a major academic publication for fatigue research'},
    'koji': {'A1': 'Pronoun', 'n': 'Which / Who; a relative pronoun used to link clauses'},
    'mechanicalelectrochemical': {'C1': 'Adjective', 'n': 'Mechanical-electrochemical; relating to the simultaneous interaction of physical stress and chemical corrosion'},
    'pri': {'B1': 'Preposition', 'n': 'At / During; used to denote conditions (e.g., at room temperature)'},
    'reaktora': {'B2': 'Noun (Genitive)', 'n': 'Of the reactor; relating to the nuclear power generation system'},
    'degradacije': {'B2': 'Noun (Genitive)', 'n': 'Of degradation; the breakdown of material properties'},
    'korozije': {'B1': 'Noun (Genitive)', 'n': 'Of corrosion; the chemical eating away of the metal'},
    'Rezultati': {'A2': 'Noun (Plural)', 'n': 'Results; the findings or data points gathered from experiments'},
    'između': {'B1': 'Preposition', 'n': 'Between; describing the interaction between two different phenomena'},
    'nuklearnih': {'B2': 'Adjective', 'n': 'Nuclear; relating to the energy released by atomic nuclei'},
    'ova': {'A1': 'Pronoun', 'n': 'This / These; a demonstrative pronoun (feminine/neuter plural)'},
    'ovoj': {'A1': 'Pronoun', 'n': 'This; a demonstrative pronoun (dative/locative feminine)'},
    'produženje': {'B2': 'Noun', 'n': 'Extension; the act of making the operational life of a component longer'},
    'radnog': {'B2': 'Adjective', 'n': 'Working / Operational; describing the life or conditions of the reactor'},

}
