# -*- coding: utf-8 -*-
# -*- mode: python; python-indent-offset: 4 -*-
#
# Some useful dicts and lists - for Polish
#
#
# 2026-03-20
#
# G. Q. Maguire Jr.
#
#
# Abbreviations used:
#  CEFR   Common European Framework of Reference for Languages: Learning, teaching, assessment.
#  POS    Part Of Speech
#
# This file contains several dicts and lists - these contain 'word' entries, but a 'word' can actually be a string of several words.
#
# Lists have been used when there can be multiple entries for the same 'word' and where there is not CEFR and POS information.
#
#
# Each dict's structure is:
# dict_name = {
#    entry,
#    entry,
# }
# Each entry is a 'word': CEFR_POS_dict
#
# a CEFR_POS_dict entry is a dict with the keys being CEFR levels (A1, A2, B1, B2, C1, C2, XX, and NA)
# followed by a string that contains comma separated POS
#
# The code 'XX' is used for an unknown CEFR level, while NA is for use when no level is applicable:
# 
# 

common_polish_words = {
    "aby": {"A2": "Conjunction", "n": "In order to; so that"},
    "ale": {"A1": "Conjunction", "n": "But; however"},
    "analizowane": {"B2": "Adjective", "n": "Analyzed; being the subject of an analysis"},
    "analizowanymi": {"C1": "Adjective", "n": "With/by those being analyzed (instrumental case)"},
    "badań": {"B2": "Noun", "n": "Research; studies (genitive plural)"},
    "badany": {"B2": "Adjective", "n": "Studied; examined; under investigation"},
    "bardziej": {"A2": "Adverb", "n": "More; to a greater degree"},
    "bazie": {"B1": "Noun", "n": "Base; basis (locative case)"},
    "bez": {"A2": "Preposition", "n": "Without"},
    "By": {"B1": "Particle", "n": "Would; in order to (conditional/purpose marker)"},
    "celu": {"B1": "Noun", "n": "Goal; aim; purpose (locative/genitive case)"},
    "celulozowej": {"C1": "Adjective", "n": "Cellulosic; made of cellulose (feminine singular)"},
    "celulozowych": {"C1": "Adjective", "n": "Cellulosic (plural)"},
    "charakteryzowany": {"C1": "Adjective", "n": "Characterized; defined by specific traits"},
    "choć": {"B1": "Conjunction", "n": "Although; even though"},
    "co": {"A1": "Pronoun", "n": "What; which"},
    "czynnikami": {"B2": "Noun", "n": "Factors (instrumental plural)"},
    "czynników": {"B2": "Noun", "n": "Factors (genitive plural)"},
    "dalej": {"A2": "Adverb", "n": "Further; further on"},
    "dalszego": {"B1": "Adjective", "n": "Further; subsequent (genitive masculine/neuter)"},
    "dalszej": {"B1": "Adjective", "n": "Further (genitive/dative/locative feminine)"},
    "dążącym": {"C1": "Adjective", "n": "Striving; aiming toward (dative/instrumental)"},
    "dla": {"A1": "Preposition", "n": "For"},
    "długotrwałych": {"B2": "Adjective", "n": "Long-term; long-lasting"},
    "do": {"A1": "Preposition", "n": "To; into; until"},
    "dodatkowo": {"B1": "Adverb", "n": "Additionally; in addition"},
    "dodatku": {"B1": "Noun", "n": "Additive; addition (genitive/locative case)"},
    "dopasować": {"B1": "Verb", "n": "To fit; to match; to adjust"},
    "dopasowywania": {"B2": "Noun", "n": "Matching; fitting; alignment (verbal noun)"},
    "dostosowane": {"B2": "Adjective", "n": "Adjusted; tailored; adapted"},
    "dwóch": {"A2": "Number", "n": "Two (genitive/accusative masculine personal)"},
    "dzisiejszym": {"B1": "Adjective", "n": "Today's; contemporary"},
    "efekt": {"B1": "Noun", "n": "Effect; result"},
    "efektami": {"B1": "Noun", "n": "Effects; results (instrumental plural)"},
    "Efekty": {"B1": "Noun", "n": "Effects (plural)"},
    "eksperymentalną": {"B2": "Adjective", "n": "Experimental (feminine accusative/instrumental)"},
    "fizycznie": {"B1": "Adverb", "n": "Physically"},
    "formowania": {"C1": "Noun", "n": "Forming; shaping; molding (verbal noun)"},
    "formowanie": {"C1": "Noun", "n": "Forming; the process of shaping"},
    "formowaniem": {"C1": "Noun", "n": "Forming (instrumental case)"},
    "gęstość": {"B2": "Noun", "n": "Density"},
    "gęstości": {"B2": "Noun", "n": "Density (genitive/dative/locative)"},
    "gęstościach": {"B2": "Noun", "n": "Densities (locative plural)"},
    "głębsze": {"B1": "Adjective", "n": "Deeper (comparative)"},
    "godnymi": {"B2": "Adjective", "n": "Worthy (instrumental plural)"},
    "gospodarki": {"B2": "Noun", "n": "Economy; management (genitive singular/nominative plural)"},
    "higroekspansji": {"C2": "Noun", "n": "Hygroexpansion; moisture-induced expansion"},
    "i": {"A1": "Conjunction", "n": "And"},
    "ich": {"A1": "Pronoun", "n": "Their; them"},
    "ilości": {"B1": "Noun", "n": "Quantity; amount (genitive singular/nominative plural)"},
    "inżynieryjnych": {"C1": "Adjective", "n": "Engineering-related (plural)"},
    "jak": {"A1": "Adverb", "n": "How; like; as"},
    "jednak": {"B1": "Conjunction", "n": "However; yet"},
    "jednym": {"A2": "Number", "n": "One (instrumental/locative)"},
    "jego": {"A1": "Pronoun", "n": "His; its"},
    "jest": {"A1": "Verb", "n": "Is (third person singular)"},
    "Jest": {"A1": "Verb", "n": "Is (capitalized)"},
    "jeszcze": {"A2": "Adverb", "n": "Still; yet; even"},
    "kg/m3": {"B2": "Noun", "n": "Kilograms per cubic meter; unit of density"},
    "kierunkach": {"B1": "Noun", "n": "Directions (locative plural)"},
    "kierunków": {"B1": "Noun", "n": "Directions (genitive plural)"},
    "kluczowe": {"B2": "Adjective", "n": "Key; crucial; pivotal"},
    "kolei": {"B1": "Noun", "n": "Turn (phrase 'z kolei' means 'in turn')"},
    "konkretnych": {"B1": "Adjective", "n": "Specific; concrete"},
    "kopalnych": {"B2": "Adjective", "n": "Fossil (e.g., fossil fuels)"},
    "która": {"A1": "Pronoun", "n": "Which; who (feminine)"},
    "kulki": {"B1": "Noun", "n": "Balls; beads; spheres"},
    "lepszego": {"A2": "Adjective", "n": "Better (comparative genitive)"},
    "mającymi": {"B2": "Verb", "n": "Having (present participle instrumental plural)"},
    "materiał": {"B1": "Noun", "n": "Material"},
    "Materiał": {"B1": "Noun", "n": "Material (capitalized)"},
    "materiałach": {"B1": "Noun", "n": "Materials (locative plural)"},
    "materiałów": {"B1": "Noun", "n": "Materials (genitive plural)"},
    "materiałowych": {"B2": "Adjective", "n": "Material-related (plural)"},
    "materiału": {"B1": "Noun", "n": "Material (genitive case)"},
    "materiały": {"B1": "Noun", "n": "Materials (plural)"},
    "mechaniczne": {"B2": "Adjective", "n": "Mechanical"},
    "mechanicznych": {"B2": "Adjective", "n": "Mechanical (plural)"},
    "mechanizmy": {"B2": "Noun", "n": "Mechanisms"},
    "metody": {"B1": "Noun", "n": "Methods (plural)"},
    "między": {"A2": "Preposition", "n": "Between; among"},
    "modele": {"B2": "Noun", "n": "Models (plural)"},
    "Modelowanie": {"C1": "Noun", "n": "Modeling (process)"},
    "modyfikacja": {"B2": "Noun", "n": "Modification"},
    "modyfikacji": {"B2": "Noun", "n": "Modification (genitive/locative)"},
    "modyfikowane": {"B2": "Adjective", "n": "Modified"},
    "mogą": {"A2": "Verb", "n": "Can; may (third person plural)"},
    "mokrych": {"A2": "Adjective", "n": "Wet (plural)"},
    "molekularnych": {"C1": "Adjective", "n": "Molecular (plural)"},
    "możliwych": {"B1": "Adjective", "n": "Possible (plural)"},
    "można": {"A2": "Adverb", "n": "One can; it is possible"},
    "na": {"A1": "Preposition", "n": "On; for; at"},
    "nad": {"A2": "Preposition", "n": "Over; above; upon"},
    "najprawdopodobniej": {"B1": "Adverb", "n": "Most likely"},
    "najstarszych": {"B1": "Adjective", "n": "Oldest (superlative)"},
    "naprężeń": {"C1": "Noun", "n": "Stresses (genitive plural)"},
    "naprężenie-odkształcenie": {"C2": "Noun", "n": "Stress-strain (relationship)"},
    "nasycenia": {"C1": "Noun", "n": "Saturation (genitive/plural)"},
    "nie": {"A1": "Particle", "n": "No; not"},
    "Niemniej": {"B2": "Adverb", "n": "Nevertheless; nonetheless"},
    "niezbędne": {"B2": "Adjective", "n": "Essential; necessary"},
    "Niniejsza": {"C1": "Adjective", "n": "This; the present (formal/academic)"},
    "niniejszej": {"C1": "Adjective", "n": "The present (formal feminine genitive/dative)"},
    "niszczenia": {"B2": "Noun", "n": "Destruction; failure; degradation"},
    "niższymi": {"A2": "Adjective", "n": "Lower (comparative instrumental plural)"},
    "nowej": {"A1": "Adjective", "n": "New (genitive/dative/locative feminine)"},
    "nowych": {"A1": "Adjective", "n": "New (plural)"},
    "numeryczne": {"C1": "Adjective", "n": "Numerical"},
    "o": {"A1": "Preposition", "n": "About; with"},
    "obciążenia:": {"B2": "Noun", "n": "Loads; stresses (plural)"},
    "obiegu": {"B2": "Noun", "n": "Circulation; loop (genitive case)"},
    "obróbkę": {"B2": "Noun", "n": "Processing; treatment (accusative case)"},
    "obszarze": {"B1": "Noun", "n": "Area; region; field (locative case)"},
    "oceniane": {"B2": "Adjective", "n": "Evaluated; assessed"},
    "od": {"A1": "Preposition", "n": "From; than"},
    "oddziaływań": {"C1": "Noun", "n": "Interactions (genitive plural)"},
    "odzwierciedlić": {"C1": "Verb", "n": "To reflect; to mirror"},
    "opracowania": {"B2": "Noun", "n": "Development; study; elaboration"},
    "oraz": {"B1": "Conjunction", "n": "As well as; and"},
    "osiągnięcia": {"B2": "Noun", "n": "Achievement; attainment (genitive singular/nominative plural)"},
    "otrzymany": {"B1": "Adjective", "n": "Obtained; received"},
    "otwartych": {"A2": "Adjective", "n": "Open (plural)"},
    "owych": {"C1": "Pronoun", "n": "Those; the aforementioned (plural)"},
    "papier": {"A1": "Noun", "n": "Paper"},
    "papieru": {"A1": "Noun", "n": "Paper (genitive case)"},
    "pełni": {"B1": "Noun", "n": "Fullness (phrase 'w pełni' means 'fully')"},
    "pewnym": {"B1": "Adjective", "n": "Certain; sure (instrumental/locative)"},
    "plastików": {"B1": "Noun", "n": "Plastics (genitive plural)"},
    "płaszczyźnie": {"C1": "Noun", "n": "Plane; level (locative case)"},
    "płaszczyzny": {"C1": "Noun", "n": "Planes (plural) or plane (genitive)"},
    "podczas": {"B1": "Preposition", "n": "During"},
    "podkreślają": {"B2": "Verb", "n": "Emphasize; highlight (third person plural)"},
    "połączeń": {"B2": "Noun", "n": "Connections; joints (genitive plural)"},
    "połączenia": {"B2": "Noun", "n": "Connections (plural)"},
    "Połączenia": {"B2": "Noun", "n": "Connections (capitalized)"},
    "połączeniach": {"B2": "Noun", "n": "Connections (locative plural)"},
    "połączeniami": {"B2": "Noun", "n": "Connections (instrumental plural)"},
    "Połączenie": {"B2": "Noun", "n": "Connection; joint"},
    "połączonych": {"B2": "Adjective", "n": "Connected; joined (plural)"},
    "półstrukturalnych": {"C1": "Adjective", "n": "Semi-structural (plural)"},
    "pomiary": {"B2": "Noun", "n": "Measurements (plural)"},
    "Pomimo": {"B1": "Preposition", "n": "Despite; in spite of"},
    "pomocą": {"B1": "Noun", "n": "Help; aid (phrase 'za pomocą' means 'by means of')"},
    "poprawy": {"B1": "Noun", "n": "Improvement (genitive singular/nominative plural)"},
    "poprzez": {"B1": "Preposition", "n": "Through; by means of"},
    "porównaniu": {"B1": "Noun", "n": "Comparison (locative case)"},
    "porównywalnych": {"B2": "Adjective", "n": "Comparable (plural)"},
    "postawę": {"B2": "Noun", "n": "Attitude; posture (accusative case)"},
    "poszerzania": {"B2": "Noun", "n": "Broadening; expanding (verbal noun)"},
    "powierzchniowa": {"B2": "Adjective", "n": "Surface (feminine)"},
    "powierzchniową": {"B2": "Adjective", "n": "Surface (accusative/instrumental feminine)"},
    "powierzchniowych": {"B2": "Adjective", "n": "Surface (plural)"},
    "powierzchwniowych": {"B2": "Adjective", "n": "Surface (likely misspelling of powierzchniowych)"},
    "powstających": {"B2": "Verb", "n": "Arising; emerging (present participle plural)"},
    "powszechnie": {"B1": "Adverb", "n": "Commonly; widely"},
    "poziomami": {"B2": "Noun", "n": "Levels (instrumental plural)"},
    "poziomie": {"B2": "Noun", "n": "Level (locative case)"},
    "poznane": {"B1": "Adjective", "n": "Known; explored"},
    "pozostaje": {"B1": "Verb", "n": "Remains (third person singular)"},
    "pozwala": {"B1": "Verb", "n": "Allows; permits"},
    "praca": {"A1": "Noun", "n": "Work; paper; study"},
    "pracy": {"A1": "Noun", "n": "Work (genitive/locative case)"},
    "prób": {"B2": "Noun", "n": "Tests; trials; attempts (genitive plural)"},
    "próbek": {"B2": "Noun", "n": "Samples (genitive plural)"},
    "proces": {"B1": "Noun", "n": "Process"},
    "Proces": {"B1": "Noun", "n": "Process (capitalized)"},
    "procesu": {"B1": "Noun", "n": "Process (genitive case)"},
    "produktów": {"A2": "Noun", "n": "Products (genitive plural)"},
    "prostopadłe": {"B2": "Adjective", "n": "Perpendicular"},
    "prowadzi": {"B1": "Verb", "n": "Leads; conducts"},
    "przekonań:": {"B2": "Noun", "n": "Beliefs; convictions (genitive plural)"},
    "przyjętych": {"B2": "Adjective", "n": "Accepted; adopted (plural)"},
    "przykładzie": {"B1": "Noun", "n": "Example (locative case)"},
    "przypadku": {"B1": "Noun", "n": "Case (locative case)"},
    "pulpy": {"C1": "Noun", "n": "Pulp (genitive singular/nominative plural)"},
    "realistyczne": {"B2": "Adjective", "n": "Realistic"},
    "roli": {"B1": "Noun", "n": "Role (locative/genitive case)"},
    "również": {"B1": "Adverb", "n": "Also; as well"},
    "rozbudowy": {"B2": "Noun", "n": "Expansion; extension (genitive singular)"},
    "rozciągania": {"C1": "Noun", "n": "Tension; stretching; pulling (verbal noun)"},
    "rozciąganie": {"C1": "Noun", "n": "Tension; stretching"},
    "różnią": {"B2": "Verb", "n": "Differ (third person plural)"},
    "różniących": {"B2": "Verb", "n": "Differing (present participle plural)"},
    "różnych": {"A2": "Adjective", "n": "Different; various (plural)"},
    "różnymi": {"A2": "Adjective", "n": "Different (instrumental plural)"},
    "rozwiązań": {"B2": "Noun", "n": "Solutions (genitive plural)"},
    "są": {"A1": "Verb", "n": "Are (third person plural)"},
    "ścinanie": {"C1": "Noun", "n": "Shear; shearing"},
    "ściskanie": {"C1": "Noun", "n": "Compression; squeezing"},
    "się": {"A1": "Pronoun", "n": "Self (reflexive particle)"},
    "sieć": {"B1": "Noun", "n": "Network; net"},
    "sieci": {"B1": "Noun", "n": "Network; net (genitive/locative/plural)"},
    "sieciowe": {"B2": "Adjective", "n": "Network-related"},
    "sieciowego": {"B2": "Adjective", "n": "Network (genitive masculine/neuter)"},
    "sieciowym": {"B2": "Adjective", "n": "Network (locative masculine/neuter)"},
    "silnych": {"A2": "Adjective", "n": "Strong (plural)"},
    "skalach": {"B2": "Noun", "n": "Scales (locative plural)"},
    "składający": {"B2": "Verb", "n": "Consisting; composed of (present participle)"},
    "skonsolidowaną": {"C1": "Adjective", "n": "Consolidated (accusative/instrumental feminine)"},
    "skutkiem": {"B1": "Noun", "n": "Effect; consequence (instrumental case)"},
    "skutkuje": {"B2": "Verb", "n": "Results in (third person singular)"},
    "słabszych": {"A2": "Adjective", "n": "Weaker (comparative plural)"},
    "słabszymi": {"A2": "Adjective", "n": "Weaker (instrumental plural)"},
    "śledzenie": {"B2": "Noun", "n": "Tracking; tracing; following"},
    "Słowa": {"A1": "Noun", "n": "Words (plural)"},
    "sobą": {"A2": "Pronoun", "n": "Each other; self (instrumental)"},
    "społeczeństwie": {"B2": "Noun", "n": "Society (locative case)"},
    "środowiskowo": {"B2": "Adverb", "n": "Environmentally"},
    "stan": {"B1": "Noun", "n": "State; condition"},
    "stanowi": {"B2": "Verb", "n": "Constitutes; represents"},
    "stanowią": {"B2": "Verb", "n": "Constitute; represent (plural)"},
    "stanowić": {"B2": "Verb", "n": "To constitute; to be"},
    "statycznych": {"B2": "Adjective", "n": "Static (plural)"},
    "stopniu": {"B1": "Noun", "n": "Degree; extent (locative case)"},
    "stosowanych": {"B2": "Adjective", "n": "Applied; used (plural)"},
    "Streszczenie": {"B2": "Noun", "n": "Abstract; summary"},
    "struktury": {"B2": "Noun", "n": "Structures (plural) or structure (genitive)"},
    "stworzyć": {"B1": "Verb", "n": "To create"},
    "suchej": {"A2": "Adjective", "n": "Dry (genitive/locative feminine)"},
    "sucho": {"A2": "Adverb", "n": "Dryly (phrase 'na sucho' means 'dry')"},
    "surowców": {"B2": "Noun", "n": "Raw materials (genitive plural)"},
    "suszenia": {"B2": "Noun", "n": "Drying (verbal noun)"},
    "symulacje": {"B2": "Noun", "n": "Simulations (plural)"},
    "system": {"B1": "Noun", "n": "System"},
    "szerokim": {"B1": "Adjective", "n": "Wide; broad (locative/instrumental)"},
    "szerszym": {"B1": "Adjective", "n": "Wider (comparative)"},
    "tak": {"A1": "Adverb", "n": "Yes; so; in this way"},
    "te": {"A1": "Pronoun", "n": "These (non-masculine personal)"},
    "testowane": {"B1": "Adjective", "n": "Tested"},
    "to": {"A1": "Pronoun", "n": "It; this; that"},
    "trzech": {"A2": "Number", "n": "Three (genitive/locative)"},
    "tworzenie": {"B1": "Noun", "n": "Creating; formation"},
    "tworzonych": {"B1": "Adjective", "n": "Created; formed (plural)"},
    "tych": {"A1": "Pronoun", "n": "Those (plural)"},
    "tym": {"A1": "Pronoun", "n": "This (instrumental/locative masculine/neuter)"},
    "typów": {"B1": "Noun", "n": "Types (genitive plural)"},
    "uchwycić": {"C1": "Verb", "n": "To capture; to grasp"},
    "ujawnia": {"B2": "Verb", "n": "Reveals; discloses"},
    "ulepszonych": {"B2": "Adjective", "n": "Improved; enhanced (plural)"},
    "uproszczoną": {"B2": "Adjective", "n": "Simplified (feminine accusative/instrumental)"},
    "Uwzględniając": {"B2": "Verb", "n": "Considering; taking into account (present participle)"},
    "użyciem": {"B1": "Noun", "n": "Use (phrase 'z użyciem' means 'using')"},
    "uzyskania": {"B2": "Noun", "n": "Obtaining; reaching (genitive)"},
    "w": {"A1": "Preposition", "n": "In; into"},
    "W": {"A1": "Preposition", "n": "In (capitalized)"},
    "warunkach": {"B1": "Noun", "n": "Conditions (locative plural)"},
    "wciąż": {"B1": "Adverb", "n": "Still; continuously"},
    "wcześniej": {"A2": "Adverb", "n": "Earlier; previously"},
    "wersję": {"B1": "Noun", "n": "Version (accusative case)"},
    "wewnętrzny": {"B2": "Adjective", "n": "Internal; inner"},
    "wiedzy": {"B1": "Noun", "n": "Knowledge (genitive case)"},
    "wiele": {"A2": "Adverb", "n": "Many; much"},
    "wielu": {"A2": "Adjective", "n": "Many (plural genitive/locative)"},
    "właściwości": {"B2": "Noun", "n": "Properties; characteristics (plural)"},
    "Właściwości": {"B2": "Noun", "n": "Properties (capitalized)"},
    "właściwościach": {"B2": "Noun", "n": "Properties (locative plural)"},
    "włókien": {"C1": "Noun", "n": "Fibers (genitive plural)"},
    "włóknami": {"C1": "Noun", "n": "Fibers (instrumental plural)"},
    "włóknistych": {"C1": "Adjective", "n": "Fibrous (plural)"},
    "wody": {"A1": "Noun", "n": "Water (genitive singular/nominative plural)"},
    "wpływ": {"B1": "Noun", "n": "Influence; impact"},
    "wpływających": {"B2": "Verb", "n": "Influencing (present participle plural)"},
    "Wreszcie": {"B1": "Adverb", "n": "Finally; at last"},
    "wskutek": {"B2": "Preposition", "n": "As a result of; due to"},
    "współcześnie": {"B1": "Adverb", "n": "Nowadays; contemporarily"},
    "Wybrane": {"B1": "Adjective", "n": "Selected (plural)"},
    "Wykazano": {"B2": "Verb", "n": "Shown; demonstrated (impersonal past)"},
    "wykorzystać": {"B1": "Verb", "n": "To use; to utilize"},
    "wymagającym": {"B2": "Adjective", "n": "Demanding (dative/instrumental)"},
    "Wyniki": {"B1": "Noun", "n": "Results (plural)"},
    "wynikiem": {"B1": "Noun", "n": "Result (instrumental case)"},
    "wysokiej": {"A2": "Adjective", "n": "High (feminine genitive/dative/locative)"},
    "występujących": {"B2": "Verb", "n": "Occurring; appearing (present participle plural)"},
    "wytworzonych": {"B2": "Adjective", "n": "Manufactured; produced (plural)"},
    "wytworzyć": {"B2": "Verb", "n": "To produce; to manufacture"},
    "wyzwanie": {"B2": "Noun", "n": "Challenge"},
    "wzrostu": {"B1": "Noun", "n": "Growth; increase (genitive case)"},
    "z": {"A1": "Preposition", "n": "With; from"},
    "za": {"A1": "Preposition", "n": "For; behind; after"},
    "zachodzi": {"B2": "Verb", "n": "Occurs; happens"},
    "zakresie": {"B2": "Noun", "n": "Range; scope (locative case)"},
    "zalety": {"B1": "Noun", "n": "Advantages; benefits"},
    "zależność": {"B2": "Noun", "n": "Dependency; relationship"},
    "zamkniętego": {"B1": "Adjective", "n": "Closed (genitive masculine/neuter)"},
    "zaprezentowane": {"B2": "Adjective", "n": "Presented"},
    "zarówno": {"B1": "Conjunction", "n": "Both (paired with 'jak i')"},
    "zastępcami": {"B2": "Noun", "n": "Substitutes; deputies (instrumental plural)"},
    "zastosowań": {"B2": "Noun", "n": "Applications (genitive plural)"},
    "zastosowaniach": {"B2": "Noun", "n": "Applications (locative plural)"},
    "ze": {"A1": "Preposition", "n": "From; with (variant of 'z')"},
    "że": {"A1": "Conjunction", "n": "That"},
    "zjawisk": {"B2": "Noun", "n": "Phenomena (genitive plural)"},
    "zjawiska": {"B2": "Noun", "n": "Phenomena (plural) or phenomenon (genitive)"},
    "zjawiskami": {"B2": "Noun", "n": "Phenomena (instrumental plural)"},
    "złożony": {"B2": "Adjective", "n": "Complex; complicated"},
    "zmianę": {"B1": "Noun", "n": "Change (accusative case)"},
    "zmiany": {"B1": "Noun", "n": "Changes (plural)"},
    "znaczenie": {"B1": "Noun", "n": "Meaning; significance"},
    "zrozumienia": {"B2": "Noun", "n": "Understanding (genitive/plural)"},
    "zrozumienie": {"B2": "Noun", "n": "Understanding (noun)"},
    "zwanej": {"B2": "Adjective", "n": "Called; known as (feminine genitive/dative/locative)"},
    "zwanych": {"B2": "Adjective", "n": "Called; known as (plural)"},
    "związanymi": {"B2": "Adjective", "n": "Associated; connected (instrumental plural)"},
    "zwiększenie": {"B2": "Noun", "n": "Increase; enhancement"},

}

