# -*- coding: utf-8 -*-
# -*- mode: python; python-indent-offset: 4 -*-
#
# Some useful dicts and lists - for Italian
#
#
# 2026-02-01
#
# G. Q. Maguire Jr.
#
#
# Abbreviations used:
#  CEFR   Common European Framework of Reference for Languages: Learning, teaching, assessment.
#  POS    Part Of Speech
#
# This file contains several dicts and lists - these contain 'word' entries, but a 'word' can actually be a string of several words.
#
# Lists have been used when there can be multiple entries for the same 'word' and where there is not CEFR and POS information.
#
#
# Each dict's structure is:
# dict_name = {
#    entry,
#    entry,
# }
# Each entry is a 'word': CEFR_POS_dict
#
# a CEFR_POS_dict entry is a dict with the keys being CEFR levels (A1, A2, B1, B2, C1, C2, XX, and NA)
# followed by a string that contains comma separated POS
#
# The code 'XX' is used for an unknown CEFR level, while NA is for use when no level is applicable:
# 
# 
common_italian_words={
    "Combinatorica": {"B1": "Noun", "n": "Combinatorics; the branch of mathematics dealing with counting, arrangement, and combination of elements within finite sets"},
    "nelle": {"A1": "Preposition (Contraction)", "n": "In the (feminine plural); used to describe locations, such as 'nelle' (in the) 'chiese' (churches) or 'nelle' (in the) 'sezioni' (sections)"},
    "d'Urbino": {"B1": "Proper Noun (Possessive/Origin)", "n": "From/Of Urbino; referring to the city or the Duchy of Urbino, a major center for 'architettura' and Renaissance 'culto'"},
    "culto": {"B1": "Noun (Masculine)", "n": "Cult / Worship; the religious use of an 'edifice' or 'Kirchenkunst' which dictates its 'liturgiska' arrangement"},
    "Palazzo": {"A1": "Noun (Masculine)", "n": "Palace / Building; a grand urban 'edifice', often featuring 'väggdekor' and serving as an 'istituto'"},
    "d'Italia": {"A1": "Proper Noun (Phrase)", "n": "Of Italy; common in institutional titles such as 'Soprintendenza d'Italia' or 'Dizionario d'Italia'"},
    "d'Ossat": {"B2": "Proper Noun", "n": "Guglielmo De Angelis d'Ossat; influential Italian architect and 'restauratör' known for his 'teoria del restauro'"},
    "ragionamenti": {"B1": "Noun (Plural)", "n": "Reasonings / Discourses; systematic 'studi' or 'Commento' regarding 'architettura' or art theory"},
    "restituita": {"B2": "Adjective / Participle (Feminine)", "n": "Restored / Returned; the goal of an 'intervento' to see an 'edifice' 'restituita' to its historical dignity"},

    "vivente": {"A2": "Adjective", "n": "Living; used to describe 'tradizione vivente' (living tradition) or contemporary 'biolog' factors"},
    "sociale": {"A2": "Adjective", "n": "Social; relating to the 'valore sociale' (social value) of a 'Denkmal' within its community"},
    "organisatio": {"B2": "Noun (Archaic/Latinate)", "n": "Organization; (Modern: organizzazione). The administrative 'organisational' structure of a 'byrå'"},
    "dovesse": {"B1": "Verb (Subjunctive Past)", "n": "Should / Might have to; used in legal 'istruzione' regarding what 'dovesse' be done for 'conservering'"},
    "donatione": {"B1": "Noun (Feminine Archaic)", "n": "Donation; (Modern: donazione). A 'beställning' or grant from 'privata' 'Kunstfreunde'"},
    "alcuni": {"A1": "Pronoun / Adjective (Plural)", "n": "Some / A few; referring to 'alcuni' (some) 'fragmentets' or specific 'edifices'"},
    "bollettino": {"B1": "Noun (Masculine)", "n": "Bulletin / Journal; a periodic 'Beretning' such as the 'Bollettino d'Arte' for 'konstvetenskap'"},
    "Archeologia": {"A2": "Noun (Feminine)", "n": "Archaeology; the 'forskning' into 'fornlemningar' and 'antiquiteter'"},
    "Antichità": {"B1": "Noun (Feminine)", "n": "Antiquity / Antiquities; the 'Antichità e Belle Arti' department responsible for 'Denkmalschutz'"},
    "Accademia": {"A2": "Noun (Feminine)", "n": "Academy; the 'Accademia di Belle Arti' or a scholarly 'istituto' like the 'Antikvitetsakademin'"},

    "scienze": {"B1": "Noun (Plural)", "n": "Sciences; referring to 'scienze applicate' (applied sciences) in the 'laboriatorio' of conservation"},
    "intervento": {"B1": "Noun (Masculine)", "n": "Intervention; the specific 'Eingriffe' or restoration action performed on a monument"},
    "dipinte": {"A2": "Adjective / Participle (Feminine Plural)", "n": "Painted; as in 'superfici dipinte' (painted surfaces) or frescoes"},
    "Stampe": {"B1": "Noun (Plural)", "n": "Prints / Engravings; often part of the 'Disegni e Stampe' (Drawings and Prints) archive"},
    "Soprintendenza": {"B2": "Noun (Feminine)", "n": "Superintendency; the Italian state body responsible for 'Denkmalschutz' and oversight"},
    "Generali": {"A2": "Adjective (Plural)", "n": "General; as in 'Direzione Generali' (General Directorates) or 'studi generali'"},
    "Daipooichê": {"C1": "Conjunction (Archaic/Variant)", "n": "Since / Seeing that; (Modern: Dopodiché or Poiché). Found in older 'handskriftssamlingen'"},
    "convegno": {"B1": "Noun (Masculine)", "n": "Conference / Symposium; a gathering like a 'Fachtagung' for scholarly 'Erfarenhetsutbytet'"},
    "conoscere": {"A2": "Verb", "n": "To know / To be acquainted with; the goal of 'arkivforskning' to 'conoscere' the history of a site"},
    "Commento": {"A2": "Noun (Masculine)", "n": "Commentary / Analysis; a critical 'Commento' in a 'Catalogue raisonné'"},
    "Certo": {"A1": "Adjective / Adverb", "n": "Certain / Sure; used to confirm the 'echten' (authentic) nature of a finding"},
    "Catalogo": {"A2": "Noun (Masculine)", "n": "Catalog; a systematic 'materialreferenssamling' of artworks or archival files"},
    "Castel": {"A2": "Noun (Masculine)", "n": "Castle; (Short for Castello). A fortified 'edifice' or 'Fortezza'"},
    "Cappella": {"A2": "Noun (Feminine)", "n": "Chapel; a small 'Kirchenraum' or 'kapellet' within a larger church or palace"},
    "dichiarate": {"B1": "Adjective / Verb (Past Participle)", "n": "Declared; referring to 'opere dichiarate' (declared works), officially recognized as heritage"},
    "dichiarazioni": {"B2": "Noun (Plural)", "n": "Declarations / Statements; the formal 'dichiarazioni di interesse' (declarations of interest) used in heritage law"},
    "complemento": {"B2": "Noun (Masculine)", "n": "Complement / Supplement; an addition that completes a 'Gesamtwirkung' or a 'dossier'"},
    "basso": {"A2": "Adjective / Noun", "n": "Low / Bottom; as in 'basso rilievo' (bas-relief) or describing the 'basso' (lower) section of a 'parete' (wall)"},
    "Dizionario": {"A2": "Noun (Masculine)", "n": "Dictionary; a reference work like a 'Handbuch' or 'Encyclopédie' for 'terminologia' research"},
    "Disegni": {"B1": "Noun (Plural)", "n": "Drawings; specifically 'Disegni e Stampe' (Drawings and Prints), a common archival department"},
    "Direzione": {"B1": "Noun (Feminine)", "n": "Direction / Directorate; the administrative 'Direzione Generale' overseeing 'fornminnesvård'"},
    "Descrizione": {"A2": "Noun (Feminine)", "n": "Description; the technical 'Descrizione' of an object's 'Etats' (condition) in an 'utredning'"},
    "Gabinetto": {"B2": "Noun (Masculine)", "n": "Cabinet / Department; as in 'Gabinetto Restauro', a specialized technical 'laboriatorio' or office"},
    "trouate": {"A1": "Verb (Archaic/Variant)", "n": "Found; (Modern: trovate). Often seen in 19th-century 'familjepapperen' or informal reports"},
    "possa": {"B1": "Verb (Subjunctive)", "n": "Can / May / Might; used in 'istruzione' to describe what 'possa essere' (might be) possible in a restoration"},
    "necessario": {"A2": "Adjective", "n": "Necessary; used in technical 'utredningar' to signal 'necessario intervento' (necessary intervention)"},
    "Trenta": {"A1": "Numeral", "n": "Thirty; e.g., 'gli anni Trenta' (the 1930s), a pivotal era for 'Historizität' and 'nationalstil' in Italy"},
    "Frage": {"B1": "Noun (Germanism)", "n": "Question; occasionally used in bilingual 'Historieteoretiska' debates (German: Frage)"},
    "Fortezza": {"B1": "Noun (Feminine)", "n": "Fortress; a type of military 'monumentalverk' requiring specific 'konserveringmetoder'"},
    "Esigenze": {"B2": "Noun (Plural)", "n": "Requirements / Needs; the 'esigenze conservative' (conservation needs) of an object"},
    "Enciclopedia": {"B1": "Noun (Feminine)", "n": "Encyclopedia; a systematic 'Gesamtausgabe' of knowledge, such as the 'Enciclopedia Italiana'"},

    "vetro": {"A2": "Noun (Masculine)", "n": "Glass; referring to 'vetro istoriato' (stained glass) or 'vasi di vetro' (glass vessels) found in 'graffältet'"},
    "sono": {"A1": "Verb (Present)", "n": "Are / Am; used in descriptions like 'le pareti sono decorate' (the walls are decorated)"},
    "linguistica": {"B2": "Noun (Feminine)", "n": "Linguistics; the study of language used to analyze 'handstilen' or regional 'dialetti' in archives"},
    "indovinar": {"B2": "Verb (Archaic/Infinitive)", "n": "To guess / To divine; (Modern: indovinare). Used in the context of identifying 'feltolkades' (misinterpreted) motifs"},
    "intendersi": {"B1": "Verb (Reflexive)", "n": "To understand one another / To be an expert in; e.g., 'intendersi di restauro' (to be an expert in restoration)"},
    "inuentione": {"C1": "Noun (Archaic)", "n": "Invention / Composition; (Modern: invenzione). Refers to the original 'gestaltats' concept or design of an artwork"},
    "anni": {"A1": "Noun (Plural)", "n": "Years; used for dating 'Instandsetzungen' or determining the 'Zeitalter' of an object"},
    "architettura": {"A2": "Noun (Feminine)", "n": "Architecture; the primary field of 'kyrkoarkitekt' and 'monumentalverk' studies"},
    "Gloriosa": {"B1": "Adjective (Feminine)", "n": "Glorious; often used in religious contexts, such as 'Vergine Gloriosa' (Glorious Virgin)"},
    "Giugno": {"A1": "Noun (Masculine)", "n": "June; a common month for archival dating in 'dossier' and 'arkivakten'"},
    "universitario": {"A2": "Adjective", "n": "University-related; referring to the 'ambito universitario' where 'Kunstwissenschaft' and research are conducted"},
    "propria": {"A2": "Adjective (Feminine)", "n": "Own / Specific; used to describe the 'caratteristica propria' (specific characteristic) of a material or style"},
    "negli": {"A1": "Preposition (Combined)", "n": "In the / Among the; e.g., 'negli archivi' (in the archives) or 'negli anni' (in the years)"},
    "formale": {"B1": "Adjective", "n": "Formal; relating to the 'analisi formale' (formal analysis) of the 'plastique' qualities of a work"},
    "debba": {"B1": "Verb (Subjunctive)", "n": "Must / Should; used in 'istruzione' to indicate actions that 'debba essere' (must be) taken during restoration"},
    "dell'ambinete": {"B1": "Noun (Genitive/Misspelling)", "n": "Of the environment; common typo for 'dell'ambiente', referring to 'Inomhusklimatet' or the surrounding context"},
    "dell'espressione": {"B2": "Noun (Genitive)", "n": "Of the expression; relating to the 'mezzi dell'espressione' (means of expression) used by a 'pittore'"},
    "centrale": {"A2": "Adjective", "n": "Central; as in the 'Istituto Centrale per il Restauro', the 'huvudenhet' for Italian conservation"},
    "Laboriatorio": {"B1": "Noun (Variant)", "n": "Laboratory / Workshop; a variant spelling of 'Laboratorio' where 'analisi' and 'mållerikonservering' are performed"},
    "scienza": {"A2": "Noun (Feminine)", "n": "Science; often refers to 'la scienza del restauro' (the science of restoration)"},
    "rigattino": {"C1": "Noun (Technical)", "n": "Hatching / Cross-hatching; a specific Italian conservation technique for retouching (tratteggio) using fine vertical lines"},
    "originale": {"A2": "Adjective", "n": "Original; referring to the 'stato originale' (original state) of a monument or artwork"},
    "l'Europa": {"A1": "Proper Noun", "n": "Europe; the broader geographical and cultural context for 'l'arte sacra'"},
    "istruzione": {"B1": "Noun (Feminine)", "n": "Education / Instruction; often refers to official guidelines issued by a ministry"},
    "fiorentino": {"B1": "Adjective", "n": "Florentine; relating to Florence, the historical heart of 'scienza' and art conservation"},
    "dall'antichità": {"B1": "Phrase", "n": "From antiquity; referring to the classical origins of architectural 'metodi'"},
    "cosa": {"A1": "Noun (Feminine)", "n": "Thing / Matter; used in general descriptions or phrases like 'la cosa pubblica' (the public matter/state)"},
    "Italiano": {"A1": "Adjective/Proper Noun", "n": "Italian; pertaining to the language, people, or the unified 'Regno d'Italia'"},
    "Istruzione": {"B1": "Noun (Proper)", "n": "Instruction / Education; often capitalized in 'Ministero della Pubblica Istruzione'"},
    "Ispettore": {"B2": "Noun (Masculine)", "n": "Inspector; the equivalent of the French 'Inspecteur', an official overseeing 'monumenti'"},
    "Istituto": {"B1": "Noun (Masculine)", "n": "Institute; a specialized body like the 'Istituto Centrale per il Restauro' (ICR)"},
    "Inutile": {"B1": "Adjective", "n": "Useless"},

    "su": {"A1": "Preposition", "n": "On / About; used to indicate location or the subject of a study (e.g., 'studi su Giotto')"},
    "pubblica": {"A2": "Adjective / Verb", "n": "Public / Publishes; refers to the 'pubblica amministrazione' or the act of releasing a 'Manuale'"},
    "ragionato": {"B2": "Adjective", "n": "Reasoned / Systematic; typically used in the phrase 'catalogo ragionato,' an exhaustive, annotated list of an artist’s works"},
    "pittore": {"A1": "Noun (Masculine)", "n": "Painter; the artist responsible for the 'immagini' or 'freschi' within a monument"},
    "distingua": {"B2": "Verb (Subjunctive/Imperative)", "n": "Distinguish / Set apart; used in technical texts to differentiate between original layers and later 'intervento'"},
    "amboni": {"C1": "Noun (Masculine Plural)", "n": "Ambones / Pulpits; raised platforms in a church used for reading the Gospel and Epistles"},
    "cauate": {"C1": "Adjective (Archaic)", "n": "Hollowed out / Excavated; (Modern: cavate). Often refers to architectural elements carved from stone or 'stanze cauate' (hewn rooms)"},
    "libro": {"A1": "Noun (Masculine)", "n": "Book; can refer to a physical volume or a specific section of a larger legal or technical 'Manuale'"},
    "lessico": {"B2": "Noun (Masculine)", "n": "Lexicon / Vocabulary; the specialized set of terms used within a field like 'architettura' or 'restauro'"},
    "laboratorio": {"B1": "Noun (Masculine)", "n": "Laboratory / Workshop; the space where scientific 'analisi' or practical 'restauro' takes place"},
    "L'Estetica": {"B2": "Proper Noun", "n": "Aesthetics; often cited in French texts when referencing Italian aesthetic theory (e.g., Benedetto Croce)"},
    "L'Italia": {"A1": "Proper Noun", "n": "Italy; frequently appears in French travelogues and art history as the primary source of 'l'art sacré'"},
    "L'arte": {"B1": "Noun", "n": "Art; Italian loanword often used in French discussions of 'L'arte povera' or Renaissance history"},
    "L'eridità": {"C1": "Noun", "n": "Heritage / Inheritance; an Italian term appearing in French texts regarding the 'eridità culturale' (cultural heritage)"},
    "L'occulatmento": {"C1": "Noun", "n": "The concealment / Hiding; likely a variant of 'L'occultamento'. Refers to the hiding or covering of artworks/frescoes"},

    "l'intervento": {"B2": "Noun", "n": "The intervention; the Italian term 'intervento' frequently appears in French restoration texts to describe a specific conservation action"},
    "remarquables": {"B1": "Adjective (French Loanword)", "n": "Remarkable / Notable; often used in Italian art catalogs of the 19th century to highlight 'remarquable' works, reflecting the period's French academic influence"},
    "studi": {"A2": "Noun (Masculine Plural)", "n": "Studies; refers to both academic research papers and preparatory sketches/drawings made by an artist"},
    "mancare": {"B1": "Verb (Infinitive)", "n": "To be missing / To fail; used in condition reports to denote missing fragments of a fresco or the 'failure' of a structural element"},
    "imagini": {"B1": "Noun (Feminine Plural - Archaic)", "n": "Images; an older spelling of 'immagini' (modern Italian uses the double 'm'). Refers to icons, figures, or visual representations"},
    "geni": {"B2": "Noun (Masculine Plural)", "n": "Geniuses / Spirits; refers to the 'geni loci' (spirit of the place) or the creative geniuses of the Renaissance"},
    "dell'Arena": {"B2": "Proper Noun Phrase", "n": "Of the Arena; most commonly refers to the Scrovegni Chapel (Cappella degli Scrovegni) in Padua, famous for Giotto's frescoes"},
    "didattici": {"B1": "Adjective (Plural)", "n": "Didactic / Educational; refers to art or museum displays intended to instruct the public in history or morality"},
    "astratti": {"B2": "Adjective (Plural)", "n": "Abstract; in 19th-century terms, often referring to theoretical or 'abstracted' principles of design rather than non-representative art"},
    "architettonico": {"A2": "Adjective (Masculine)", "n": "Architectural; pertaining to the structural and stylistic design of buildings"},
    "Risorgimento": {"B1": "Proper Noun", "n": "Risorgimento; the 19th-century movement for Italian unification, which heavily influenced the 'patriotic' restoration of monuments"},
    "Manuale": {"B1": "Noun (Masculine)", "n": "Manual / Handbook; a technical guide for practitioners, such as Boito's manuals on restoration ethics"},
    "Macchia": {"C1": "Noun (Feminine)", "n": "Spot / Sketch; refers to a 'stain' or 'sketch,' and specifically to the 'Macchiaioli'—a group of Italian painters who used spots of color"},
    "Maestra": {"B1": "Noun (Feminine) / Adjective", "n": "Master / Main; refers to a 'master' teacher or the 'parete maestra' (main load-bearing wall)"},
    "Ministero": {"B1": "Noun (Masculine)", "n": "Ministry; the government body (e.g., 'Ministero della Pubblica Istruzione') overseeing national heritage"},

    "tuttavia": {"A2": "Conjunction", "n": "However / Nevertheless; used in scholarly arguments to introduce a counterpoint or qualification"},
    "prinicipi": {"B1": "Noun (Plural - Misspelling)", "n": "Principles; a common typographical error for 'principi' (extra 'i')"},
    "potuto": {"A2": "Verb (Past Participle)", "n": "Been able to; the past participle of 'potere'. Used to describe what was possible during a past restoration"},
    "peincipi": {"B1": "Noun (Plural - Misspelling)", "n": "Principles; a common typographical error for 'principi' (e instead of r)"},
    "pensiero": {"B2": "Noun (Masculine)", "n": "Thought / Philosophy; refers to the theoretical framework or school of thought behind an intervention"},
    "ministro": {"B1": "Noun (Masculine)", "n": "Minister; refers to a high-ranking government official (e.g., 'Ministro della Pubblica Istruzione')"},
    "illusio": {"C1": "Noun (Archaic/Latinate)", "n": "Illusion; an archaic form or a specific philosophical reference to the 'deception' of the eye in art"},
    "descrittione": {"C1": "Noun (Feminine - Archaic)", "n": "Description; the Renaissance/Baroque spelling of 'descrizione'. Frequently used in titles of historical treatises"},
    "detti": {"A2": "Adjective / Noun (Plural)", "n": "Said / Called; used to refer back to previously mentioned objects or 'the so-called' elements"},
    "culturali": {"A2": "Adjective (Plural)", "n": "Cultural; as in 'beni culturali' (cultural heritage/assets)"},
    "Nascita": {"B1": "Noun (Feminine)", "n": "Birth / Origin; used to discuss the 'nascita' of a movement or the provenance of an artist"},
    "Marzo": {"A1": "Noun (Masculine)", "n": "March; the third month of the year. In historical conservation records, this often marks the beginning of the 'building season' as weather conditions improved for masonry and fresco work"},
    "toni": {"B1": "Noun (Masculine Plural)", "n": "Tones / Hues; refers to the color values and gradations in a painting, essential for discussing 'patina'"},
    "stabilire": {"B2": "Verb (Infinitive)", "n": "To establish / To fix; used when determining the date of a work or 'fixing' loose pigment during restoration"},
    "semestrale": {"B1": "Adjective / Noun", "n": "Semiannual / Half-yearly; often refers to the frequency of academic journals or progress reports"},
    "pittre": {"C1": "Noun (Archaic/Typo)", "n": "Painters; likely an archaic variant or OCR error for 'pittori'. Refers to the artists themselves"},
    "operazioni": {"B1": "Noun (Feminine Plural)", "n": "Operations / Procedures; the specific technical steps taken during a restoration project (e.g., cleaning, consolidating)"},
    "overo": {"C1": "Conjunction (Archaic)", "n": "Or / That is to say; archaic spelling of 'ovvero'. Used to introduce an alternative name or explanation"},
    "communi": {"C1": "Adjective (Archaic Spelling)", "n": "Common; older spelling of 'comuni' with a double 'm'. Refers to shared traits or public property"},
    "accademico": {"B1": "Adjective", "n": "Academic; relating to formal art education or the 'insegnamento accademico' mentioned previously"},
    "affreschi": {"B1": "Noun (Masculine Plural)", "n": "Frescoes; the technique of mural painting on freshly laid lime plaster (the Italian equivalent of 'kalkmålningar')"},
    "avrebbero": {"B1": "Verb (Conditional)", "n": "They would have; used in historical hypothesis regarding how a building 'would have' looked before changes"},
    "Profano": {"B2": "Adjective", "n": "Secular / Profane; art or architecture that is not religious in nature, often contrasted with 'Sacro'"},
    "Profilili": {"C1": "Noun (Misspelling)", "n": "Profiles; a typographical error for 'Profili'. Refers to architectural cross-sections or side views of faces"},
    "Pratiche": {"B1": "Noun (Feminine Plural)", "n": "Practices / Files; can refer to the 'pratice di restauro' (restoration records) or administrative dossiers"},
    "Povera": {"B1": "Adjective (Feminine)", "n": "Poor / Humble; as in 'Arte Povera' (using simple materials) or describing the modest state of a ruin"},
    "Postilla": {"C1": "Noun (Feminine)", "n": "Marginal note / Annotation; a handwritten comment found in the margin of a historical manuscript or report"},
    "Pietà": {"B1": "Proper Noun / Noun", "n": "Pietà / Pity; the iconographic depiction of the Virgin Mary cradling the dead body of Jesus"},
    "perché": {"A1": "Conjunction", "n": "Because / Why; used to explain the rationale behind a specific conservation choice"},
    "percorsi": {"B2": "Noun (Masculine Plural)", "n": "Paths / Routes; refers to the physical flow of visitors through a museum or the historical 'trajectory' of a style"},
    "Pensiero": {"B2": "Noun (Masculine)", "n": "Thought / Thinking; the theoretical framework or 'philosophy' behind an artistic movement"},
    "Nuovi": {"A1": "Adjective (Masculine Plural)", "n": "New; often used in titles describing recent discoveries or 'Nuovi studi' (New studies)"},
    "pirrorici": {"C2": "Adjective (Archaic/Rare)", "n": "Pyrrhic; likely a misspelling or archaic variant related to 'pirrico' (Pyrrhic), or a specific reference to the Greek philosopher Pyrrho in a theoretical art context"},
    "dallo": {"A1": "Contraction", "n": "From the / By the; contraction of the preposition 'da' (from/by) and the masculine definite article 'lo'"},
    "dell'insegnamento accademico": {"B2": "Noun Phrase", "n": "Of academic teaching; referring to the formalized instruction provided by Art Academies (e.g., Accademia di Belle Arti)"},
    "dell'insegnamento": {"B1": "Noun Phrase", "n": "Of teaching / Of instruction; referring to the pedagogical aspect of art or science"},
    "dell'isegnamento": {"C1": "Noun Phrase (Misspelling)", "n": "Of teaching; a common typographical error or archaic variant of 'dell'insegnamento' (missing the 'n')"},
    "descialbo": {"C1": "Noun (Masculine)", "n": "Descialbo; the technical process of removing layers of whitewash or plaster to reveal underlying frescoes or paintings"},
    "divisione": {"B1": "Noun (Feminine)", "n": "Division; can refer to an administrative department or the artistic technique of 'Divisionismo' (Pointillism variant)"},
    "celebri": {"A2": "Adjective (Plural)", "n": "Famous / Celebrated; used to describe renowned artists or landmark monuments"},
    "artistico": {"A1": "Adjective", "n": "Artistic; relating to art or the aesthetic quality of an object"},
    "Rivista": {"B1": "Noun (Feminine)", "n": "Review / Magazine / Journal; frequently used in the titles of academic publications (e.g., 'Rivista del Restauro')"},
    "Iconologia": {"C1": "Noun (Feminine)", "n": "Iconology; the branch of art history that studies the deeper meaning and symbolism within images, famously established by Cesare Ripa"},
    "Retireringen": {"C1": "Noun (Scandinavian/Italian Hybrid)", "n": "The Relining; likely a Swedish/Danish adaptation of the Italian 're-intelatura' or a specific technical term used in mixed-language conservation reports"},
    "Reale": {"B1": "Adjective", "n": "Royal; often found in the names of national institutions (e.g., 'Reale Accademia')"},
    "Questo": {"A1": "Pronoun/Adjective", "n": "This; demonstrative used to specify a particular object or subject in the text"},
    "Pubbliche": {"A2": "Adjective (Feminine Plural)", "n": "Public; usually referring to 'Opere Pubbliche' (Public Works) or 'Istituzioni Pubbliche'"},
    "Pubblica": {"A2": "Adjective (Feminine Singular)", "n": "Public; as in 'Pubblica Amministrazione' or 'Istruzione Pubblica'"},
    
    "asterremo": {"B2": "Verb (Future)", "n": "We shall abstain; first-person plural future of 'astenersi' (to refrain from an action or a vote)"},
    "cicli": {"B2": "Noun (Masculine Plural)", "n": "Cycles; a series of artworks (such as frescoes) that narrate a story or a theological theme"},
    "dell'OIM": {"B2": "Proper Noun (+ Article)", "n": "Of the IOM; relating to the International Organization for Migration or a specific historical acronym"},
    "insieme": {"A1": "Adverb / Noun", "n": "Together / Set; the totality of elements or a coordinated way of acting"},
    "mediovali": {"B1": "Adjective (Plural - Archaic)", "n": "Medieval; relating to the Middle Ages. Frequently found in 19th-century texts before the standardization to 'medievali'"},
    "moderno": {"A2": "Adjective (Masculine)", "n": "Modern; referring to the current era or the historical period following the Middle Ages"},
    "occultamento": {"C1": "Noun (Masculine)", "n": "Concealment / Hiding; the act of covering architectural or decorative elements"},
    "riparazioni riprazioni": {"B2": "Noun (Plural - Archaic/Typo)", "n": "Repairs; maintenance interventions or the restoration of an artifact (Correct: )"},

    "principo": {"B2": "Noun (Masculine - Archaic)", "n": "Principle / Beginning; the start, foundation, or theoretical basis of a work or thought (Modern: principio)"},
    "riforma": {"B1": "Noun (Feminine)", "n": "Reform; a substantial modification of a system, institution, or religious movement"},
    "riprazioni": {"B2": "Noun (Plural - Archaic/Typo)", "n": "Repairs; maintenance interventions or the restoration of an artifact (Correct: riparazioni)"},
    "Schizofrenia": {"C1": "Noun (Feminine)", "n": "Schizophrenia; a psychic disorder, used metaphorically to indicate a split or inconsistency in a system"},
    "Scipione": {"-": "Proper Noun", "n": "Scipione; a male given name (e.g., Scipio Africanus or the painter Gino Bonichi, known as Scipione)"},
    "Scoperta": {"B1": "Noun (Feminine)", "n": "Discovery; the finding of an artifact or the identification of new historical data"},
    "Scritti": {"B1": "Noun (Plural)", "n": "Writings; literary works, essays, or documents written by an author"},
    "Sopraintendenzia": {"C1": "Noun (Archaic)", "n": "Superintendency; the local office of the Ministry of Culture responsible for safeguarding heritage (Modern spelling: Soprintendenza)"},
    "ci": {"A1": "Pronoun / Adverb", "n": "Ci; reflexive pronoun, pronominal particle, or adverb of place (there/here)"},
    "liturgico": {"B2": "Adjective (Masculine)", "n": "Liturgical; relating to liturgy or religious worship"},
    "medievali": {"B1": "Adjective (Plural)", "n": "Medieval; relating to the Middle Ages (approx. 5th–15th century)"},
    "metodologia": {"C1": "Noun (Feminine)", "n": "Methodology; the systematic study of methods applied to research or restoration"},
    "oggetti": {"A2": "Noun (Plural)", "n": "Objects; artifacts or material elements analyzed in a museum or conservation context"},
    "origine": {"B1": "Noun (Feminine)", "n": "Origin / Provenance; the starting point or historical source of a work or idea"},
    "pratica": {"B1": "Noun (Feminine)", "n": "Practice / Dossier; the concrete application of a theory or an administrative file"},
    "precedimenti": {"B2": "Noun (Plural - Typo)", "n": "Proceedings / Procedures; a series of connected acts or phases to achieve an end (Correct: procedimenti)"},
    "regionali": {"B1": "Adjective (Plural)", "n": "Regional; relating to a specific geographical or administrative region"},
    "seduta": {"B1": "Noun (Feminine)", "n": "Meeting / Session; a formal gathering of a committee or assembly"},
    "segreteria": {"A2": "Noun (Feminine)", "n": "Secretary's office / Secretariat; the office in charge of administrative management and correspondence"},
    "sul": {"A1": "Preposition (Contraction)", "n": "On the (su + il)"},
    "sulle": {"A1": "Preposition (Contraction)", "n": "On the (su + le)"},
    "Storie": {"A2": "Noun (Plural)", "n": "Stories / Histories; often used in titles like 'Storie dell'arte' (Histories of Art)"},
    "Supplemento": {"B2": "Noun (Masculine)", "n": "Supplement; an addition to a document, journal, or book to provide further information"},
    "Teoria": {"B1": "Noun (Feminine)", "n": "Theory; a system of ideas intended to explain something, particularly in art or science"},
    "basato": {"A2": "Adjective / Participle", "n": "Based / Grounded; often used as 'basato su' (based on)"},
    "distanza": {"A2": "Noun (Feminine)", "n": "Distance; can refer to physical space or a temporal gap in historical analysis"},
    "fondatori": {"B2": "Noun (Plural)", "n": "Founders; the individuals who establish an institution, movement, or set of principles"},
    "l'attività": {"A2": "Noun (Feminine + Article)", "n": "The activity / The work / The operation"},
    "scopo": {"B1": "Noun (Masculine)", "n": "Purpose / Aim / Goal; the objective of a specific activity or project"},
    "sulla": {"A1": "Preposition (Contraction)", "n": "On the / About the (su + la)"},
    "tecnici": {"B1": "Noun (Plural) / Adjective", "n": "Technicians / Technical; professionals who handle the practical application of a craft or science"},
    "linee": {"B1": "Noun", "n": "Lines; Refers to linear elements or stylistic directions"},
    "ingegneri": {"A2": "Noun", "n": "Engineers; professionals specializing in structure and technique"},
    "Teorie": {"B1": "Noun (Plural)", "n": "Theories; systematic formulations of principles, such as restoration theories"},
    "Uffici": {"A1": "Noun (Plural)", "n": "Offices; administrative workplaces or, historically, the Florentine magistracies"},
    "avevano": {"A2": "Verb (Imperfect)", "n": "They had; third-person plural of 'avere' (to have)"},
    "dell'ottocento": {"B1": "Phrase / Noun", "n": "Of the nineteenth century; relating to the 1800s (Ottocento)"},
    "quindi": {"A2": "Conjunction", "n": "Therefore / So / Consequently"},
    "vecchio": {"A1": "Adjective", "n": "Old / Ancient; belonging to a previous era or aged"},
    "aborra": {"C1": "Verb (Present Subjunctive/Imperative)", "n": "Abhors / Detests (from 'aborrire'); often used in moralistic art critiques"},
    "architetti": {"A2": "Noun (Plural)", "n": "Architects; professionals who design buildings and oversee their restoration"},
    "arti": {"A2": "Noun (Plural)", "n": "Arts; the various branches of creative activity"},
    "coperta": {"A2": "Noun (Feminine)", "n": "Cover / Blanket / Deck (of a ship); in a library context, it can refer to a book cover"},
    "figurative": {"B2": "Adjective (Plural)", "n": "Figurative; relating to art that represents recognizable forms (as opposed to abstract art)"},
    "ingegneri": {"A2": "Noun (Plural, corrected)", "n": "Engineers; specialists in structural stability and technical systems (Note: 'ingengeri' is a typo)"},
    "sistema": {"A2": "Noun (Masculine)", "n": "System; an organized set of principles or a technical assembly"},
    "verità": {"B1": "Noun (Feminine)", "n": "Truth; often refers to 'verità storica' (historical truth) or 'verità dei materiali' (truth to materials)"},
    "volentieri": {"A2": "Adverb", "n": "Willingly / Gladly / With pleasure"},

    "saponaria": {"C1": "Noun (Feminine)", "n": "Soapwort; a plant used in conservation for delicate cleaning due to its natural surfactants"},
    "rovine": {"B1": "Noun (Plural)", "n": "Ruins; the remains of a building that has suffered decay or destruction"},
    "riconoscimento": {"B2": "Noun", "n": "Recognition / Acknowledgement; in restoration, the critical act of identifying an object's cultural value"},
    "italiana": {"A1": "Adjective (Feminine)", "n": "Italian; relating to Italy"},
    "ingegneri": {"A2": "Noun (Plural)", "n": "Engineers; professionals specializing in structural stability and technical calculations"},
    "architetti": {"A2": "Noun (Plural)", "n": "Architects; professionals who design buildings and supervise restoration work"},
    "disegno": {"A1": "Noun", "n": "Drawing / Design; the graphic representation of an object or a preliminary plan"},
    "cautele": {"C1": "Noun (Plural)", "n": "Precautions / Safeguards; methodological cares taken to avoid damaging original historical material"},
    "attendere": {"B1": "Verb", "n": "To wait / To attend to; often used regarding the 'setting time' for materials or solvents"},
    "artistica": {"A2": "Adjective (Feminine)", "n": "Artistic; relating to art or the aesthetic quality of a work"},
    "al'altro": {"-": "Phrase (Archaic)", "n": "To the other; an elided form of 'all'altro'"},
    "carta": {"A1": "Sostantivo", "n": "Carta; il supporto cartaceo o documento"},
    "cromatica": {"B2": "Aggettivo (Femminile)", "n": "Cromatica; relativo ai colori o alla gamma dei colori"},
    "degli": {"A2": "Preposizione articolata", "n": "Di + gli; appartenente a loro o alcuni"},
    "desideri": {"B1": "Sostantivo (Plurale) / Verbo", "n": "Desideri; aspirazioni o desiderare (tu)"},
    "estetica": {"B2": "Sostantivo / Aggettivo", "n": "Estetica; la filosofia della bellezza e dell'arte"},
    "l'istanza": {"C1": "Sostantivo (Femminile)", "n": "L'istanza; richiesta o momento critico (es. 'istanza storica' o 'istanza estetica' nel restauro)"},
    "l'objet": {"-": "Sostantivo (Francese)", "n": "L'oggetto; termine spesso usato in saggi comparativi di estetica"},
    "li": {"A1": "Pronome / Avverbio", "n": "Li (pronome plurale) o Lì (avverbio di luogo)"},
    "metodologico": {"B2": "Aggettivo", "n": "Metodologico; relativo al metodo o alla logica di un processo scientifico"},
    "modellato": {"B2": "Sostantivo / Participio", "n": "Modellato; la resa plastica e tridimensionale di una figura"},
    "occupare": {"A2": "Verbo", "n": "Occupare; prendere spazio o dedicarsi a un'attività"},
    "procedere": {"B1": "Verbo", "n": "Procedere; andare avanti in un'operazione o un ragionamento"},
    "quadri": {"A2": "Sostantivo (Plurale)", "n": "Quadri; dipinti o cornici"},
    "radica": {"B2": "Verbo / Sostantivo", "n": "Radica (si radica) o legno di radica; riferito a qualcosa che ha radici profonde o a un materiale decorativo"},
    "tecnica": {"A2": "Sostantivo", "n": "Tecnica; l'insieme di regole e procedimenti pratici di un'arte"},
    "telle": {"-": "Aggettivo (Francese)", "n": "Tale; spesso presente in testi di influenza francofona"},
    "gomma": {"C1 (Technical)": "Noun", "n": "Rubber / Gum, In the phrase 'gomma pane', it refers to a kneaded eraser or dough used for surface cleaning."},
    "abbassamento": {"C1": "Noun", "n": "Lowering / Abatement / Subsidence (of a surface or structural element)"},
    "accomodare": {"B1": "Verb", "n": "To arrange / To repair / To accommodate"},
    "astanza": {"C2": "Noun", "n": "Astanza; a philosophical term in Italian aesthetics (Cesare Brandi) referring to the 'presence' or pure being of an artwork"},
    "astrazione": {"B2": "Noun", "n": "Abstraction"},
    "autenticità": {"B2": "Noun", "n": "Authenticity; the quality of being genuine or original"},
    "bianco": {"A1": "Noun / Adjective", "n": "White"},
    "capo": {"A2": "Noun", "n": "Head / Chief / End / Piece"},
    "cene": {"A2": "Noun (Plural)", "n": "Suppers / Dinners (often in 'Ultime Cene' - Last Suppers)"},
    "colla": {"B1": "Noun", "n": "Glue / Adhesive"},
    "conservatore": {"B2": "Noun", "n": "Conservator / Curator / Preserver"},
    "culturale": {"B1": "Adjective", "n": "Cultural"},
    "d'arte": {"A2": "Phrase", "n": "Of art / Artistic"},
    "d'une": {"-": "Phrase (French)", "n": "Of a / From one (Italian equivalent: d'una)"},
    "decalogo": {"B2": "Noun", "n": "Decalogue; a set of ten fundamental rules or principles"},
    "dell'analisi": {"B2": "Phrase", "n": "Of the analysis"},
    "dell'arte": {"A2": "Phrase", "n": "Of the art"},
    "deriva": {"B2": "Noun, Verb", "n": "Drift / Derivation / Steers (from 'derivare')"},
    "diagnostica": {"C1": "Noun / Adjective", "n": "Diagnostics; the scientific analysis of an object's state"},
    "emenita": {"-": "Proper Noun/Adj", "n": "Yemenite (Modern: yemenita)"},
    "fotografica": {"B1": "Adjective (Feminine)", "n": "Photographic"},
    "internazionale": {"B1": "Adjective", "n": "International"},
    "momento": {"A1": "Noun", "n": "Moment / Stage / Step (often used for a historical phase)"},
    "murali": {"B2": "Adjective (Plural)", "n": "Mural / Wall-based (as in 'pitture murali')"},
    "però": {"A2": "Conjunction", "n": "But / However / Yet"},
    "senza": {"A1": "Preposition", "n": "Without"},
    "termini": {"B1": "Noun (Plural)", "n": "Terms / Limits / Boundaries"},
    "transporre": {"C1": "Verb", "n": "To transpose / To transfer / To move (Modern: trasporre)"},

    "ottocento": {"B1": "Noun", "n": "The nineteenth century (1800s)"},
    "domini": {"B2": "Noun (Plural)", "n": "Domains / Territories / Dominions"},
    "documentazione": {"B1": "Noun", "n": "Documentation / Records"},
    "desto": {"B2": "Adjective", "n": "Awake / Alert / Sharp"},
    "dernier": {"B1": "Adjective (French)", "n": "Last / Latest (often used in art history for 'the latest style')"},
    "dell'Annunciazione": {"B2": "Phrase", "n": "Of the Annunciation (common dedication for churches and artworks)"},
    "dell'architettura": {"B1": "Phrase", "n": "Of architecture / Architectural"},
    "dell'opera": {"B1": "Phrase", "n": "Of the work / Of the opera / Of the cathedral workshop (Opera del Duomo)"},
    "dell'unità": {"B2": "Phrase", "n": "Of the unity / Of the unification (e.g., Unification of Italy)"},
    "dekokt": {"B2": "Noun (Germanic/Technical)", "n": "Decoction; a method of extraction by boiling, sometimes used in traditional varnish prep"},
    "decorazione": {"B1": "Noun", "n": "Decoration / Ornamentation"},
    "definizione": {"B1": "Noun", "n": "Definition"},
    "dalla": {"A1": "Preposition (Combined)", "n": "From the / By the"},
    "custodia": {"B1": "Noun", "n": "Custody / Care / Case / Shrine"},
    "cura": {"A2": "Noun", "n": "Care / Treatment / Oversight"},
    "cultura": {"A2": "Noun", "n": "Culture"},
    "critico": {"B1": "Noun / Adjective", "n": "Critic / Critical"},
    "costituice": {"B2": "Verb (Typo)", "n": "Constitutes (Standard: costituisce)"},
    "costituisce": {"B2": "Verb", "n": "Constitutes / Forms / Makes up"},
    "conservazione": {"B2": "Noun", "n": "Conservation / Preservation"},
    "contributo": {"B1": "Noun", "n": "Contribution"},
    "consiste": {"B1": "Verb", "n": "Consists / Lies in"},
    "consérvo": {"B1": "Verb", "n": "I preserve / I keep"},
    "congresso": {"B1": "Noun", "n": "Congress / Conference"},
    "conoscitore": {"C1": "Noun", "n": "Connoisseur; an expert judge in matters of taste and attribution"},
    "ciò": {"B1": "Pronoun", "n": "This / That / What"},
    "complesso": {"B1": "Noun / Adjective", "n": "Complex / Building complex / Complicated"},
    "chiesa": {"A1": "Noun", "n": "Church"},
    "caduto": {"B1": "Adjective / Participle", "n": "Fallen / Dropped"},
    "professionalità": {"B2": "Noun (Feminine)", "n": "Professionalism; the competence or skill expected of a professional"},
    "ommagio": {"A2": "Noun (Masculine)", "n": "Homage / Tribute; a sign of respect or a gift"},
    "internventi": {"B2": "Noun (Masculine Plural)", "n": "Interventions / Actions; in conservation, refers to the physical work performed on an object"},
    "falso": {"A2": "Adjective/Noun", "n": "False / Fake / Forgery; an object that is not authentic or is counterfeit"},
    "fondamento": {"B2": "Noun", "n": "Foundation / Basis; the underlying support of a structure or the justification for an idea"},
    "formazione": {"B1": "Noun", "n": "Formation / Education; the process of development, schooling, or the way something is structured"},
    "fresko-": {"B2": "Prefix", "n": "Fresco-related; pertaining to the technique of mural painting on wet lime plaster"},
    "generale": {"A2": "Adjective", "n": "General; relating to the whole or the majority; not specific"},
    "generell": {"B1": "Adjective (German/Swedish)", "n": "General; universal; broad or non-specific"},
    "gentibis": {"C2": "Noun (Latin/Archaic)", "n": "Likely a variant of 'gentibus' (to/for the peoples); used in historical or ecclesiastical contexts regarding nations or groups"},
    "gli": {"A1": "Article", "n": "The (Masculine plural definite article)"},
    "mostre": {"A2": "Noun (Plural)", "n": "Exhibitions; public displays of art, historical objects, or products"},
    "omaggio": {"A2": "Noun", "n": "Homage; a tribute or expression of high regard; a gift given as a sign of respect"},
    "musei": {"B1": "Noun (Italian Plural)", "n": "Museums"},
    "l'immagine": {"B1": "Noun (Italian)", "n": "The image"},
    "l'integrazione": {"B2": "Noun (Italian)", "n": "The integration (as in 'integrazione delle lacune' in restoration)"},

    "gestione": {"B1": "Noun (Feminine)", "n": "Management / Administration / Governance (e.g., 'gestione dei beni culturali' - management of cultural heritage)"},

    "riparazione": {"B1": "Noun", "n": "Repair / Restoration / Fixing"},
    "presenta": {"A2": "Verb (Present)", "n": "Presents / Shows / Features (e.g., 'la facciata presenta...' - the facade features...)"},

    "Appendice": {"A2": "Noun", 'n': "Appendix; a supplementary section at the end of a report or book containing additional data"},
    "Aracoeli": {"B2": "Proper Noun", 'n': "Altar of the Heavens; specifically referring to Santa Maria in Aracoeli, a prominent basilica in Rome built on the Capitoline Hill"},
    "Assisi": {"B1": "Proper Noun", 'n': "Assisi; home of the Basilica of St. Francis, a primary site for medieval mural conservation debates"},
    "Basilica": {"A2": "Noun", 'n': "Basilica; a large and important church building"},
    "Callisto": {"N/A": "Proper Noun", 'n': "Callisto; likely referring to the mythological figure or the specific chapel/painting involving the name"},
    "Ferrovie": {"B2": "Noun", 'n': "Railways; often used in the context of 'Ferrovie dello Stato', the Italian state railway system"},
    "Firenze": {"A1": "Proper Noun", 'n': "Florence; the major center for the 'Opificio delle Pietre Dure' and restoration history"},
    "Fondazione": {"B1": "Noun", 'n': 'Foundation; can refer to a physical structural base or a legal/charitable institution'},
    "Gestalt": {"C1": "Noun (German loan)", 'n': "Gestalt; the theory that the human brain perceives images as whole forms rather than just the sum of their parts. Central to how we view fragmented art"},
    "Italiane": {"A1": "Adjective (feminine plural form)"},
    "Lamiera": {"C1": "Noun", 'n': 'Sheet metal; a diagnostic material record in industrial design and structural engineering'},
    "Politecnico": {"B2": "Noun", 'n': 'Polytechnic; refers to technical universities specializing in engineering and architecture'},
    "Poste": {"A2": "Noun", 'n': "Post/Mail service; often part of 'Poste Italiane'"},
    "adagio": {"B1": "Adverb", 'n': 'Musical Term (Slowly; a tempo marking indicating a slow, leisurely pace)'},
    "al": {"A1": "Contraction", 'n': "To the / At the (a + il)"},
    "alla": {"A1": "Contraction", 'n': "To the / At the"},
    "allegro": {"B1": "Adverb", 'n': '/Musical Term (Cheerful/Lively; a tempo marking indicating a fast, brisk pace)'},
    "annunciazione": {"B1": "Noun", 'n': "Annunciation; the iconographic scene where the Angel Gabriel visits the Virgin Mary, a frequent subject in mural cycles"},
    "appena": {"A2": "Adverb", 'n': "Barely / Just; often used to describe interventions that are 'barely' visible to respect the original surface"},
    "appunti": {"A2": "Noun (Plural)", 'n': "Notes / Sketches; refers to field notes, rough drafts, or scholarly jottings found in archival folders"},
    "archeologica": {"A2": "Adjective (Feminine)", 'n': "Archaeological; relating to the scientific study of material remains (e.g., 'Soprintendenza Archeologica')"},
    "arte": {"B2": "Noun", 'n': 'Art; often used in philosophical or aesthetic citations'},
    "bacchette": {"B2": "Noun", 'n': "Rods/Sticks; can refer to drumsticks, conductors' batons, or small structural rods"},
    "bello": {"A1": "Adjective", 'n': 'Beautiful; a general aesthetic descriptor'},
    "che": {"A1": "Conjunction/Pronoun", 'n': "That / Which"},
    "classifica": {"A2": "Noun", 'n': 'Classification/Ranking; a record of order or hierarchy'},
    "colore": {"A1": "Noun", 'n': "Color"},
    "colore": {"A1": "Noun", 'n': "Color"},
    "confronti": {"B1": "Noun (Plural)", 'n': "Comparisons / Relations; used in the analysis of the relationships between different parts of a work"},
    "cui": {"B1": "Pronoun", 'n': "Which / Whom / Whose"},
    "da": {"A1": "Preposition", 'n': "From / By"},
    "dei": {"A1": "Preposition", 'n': "Of the (Plural); contraction of 'di + i'"},
    "del restauro": {"C1": "Noun", 'n': "Of restoration; often refers to 'Teoria del restauro', a foundational theory of conservation"},
    "del": {"A1": "Contraction", 'n': "Of the (di + il); Of the (masculine singular)"},
    "dell": {"B2": "Preposition", 'n': "Of; often found in titles like 'Teoria del restauro'"},
    "delle": {"A1": "Contraction", 'n': "Of the (plural)"},
    "dell’arte": {"B1": "Noun Phrase", 'n': "Of art; e.g., 'storia dell'arte' or 'opera d'arte'"},
    "dell’opera": {"B2": "Noun Phrase", 'n': "Of the work; referring to the physical and aesthetic existence of the 'opera'"},
    "dell’originale": {"B2": "Noun (Genitive)", 'n': "Of the original; a core concept regarding the preservation of the historical substance of the work"},
    "dell’ottocento": {"B2": "Noun Phrase", 'n': "Of the 1800s (19th century); an era known for stylistic 'ripristini'"},
    "dell’unità": {"C1": "Noun Phrase", 'n': "Of the unity; e.g., 'unità potenziale' (the potential unity of a fragmented work)"},
    "deve": {"B1": "Verb (Present)", 'n': "Must / Should; expresses the restorer's ethical obligation ('si deve...')"},
    "di": {"A1": "Preposition", 'n': 'Of/From; a foundational functional particle'},
    "differenza": {"A2": "Noun", 'n': "Difference; fundamental in critical restoration to distinguish the modern addition from the ancient fragment"},
    "dipinti": {"B1": "Noun (Plural)", 'n': "Paintings"},
    "documentaria": {"B2": "Adjective (Feminine)", 'n': "Documentary; relating to records or primary sources (e.g., 'ricerca documentaria' - documentary research)"},
    "dovrà": {"B1": "Verb (Future)", 'n': "Must / Shall have to"},
    "e": {"A1": "Conjunction", 'n': "And; a fundamental connector used in titles of laws or organizations (e.g., 'Tutela e Restauro')"},
    "essere": {"A1": "Verb (Infinitive)", 'n': "To be; fundamental to the ontology of the artwork"},
    "facile": {"A1": "Adjective", 'n': "Easy"},
    "federali": {"B2": "Adjective", 'n': 'Federal; plural form referring to national or central government systems'},
    "futuro": {"A2": "Noun", 'n': "Future; the restorer's duty to transmit the work to the future"},
    "il": {"A1": "Article", 'n': "The; masculine singular definite article"},
    "infatti": {"A2": "Conjunction", 'n': "In fact / Indeed; used to argue a technical or critical thesis"},
    "inoltre": {"B1": "Adverb", 'n': "Furthermore / Moreover; used to link theoretical arguments"},
    "italiani": {"A1": "Adjective/Noun (Plural)", 'n': "Italians / Italian; referring to the highly influential 'Italian School' of conservation"},
    "la": {"A1": "Article", 'n': "The; feminine singular definite article"},
    "lacune": {"B2": "Noun (Plural)", 'n': "Lacunae / Gaps; physical losses in the paint layer or support that interrupt the 'Gestalt'"},
    "le": {"A1": "Article (Plural Feminine)", 'n': "The"},
    "legato": {"B2": "Adjective", 'n': "Musical Term (Bound/Tied together; in music, notes played smoothly without gaps; in mechanics, 'linked'"},
    "l’immagine": {"B1": "Noun (Definite)", 'n': "The image; the aesthetic aspect of the work of art (the 'istanza estetica')"},
    "l’integrazione": {"B2": "Noun (Definite)", 'n': "Integration; the process of filling a gap (lacuna) to restore the formal unity of an image"},
    "mancanze": {"B2": "Noun (Plural)", 'n': "Losses / Gaps; missing parts of the paint layer or structure (lacunae)"},
    "mancanze": {"B2": "Noun (Plural)", 'n': "Losses / Gaps; often used interchangeably with 'lacune'"},
    "mantunendo": {"B2": "Verb (Gerund - variant)", 'n': "Maintaining / Preserving; the act of keeping values or material intact over time"},
    "materia": {"B2": "Noun", 'n': "Matter / Substance; the physical vehicle of the image (the 'istanza storica')"},
    "meglio": {"A2": "Adverb/Adjective", 'n': "Better; e.g., to 'meglio' understand a work's history"},
    "memofonte": {"B1": "Noun", "n": "A source of memory (Fountain of memory). Likely refers to 'Memofonte', the name of a prominent Italian foundation/digital archive dedicated to the study of art historical sources (Fondazione Memofonte)"},
    "metallo": {"A2": "Noun", 'n': 'Metal; a general material category'},
    "metà": {"B1": "Noun", 'n': "Half / Middle; e.g., 'metà dell'ottocento' (mid-19th century)"},
    "mezzatinta": {"C1": "Noun", 'n': "Mezzotint / Half-tone; a technique or state of color transition between light and shadow"},
    "negato": {"B1": "Adjective/Participle", 'n': "Denied; often used in the context of 'intervento negato' (denied intervention) or a lost feature"},
    "nei": {"A1": "Preposition", 'n': "In the (Plural); contraction of 'in + i'"},
    "nel": {"A1": "Contraction", 'n': "In the"},
    "nella": {"A1": "Contraction", 'n': "In the"},
    "non": {"A1": "Adverb", 'n': "Not"},
    "omaggio": {"B2": "Noun (Archaic spelling: ommagio)", 'n': "Homage / Respect; acting in respect to the original artist"},
    "onesto": {"B1": "Adjective", 'n': "Honest; used in the context of 'honest restoration' (restauro onesto), where interventions are visible and non-deceptive"},
    "onore": {"B1": "Noun", 'n': "Honor"},
    "peintures murales": {"C1": "Noun", 'n': 'Mural paintings; a term often used in international conservation literature'},
    "percettibile": {"B2": "Adjective", 'n': "Perceptible / Visible; referring to an integration that must be recognizable upon close inspection"},
    "perfetto": {"A2": "Adjective", 'n': "Perfect; often a point of critique, as 'perfecting' an object can lead to the loss of historical patina"},
    "piccole": {"A1": "Adjective (Plural)", 'n': "Small"},
    "pittura": {"A2": "Noun", 'n': "Painting"},
    "pitture": {"B1": "Noun (Plural)", 'n': "Paintings / Mural decorations"},
    "potenziale": {"B2": "Adjective", 'n': "Potential; used to describe the inherent wholeness that remains even in a damaged work"},
    "practico": {"B1": "Adjective (Archaic/Variant)", 'n': "Practical / Applied; (Modern: pratico)"},
    "primo": {"A1": "Adjective", 'n': "First"},
    "principio": {"B2": "Noun", 'n': "Principle; a fundamental rule or axiom of conservation (e.g., reversibility)"},
    "problema": {"A2": "Noun", 'n': "Problem; specifically theoretical dilemmas in conservation"},
    "profili": {"B1": "Noun (Plural)", 'n': "Profiles / Contours / Outlines"},
    "psycologie / psykologie": {"B2": "Noun", 'n': "Psychology; specifically 'psicologia della forma' (Gestalt psychology) used to justify how gaps in paintings are filled"},
    "rapporto": {"B1": "Noun", 'n': "Relationship / Ratio; the connection between the figurative or spatial elements of a monument"},
    "relativo": {"B1": "Adjective", 'n': "Relative"},
    "restauratore": {"B2": "Noun", 'n': "Restorer; the professional practitioner responsible for the physical and ethical care of the object"},
    "restauratori": {"B1": "Noun (Plural)", 'n': "Restorers; the professionals performing the treatment"},
    "restauri": {"B1": "Noun (Plural)", 'n': "Restorations / Interventions"},
    "restauro": {"B1": "Noun", 'n': "Restoration; in the Italian tradition, defined as the 'methodological moment' of recognition of the work of art"},
    "riconoscibile": {"B2": "Adjective", 'n': "Recognizable; the ethical principle that any modern intervention must be visible upon close inspection to avoid deception"},
    "riferisce": {"B1": "Verb (Present)", 'n': "Refers to / Relates to"},
    "rimediare": {"B2": "Verb", 'n': "To remedy / To fix"},
    "rimettere": {"B2": "Verb", 'n': "To put back / To restore / To replace; often used in the sense of reintegrating a loss"},
    "ripristini": {"C1": "Noun (Plural)", 'n': "Restorations to an 'original' state; often used to critique heavy-handed 19th-century reconstructions"},
    "ripristino": {"C2": "Noun", 'n': "Restoration to an original state; often used in the context of 'restauro di ripristino' (reconstructive restoration)"},
    "riscarcire": {"C2": "Verb", 'n': "To compensate / To repair; specifically filling a loss in a surface"},
    "ristabilimento": {"C1": "Noun", 'n': "Re-establishment / Restoration; the process of restoring the formal or functional integrity of an object"},
    "ristabilire": {"B2": "Verb", 'n': "To re-establish / To restore; the goal of recovering the potential unity of the artwork without creating a 'fake'"},
    "risulta": {"B1": "Verb (Present)", 'n': "Results / Appears / Turns out"},
    "ritrovato": {"B1": "Adjective/Participle", 'n': "Rediscovered / Found again; e.g., a 'ritrovato' fresco under layers of lime"},
    "rivelazione": {"C2": "Noun", 'n': "Revelation / Uncovering; the act of revealing hidden layers of an artwork"},
    "rivivirere": {"B2": "Verb", 'n': "To revive / To live again; the act of bringing a work back to public or aesthetic life"},
    "sarebbe": {"B1": "Verb (Conditional)", 'n': "Would be / It would be"},
    "scientifico": {"B2": "Adjective", 'n': "Scientific; e.g., 'restauro scientifico' (the analytical approach to conservation)"},
    "scrostato": {"B2": "Adjective/Participle", 'n': "Flaked / Peeled; describing a surface where the paint or plaster has detached"},
    "secoli": {"A2": "Noun (Plural)", 'n': "Centuries"},
    "secolo": {"A2": "Noun", 'n': "Century"},
    "seconda": {"A2": "Adjective", 'n': "Second"},
    "sempre": {"A1": "Adverb", 'n': "Always"},
    "sentono": {"B1": "Verb (Present)", 'n': "They feel / They hear"},
    "si": {"A1": "Pronoun", 'n': "One / Self; used in passive/impersonal constructions (e.g., 'si restaura')"},
    "skraffitto": {"C1": "Noun", 'n': "Sgraffito; a technique of scratching through a surface layer to reveal a contrasting color beneath"},
    "skrafitto": {"C1": "Noun (Variant spelling)", 'n': "Sgraffito"},
    "sotto": {"A2": "Preposition", 'n': "Under / Beneath; e.g., the layers 'sotto' the surface varnish"},
    "spaziali": {"B2": "Adjective (Plural)", 'n': "Spatial; relating to the qualities of volume and the placement of the work"},
    "storia": {"A1": "Noun", 'n': "History; the discipline of studying the past, central to 'storia dell’arte' (art history)"},
    "strappo": {"C1": "Noun", 'n': "Strappo; the most invasive detachment technique where only the pigment layer of a mural is removed from the wall"},
    "svizzere": {"A1": "Adjective (feminine plural form)", 'n': 'Swiss'},
    "taccuini": {"B2": "Noun (Plural)", 'n': "Notebooks / Sketchbooks; primary sources for understanding an artist's or restorer's process"},
    "tecniche": {"B2": "Noun (Plural)", 'n': "Techniques; often used in Swedish scholarship to refer to Italian methods of fresco or oil painting"},
    "teoretico": {"C1": "Adjective", 'n': "Theoretical; relating to the underlying principles rather than just the manual practice"},
    "terzo": {"A2": "Adjective/Noun", 'n': "Third; e.g., 'the third way' or a third party"},
    "tono": {"B1": "Noun", 'n': "Tone / Hue; the specific value or intensity of a color in a painting"},
    "tra": {"A1": "Preposition", 'n': "Between / Among"},
    "tratta": {"A2": "Verb", 'n': "Treats / Deals with; used to define the subject of a technical report"},
    "trattamento": {"B1": "Noun", 'n': "Treatment; the physical or chemical intervention on an object"},
    "tutela": {"B2": "Noun", 'n': "Protection / Safeguarding; the legal and administrative oversight of cultural heritage by the state (the 'Soprintendenze')"},
    "tutte": {"A1": "Adjective (Plural)", 'n': "All"},
    "una": {"A1": "Article", 'n': "A / One; feminine singular indefinite article"},
    "valori": {"B1": "Noun (Plural)", 'n': "Values; the aesthetic, historical, and cultural meanings intrinsic to the object of restoration"},
    "verniciata": {"B2": "Adjective, Past Participle", 'n': 'Painted/Varnished; a record of surface treatment, often for protection or aesthetics'},
    "vero": {"A1": "Adjective/Noun", 'n': "True / Truth; the 'true' historical and aesthetic state of the work"},
    "è": {"A1": "Verb (Present)", 'n': "Is"},
    'd’arte': {'B1': 'Noun Phrase', 'n': 'Of art'},
    'intelletto': {'B2': 'Noun', 'n': 'Intellect / Understanding'},
    "alle": {'A1': 'Contraction', 'n': 'To the / At the'},
    "carte": {'B1': 'Noun (Plural)', 'n': 'Papers / Maps / Documents'},
    "della": {'A1': 'Contraction', 'n': 'Of the'},
    "depicta": {'C1': 'Adjective / Participle (Latin)', 'n': 'Depicted / Painted'},
    "diagnostiche": {'C1': 'Adjective (Plural)', 'n': 'Diagnostic; referring to scientific tests (X-ray, UV) on art'},
    "ecclesia": {'C1': 'Noun (Latin)', 'n': 'Church'},
    "est": {'A1': 'Verb (Latin)', 'n': 'Is'},
    "et": {'A1': 'Conjunction (Latin)', 'n': 'And'},
    "gallerie": {'B1': 'Noun (Plural)', 'n': 'Galleries'},
    "indagine": {'B2': 'Noun', 'n': 'Investigation / Survey'},
    "indagini": {'B2': 'Noun (Plural)', 'n': 'Investigations / Analyses'},
    "intendenza": {'C1': 'Noun', 'n': 'Superintendency / Administration; the governing body for heritage (Soprintendenza)'},
    "interroghi": {'C1': 'Verb', 'n': 'Interrogate / Question (Subjunctive)'},
    "inventarium": {'C1': 'Noun (Latin)', 'n': 'Inventory'},
    "laboratori": {'B1': 'Noun (Plural)', 'n': 'Laboratories'},
    "masaccio": {'C1': 'Proper Noun', 'n': "Famous early Renaissance painter, known for 'The Trinity'"},
    "medievo": {'B2': 'Noun', 'n': 'Middle Ages; (Modern: Medioevo)'},
    "meno": {'A2': 'Adverb', 'n': 'Less'},
    "miglior": {'B1': 'Adjective', 'n': 'Better / Best'},
    "mirare": {'B2': 'Verb', 'n': 'To aim / To gaze upon'},
    "monumenti": {'A2': 'Noun (Plural)', 'n': 'Monuments'},
    "monumento": {'A2': 'Noun', 'n': 'Monument'},
    "mostra": {'B1': 'Noun', 'n': 'Exhibition'},
    "museum": {'A1': 'Noun (Latin/International)', 'n': 'Museum'},
    "opere": {'B1': 'Noun (Plural)', 'n': 'Works (of art)'},
    "quarantennio": {'C1': 'Noun', 'n': 'Forty-year period'},
    "quello": {'A2': 'Pronoun', 'n': 'That one'},
    "restaurata": {'B1': 'Adjective / Participle (Feminine)', 'n': 'Restored'},
    "restaurate": {'B1': 'Adjective / Participle (Plural)', 'n': 'Restored'},
    "scientifiche": {'B2': 'Adjective (Plural)', 'n': 'Scientific'},
    "scorge": {'C1': 'Verb', 'n': 'Glimpses / Discerns / Sees'},
    "sepulto": {'C1': 'Adjective / Participle (Latin)', 'n': 'Buried'},
    "sopra": {'A2': 'Preposition', 'n': 'Above / Over'},
    "suo": {'A1': 'Determiner', 'n': 'His / Her / Its'},
    "tabulata": {'C1': 'Noun (Latin)', 'n': 'Planked / Boarded; often referring to a wooden panel or floor'},
    "unità": {'B2': 'Noun', 'n': 'Unit / Unity'},
    "virtuale": {'B1': 'Adjective', 'n': 'Virtual'},

}
