# -*- coding: utf-8 -*-
# -*- mode: python; python-indent-offset: 4 -*-
#
# Some useful dicts and lists - for Danish
#
#
# 2026-02-01
#
# G. Q. Maguire Jr.
#
#
# Abbreviations used:
#  CEFR   Common European Framework of Reference for Languages: Learning, teaching, assessment.
#  POS    Part Of Speech
#
# This file contains several dicts and lists - these contain 'word' entries, but a 'word' can actually be a string of several words.
#
# Lists have been used when there can be multiple entries for the same 'word' and where there is not CEFR and POS information.
#
#
# Each dict's structure is:
# dict_name = {
#    entry,
#    entry,
# }
# Each entry is a 'word': CEFR_POS_dict
#
# a CEFR_POS_dict entry is a dict with the keys being CEFR levels (A1, A2, B1, B2, C1, C2, XX, and NA)
# followed by a string that contains comma separated POS
#
# The code 'XX' is used for an unknown CEFR level, while NA is for use when no level is applicable:
# 
# 
common_danish_words={
    "Monumentmalerei": {"B2": "Noun (Germanic influence)", "n": "Monumental painting; large-scale mural art designed for 'edifices' such as 'katedralen' or public halls."},
    "jaevne": {"A2": "Adjective / Verb", "n": "Even / Smooth; describing the 'jaevne' surface of a 'Putzgrundes' or the process of leveling a substrate."},
    "tiltala": {"B1": "Verb", "n": "To appeal to / To address; often used regarding how an aesthetic 'stilens' or 'restaureringsästhetik' appeals to the viewer"},
    "gik": {"A1": "Verb (Past)", "n": "Went; used in 'Beretning' (reports) to describe how a process 'gik' (proceeded) during a 'besiktigade'"},
    "Bildflege": {"B2": "Noun (Archaic/Germanic influence)", "n": "Image care / Iconography management; (Modern: Billedpleje). The systematic 'bevare' of sacred imagery"},
    "Billederne": {"A2": "Noun (Plural Definite)", "n": "The pictures / The images; referring to 'figurscenerna' in a 'väggdekor'"},
    "Augustinklostret": {"B1": "Proper Noun (Definite)", "n": "The Augustinian Monastery; a site often containing significant 'Gewölbemalereien' and 'gravminnen'"},
    "Arbejdsmarken": {"B1": "Proper Noun (Definite)", "n": "The Field of Work; often referring to 'Nationalmuseets Arbejdsmark', a key Danish heritage journal"},
    "Alfrescon": {"B2": "Noun (Definite)", "n": "The fresco; a 'måleriteknik' where pigment is applied to wet 'Putzgrundes' (plaster)"},
    "Aarhundrede": {"A2": "Noun", "n": "Century; (Modern: Århundrede). Used to define the 'Zeitalter' of an 'edifice' or 'monumentalverk'"},
    "keskaegsete": {"C1": "Adjective (Estonian/Archaic)", "n": "Medieval; specifically 'keskaegsete kirikute' (medieval churches). Often found in Danish-Estonian research reports"},
    "cementen": {"B1": "Noun (Definite)", "n": "The cement; a 19th-century 'Eingriffe' material that often causes modern 'saltproblematiken' in stone buildings"},
    "Dage": {"A2": "Noun (Plural)", "n": "Days; used in 'arkivforskning' to date specific events or 'besiktigade' periods (e.g., 'i disse Dage')"},
    "ødelagt": {"B1": "Adjective / Participle", "n": "Destroyed / Damaged; used in 'besiktigade' reports to describe the 'Etats' (state) of 'fragmentets'"},
    "kirikute": {"B2": "Noun (Genitive Plural - Estonian)", "n": "Churches'; often found in Danish research regarding 'Eesti' (Estonian) 'kulturminnena' and 'Hanseatic' architecture"},
    "Fransiskus liv": {"B2": "Proper Noun (Phrase)", "n": "Life of St. Francis; a common 'kalkmålningsmotiv' (mural motif) depicting the 'legend' of St. Francis of Assisi"},
    "Dragter": {"B1": "Noun (Plural)", "n": "Costumes / Suits; the study of 'Dragter' in 'figurscenerna' used to date 'väggdekor' based on fashion history"},
    "blitt": {"A1": "Verb (Past Participle)", "n": "Been / Become; (Modern Danish: blevet). Often used to describe the state a monument 'blitt' (has become) over time"},
    "Gilde": {"B1": "Noun (Common)", "n": "Guild / Society; referring to medieval 'hantverkarnas' organizations or a modern 'fornminnessällskap'"},
    "Georgskoret": {"B2": "Proper Noun (Definite)", "n": "The St. George Choir; a specific chapel or choir section dedicated to St. George, often housing 'Görans-studier' motifs"},
    "Frue": {"A2": "Noun (Common)", "n": "Lady / Our Lady; as in 'Vor Frue Kirke' (Church of Our Lady), a common dedication for 'Granitbasilika' churches"},
    "Frihed": {"B1": "Noun (Common)", "n": "Freedom / Liberty; often appearing in 'nationalstil' rhetoric or 19th-century 'Historieteoretiska' texts"},
    "Fresko": {"B1": "Noun", "n": "Fresco; the technique of 'kalkmålningar' where pigment is applied to wet lime plaster"},
    "Fresko-og Kalkmalerier": {"B2": "Noun (Plural)", "n": "Fresco and lime paintings; the broader category of 'väggdekor' found on church interiors"},
    "Freskoepoken": {"C1": "Noun (Definite)", "n": "The Fresco Epoch; a specific historical 'Zeitalter' defined by the prevalence of monumental wall painting"},
    "Forskningsexerpter": {"B2": "Noun (Plural)", "n": "Research excerpts; condensed notes taken during 'arkivforskning' from 'Handskriftssamlingen'"},
    "Forening": {"A2": "Noun (Common)", "n": "Association / Society; such as a 'Hembygdsforening' or a professional 'Gilde'"},
    "Festskrift": {"B1": "Noun", "n": "Festschrift; a celebratory 'Hyllningsskriften' published for a scholar's 'jubilæum'"},
    "Farveteknisk": {"B2": "Adjective", "n": "Color-technical; relating to 'färganalys' and the chemical 'scienza' of pigments"},
    "Excerpter": {"B2": "Noun (Plural)", "n": "Excerpts; notes and 'Forskningsexerpter' used to compile an 'utredning'"},
    "Ert": {"A1": "Pronoun (Archaic)", "n": "Your; (Modern: Jer/Jeres). Found in formal correspondence and 'familjepapperen'"},
    "Eesti": {"B1": "Proper Noun", "n": "Estonia; often mentioned in Baltic 'kulturminnena' research and 'Hanseatic' trade history"},

    "løp": {"B1": "Noun (Common)", "n": "Course / Run; in architecture, can refer to the 'løp' (flight) of a staircase or the 'løp' (flow) of a molding"},
    "klassicisme": {"B2": "Noun", "n": "Classicism; the architectural and artistic movement inspired by Greek and Roman 'antichità', emphasizing symmetry and 'formale' clarity"},
    "årenens": {"C1": "Noun (Archaic/Definite)", "n": "The years'; (Modern: årenes). Used in 'indberetninger' (reports) to refer back to a specific period of time"},
    "Hvis": {"A1": "Conjunction", "n": "If; used in 'restaureringsanvisningar' to describe conditional steps (e.g., 'if the stone is damp...')"},
    "høymiddelalderen": {"B2": "Noun (Definite)", "n": "The High Middle Ages; the era (c. 1000–1300) when many stone 'kirkevaeggene' were first constructed"},
    "Holdning": {"B1": "Noun", "n": "Attitude / Position; refers to the theoretical 'holdning' a restorer takes toward 'äkthet' (authenticity)"},
    "Heste": {"A2": "Noun (Plural)", "n": "Horses; common in iconographic scenes or historical accounts of travel to 'monument' sites"},
    "Havde": {"A1": "Verb (Past)", "n": "Had; the auxiliary verb used to describe the state of a monument before an 'intervento'"},
    "eksempler": {"A2": "Noun (Plural)", "n": "Examples; (Modern Swedish: exempel)"},
    "stilimitation": {"B2": "Noun", "n": "Style imitation; the deliberate copying of historical styles, often debated in the context of 'restaurering' vs. 'nybygning'"},
    "søgt": {"B1": "Adjective/Participle", "n": "Sought / Affected; can refer to information being 'søgt' (searched) or a style that feels 'søgt' (contrived/unnatural)"},
    "omraade": {"A2": "Noun (Archaic)", "n": "Area / Field; (Modern: område). Refers to a geographical 'omraade' or a specific 'kunstens' domain"},
    "historie": {"A1": "Noun", "n": "History / Story; the chronological account of a 'monument' or the academic discipline of 'historie'"},
    "Køn": {"B1": "Noun (Common)", "n": "Gender / Sex; found in historical demographic records or in aesthetic contexts as 'beautiful' (archaic 'køn')"},
    "Januar": {"A1": "Noun", "n": "January; often used in archival dating for 'indberetninger' (reports)"},
    "Jaernbanerne": {"B1": "Noun (Plural Definite Archaic)", "n": "The railways; (Modern: Jernbanerne). Key to the 'Industrialismen' and the transport of heavy building materials"},
    "oprindelige": {"A2": "Adjective", "n": "Original / Initial; used to describe the first state of a building or the 'original' paint layer before restoration"},
    "middelalderligt": {"B1": "Adjective", "n": "Medieval; pertaining to the Middle Ages (approx. 500–1500 AD), often used in the context of 'middelalderligt inventar'"},
    "derudfra": {"B2": "Adverb", "n": "From there / Based on that; a transitional phrase used in scholarly arguments to draw conclusions from observed data"},
    "Lombardiet": {"B2": "Proper Noun", "n": "Lombardy; the Italian region influential for its Romanesque brick architecture, frequently cited as a model for Danish church building"},
    "Litteraere": {"B1": "Adjective", "n": "Literary; relating to books or written sources (Modern Danish: litterære)"},
    "Landes": {"B2": "Noun (Genitive Plural - Archaic)", "n": "Countries' / Lands'; referring to the territories or estates belonging to a specific region or crown"},
    "Laboratorieassistent": {"B1": "Noun (Common)", "n": "Laboratory assistant; a professional role involved in the chemical analysis of pigments and binders in a conservation lab"},
    "København": {"A1": "Proper Noun", "n": "Copenhagen; the capital of Denmark and center of Danish heritage administration"},
    "Köbenhavn": {"A1": "Proper Noun (Archaic Variant)", "n": "Copenhagen; an older spelling variant using the German-style umlaut 'ö' instead of the Danish 'ø'"},
    "Kvinder": {"A1": "Noun (Plural)", "n": "Women; found in historical records regarding parish demographics or specific female donors and artists"},
    "Kusk": {"A2": "Noun (Common)", "n": "Coachman / Driver; often mentioned in 19th-century travelogues of heritage officials visiting rural districts"},
    "Knaphed": {"B2": "Noun (Common)", "n": "Scarcity / Shortage; used in reports to describe the 'knaphed' of financial resources or quality building materials"},
    "Kirkevaeggene": {"B1": "Noun (Plural Definite)", "n": "The church walls; the primary physical surfaces for 'middelalderlige' murals (Modern: kirkevæggene)"},
    "kirkevæggene": {"B1": "Noun (Plural Definite)", "n": "The church walls; the primary physical surfaces for 'middelalderlige' murals"},

    "Kirken": {"A1": "Noun (Definite)", "n": "The church; referring to either the specific building or the institutional Church"},
    "Kunstens": {"A2": "Noun (Genitive)", "n": "Of the art; equivalent to the Swedish 'konstens'"},
    "Kong": {"A2": "Noun", "n": "King; equivalent to the Swedish 'Kung'"},
    "virksomhed": {"B1": "Noun", "n": "Activity / Operation / Enterprise; refers to the ongoing work of a conservation studio or the 'activities' of a government department"},
    "maler": {"A1": "Noun", "n": "Painter; can refer to a fine artist, a decorative house painter, or a 'muralmåler' working on church walls"},
    "malerikonservatorer": {"C1": "Noun (Plural)", "n": "Painting conservators; specialized professionals who preserve and restore painted surfaces (canvas, wood, or wall)"},
    "iklaedes": {"C1": "Verb (Passive)", "n": "To be clothed / To be clad; in a technical sense, it often refers to covering a surface with a new layer (e.g., 'iklædes' a new plaster or protective coating)"},
    "dets": {"A1": "Pronoun (Genitive)", "n": "Its; the possessive form of 'det.' Used to describe the features of a building or object (e.g., 'dets murværk')"},
    "tidstil": {"B2": "Noun (Compound)", "n": "Period style; referring to the specific architectural or artistic style of a particular era (e.g., 'Gothic' or 'Renaissance')"},
    "Maal": {"B1": "Noun (Archaic Spelling)", "n": "Goal / Measure / Dimension; pre-1948 spelling of 'mål.' Essential for recording the physical 'dimensions' of a monument"},
    "Mangel": {"B1": "Noun", "n": "Defect / Lack / Shortcoming; used in condition reports to identify missing elements or structural failures in a building"},
    "naar": {"A1": "Conjunction (Archaic)", "n": "When; the older spelling used before the Danish orthography reform of 1948 (Modern: når). Used to indicate time or condition"},
    "Muurvaerket": {"B2": "Noun (Definite, Archaic)", "n": "The masonry / The brickwork; archaic spelling using double 'u' and 'ae'. Refers to the structural parts of a building made of stone and mortar"},
    "Murværket": {"B2": "Noun (Definite)", "n": "The masonry / The brickwork; the modern spelling. A central term in restoration reports regarding cleaning, pointing, or stabilization"},
    "Monumenter": {"B1": "Noun (Plural)", "n": "Monuments; memorials or buildings of historical and cultural significance that are subjects of preservation"},
    "Minder": {"A2": "Noun (Plural)", "n": "Memories / Monuments; can refer to both mental recollections and physical 'fortidsminder' (ancient monuments or relics)"},
    "Middelalderens": {"B1": "Noun (Genitive, Definite)", "n": "Of the Middle Ages; belonging to the period approx. 1000–1536 in a Danish context. Often used regarding church architecture and frescoes"},
    "Middelalder": {"B1": "Noun", "n": "Middle Ages; the historical epoch between the Viking Age and the Reformation"},
    "Malerikonservering": {"C1": "Noun", "n": "Painting conservation; the technical and scientific discipline of preserving painted surfaces, including both canvas and wall paintings"},
    "Meningsmangfold": {"C1": "Noun", "n": "Plurality of meaning / Diversity of opinion; (Norwegian-influenced Danish) refers to the presence of various interpretations or stances regarding a heritage object"},
    "ud": {"A1": "Adverb / Preposition", "n": "Out; used in spatial descriptions or to indicate the publishing of a work ('udgivet')"},
    "inden": {"A2": "Preposition / Conjunction", "n": "Within / Before; used to define temporal limits or interior spaces of a building"},
    "problematikken": {"B2": "Noun (Definite)", "n": "The set of problems / The problematic; refers to the complex of issues surrounding a specific research topic or restoration project"},
    "uønsket": {"B1": "Adjective", "n": "Unwanted / Undesired; often used in conservation to describe harmful biological growth or modern additions to a historical site"},
    "papisme": {"C1": "Noun", "n": "Popery / Papism; a historical, often polemical term used in post-Reformation Denmark to refer to Roman Catholic practices or aesthetics"},
    "Oldkyndighed": {"C1": "Noun", "n": "Antiquarianism / Knowledge of antiquity; the study of ancient history and artifacts. A core term for the 19th-century pioneers of Danish archaeology"},
    "optrin": {"C1": "Noun", "n": "Scene/Episode; a Danish term found in older texts describing an event"},
    "Oldsagers": {"C1": "Noun (Genitive Plural)", "n": "Antiquities'; Danish term (Modern: oldsager) referring to ancient artifacts"},
    "Opbevaring": {"B1": "Noun", "n": "Storage/Preservation; the act of keeping something safe"},
    "Oldsagskommissionen": {"C1": "Proper Noun", "n": "The Antiquities Commission; the 19th-century Danish body for heritage"},
    "Nordiske": {"B1": "Adjective", "n": "Nordic; relating to the Scandinavian region"},

    "tømmes": {"B2": "Verb (Passive)", "n": "To be emptied; often used in the context of clearing out a building, a crypt, or a room before restoration work begins"},
    "gaaet": {"A2": "Verb (Past Participle - Archaic)", "n": "Gone / Walked; the older spelling of 'gået' (Modern Danish). Frequently found in 19th-century reports describing the condition of a structure ('det er gaaet i forfald')"},
    "Religiøs": {"A2": "Adjective", "n": "Religious; relating to faith or the church. Used to describe the function of art, buildings, or specific collections of objects"},
    "Vejen": {"B1": "Proper Noun / Noun", "n": "Vejen (a town in Jutland) / The road (Definite form of 'vej')"},
    "amt": {"B2": "Noun (Neuter)", "n": "County / District; a historical administrative division in Denmark (replaced by 'Regions' in 2007)"},
    "daa": {"C1": "Conjunction / Adverb (Archaic)", "n": "When / As / Then (Modern spelling: 'da'). Often found in 19th-century manuscripts"},
    "hører": {"A2": "Verb (Present)", "n": "Hears / Belongs to; used in 'hører til' (belongs to) or 'hører efter' (listens)"},
    "muligt": {"A2": "Adjective / Adverb", "n": "Possible / Possibly"},
    "Saaledes": {"B2": "Adverb (Archaic)", "n": "Thus / In this way / So (Modern: Således)"},
    "Saavidt": {"B2": "Conjunction (Archaic)", "n": "As far as / Insofar as (Modern: Såvidt)"},
    "Smaapladserne": {"C1": "Noun (Definite Plural, Archaic)", "n": "The small plots / The smallholdings; often referring to minor land allotments in rural history (Modern: Småpladserne)"},
    "Sorø": {"B1": "Proper Noun", "n": "Sorø; a Danish town famous for its academy and medieval abbey church"},
    "behøver": {"A1": "Verb (Present)", "n": "Need / Require"},
    "hver": {"A2": "Pronoun / Adjective", "n": "Each / Every"},
    "sejl": {"A2": "Noun (Neuter)", "n": "Sail; the fabric used to catch wind for propulsion"},
    "laerred": {"B1": "Noun (Neuter)", "n": "Canvas; the fabric surface used for oil or acrylic painting (Modern: lærred)"},
    "staffelibillede": {"B2": "Noun (Neuter)", "n": "Easel painting; a portable painting produced on an easel, as opposed to a mural or fresco"},
    "staffelibilleder": {"B2": "Noun (Plural)", "n": "Easel paintings"},
    "stilarter": {"B2": "Noun (Plural)", "n": "Artistic styles / Stylistic periods (e.g., Baroque, Renaissance)"},
    "stykke": {"A2": "Noun (Neuter)", "n": "Piece / Fragment / Play / Track"},
    "takket": {"B1": "Preposition / Adjective", "n": "Thanks to (takket være) / Jagged / Serrated"},
    "tegn": {"A2": "Noun (Neuter)", "n": "Sign / Mark / Token / Gesture"},
    "vaegbillede": {"B2": "Noun (Neuter)", "n": "Wall painting / Mural (Modern: vægbillede)."},
    "Tenstaartikel": {"B2": "Noun", "n": "Tensta article; a specific scholarly article or text concerning Tensta (a district known for its medieval church)"},
    "tidlig": {"A1": "Adjective", "n": "Early (Modern Swedish: tidig)"},

    "udtrykt": {"B2": "Adjective, Participle", "n": "Expressed / Manifested / Explicit"},
    "mindesmaerker": {"B1": "Noun (Plural)", "n": "Monuments / Memorials (Modern: mindesmærker)"},
    "skønnere": {"B2": "Adjective (Comparative)", "n": "More beautiful / Fairer"},
    "oldsager": {"B2": "Noun (Plural)", "n": "Antiquities / Ancient artifacts / Relics of the past"},
    "eneste": {"A2": "Adjective, Pronoun", "n": "Only / Sole / Single"},
    "ondt": {"A2": "Adjective", "n": "Evil / Bad / Sore"},

    "vaegtigere": {"B2": "Adjective (Comparative)", "n": "Weightier / More significant (Modern: vægtigere)"},
    "snaerende": {"C1": "Adjective / Participle", "n": "Constricting / Oppressive / Chafing (Modern: snærende)"},
    "faedrelandska": {"B2": "Adjective (Archaic/Typo)", "n": "Patriotic / National (Modern: fædrelandsk)"},

    "villet": {"B2": "Adjective", "C1": "Past Participle", "n": "Intentional / Willed / Studied / Deliberate"},
    "aeldste": {"A2": "Adjective (Superlative)", "n": "Oldest / Eldest (Modern: ældste)"},
    "bedre": {"A2": "Adjective (Comparative)", "n": "Better"},
    "biledflaesning": {"C1": "Noun (Archaic)", "n": "Visual analysis / Reading of images (Modern: billedlæsning)"},
    "blive": {"A1": "Verb", "n": "To become / To remain"},
    "boghaandvaerk": {"B2": "Noun", "n": "Bookbinding / The craft of bookmaking (Modern: boghåndværk)"},
    "Farvedekoration": {"B2": "Noun", "n": "Color decoration / Polychromy; the use of color in architectural or sculptural ornament"},
    "laegger": {"A2": "Verb (Present)", "n": "Lays / Places / Sets (Modern: lægger)"},
    "laeret": {"B1": "Noun / Participle", "n": "The cloth / The canvas / Learned (Modern: lærred / lært)"},

    "afbildninger": {"B1": "Noun (Plural", "n": "Depictions"},
    "afholdt": {"B2": "Adjective", "n": "Respected / Esteemed"},
    "anvendte": {"B2": "Verb (Past)", "n": "Used (Modern Swedish: använde)"},
    "billeder": {"B1": "Noun (Plural)", "n": "Pictures / Images (Swedish: bilder)"},
    "billedserie": {"B2": "Noun", "n": "Picture series (Swedish: bildserie)"},
    "fordringsfuld": {"B2": "Adjective", "n": "Demanding / Exacting"},
    "kopier": {"B1": "Noun (Plural)", "n": "Copies (Swedish: kopior)"},


    "beste": {"A1": "Adjective", "n": "Best (Swedish: bästa)"},
    "een": {"A1": "Numeral / Article (Archaic)", "n": "One / A / An (Modern spelling: en)"},
    "drømmer": {"A2": "Noun / Verb", "n": "Dreamer (noun) / Dreams / Is dreaming (verb)"},
    "disse": {"A1": "Pronoun / Determiner", "n": "These"},
    "bundne": {"B2": "Adjective / Participle (Plural/Definite)", "n": "Bound / Tied / Fixed (often used as 'bundne former' referring to rhymed or rhythmic verse)"},
    "fremdrage": {"C1": "Verb", "n": "To stand out / To project / To emerge; to be prominent (equivalent to Swedish 'framträda')"},
    "forklare": {"B1": "Verb", "n": "To explain (Swedish: förklara)"},
    "gjenfundne": {"C1": "Adjective", "n": "Rediscovered"},

    "domkirke": {"B1": "Noun", "n": "Cathedral (Modern Swedish: domkyrka)"},

    "restaurere": {"B2": "Verb", "n": "To restore; to return a building or object to a former condition"},
    "maa": {"A2": "Verb (Modal)", "n": "May / Must; indicates permission or necessity (Modern spelling: må)"},
    "middelalderen": {"B2": "Noun (Definite)", "n": "The Middle Ages (Modern Swedish: medeltiden)"},

    "huskes": {"B1": "Verb (Passive)", "n": "To be remembered / Is remembered"},
    "gennemføre": {"B2": "Verb", "n": "To implement / To carry out / To complete (e.g., a project or a task)"},
    "genbrug": {"A2": "Noun", "n": "Recycling / Reuse; the action or process of converting waste into reusable material"},
    "forståelse": {"B1": "Noun", "n": "Understanding / Comprehension / Insight"},
    "fordi": {"A2": "Conjunction", "n": "Because; since; for the reason that"},

    "fremdrage": {'B2': 'Verb', 'n': "To bring to light / To uncover / To highlight; (e.g., 'at fremdrage nye fund' - to bring new finds to light)"},
    "finde": {'A1': 'Verb', 'n': 'To find / To locate'},
    "fordre": {'B2': 'Verb', 'n': 'To demand / To require; often used in the context of academic or legal requirements'},
    "forstyrre": {'B1': 'Verb', 'n': "To disturb / To interfere with; (e.g., 'forstyrre jordlagene' - to disturb the soil layers)"},
    "forskning": {'B1': 'Noun', 'n': 'Research / Scholarly investigation'},
    "forvalte": {'B2': 'Verb', 'n': 'To manage / To administer; specifically used for the stewardship of heritage or property'},
    "fællesskab": {'B1': 'Noun', 'n': 'Community / Fellowship / Joint ownership'},
    "fornemme": {'B2': 'Verb', 'n': 'To sense / To perceive; used for subtle observations in art or atmosphere'},

    "fra": {"A1": "Preposition", "n": "From (Swedish: från)"},

    "gennemgang": {"B2": "Noun", "n": "Review / Walkthrough / Passage (Swedish: genomgång)"},

    "gab": {"A1": "Verb", "n": "Gave (Swedish: gav)"},
    "tjener": {"B1": "Verb", "n": "Serves (Modern Swedish: tjänar)"},
    "understøttelse": {"B2": "Noun", "n": "Support / Underpinning / Subsidy; (e.g., 'økonomisk understøttelse' - financial aid; 'bygningsmæssig understøttelse' - structural support)."},

    "østerlandske": {"B2": "Adjective", "n": "Relating to the lands of the East (the Orient). Often used for Oriental styles or cultures"},
    "vort": {"A2": "Pronoun (possessive)", "n": "Formal or older form of 'our' (e.g., 'vort land' - our country)"},
    "strøminger": {"B2": "Noun (plural)", "n": "Cultural, political, or artistic movements and trends of the time"},
    "højt": {"A1": "Adjective / Adverb", "n": "Located at a great height, high volume, or figuratively regarding something distinguished"},

    "hoppe": {"A2": "Noun", "n": "Hope"},
    "ihjael": {"B1": "Adverb", "n": "To death (Modern: ihjäl)"},
    "meget": {"B1": "Adverb", "n": "Much / Very (Swedish: mycket)"},
    "trae": {"A2": "Noun", "n": "Wood / Tree (Modern Swedish: trä)"},
    "udgivet": {"B1": "Adjective, Participle", "n": "Published / Issued (Modern Swedish: utgivet)"},
    "ydre": {"B1": "Adjective", "n": "Outer / External (Modern: yttre)"},
    "holde": {"B1": "Verb", "n": "To hold / To keep (Modern: hålla)"},
    "hvor": {"A1": "Adverb / Conjunction", "n": "Where / How (e.g., 'Hvor er det?' - Where is it?; 'Hvor smukt' - How beautiful)"},
    "hvori": {"B2": "Adverb / Pronoun", "n": "In which / Wherein (e.g., 'Den kasse, hvori brevet lå' - The box in which the letter lay)"},

    "klosterkirke": {'B1': 'Noun', 'n': 'Monastery church; (Modern Swedish: klosterkyrka)'},
    "monumentale": {'B1': 'Adjective', 'n': 'Monumental; (Modern: monumentala)'},
    "vaesentlige": {'B1': 'Adjective', 'n': 'Essential / Significant; (Modern Swedish: väsentliga)'},
    "våben": {'B1': 'Noun', 'n': 'Weapon / Coat of arms; (Modern Swedish: vapen)'},
    "kirke": {"B1": "Noun", 'n': "Church; (Standard Swedish: kyrka)"},
    "A/S": {"B1": "Abbreviation", 'n': "A/S; abbreviation for Aktieselskab"},
    "Aarbøger": {"B2": "Noun (Plural)", 'n': "Yearbooks; commonly used in the titles of historical or archaeological journals"},
    "Aktieselskab": {"B1": "Noun", 'n': "Joint-stock company; a public limited company"},
    "ApS": {"B1": "Abbreviation", 'n': "Anpartsselskab; a private limited company"},
    "Baand": {"B2": "Noun (Archaic)", 'n': "Volume; older spelling of 'bind' (e.g., 'Første Baand' - Volume One)"},
    "Baandet": {"B2": "Noun (Definite Archaic)", 'n': "The volume / The bond"},
    "Danske": {"A1": "Adjective/Proper Noun", 'n': "Danish; e.g., 'Den Danske Stat'"},
    "Grad": {"A2": "Noun", 'n': "Degree / Extent"},
    "Indhold": {"B1": "Noun", 'n': "Content / Substance"},
    "Kulge": {"C2": "Proper Noun/Variant", 'n': "Likely a name or variant of 'Kugle' (Sphere), though context is needed"},
    "Kystfartøj": {"B2": "Noun", 'n': "Coastal vessel; a ship designed for navigation along the coastline rather than open sea"},
    "Maade": {"B2": "Noun (Archaic spelling)", 'n': "Way / Manner / Method; Modern Danish: 'måde'. Often used in technical descriptions regarding the 'way' a structure was built or a treatment applied"},
    "Rummet": {"A2": "Noun (Definite)", 'n': "The room / The space"},
    "Selskabs": {"B2": "Noun (Genitive)", 'n': "Society's / Company's; e.g., 'Det Kongelige Danske Videnskabernes Selskab'"},
    "Skrifter": {"B2": "Noun (Plural)", 'n': "Writings / Publications; often used in series titles like 'Videnskabelige Skrifter'"},
    "Støtte": {"B1": "Noun / Verb", 'n': "Support / Prop / Pillar; Can refer to a physical architectural support (like a buttress or column) or financial/moral support for a project"},
    "Vaegten": {"B1": "Noun (Definite)", 'n': "The weight / The emphasis"},
    "Videnskabernes": {"C1": "Noun (Genitive Plural)", 'n': "The Sciences'; as in 'The Academy of Sciences'"},
    "af": {"A1": "Preposition", 'n': "Of / By"},
    "anden": {"A1": "Adjective, Pronoun", 'n': "Other / Second; Used to distinguish between two things or to refer to the 'other' part of a building or document"},
    "belyst": {"B1": "Adjective/Participle", 'n': "Illuminated / Lit; also used metaphorically to mean 'clarified' or 'examined'"},
    "billedkunst": {"B2": "Noun", 'n': "Visual arts / Fine arts"},
    "censurering": {"B2": "Noun", 'n': "Censoring / Censorship"},
    "danske": {"A1": "Adjective", 'n': "danish (lower case)"},
    "det": {"A1": "Article/Pronoun", 'n': "The / It (Neuter)"},
    "en": {"A1": "Article, Numeral", 'n': "A / An / One; The common indefinite article or the number one"},
    "enkeltvis": {"B2": "Adverb", 'n': "Individually / One by one; e.g., items or vessels listed individually"},
    "enkle": {"A2": "Adjective (Plural/Definite)", 'n': "Simple / Plain; used to describe 'enkle former' (simple forms) in neoclassical or early modernist design"},
    "farver": {"A1": "Noun (Plural)", 'n': "Colors; the palette or chromatic composition of a work"},
    "for": {"A1": "Preposition/Conjunction", 'n': "For / Because"},
    "fortaelling": {"B1": "Noun", 'n': "Narrative / Story / Tale"},
    "frem": {"A2": "Adverb", 'n': "Forward / Forth; e.g., 'at træde frem' (to step forward)"},
    "høj": {"A2": "Adjective", 'n': "High / Tall"},
    "i": {"A1": "Preposition", 'n': "In"},
    "ikke": {"A1": "Adverb", 'n': "Not"},
    "ingresser": {"C1": "Noun (Plural)", 'n': "Leads / Introductions; the opening paragraphs of an article or chapter"},
    "instrumen": {"B2": "Noun (Truncated/Variant)", 'n': "Instrument; likely a fragment of 'instrumenter' or 'instrumentet'"},
    "jeg": {"A1": "Pronoun", 'n': "I"},
    "jo": {"A2": "Adverb / Particle", 'n': "Yes (in response to negative) / As you know / Indeed"},
    "kaldes": {"B1": "Verb (Passive)", 'n': "Is called / Is named"},
    "kirkekunst": {"B2": "Noun", 'n': "Church art / Ecclesiastical art"},
    "kirkelig": {"B1": "Adjective", 'n': "Ecclesiastical / Church-related"},
    "kongelige": {"B1": "Adjective", 'n': "Royal"},
    "lagde": {"A2": "Verb (Past)", 'n': "Laid / Placed"},
    "lavadelig": {"C2": "Adjective (Archai)", 'n': "Lower-noble; relating to the lower gentry/aristocracy"},
    "let": {"A2": "Adjective / Adverb", 'n': "Easy / Light / Lightly"},
    "lige": {"A1": "Adverb", "A2": "Adverb, Adjective", 'n': "Equal / Just; (Swedish: lika/precis)"},
    "lysbevægelsen": {"C1": "Noun (Definite)", 'n': "The movement of light; often found in 19th-century physics or optics texts"},
    "lysbølger": {"C1": "Noun (Plural)", 'n': "Light waves"},
    "maaske": {"A2": "Adverb", 'n': "Maybe / Perhaps; (Modern: måske)"},
    "maleri": {"A2": "Noun", 'n': "Painting"},
    "man": {"A1": "Pronoun (Indefinite)", 'n': "One / You / People; e.g., 'man siger' (one says)"},
    "mellem": {"A1": "Preposition", "n": "Between / Among; (Swedish: 'mellan'). Frequently found in 19th-century Scandinavian correspondence or comparative regional studies."},
    "mere": {"A2": "Adverb/Adjective", 'n': "More; used for comparisons"},
    "middelalderlige": {"B1": "Adjective", "n": "Medieval; (Swedish: 'medeltida'). Refers to the Middle Ages, typically used when discussing North Germanic architecture or law from the period 1050–1500."},
    "noget": {"B2": "Adjective", 'n': "Some / A bit (Modern Swedish: 'något')"},
    "nogle": {"B2": "Adjective", 'n': "Some / A few (Modern Swedish: 'några')"},
    "og": {"A1": "Conjunction", 'n': "And"},
    "ogsaa": {"A1": "Adverb (Archaic spelling)", 'n': "Also / Too; Modern Danish: 'også'. Used to indicate addition or inclusion"},
    "opgave": {"A2": "Noun", 'n': "Task / Assignment / Purpose; the 'kunstens opgave' refers to the mission or social role of art"},
    "paa": {"A1": "Preposition (Archaic spelling)", 'n': "On / At / In; Modern Danish: 'på'. A fundamental preposition describing location or state"},
    "plane": {"B2": "Adjective (Plural) / Noun", 'n': "Plane / Flat; e.g., 'plane lysbølger' (plane light waves)"},
    "seg": {"B1": "Pronoun (Reflexive - Variant)", 'n': "Self / Oneself; (Note: In modern Danish this is 'sig', while 'seg' is the Norwegian/Old Danish form)"},
    "selv": {"A1": "Pronoun, Adverb", "n": "Self / Even; Equivalent to Swedish 'själv'. It is used both as an emphatic pronoun (e.g., 'han gjorde det selv' — he did it himself) and as an adverb meaning 'even' (e.g., 'selv her' — even here)."},
    "skønnaste": {"C1": "Adjective (Superlative)", 'n': "The most beautiful; an archaic/poetic spelling of 'skønneste'. Used in romanticized art theory"},
    "staerke": {"A2": "Adjective (Plural/Definite)", 'n': "Strong / Intense; archaic spelling of 'stærke'. Often refers to vivid pigments or bold brushwork"},
    "stilløs": {"B2": "Adjective", 'n': "Styleless / Without style; a critique of a work that lacks a clear stylistic lineage or formal discipline"},
    "stramme": {"B1": "Adjective / Verb", 'n': "Tight / To tighten"},
    "søger": {"A2": "Verb (Present)", 'n': "Seeks / Looks for; can refer to a person seeking a position or a vessel 'seeking' a harbor"},
    "taenke": {"A2": "Verb", 'n': "To think; (Modern: tænke)"},
    "til": {"A1": "Preposition", 'n': "To / For / At"},
    "tilbakeblikk": {"B1": "Noun", 'n': "Retrospective / Look back; occasionally found in Scandinavian cross-border scholarship"},
    "tøjler": {"B2": "Noun (Plural)", 'n': "Reins"},
    "tøre": {"C1": "Verb (Variant/Contextual)", 'n': "To steer / To govern; specifically in the idiom 'at tøre med stramme tøjler' (to govern with tight reins/strict control)"},
    "uden": {"A2": "Preposition", 'n': "Without"},
    "udtryk": {"B1": "Noun", 'n': "Expression / Term; e.g., 'fagligt udtryk' (technical term)"},
    "vaere": {"A1": "Verb (Infinitive)", 'n': "To be; (Modern spelling: 'være')"},
    'Naerum': {'B2': 'Proper Noun', 'n': 'A suburb in Denmark famous for its allotment gardens (Nærumvænge)'},
    'Nærum': {'B2': 'Proper Noun', 'n': 'A suburb in Denmark famous for its allotment gardens (Nærumvænge)'},

}

