# -*- coding: utf-8 -*-
# -*- mode: python; python-indent-offset: 4 -*-
#
# Some useful dicts and lists - for Finnish
#
#
# 2026-02-01
#
# G. Q. Maguire Jr.
#
#
# Abbreviations used:
#  CEFR   Common European Framework of Reference for Languages: Learning, teaching, assessment.
#  POS    Part Of Speech
#
# This file contains several dicts and lists - these contain 'word' entries, but a 'word' can actually be a string of several words.
#
# Lists have been used when there can be multiple entries for the same 'word' and where there is not CEFR and POS information.
#
#
# Each dict's structure is:
# dict_name = {
#    entry,
#    entry,
# }
# Each entry is a 'word': CEFR_POS_dict
#
# a CEFR_POS_dict entry is a dict with the keys being CEFR levels (A1, A2, B1, B2, C1, C2, XX, and NA)
# followed by a string that contains comma separated POS
#
# The code 'XX' is used for an unknown CEFR level, while NA is for use when no level is applicable:
# 
# 
common_finnish_words = {
    "Oy": {"B2": "Abbreviation (Noun)", "n": "Osakeyhtiö; the Finnish term for a limited liability company (equivalent to 'Ltd' or 'GmbH')"},
    "Oyj": {"B2": "Abbreviation (Noun)", "n": "Julkinen osakeyhtiö): A public limited company (listed on the stock exchange)"},
    "Mummalle": {"A1": "Noun (Allative)", "n": "To/for Grandma; a dedication to a grandmother"},
    "Artikkelissa": {"B1": "Noun (Inessive)", "n": "In the article; refers to the location of information within a specific 'forskningsantologi' or publication"},
    "geeniekspression": {"C1": "Noun (Genitive)", "n": "Of gene expression; the 'genuttrycksmönster' or process by which information from a gene is used in the synthesis of 'RNA molecules'"},
    "jotka": {"A2": "Pronoun (Plural)", "n": "Which / Who / That; a relative pronoun used to connect 'single cells' or 'cell types' to further descriptive clauses"},
    "aiemmin": {'A2': 'Adverb', 'n': 'Previously or earlier; used to describe prior research states.'},
    "aina": {'A1': 'Adverb', 'n': "Always; e.g., 'always interested in biology'"},
    "alaa": {'B1': 'Noun (Partitive)', 'n': "The field or industry; referring to the 'construction sector' or 'plant biology' field"},
    "alkioille": {'C1': 'Noun (Allative)', 'n': "For the embryos; relating to 'cellular differentiation' in early developmental stages"},
    "annotaatioina": {'C1': 'Noun (Essive)', 'n': "As annotations; data labels used in 'resolved transcriptomics' to identify 'cell types'"},
    "automatisoidun": {'B2': 'Adjective (Genitive)', 'n': "Automated; such as an 'automatisoidun' 'library preparation' process"},
    "Avaintermit": {'B1': 'Noun (Plural)', 'n': "Key terms; the 'keywords' used to index a 'väitöskirja' (dissertation)"},
    "avulla": {'A2': 'Postposition', 'n': "With the help of / by means of; e.g., 'ST-teknologian avulla' (with the help of ST technology)"},
    "biologiasta": {'B1': 'Noun (Elative)', 'n': 'About biology; the subject of interest or study.'},
    "biologisen": {'B2': 'Adjective (Genitive)', 'n': "Biological; relating to 'biologisen' 'monimuotoisuuden' (biological diversity)"},
    "edellyttää": {'B2': 'Verb', 'n': "To require or demand; a condition necessary for 'high SNR' or 'test accuracy'"},
    "edistää": {'B2': 'Verb', 'n': "To promote or advance; e.g., to advance 'gender equality' or 'nuclear fusion' research"},
    "edistävät": {'B2': 'Verb (Plural)', 'n': "They promote/advance; factors that 'edistävät' 'cellular differentiation'"},
    "ei": {'A1': 'Adverb/Verb', 'n': 'No / Not; the negative particle.'},
    "ei-malliorganismi": {'C1': 'Noun', 'n': "Non-model organism; species like 'abies' that are not 'Arabidopsis thaliana'"},
    "ekologisista": {'B2': 'Adjective (Elative)', 'n': "From ecological; relating to the 'propagation environment' or nature"},
    "elämän": {'B1': 'Noun (Genitive)', 'n': "Of life; e.g., 'elämän' 'monimuotoisuus' (the diversity of life)"},
    "eliöiden": {'B2': 'Noun (Genitive Plural)', 'n': "Of organisms; 'eliöiden' 'vuorovaikutus' (interaction of organisms)"},
    "Eliöiden": {'B2': 'Noun (Genitive Plural)', 'n': "Capitalized form of 'eliöiden'"},
    "eliöissä": {'B2': 'Noun (Inessive Plural)', 'n': "In organisms; where 'genuttrycksmönster' occur"},
    "eliöistä": {'B2': 'Noun (Elative Plural)', 'n': "From/about organisms; studied in 'metatranscriptomics'"},
    "eliökunnissa": {'C1': 'Noun (Inessive Plural)', 'n': "In the kingdoms of life; e.g., 'Viridiplantae' or 'Metazoa'"},
    "eliöryhmä": {'B2': 'Noun', 'n': 'A group of organisms; a specific taxonomic or ecological category.'},
    "eliöt": {'B1': 'Noun (Plural)', 'n': "Organisms; all living 'biological systems'"},
    "en": {'A1': 'Verb', 'n': 'I do not; the 1st person singular negative verb.'},
    "englantia": {'A1': 'Noun (Partitive)', 'n': "English (language); e.g., 'puhuimme englantia' (we spoke English)"},
    "ensimmäisinä": {'B1': 'Adjective (Essive Plural)', 'n': "As the first ones; being pioneers in an 'initiative'"},
    "eri": {'A2': 'Adjective', 'n': "Different or various; used to describe 'eri' 'solutyypit' (various cell types)"},
    "erikoistuneet": {'B2': 'Adjective/Verb', 'n': "Specialized; cells that have completed 'cellular differentiation'"},
    "erilaisia": {'A2': 'Adjective (Partitive Plural)', 'n': "Different kinds of; 'erilaisia' 'geeniekspressiomalleja' (different gene expression models)"},
    "erilaisiin": {'A2': 'Adjective (Illative Plural)', 'n': "Into different kinds of; e.g., adapting to 'erilaisiin' 'ympäristöihin'"},
    "erilaistuvat": {'C1': 'Verb (Plural)', 'n': "They differentiate; process of 'meristematic' cells becoming specialized"},
    "erityisesti": {'B1': 'Adverb', 'n': "Especially or particularly; e.g., 'erityisesti' 'havupuiden' kohdalla"},
    "esittelee": {'B1': 'Verb', 'n': "Introduces or presents; this 'väitöskirja' 'esittelee' new findings"},
    "esittelemme": {'B1': 'Verb', 'n': "We introduce/present; used in a 'write-up' to describe the 'ST-teknologian'"},
    "esittelimme": {'B1': 'Verb (Past)', 'n': "We introduced/presented; past tense of 'esittelemme'"},
    "että": {'A1': 'Conjunction', 'n': 'That; used to connect clauses.'},
    "geenejä": {'B2': 'Noun (Partitive Plural)', 'n': "Genes; the units of 'DNA molecules' analyzed"},
    "geeniekspressioanalyysin": {'C1': 'Noun (Genitive)', 'n': "Of gene expression analysis; the 'spatial profiling' of 'mRNA molecules'"},
    "geeniekspressiokartaston": {'C1': 'Noun (Genitive)', 'n': "Of a gene expression atlas; a 'spatial context' map of 'gene expression'"},
    "geeniekspressiokuvioiden": {'C1': 'Noun (Genitive Plural)', 'n': "Of gene expression patterns; synonym for 'genuttrycksmönster'"},
    "geeniekspressiokuviot": {'C1': 'Noun (Plural)', 'n': "Gene expression patterns; the visual result of 'spatial profiling'"},
    "geeniekspressiomalleja": {'C1': 'Noun (Partitive Plural)', 'n': "Gene expression models; mathematical 'NN-model' representations of 'transcriptome-wide' data"},
    "geeniekspressioon": {'C1': 'Noun (Illative)', 'n': "Into gene expression; factors influencing 'geeniekspressioon'"},
    "geenien": {'B2': 'Noun (Genitive Plural)', 'n': "Of genes; 'geenien' 'säätely' (regulation of genes)"},
    "geneettisiin": {'B2': 'Adjective (Illative Plural)', 'n': "Into genetic; relating to 'geneettisiin' 'prosesseihin'"},
    "geneettisten": {'B2': 'Adjective (Genitive Plural)', 'n': "Of genetic; e.g., 'geneettisten' 'säätelyverkostojen' (of genetic regulatory networks)"},
    "haasteita": {'B1': 'Noun (Partitive Plural)', 'n': "Challenges; such as 'haasteita' in 'library preparation' for 'plant cells'"},
    "Haluan": {'A1': 'Verb', 'n': "I want; often used in acknowledgments ('Haluan kiittää...')"},
    "havainnollistaa": {'B2': 'Verb', 'n': "To illustrate or demonstrate; using 'concentra-Figure' to 'havainnollistaa' data"},
    "havaitsimme": {'B1': 'Verb (Past)', 'n': "We observed/detected; 'havaitsimme' 'spatial gene expression' variations"},
    "havupuiden": {'C1': 'Noun (Genitive Plural)', 'n': "Of conifers; relating to 'abies' and other 'gymnosperm' species"},
    "heterogeenisyyden": {'C1': 'Noun (Genitive)', 'n': "Of heterogeneity; the 'cell type' diversity within 'plant tissues'"},
    "hyödyntää": {'B2': 'Verb', 'n': "To utilize or exploit; e.g., 'hyödyntää' 'ST-teknologiaa'"},
    "ilman": {'A2': 'Preposition', 'n': "Without; e.g., 'ilman' 'CSI updates' (without CSI updates)"},
    "isäntäeliön": {'C1': 'Noun (Genitive)', 'n': "Of the host organism; in 'host-bacteria-fungi' interactions"},
    "isäntäkasvin": {'C1': 'Noun (Genitive)', 'n': "Of the host plant; specifically 'isäntäkasvin' 'mikrobiomi'"},
    "isoihin": {'A2': 'Adjective (Illative Plural)', 'n': "Into big/large; e.g., 'isoihin' 'dataset size' datasets"},
    "ja": {'A1': 'Conjunction', 'n': 'And; the most common coordinating conjunction.'},
    "joita": {'A2': 'Pronoun (Partitive Plural)', 'n': "Which / that; relative pronoun referring to plural 'solutyypit' or 'geenejä'"},
    "joka": {'A2': 'Pronoun', 'n': 'Which / that / who; relative pronoun for singular subjects.'},
    "juuri": {'A2': 'Adverb/Noun', 'n': "Just / Root; 'juuri' (root) is a key 'plant tissue' for 'spatial profiling'"},
    "kaiken": {'A2': 'Pronoun (Genitive)', 'n': "Of everything; 'ymmärtää kaiken' (to understand everything)"},
    "kaikista": {'A2': 'Pronoun (Elative Plural)', 'n': "Of all; 'kaikista' 'eliöistä' (of all organisms)"},
    "kannustaneet": {'B2': 'Verb (Past Participle Plural)', 'n': "Encouraged; 'perhettäni' on 'kannustaneet' minua (my family has encouraged me)"},
    "kannustivat": {'B2': 'Verb (Past Plural)', 'n': "They encouraged; e.g., 'postdocs' who 'kannustivat' the study"},
    "Kartaston": {'B2': 'Noun (Genitive)', 'n': "Of the atlas; 'geeniekspressiokartaston' 'tuottaminen'"},
    "kasveista": {'B1': 'Noun (Elative Plural)', 'n': "From/about plants; 'opin kasveista' (I learned about plants)"},
    "kasvibiologia": {'B2': 'Noun', 'n': "Plant biology; the study of 'plant cells' and 'angiosperm' species"},
    "kasvien": {'B1': 'Noun (Genitive Plural)', 'n': "Of plants; 'kasvien' 'kehitys' (development of plants)"},
    "kasvusilmujen": {'C1': 'Noun (Genitive Plural)', 'n': "Of growth buds; 'meristematic' regions in 'havupuiden'"},
    "käyttää": {'A2': 'Verb', 'n': "To use; e.g., 'käyttää' 'Sanger sequencing' menetelmää"},
    "kehittymisen": {'B2': 'Noun (Genitive)', 'n': "Of the development; the process of 'cellular differentiation' or growth"},
    "kehityksen": {'B2': 'Noun (Genitive)', 'n': "Of the development; synonym for 'kehittymisen'"},
    "kehitys": {'B1': 'Noun', 'n': "Development; 'eliöiden' 'kehitys' (the development of organisms)"},
    "kehitysbiologiaan": {'C1': 'Noun (Illative)', 'n': "Into developmental biology; the field of 'alkioille' and 'meristem' research"},
    "kehitysbiologisesti": {'C1': 'Adverb', 'n': "Developmentally; in a 'kehitysbiologisesti' interesting way"},
    "kerroista,": {'B1': 'Noun (Partitive Plural)', 'n': "Of times; 'niistä kerroista' (of those times)"},
    "keskittyy": {'B1': 'Verb', 'n': "Focuses; this 'tutkimus' 'keskittyy' 'spatiaaliseen' 'transkriptomiikkaan'"},
    "kestävän": {'B2': 'Adjective (Genitive)', 'n': "Sustainable; 'kestävän' 'metsätalouden' (of sustainable forestry)"},
    "kiinnostuin": {'B1': 'Verb (Past)', 'n': "I became interested; 'kiinnostuin' 'biologiasta' (I became interested in biology)"},
    "Kiitos": {'A1': 'Noun/Interjection', 'n': 'Thank you; used in acknowledgments.'},
    "kiittää": {'A1': 'Verb', 'n': "To thank; 'Haluan kiittää Mariaa'"},
    "kohtaamaan": {'B2': 'Verb', 'n': "To face or encounter; e.g., 'kohtaamaan' 'haasteita' (to face challenges)"},
    "korostavat": {'B2': 'Verb (Plural)', 'n': "They emphasize; results that 'korostavat' 'spatial context' merkitystä"},
    "kukkapenkkejä": {'B1': 'Noun (Partitive Plural)', 'n': "Flower beds; 'Mummalle!' shared 'kukkapenkkejä' with me"},
    "kummallekin": {'B1': 'Pronoun (Allative)', 'n': "To/for both; providing 'inclusion' for 'kummallekin'"},
    "kun": {'A1': 'Conjunction', 'n': 'When / While; used to introduce temporal clauses.'},
    "kuten": {'A2': 'Adverb', 'n': "Such as / Like; e.g., 'kuten' 'Arabidopsis thaliana'"},
    "kuusen": {'B2': 'Noun (Genitive)', 'n': "Of the spruce; 'Picea abies' or 'kuusen' 'genomi'"},
    "kuvaamisen": {'B2': 'Noun (Genitive)', 'n': "Of describing/imaging; e.g., 'solukkorakenteiden' 'kuvaamisen' tarkkuus"},
    "kysymyksiin": {'B1': 'Noun (Illative Plural)', 'n': "To/into questions; 'vastaavat' 'biologisiin' 'kysymyksiin'"},
    "laaja": {'B1': 'Adjective', 'n': "Wide or extensive; a 'laaja' 'tutkimus' (an extensive study)"},
    "laajan": {'B1': 'Adjective (Genitive)', 'n': "Of a wide/extensive; 'laajan' 'transkriptomin' 'analyysi'"},
    "laajentavat": {'B2': 'Verb (Plural)', 'n': "They expand; new 'discoveries' that 'laajentavat' 'ymmärrystämme'"},
    "lähestymistavan": {'B2': 'Noun (Genitive)', 'n': "Of an approach; 'uuden' 'lähestymistavan' 'esitteleminen'"},
    "lähti": {'A2': 'Verb (Past)', 'n': "Started / Left; e.g., 'lähti' lapsuuden leikkeistä (started from childhood games)"},
    "lajeihin": {'B2': 'Noun (Illative Plural)', 'n': "Into species; relating to 'eri' 'lajeihin'"},
    "lajien": {'B1': 'Noun (Genitive Plural)', 'n': "Of species; 'lajien' 'monimuotoisuus' (diversity of species)"},
    "lapsena": {'B1': 'Noun (Essive)', 'n': "As a child; when the author first learned about 'kasveista'"},
    "lehdistä": {'B1': 'Noun (Elative Plural)', 'n': "From/about leaves; 'lehdistä' 'eristetty' 'RNA' (RNA isolated from leaves)"},
    "leikkeisiin": {'B1': 'Noun (Illative Plural)', 'n': "Into games/play; childhood 'leikkeihin'"},
    "liittyviin": {'B2': 'Adjective (Illative Plural)', 'n': "Into related; 'tutkimukseen' 'liittyviin' 'kysymyksiin'"},
    "lisääntymisbiologiasta": {'C1': 'Noun (Elative)', 'n': "About reproductive biology; studying 'seed' and 'pollen' development"},
    "lituruohon": {'C1': 'Noun (Genitive)', 'n': "Of the thale cress; the Finnish name for 'Arabidopsis thaliana'"},
    "määrää": {'B1': 'Noun (Partitive) / Verb', 'n': "Amount / Determines; 'määrää' 'geeniekspression' tasoa"},
    "mahdollinen": {'B1': 'Adjective', 'n': "Possible; e.g., 'mahdollinen' 'tau-violation' (possible delay violation)"},
    "mahdollisti": {'B2': 'Verb (Past)', 'n': "Made possible / Enabled; 'mahdollisti' 'transcriptome-wide' analysis"},
    "mahdollisuuksia": {'B1': 'Noun (Partitive Plural)', 'n': "Opportunities/Possibilities; 'uusia' 'mahdollisuuksia' 'tutkimukseen'"},
    "Maria": {'A1': 'Proper Noun', 'n': 'A personal name; often a colleague or mentor mentioned in acknowledgments.'},
    "matkustamaan": {'B1': 'Verb', 'n': "To travel; e.g., to travel to 'GLOBECOM' or other conferences"},
    "Me": {'A1': 'Pronoun', 'n': 'We; referring to the research team or authors.'},
    "Menetelmä": {'B1': 'Noun', 'n': "Method; a specific 'SRT-menetelmä' or 'spatial profiling' technique"},
    "menetelmää": {'B1': 'Noun (Partitive)', 'n': "Method (partitive); 'käytimme tätä menetelmää' (we used this method)"},
    "menetelmällä": {'B1': 'Noun (Adessive)', 'n': "With/by the method; 'tällä menetelmällä' 'saavutimme' high accuracy"},
    "menetelmän": {'B1': 'Noun (Genitive)', 'n': "Of the method; 'menetelmän' 'toistettavuus' (reproducibility of the method)"},
    "Menetelmän": {'B1': 'Noun (Genitive)', 'n': "Capitalized form of 'menetelmän'"},
    "menetelmiä": {'B1': 'Noun (Partitive Plural)', 'n': "Methods (plural); 'uusia' 'menetelmiä' 'tutkimukseen'"},
    "menetelmien": {'B1': 'Noun (Genitive Plural)', 'n': "Of the methods; 'menetelmien' 'vertailu' (comparison of methods)"},
    "merkittävien": {'B2': 'Adjective (Genitive Plural)', 'n': "Of significant; 'merkittävien' 'löydösten' (of significant findings)"},
    "metsätalouden": {'B2': 'Noun (Genitive)', 'n': "Of forestry; 'kestävän' 'metsätalouden' tarpeisiin"},
    "mikrobien": {'B2': 'Noun (Genitive Plural)', 'n': "Of microbes; 'mikrobien' 'monimuotoisuus' (diversity of microbes)"},
    "mikrobiomi": {'C1': 'Noun', 'n': "Microbiome; the 'host-bacteria-fungi' community of a 'kasvien'"},
    "mikrobiomin": {'C1': 'Noun (Genitive)', 'n': "Of the microbiome; 'mikrobiomin' 'säätely' (regulation of the microbiome)"},
    "mikrobipesäkkeitä": {'C1': 'Noun (Partitive Plural)', 'n': "Microbial colonies; 'mikrobipesäkkeitä' 'isäntäeliön' pinnalle"},
    "mikrobiyhteisöjen": {'C1': 'Noun (Genitive Plural)', 'n': "Of microbial communities; studied via 'metatranscriptomics'"},
    "mikro-organismien": {'B2': 'Noun (Genitive Plural)', 'n': "Of micro-organisms; synonym for 'mikrobien'"},
    "miksi": {'A1': 'Adverb', 'n': "Why; e.g., 'miksi' 'monisoluisuus' kehittyi?"},
    "minua": {'A1': 'Pronoun (Partitive)', 'n': "Me; 'minua' on 'kannustettu' (I have been encouraged)"},
    "miten": {'A1': 'Adverb', 'n': "How; e.g., 'miten' 'geenit' 'vaikuttavat' 'kehitykseen'"},
    "molekyylimenetelmistä": {'C1': 'Noun (Elative Plural)', 'n': "About molecular methods; including 'RNA sequencing' and 'Sanger sequencing'"},
    "monimuotoinen": {'B2': 'Adjective', 'n': "Diverse or multifaceted; 'monimuotoinen' 'eliöryhmä'"},
    "monimuotoisuudesta": {'B2': 'Noun (Elative)', 'n': "About diversity; 'biologisesta' 'monimuotoisuudesta'"},
    "monimuotoisuuteen": {'B2': 'Noun (Illative)', 'n': "Into diversity; factors leading to 'monimuotoisuuteen'"},
    "monimuotoisuutta": {'B2': 'Noun (Partitive)', 'n': "Diversity; 'lisätä' 'geneettistä' 'monimuotoisuutta'"},
    "monimutkaisen": {'B2': 'Adjective (Genitive)', 'n': "Of a complex; 'monimutkaisen' 'säätelyverkoston' 'analyysi'"},
    "monimutkaisia": {'B2': 'Adjective (Partitive Plural)', 'n': "Complex (plural); 'monimutkaisia' 'biologisia' 'prosesseja'"},
    "Monisoluisissa": {'C1': 'Adjective (Inessive Plural)', 'n': "In multicellular (organisms); relating to 'Metazoa' and 'Viridiplantae'"},
    "monisoluisista": {'C1': 'Adjective (Elative Plural)', 'n': "From/about multicellular (organisms); 'monisoluisista' 'eliöistä'"},
    "monisoluisten": {'C1': 'Adjective (Genitive Plural)', 'n': "Of multicellular (organisms); 'monisoluisten' 'kehitysbiologia'"},
    "morfologisen": {'C1': 'Adjective (Genitive)', 'n': "Of morphological; 'morfologisen' 'rakenteen' 'kuvaaminen'"},
    "muille": {'A2': 'Pronoun (Allative Plural)', 'n': "To others; 'esitellä' 'muille' tutkijoille"},
    "multimodaalisen": {'C1': 'Adjective (Genitive)', 'n': "Of multimodal; 'multimodaalisen' 'datan' 'yhdistäminen'"},
    "Mummalle!": {'A1': 'Noun (Allative)', 'n': "To Grandma! A dedication in a 'väitöskirja' to a grandmother"},
    "muodostaen": {'B2': 'Verb (Gerund)', 'n': "Forming; 'muodostaen' 'monimutkaisia' 'rakenteita'"},
    "muuttuviin": {'B2': 'Adjective (Illative Plural)', 'n': "Into changing; e.g., 'muuttuviin' 'ympäristöolosuhteisiin' (to changing environmental conditions)"},
    "myös": {'A1': 'Adverb', 'n': 'Also / Too; used to add information.'},
    "näiden": {'A2': 'Pronoun (Genitive Plural)', 'n': "Of these; 'näiden' 'tulosten' 'perusteella' (on the basis of these results)"},
    "näistä": {'A2': 'Pronoun (Elative Plural)', 'n': "From these; 'yksi näistä' 'menetelmistä' (one of these methods)"},
    "Nämä": {'A2': 'Pronoun (Plural)', 'n': 'These; used to refer back to multiple items.'},
    "ne": {'A1': 'Pronoun (Plural)', 'n': "They / Those; referring to inanimate objects or 'eliöt'"},
    "Ne": {'A1': 'Pronoun (Plural)', 'n': "Capitalized form of 'ne'"},
    "niiden": {'A2': 'Pronoun (Genitive Plural)', 'n': "Their / Of them; 'niiden' 'vuorovaikutus' (their interaction)"},
    "niistä": {'A2': 'Pronoun (Elative Plural)', 'n': "Of them / From them; e.g., 'niistä' 'kerroista' (of those times)"},
    "niitä": {'A2': 'Pronoun (Partitive Plural)', 'n': "Them; 'tutkia niitä' (to study them)"},
    "ohjaavista": {'B2': 'Adjective (Elative Plural)', 'n': "Of/from those guiding; 'kehitystä' 'ohjaavista' 'geeneistä'"},
    "ohuisiin": {'B2': 'Adjective (Illative Plural)', 'n': "Into thin; e.g., 'ohuisiin' 'solukkoleikkeisiin' (into thin tissue sections)"},
    "olette": {'A1': 'Verb', 'n': "You are (plural); 'Te olette auttaneet minua'"},
    "olisi": {'A2': 'Verb (Conditional)', 'n': "Would be; 'se olisi mahdollista' (it would be possible)"},
    "ollut": {'A2': 'Verb (Past Participle)', 'n': "Been; 'on ollut' (has been)"},
    "on": {'A1': 'Verb', 'n': "Is / Has; the 3rd person singular of 'olla'"},
    "opin": {'A2': 'Verb (Past)', 'n': "I learned; 'opin' 'paljon' 'tutkimuksen' aikana"},
    "oppimiseen": {'B1': 'Noun (Illative)', 'n': "Into learning; 'kannustaa' 'oppimiseen'"},
    "ovat": {'A1': 'Verb (Plural)', 'n': "They are / Have; the 3rd person plural of 'olla'"},
    "paikalliseen": {'B1': 'Adjective (Illative)', 'n': "Into local; relating to 'paikalliseen' 'transkriptomiin'"},
    "paljastanut": {'B2': 'Verb (Past Participle)', 'n': "Revealed; 'tutkimus' on 'paljastanut' 'uutta' tietoa"},
    "parantaa": {'B1': 'Verb', 'n': "To improve; e.g., 'parantaa' 'tehokkuutta' or 'prediction accuracy'"},
    "parantamiseksi": {'B2': 'Noun (Translative)', 'n': "For improving; 'tietämyksen' 'parantamiseksi'"},
    "perhettäni": {'B1': 'Noun (Partitive)', 'n': "My family; 'kiitän perhettäni'"},
    "perusteella": {'B1': 'Postposition', 'n': "On the basis of; 'tulosten perusteella' (on the basis of the results)"},
    "perusteita,": {'B1': 'Noun (Partitive Plural)', 'n': "Basics / Foundations; 'ymmärtää' 'perusteita'"},
    "perustunut": {'B2': 'Verb (Past Participle)', 'n': "Based on; 'tutkimus' on 'perustunut' 'ST-teknologiaan'"},
    "perustuvien": {'B2': 'Adjective (Genitive Plural)', 'n': "Based on (plural); 'sekvensointiin' 'perustuvien' 'menetelmien'"},
    "planktonlajeihin": {'C1': 'Noun (Illative Plural)', 'n': "Into plankton species; 'sovelsimme' 'menetelmää' 'planktonlajeihin'"},
    "prosesseista": {'B1': 'Noun (Elative Plural)', 'n': "About processes; 'biologisista' 'prosesseista'"},
    "puhumaan": {'A1': 'Verb', 'n': "To speak; 'oppia puhumaan englantia'"},
    "puutarhaan": {'B1': 'Noun (Illative)', 'n': "Into the garden; 'Mummalle!' 'puutarhaan'"},
    "pystyimme": {'B1': 'Verb (Past)', 'n': "We were able to; 'pystyimme' 'tunnistamaan' 'solutyypit'"},
    "pystyy": {'B1': 'Verb', 'n': "Is able to; 'menetelmä' 'pystyy' 'erottamaan' 'geenit'"},
    "rakenteita": {'B1': 'Noun (Partitive Plural)', 'n': "Structures; e.g., 'solukkorakenteiden' (of tissue structures)"},
    "reagoivat": {'B2': 'Verb (Plural)', 'n': "They react/respond; 'eliöt' 'reagoivat' 'ympäristöön'"},
    "resursseina": {'B2': 'Noun (Essive Plural)', 'n': "As resources; 'hyödyntää' 'resursseina'"},
    "rooleista": {'B1': 'Noun (Elative Plural)', 'n': "About roles; 'geenien' 'rooleista' 'kehityksessä'"},
    "säätelymekanismeista": {'C1': 'Noun (Elative Plural)', 'n': "About regulatory mechanisms; the 'säätely' of 'biologiset prosessit'"},
    "säätelyverkkojen": {'C1': 'Noun (Genitive Plural)', 'n': "Of regulatory networks; synonym for 'säätelyverkostojen'"},
    "säätelyverkostoihin": {'C1': 'Noun (Illative Plural)', 'n': "Into regulatory networks; 'pureutua' 'säätelyverkostoihin'"},
    "säätelyverkostoja": {'C1': 'Noun (Partitive Plural)', 'n': "Regulatory networks; 'tutkia' 'geenien' 'säätelyverkostoja'"},
    "säätelyverkostojen": {'C1': 'Noun (Genitive Plural)', 'n': "Of regulatory networks; the 'mapping' of 'geneettisten' networks"},
    "säätelyyn": {'C1': 'Noun (Illative)', 'n': "Into regulation; 'osallistua' 'geenien' 'säätelyyn'"},
    "saavuttamiseksi": {'B2': 'Noun (Translative)', 'n': "For achieving; 'tavoitteiden' 'saavuttamiseksi'"},
    "saimme": {'A2': 'Verb (Past)', 'n': "We got/received; 'saimme' 'erinomaisia' 'tuloksia'"},
    "samanaikaisen": {'B2': 'Adjective (Genitive)', 'n': "Of simultaneous; 'samanaikaisen' 'analyysin' 'mahdollistaminen'"},
    "samanaikaisesti": {'B2': 'Adverb', 'n': "Simultaneously; capturing 'spatial context' and 'gene expression' 'samanaikaisesti'"},
    "sekä": {'A2': 'Conjunction', 'n': 'As well as / And; used to connect words or phrases in a series.'},
    "sekvensointikirjastojen": {'C1': 'Noun (Genitive Plural)', 'n': "Of sequencing libraries; 'valmistamiseen' 'sekvensointikirjastojen'"},
    "Sen": {'A2': 'Pronoun (Genitive)', 'n': "Its / Of it; 'sen' 'avulla' (with its help)"},
    "sietokyvyn": {'B2': 'Noun (Genitive)', 'n': "Of tolerance/resilience; 'kuusen' 'sietokyvyn' 'parantaminen'"},
    "signaaleihin": {'B2': 'Noun (Illative Plural)', 'n': "Into signals; 'solut' 'reagoivat' 'signaaleihin'"},
    "sijaan": {'A2': 'Postposition', 'n': "Instead of; e.g., 'CSI updates' 'sijaan' (instead of CSI updates)"},
    "sirutekniikkaan": {'C1': 'Noun (Illative)', 'n': "Into chip technology; relating to 'NanoString' or 'microarray' platforms"},
    "sisältyvät": {'B2': 'Verb (Plural)', 'n': "Are included; 'tutkimukseen' 'sisältyvät' 'artikkelit'"},
    "sitä": {'A1': 'Pronoun (Partitive)', 'n': "It; 'tutkimme sitä' (we study it)"},
    "skaalautuvuutta": {'C1': 'Noun (Partitive)', 'n': "Scalability; 'parantaa' 'menetelmän' 'skaalautuvuutta'"},
    "solujen": {'B2': 'Noun (Genitive Plural)', 'n': "Of cells; 'solujen' 'erilaistuminen' (differentiation of cells)"},
    "solukkoleikkeissä": {'C1': 'Noun (Inessive Plural)', 'n': "In tissue sections; using 'slide' 'solukkoleikkeissä'"},
    "solukkorakenteiden": {'C1': 'Noun (Genitive Plural)', 'n': "Of tissue structures; 'resoluutio' 'solukkorakenteiden' 'kuvaamisessa'"},
    "solukoita": {'C1': 'Noun (Partitive Plural)', 'n': "Tissues; 'erilaisia' 'kasvien' 'solukoita'"},
    "solusta": {'B2': 'Noun (Elative)', 'n': "From a cell; 'yksittäisestä' 'solusta' (from a single cell)"},
    "solutyypit": {'B2': 'Noun (Plural)', 'n': "Cell types; identified through 'gene expression patterns'"},
    "sopeutumaan": {'B2': 'Verb', 'n': "To adapt; e.g., 'sopeutumaan' 'ilmastonmuutokseen' (to adapt to climate change)"},
    "sovelsimme": {'B2': 'Verb (Past)', 'n': "We applied; 'sovelsimme' 'menetelmää' 'havupuiden' 'neulasiin'"},
    "Sovelsimme": {'B2': 'Verb (Past)', 'n': "Capitalized form of 'sovelsimme'"},
    "Spatiaalinen": {'C1': 'Adjective', 'n': "Spatial; relating to 'spatial context' or 'spatial profiling'"},
    "spatiaalisen": {'C1': 'Adjective (Genitive)', 'n': "Of spatial; 'spatiaalisen' 'transkriptomiikan' 'kehitys'"},
    "spatiaalisessa": {'C1': 'Adjective (Inessive)', 'n': "In spatial; 'spatiaalisessa' 'yhteydessä' (in a spatial context)"},
    "spatiaalisten": {'C1': 'Adjective (Genitive Plural)', 'n': "Of spatial (plural); 'spatiaalisten' 'menetelmien' 'hyödyntäminen'"},
    "spatiotemporaalisen": {'C1': 'Adjective (Genitive)', 'n': "Of spatiotemporal; mapping both space and time in 'cellular differentiation'"},
    "ST-teknologiaa": {'C1': 'Noun (Partitive)', 'n': "ST technology (Spatial Transcriptomics); 'käyttää' 'ST-teknologiaa'"},
    "ST-teknologialla": {'C1': 'Noun (Adessive)', 'n': "With/by ST technology; 'tutkia' 'solukoita' 'ST-teknologialla'"},
    "ST-teknologian": {'C1': 'Noun (Genitive)', 'n': "Of ST technology; 'ST-teknologian' 'sovellukset' (applications of ST technology)"},
    "Suuri": {'A2': 'Adjective', 'n': "Big / Large; 'Suuri' kiitos kaikille"},
    "syy,": {'A2': 'Noun', 'n': "Reason; 'tärkein syy' (the most important reason)"},
    "Tähän": {'A2': 'Pronoun (Illative)', 'n': "To this; 'tähän' 'tutkimukseen' 'osallistui'"},
    "tällainen": {'A2': 'Pronoun', 'n': "Such / Like this; 'tällainen' 'lähestymistapa' (such an approach)"},
    "Tämä": {'A1': 'Pronoun', 'n': 'This; singular proximal demonstrative pronoun.'},
    "Tarja,": {'A1': 'Proper Noun', 'n': 'A personal name; often appearing in acknowledgments.'},
    "tärkeää": {'A2': 'Adjective (Partitive)', 'n': "Important; 'on tärkeää' 'ymmärtää' (it is important to understand)"},
    "tärkeitä": {'A2': 'Adjective (Partitive Plural)', 'n': "Important (plural); 'tärkeitä' 'havaintoja' (important observations)"},
    "tarkkuutta": {'B2': 'Noun (Partitive)', 'n': "Precision / Accuracy; 'parantaa' 'spatiaalista' 'tarkkuutta'"},
    "tässä": {'A1': 'Adverb', 'n': "Here / In this; 'tässä' 'artikkelissa' (in this article)"},
    "taustalla": {'B1': 'Adverb/Noun', 'n': "In the background / Behind; 'ilmiön taustalla' (behind the phenomenon)"},
    "tautiriskin": {'B2': 'Noun (Genitive)', 'n': "Of disease risk; 'tautiriskin' 'arviointi' (assessment of disease risk)"},
    "tavoitteiden": {'B2': 'Noun (Genitive Plural)', 'n': "Of goals/objectives; 'tavoitteiden' 'saavuttaminen'"},
    "tehokkuuden": {'B2': 'Noun (Genitive)', 'n': "Of efficiency; 'tehokkuuden' 'parantaminen' in 'transport capacity'"},
    "tehokkuutta": {'B2': 'Noun (Partitive)', 'n': "Efficiency; 'lisätä' 'laskennallista' 'tehokkuutta'"},
    "tehtyihin": {'B2': 'Verb (Past Participle Illative Plural)', 'n': "Into those made; 'aikaisemmin' 'tehtyihin' 'tutkimuksiin'"},
    "teimme": {'A2': 'Verb (Past)', 'n': "We did/made; 'teimme' 'useita' 'kokeita'"},
    "teitä": {'A2': 'Pronoun (Partitive Plural)', 'n': "You (plural); 'kiitän teitä kaikkia'"},
    "thaliana)": {'C1': 'Proper Noun', 'n': "The specific epithet for 'Arabidopsis thaliana'"},
    "tietämystä": {'B2': 'Noun (Partitive)', 'n': "Knowledge; 'lisätä' 'tietämystä' 'biologiasta'"},
    "tieto": {'A2': 'Noun', 'n': 'Knowledge / Information; general term for data or awareness.'},
    "tietoa": {'A2': 'Noun (Partitive)', 'n': "Information; 'saada' 'tietoa' 'säätelyverkostoista'"},
    "Tiivistelmä": {'B1': 'Noun', 'n': "Abstract / Summary; the 'write-up' at the beginning of a paper"},
    "toiminnan": {'B1': 'Noun (Genitive)', 'n': "Of the function/activity; 'solujen' 'toiminnan' 'ymmärtäminen'"},
    "toimivat": {'B1': 'Verb (Plural)', 'n': "They function/work; 'geenit' 'toimivat' yhdessä"},
    "toisiin": {'A2': 'Pronoun (Illative Plural)', 'n': "Into others; 'vaikuttaa' 'toisiin' soluihin"},
    "toistettavuutta": {'C1': 'Noun (Partitive)', 'n': "Reproducibility; 'parantaa' 'menetelmän' 'toistettavuuutta'"},
    "transkriptomia": {'C1': 'Noun (Partitive)', 'n': "Transcriptome; 'tutkia' 'koko' 'transkriptomia'"},
    "transkriptomiikan": {'C1': 'Noun (Genitive)', 'n': "Of transcriptomics; 'transkriptomiikan' 'menetelmät'"},
    "transkriptomiikassa": {'C1': 'Noun (Inessive)', 'n': "In transcriptomics; applying 'ST-teknologiaa' 'transkriptomiikassa'"},
    "transkriptomiikka": {'C1': 'Noun', 'n': "Transcriptomics; the study of 'RNA sequencing' data"},
    "transkriptomin": {'C1': 'Noun (Genitive)', 'n': "Of the transcriptome; 'transkriptomin' 'sekvensointi'"},
    "tukeneet": {'B2': 'Verb (Past Participle Plural)', 'n': "Supported; 'ihmiset', jotka ovat 'tukeneet' minua"},
    "tuleviin": {'B1': 'Adjective (Illative Plural)', 'n': "Into future; 'tuleviin' 'tutkimuksiin' (into future studies)"},
    "tulkintaa": {'B2': 'Noun (Partitive)', 'n': "Interpretation; 'helpottaa' 'tulosten' 'tulkintaa'"},
    "Tulokset": {'B1': 'Noun (Plural)', 'n': "Results; the findings of a 'tutkimus'"},
    "tuloksia": {'B1': 'Noun (Partitive Plural)', 'n': "Results; 'saada' 'mielenkiintoisia' 'tuloksia'"},
    "tunnistaen": {'B2': 'Verb (Gerund)', 'n': "Identifying; 'tunnistaen' 'uusia' 'solutyyppejä'"},
    "tunnistamiseen": {'B2': 'Noun (Illative)', 'n': "Into identifying; 'solujen' 'tunnistamiseen' 'kudoksesta'"},
    "tunnistimme": {'B2': 'Verb (Past)', 'n': "We identified; 'tunnistimme' 'geenit', jotka ohjaavat kehitystä"},
    "tuntemattomia": {'B2': 'Adjective (Partitive Plural)', 'n': "Unknown; 'tuntemattomia' 'biologisia' 'mekanismeja'"},
    "tuotekehitys": {'B2': 'Noun', 'n': "Product development; applying research to commercial 'kits'"},
    "tuotimme": {'B2': 'Verb (Past)', 'n': "We produced; 'tuotimme' 'geeniekspressiokartaston'"},
    "tutkijoille": {'B1': 'Noun (Allative Plural)', 'n': "To researchers; providing resources 'tutkijoille'"},
    "tutkimaan": {'B1': 'Verb', 'n': "To study/examine; 'lähteä' 'tutkimaan' 'maailmaa'"},
    "tutkimisen": {'B2': 'Noun (Genitive)', 'n': "Of studying/examining; 'eliöiden' 'tutkimisen' tärkeys"},
    "tutkimme": {'B1': 'Verb', 'n': "We study/examine; 'tutkimme' 'monisoluisten' kehitystä"},
    "tutkimukseen": {'B1': 'Noun (Illative)', 'n': "Into research; 'osallistua' 'tutkimukseen'"},
    "tutkimuksessa": {'B1': 'Noun (Inessive)', 'n': "In the research; 'tässä tutkimuksessa' (in this research)"},
    "tutkimukset": {'B1': 'Noun (Plural)', 'n': "Studies / Researches; 'aiemmat tutkimukset' (previous studies)"},
    "tutkimus": {'B1': 'Noun', 'n': "Research / Study; the central activity of 'väitöskirja'"},
    "Tutkimus": {'B1': 'Noun', 'n': "Capitalized form of 'tutkimus'"},
    "tutkimushankkeisiin": {'C1': 'Noun (Illative Plural)', 'n': "Into research projects; 'osallistua' 'laajoihin' 'tutkimushankkeisiin'"},
    "uuden": {'A2': 'Adjective (Genitive)', 'n': "Of a new; 'uuden' 'menetelmän' 'kehittäminen'"},
    "uusia": {'A2': 'Adjective (Partitive Plural)', 'n': "New (plural); 'uusia' 'havaintoja' (new observations)"},
    "uusien": {'A2': 'Adjective (Genitive Plural)', 'n': "Of new; 'uusien' 'ratkaisujen' 'etsiminen'"},
    "uutta": {'A2': 'Adjective (Partitive)', 'n': "New; 'saada' 'uutta' tietoa"},
    "vaikuttavat": {'B1': 'Verb (Plural)', 'n': "They affect / Influence; 'geenit' 'vaikuttavat' kehitykseen"},
    "väitöskirja": {'B2': 'Noun', 'n': "Doctoral dissertation; the 'write-up' of a PhD project"},
    "Väitöskirja": {'B2': 'Noun', 'n': "Capitalized form of 'väitöskirja'"},
    "väitöskirjaan": {'B2': 'Noun (Illative)', 'n': "Into the dissertation; 'sisältyvät' 'väitöskirjaan'"},
    "välisen": {'A2': 'Adjective (Genitive)', 'n': "Between; 'isännän ja mikrobin' 'välisen' 'vuorovaikutuksen'"},
    "välisiä": {'B1': 'Adjective (Partitive Plural)', 'n': "Between (plural); 'eliöiden' 'välisiä' 'suhteita'"},
    "välisiin": {'B1': 'Adjective (Illative Plural)', 'n': "Into between; 'pureutua' 'välisiin' 'eroihin'"},
    "valmistamiseen": {'B2': 'Noun (Illative)', 'n': "Into preparation/making; 'sekvensointikirjastojen' 'valmistamiseen'"},
    "valtavan": {'B2': 'Adjective (Genitive)', 'n': "Of a huge/vast; 'valtavan' 'datamäärän' (of a vast amount of data)"},
    "vastaavat": {'B1': 'Verb (Plural)', 'n': "They answer / Correspond; 'tulokset' 'vastaavat' 'odotuksia'"},
    "Viimeaikainen": {'B2': 'Adjective', 'n': "Recent; 'Viimeaikainen' 'kehitys' 'transkriptomiikassa'"},
    "viljelykasvien": {'B2': 'Noun (Genitive Plural)', 'n': "Of crops; e.g., 'viljelykasvien' 'sietokyky' (resilience of crops)"},
    "voivat": {'A2': 'Verb (Plural)', 'n': "They can; 'geenit' 'voivat' muuttua"},
    "vuorovaikutuksen": {'B2': 'Noun (Genitive)', 'n': "Of interaction; 'isännän ja mikrobin' 'vuorovaikutuksen' 'analyysi'"},
    "vuorovaikutuksia": {'B2': 'Noun (Partitive Plural)', 'n': "Interactions; 'eliöiden' 'välisiä' 'vuorovaikutuksia'"},
    "vuorovaikutussuhteisiin": {'C1': 'Noun (Illative Plural)', 'n': "Into interaction relationships; studying 'mikrobiomin' 'vuorovaikutussuhteisiin'"},
    "yhdestä": {'A1': 'Numeral (Elative)', 'n': "From one; 'yhdestä' 'solusta' (from one cell)"},
    "yhdistimme": {'B2': 'Verb (Past)', 'n': "We combined; 'yhdistimme' 'spatiaalisen' ja 'ajallisen' datan"},
    "yksi-": {'A1': 'Prefix', 'n': "One- / Single-; used in words like 'yksisoluinen'"},
    "yksisoluiset": {'B2': 'Adjective (Plural)', 'n': "Single-celled; 'yksisoluiset' 'eliöt' (single-celled organisms)"},
    "yksisoluisista": {'B2': 'Adjective (Elative Plural)', 'n': "From/about single-celled; 'kehitys' 'yksisoluisista' 'monisoluisiin'"},
    "ymmärrystämme": {'B2': 'Noun (Partitive + Suffix)', 'n': "Our understanding; 'lisätä' 'ymmärrystämme' 'biologiasta'"},
    "ymmärtäminen": {'B1': 'Noun', 'n': "Understanding; 'mekanismien' 'ymmärtäminen'"},
    "ymmärtämiseen": {'B1': 'Noun (Illative)', 'n': "Into understanding; 'panostaa' 'asioiden' 'ymmärtämiseen'"},
    "ympäristöihin": {'B1': 'Noun (Illative Plural)', 'n': "Into environments; sopeutua 'eri' 'ympäristöihin'"},
    "ympäristöstä": {'B1': 'Noun (Elative)', 'n': "From/about the environment; 'saada' 'viestejä' 'ympäristöstä'"},

}

