# -*- coding: utf-8 -*-
# -*- mode: python; python-indent-offset: 4 -*-
#
# Some useful dicts and lists - for French
#
#
# 2024-01-20
#
# G. Q. Maguire Jr.
#
#
# Abbreviations used:
#  CEFR   Common European Framework of Reference for Languages: Learning, teaching, assessment.
#  POS    Part Of Speech
#
# This file contains several dicts and lists - these contain 'word' entries, but a 'word' can actually be a string of several words.
#
# Lists have been used when there can be multiple entries for the same 'word' and where there is not CEFR and POS information.
#
#
# Each dict's structure is:
# dict_name = {
#    entry,
#    entry,
# }
# Each entry is a 'word': CEFR_POS_dict
#
# a CEFR_POS_dict entry is a dict with the keys being CEFR levels (A1, A2, B1, B2, C1, C2, XX, and NA)
# followed by a string that contains comma separated POS
#
# The code 'XX' is used for an unknown CEFR level, while NA is for use when no level is applicable:
# 
# 
common_french_words={
    "grenouille": {"A1": "Noun", "n": "Frog; an 'amphibian' often used as a 'biological system' or model organism in developmental and physiological research."},

    "physico-chimiques": {"C1": "Adjective (Plural)", "n": "Physicochemical; relating to the 'l'analyse' of both physical and chemical 'Eigenschaften' of 'Werkstoffe'"},
    "Palais": {"A2": "Noun (Masculine)", "n": "Palace; a grand 'edifice' or 'slottskyrka' complex, often the site of 'monumentalkunst'"},
    "Museion": {"B2": "Proper Noun (Greek/Archaic)", "n": "The Museion; the classical 'templet' of the Muses, the historical 'förebilden' for the modern museum"},
    "Muséion": {"B2": "Proper Noun (French Variant)", "n": "French spelling for Museion; often referring to the OICM/ICOM journal founded in 1927"},
    "Recherches": {"B1": "Noun (Plural)", "n": "Research / Inquiries; the 'forskning' and 'undersökningar' carried out in an 'arkivforskning' context"},
    "esthétique": {"B2": "Noun / Adjective", "n": "Aesthetic; relating to the 'Restaureringsästhetik' and the visual 'Eindruck' of an object"},
    "formulées": {"B1": "Verb (Past Participle Feminine Plural)", "n": "Formulated; as in technical 'regler' or 'anvisningar' formulated by a 'kulturkommitté'"},
    "française": {"A1": "Adjective (Feminine)", "n": "French; used to denote 'française' (French) 'architettura' or 'Ecole' (school)"},
    "l'Arts": {"B1": "Noun (Masculine - Typo/Archaic)", "n": "The Arts; likely referring to 'Beaux-Arts' or 'l'Art' within a 'monumental' context"},
    "l'analyse": {"B2": "Noun (Feminine)", "n": "The analysis; the technical 'l'analyse' (e.g., chemical or stylistic) performed during a 'besiktigade'"},
    "synthèse": {"B2": "Noun (Feminine)", "n": "Synthesis; the 'sammanfattning' of various 'erfarenhetsutbytet' into a single 'utredning'"},
    "raisonné": {"B2": "Adjective", "n": "Reasoned / Systematic; as in 'Catalogue raisonné', a complete 'förteckning' of an artist's 'verk'"},
    "partages": {"B1": "Noun (Plural)", "n": "Shares / Divisions; referring to 'partages' of responsibilities between 'förvaltarna' and experts"},
    "nouveaux": {"A2": "Adjective (Plural)", "n": "New; describing 'nouveaux' 'Eingriffe' or modern 'tillsatser' in an 'edifice'"},
    "méconnu": {"B2": "Adjective", "n": "Unrecognized / Overlooked; an artist or 'väggdekor' that has been 'försummat' by history"},
    "institutionnel": {"B1": "Adjective", "n": "Institutional; relating to the 'organisational' framework of 'fornminnesvård'"},
    "fait": {"A1": "Noun (Masculine) / Verb", "n": "Fact / Made; a documented 'fait' in a 'besiktigade' or an object 'fait à la main'"},
    "considérations": {"B1": "Noun (Plural)", "n": "Considerations; the theoretical 'considérations' guiding a 'restaureringsanvisningar'"},
    "cher": {"A1": "Adjective", "n": "Dear / Expensive; a 'påkostat' project or a 'cher' (beloved) 'fädernesland'"},
    "architecturales": {"B1": "Adjective (Plural)", "n": "Architectural; relating to the 'huvudlinjer' and 'formale' elements of 'architettura'"},
    "Baigneuses": {"B2": "Proper Noun (Plural)", "n": "The Bathers; a common 'figurscenerna' motif in 'monumentalkunst' (e.g., Cézanne or Renoir)"},
    "Autonomie": {"C1": "Noun (Feminine)", "n": "Autonomy; the 'självständighet' of art from 'liturgik' or 'dynastipolitik'"},
    "Ateliers": {"B1": "Noun (Plural)", "n": "Workshops / Studios; the 'Ateliers' where 'restaureringsbottegor' and 'hantverkare' operate"},
    "l'intégration": {"B2": "Noun (Feminine)", "n": "Integration; the 'l'intégration' of 'nouveaux' elements into a 'historisk' 'miljö'"},
    "siecle": {"A2": "Noun (Masculine)", "n": "Century; (Standard: siècle). Refers to a specific 'Zeitalter' or 'Fin-de-siècle'"},
    "raissoné": {"B2": "Adjective (Misspelling)", "n": "Reasoned; typo for 'raisonné', as in 'Catalogue raisonné' (a critical 'Catalogen')"},
    "dès": {"A2": "Preposition", "n": "From / As early as; used to date the 'emergences' of a style or 'Eingriffe'"},
    "d'imprégnant": {"C1": "Noun (Masculine)", "n": "Impregnant / Consolidant; a chemical 'impregneringsmedel' used to restore stone 'Festigkeit'"},
    "asiatiques": {"B1": "Adjective (Plural)", "n": "Asian; used in 'Etnografi' or 'forskning' regarding Silk Road influences on 'väggdekor'"},
    "architectes": {"A2": "Noun (Plural)", "n": "Architects; the 'byggnadskonstnären' responsible for 'edifices' and 'restaurering'"},
    "St-Thomas": {"B1": "Proper Noun", "n": "St. Thomas; a common church dedication or a reference to 'Thomas-studier' (Thomism)"},
    "Primitifs": {"B2": "Proper Noun (Plural)", "n": "Primitives; referring to early painters (e.g., 'Primitifs Flamands') central to 'Gemäldekunde'"},
    "C´est-à-dire": {"B1": "Phrase", "n": "That is to say; used for clarification in 'Historieteoretiska' debates"},
    "Célèbre": {"A2": "Adjective", "n": "Famous; describing a 'namnkunnigaste' artist or a 'monumentalverk'"},
    "Cène": {"B1": "Proper Noun (Feminine)", "n": "The Last Supper; a frequent 'kalkmålningsmotiv' depicting 'nattvarden'"},
    "conflits": {"B2": "Noun (Plural)", "n": "Conflicts; the 'conflits' between modern 'bruksproblem' and historical 'identità'"},
    "Collège": {"B1": "Noun (Masculine)", "n": "College / Board; a scholarly 'Gemenscap' or an educational 'fackskolan'"},
    "Charte": {"B2": "Noun (Feminine)", "n": "Charter; such as the 'Charte de Venise' (Venice Charter) governing 'fornminnesvård'"},
    "Certaines": {"A2": "Adjective / Pronoun (Feminine Plural)", "n": "Certain; used in 'besiktigade' to specify 'certaines' (certain) sections of a wall"},
    "Cercle": {"B1": "Noun (Masculine)", "n": "Circle; referring to an artist's 'Cercle' (circle/school) or a scholarly 'forening'"},
    "Cahier": {"B2": "Noun (Masculine)", "n": "Notebook / Journal; an archival 'Cahier' containing 'Forskningsexerpter' and 'excerpter'"},
    "C'est": {"A1": "Phrase", "n": "It is; a foundational identifier in 'descrizione' and 'istruzione' texts"},
    "Bref": {"B1": "Adjective / Adverb", "n": "Brief / In short; used to summarize a technical 'Exposé'"},
    "Bois": {"A2": "Noun (Masculine)", "n": "Wood; the material for 'polychrome' sculpture or 'skulpturen' frames"},
    "sommaire": {"A2": "Noun (Masculine) / Adjective", "n": "Sommaire ; le 'registre' ou la table des matières d'un 'dossier' ou d'une 'utredning'."},
    "l'Ecole": {"A1": "Noun (Feminine)", "n": "L'École ; comme l'École des Beaux-Arts, centrale pour l'enseignement de l'architettura'."},
    "l'emploi": {"B1": "Noun (Masculine)", "n": "L'emploi ; l'usage ou l'application d'une technique de 'konserveringmetoder'."},
    "l'internationalisation": {"B2": "Noun (Feminine)", "n": "L'internationalisation ; le processus d'échange global comme l'Erfarenhetsutbytet'."},
    "haute": {"A2": "Adjective (Feminine)", "n": "Haute ; par exemple 'Haute Époque', désignant une période ancienne du 'médievalisme'."},
    "exectuées": {"B1": "Verb (Past Participle - Misspelling)", "n": "Exécutées ; orthographe erronée pour 'exécutées', concernant des mesures 'verkställdes'."},
    "connaissances": {"B1": "Noun (Plural)", "n": "Connaissances ; l'ensemble des 'Erkenntnisse' acquises par la 'forskning'."},
    "Saint-Luc": {"B2": "Proper Noun", "n": "Saint-Luc ; patron des peintres, souvent associé aux 'Gilde' (guildes) d'artistes."},
    "Fin-de": {"B2": "Prepositional Phrase", "n": "Fin-de ; généralement utilisé dans 'Fin-de-siècle' pour décrire le 'Zeitalter' 1900."},
    "Dérestauration": {"C1": "Noun (Feminine)", "n": "Dérestauration ; action de retirer des ajouts modernes pour retrouver l'état 'echten'."},
    "Déco": {"A2": "Noun / Adjective", "n": "Déco ; abréviation de 'Décoratif' ou 'Art Déco', un style de 'väggdekor' du XXe siècle."},
    "Découvrir": {"A2": "Verb", "n": "Découvrir ; l'acte de mettre au jour des 'fresko' cachées sous un badigeon."},
    "Discours": {"B2": "Noun (Masculine)", "n": "Discours ; le 'Diskursens' théorique ou une présentation lors d'un 'expertsymposier'."},
    "Dictionnaire": {"A2": "Noun (Masculine)", "n": "Dictionnaire ; un ouvrage de référence tel qu'un 'Handbuch' pour la 'Gemäldekunde'."},
    "romand": {"B2": "Adjective", "n": "Romand; referring to the French-speaking part of Switzerland, often cited in 'Schweizerstil' research"},
    "d'Auxerrois": {"C1": "Proper Noun", "n": "Of Auxerrois; specifically Saint-Germain l'Auxerrois, a major site for Gothic 'architettura' and murals"},
    "des-Prés": {"B1": "Proper Noun", "n": "Of the Fields; as in Saint-Germain-des-Prés, one of the oldest churches in Paris with significant 'väggdekor'"},
    "Sainte": {"A2": "Adjective (Feminine)", "n": "Holy / Saint; as in 'Sainte-Chapelle', famous for its 'glas-målningar' and Gothic 'Gestaltung'"},
    "Galerie": {"A2": "Noun (Feminine)", "n": "Gallery; an elongated 'hals' or 'ateljéerna' space for displaying 'konstverk'"},
    "Frontiéres": {"B2": "Noun (Plural)", "n": "Borders / Frontiers; often used in 'gränsöverskridare' contexts or 'nationalstil' mapping"},
    "Fin-de siecle": {"B2": "Noun / Adjective", "n": "End of the century; the 'Zeitalter' around 1900 characterized by 'decadence' and 'nationalstil' transitions"},
    "Expériences": {"B1": "Noun (Plural)", "n": "Experiments / Experiences; equivalent to 'Erfarenhetsutbytet' in scientific 'scienza' and 'konserveringmetoder'"},
    "Exposé": {"B2": "Noun (Masculine)", "n": "Presentation / Brief; a formal 'utredning' or 'Föredragskoncept' describing a project's state"},
    "Etats": {"B1": "Noun (Plural)", "n": "States / Conditions; used to describe the 'Etats de conservation' (states of conservation) of a monument"},
    "Esprit": {"B2": "Noun (Masculine)", "n": "Spirit / Mind; the 'Zeitgeist' or the 'Esprit de corps' of a scholarly 'Forening'"},
    "Entretiens": {"B2": "Noun (Plural)", "n": "Conversations / Interviews; a collection of 'Gästföreläsningar' or scholarly dialogues"},
    "Entendons-nous": {"B1": "Phrase", "n": "Let us understand each other; a rhetorical device used in 'Historieteoretiska' debates to clarify 'Grundbegriffe'"},
    "Encyclopédie": {"B1": "Noun (Feminine)", "n": "Encyclopedia; the Enlightenment 'Gesamtausgabe' of knowledge (e.g., Diderot & d'Alembert)"},
    "résulter": {"B2": "Verb (Infinitive)", "n": "To result / To follow; used in technical reports to describe the condition 'résulter' (resulting) from damp or 'Instandsetzungen'"},
    "Groupe": {"A1": "Noun (Masculine)", "n": "Group; referring to an artistic collective such as the 'Tierpgruppen' or a 'Groupe de travail' (working group)"},
    "pouvant": {"B1": "Verb (Present Participle)", "n": "Being able to / Capable of; used to describe materials 'pouvant' (able to) resist certain climatic conditions"},
    "plastique": {"B2": "Adjective / Noun", "n": "Plastic / Visual; refers to the 'arts plastiques' (visual arts) or the 'qualité plastique' (form and volume) of a sculpture"},
    "folie": {"C1": "Noun (Feminine)", "n": "Folly; in architecture, a costly, ornamental building with no practical purpose, often found in 18th-century 'manors' or parks"},
    "Hommage": {"B1": "Noun (Masculine)", "n": "Homage / Tribute; a work or 'Hyllningsskriften' created to honor a master like 'Ioh.' Rhezelius"},
    "Haut": {"A2": "Adjective / Noun", "n": "High / Upper; refers to 'Haut-relief' (high relief) or the 'Haut Moyen Âge' (Early Middle Ages)"},
    "savoir": {"A1": "Verb / Noun", "n": "To know / Knowledge; refers to both the act of knowing and the body of 'knowledges' held by experts"},
    "psychologique": {"B1": "Adjective", "n": "Psychological; relating to the mental or emotional state, often used regarding the 'psychologique' impact of heritage destruction"},
    "présentement": {"B2": "Adverb", "n": "Currently / At present; used in reports to describe the 'présentement' condition of a monument"},
    "méthodes": {"A2": "Noun (Plural)", "n": "Methods; the systematic 'techniques' used for 'l'examen' or 'restauro' of an object"},
    "interdit": {"B1": "Adjective / Noun", "n": "Forbidden / Prohibited; used in legal contexts regarding 'interdit' interventions on protected sites"},
    "intellectuels": {"B1": "Noun / Adjective (Plural)", "n": "Intellectuals; refers to the scholarly community involved in defining 'ismer' and 'Kulturvärlden'"},
    "droit": {"A2": "Noun (Masculine)", "n": "Law / Right; refers to 'le droit' (the law) governing heritage or the 'droit' (right) of public access"},
    "confirmer": {"A2": "Verb", "n": "To confirm; to validate a hypothesis during 'l'examen' or to ratify a treaty"},
    "attirée": {"B1": "Adjective (Feminine)", "n": "Attracted; often used to describe how public attention is 'attirée' to a specific 'chef-d'œuvre'"},
    "Publique": {"A1": "Adjective (Feminine)", "n": "Public; as in 'l'administration publique' or 'la collection publique'"},
    "Psyché": {"C1": "Proper Noun / Noun", "n": "Psyche; can refer to the Greek myth (often a 'kalkmålningsmotiv') or a full-length tilting mirror"},
    "Intégration": {"B2": "Noun", "n": "Integration; the 'intégration' of modern elements into an 'ancienne' structure or the social integration of heritage"},
    "Internationaux": {"B1": "Adjective (Masculine Plural)", "n": "International; referring to 'accords internationaux' (international agreements) like the Venice Charter"},
    "savons": {"A1": "Verb / Noun", "n": "We know (from 'savoir') / Soaps; in conservation, refers to specialized cleaning agents or the collective 'we know' of a scholarly group"},
    "parfois": {"A2": "Adverb", "n": "Sometimes; used to qualify observations in condition reports or stylistic analyses"},
    "pas": {"A1": "Adverb / Noun", "n": "Not / Step; the primary negation marker or a physical 'step' in a staircase or process"},
    "occupent": {"B1": "Verb (Plural)", "n": "Occupy; used to describe how certain features 'occupy' a space or how scholars 'occupy' themselves with a topic"},
    "inspecteur": {"B2": "Noun (Masculine)", "n": "Inspector; a high-ranking official (e.g., 'Inspecteur des Monuments Historiques') responsible for heritage oversight"},
    "ancienne": {"A1": "Adjective (Feminine)", "n": "Ancient / Old / Former; refers to the 'ancienne église' (former church) or 'l'antiquité' (ancient times)"},
    "L'Archeologie": {"B1": "Proper Noun", "n": "Archaeology; the study of human history through material remains. (Note: Often appears without the accent 'é' in older typesets)"},
    "L'Artisan": {"B1": "Noun / Title", "n": "The Artisan; refers to the craftsman/maker, often used as a title for journals or in debates on craft vs. industry"},
    "L'Esprit": {"B2": "Noun", "n": "The Spirit / The Mind; often refers to 'L'Esprit Nouveau' (the influential journal by Le Corbusier) or the 'spirit' of a place"},
    "L'OEuvre": {"B1": "Noun / Title", "n": "The Work; referring to the 'total work' of an artist or a specific monument (OE ligature is common in French printing)"},
    "L'Opium": {"C1": "Noun / Title", "n": "Opium; in a cultural context, often a reference to Jean Cocteau’s writings or Marx's 'opium of the people'"},
    "L'archéologie": {"B1": "Noun", "n": "Archaeology; (Modern accented version)"},
    "L'attention": {"B1": "Noun", "n": "Attention; the focus required for 'l'examen' of a delicate fresco or structural crack"},
    "L'effet": {"B1": "Noun", "n": "The effect; the visual impact of lighting or the 'effet' of a chemical treatment on stone"},
    "L'examen": {"B1": "Noun", "n": "The examination; the preliminary diagnostic phase of a conservation project"},
    "L'image": {"A1": "Noun", "n": "The image; can refer to a photograph, a religious icon, or the mental 'image' of a restored building"},
    "L'été": {"A1": "Noun", "n": "The summer; the primary season for 'l'examen' and outdoor masonry work due to the dry climate"},

    "remarquables": {"B1": "Adjective (Plural)", "n": "Remarkable / Notable; used to highlight specific architectural features or artworks in a survey or 'monographie'"},
    "sacristie": {"B1": "Noun (Feminine)", "n": "Sacristy; a room in a church where a priest prepares for a service and where vestments and other articles of worship are kept"},
    "s'ils": {"A2": "Contraction", "n": "If they; a contraction of 'si' and 'ils', used to introduce conditions in historical or theoretical arguments"},
    "l'honneur": {"B1": "Noun (Masculine)", "n": "The honor; often used in formal prefaces or when discussing the 'honor' of a nation or a specific artist"},
    "avons-nous": {"A2": "Verb Phrase", "n": "Have we; the inverted form of 'nous avons', common in rhetorical questions within 19th-century academic prose"},
    "beaux-arts": {"B1": "Noun (Plural)", "n": "Fine arts; the academic study and practice of aesthetics, often referring to the 'Académie des Beaux-Arts'"},
    "ces": {"A1": "Determiner (Plural)", "n": "These / Those; used to specify certain objects or 'théories' previously mentioned"},
    "andre": {"A1": "Proper Noun (Misspelling)", "n": "André; a common name (often André Malraux in later contexts), frequently appearing without the accent in OCR-processed text"},
    "théories": {"B1": "Noun (Feminine Plural)", "n": "Theories; the abstract principles or philosophies governing a field like 'l'architecture' or 'la restauration'"},
    "mais": {"A1": "Conjunction", "n": "But; used to introduce a contrast or qualification in a scholarly debate"},
    "Mademoiselle": {"A1": "Noun (Feminine)", "n": "Miss; a title for an unmarried woman, often found in donor lists or when referring to a specific researcher or artist"},
    "rubriques": {"B1": "Noun (Feminine Plural)", "n": "Headings / Sections; specific categories within an inventory, archive, or scholarly journal (e.g., 'archaeological heading')"},
    "pathologie": {"B2": "Noun (Feminine)", "n": "Pathology; the study of decay and structural disorders in building materials and artworks"},
    "littérature": {"A2": "Noun (Feminine)", "n": "Literature; in this context, often refers to the 'grey literature' or bibliography related to a specific monument"},
    "d'architecture": {"A2": "Noun Phrase", "n": "Of architecture; a qualifying phrase common in titles (e.g., 'Revue d'architecture')"},
    "chretienne": {"A2": "Adjective (Feminine)", "n": "Christian; relating to religious buildings or iconography (e.g., 'archéologie chrétienne'). Often appears without an accent in historical OCR"},
    "appeler": {"A1": "Verb", "n": "To call / To name; used to identify a specific technique or refer to an artist by a certain name"},
    "Les Nabis": {"C1": "Proper Noun (Plural)", "n": "The Nabis; a group of Post-Impressionist French artists (late 19th c.) who influenced monumental and decorative painting"},
    "N'en": {"B1": "Pronoun Construction", "n": "Not of it / Not any; a negative contraction used to restrict or deny a subject in scholarly prose"},
    "même": {"A1": "Adjective / Adverb", "n": "Same / Even; used to denote similarity or to emphasize a specific architectural detail"},
    "mélanges": {"C1": "Noun (Masculine Plural)", "n": "Miscellany / Festschrift; a collection of essays honoring a scholar, or a mix of restoration materials (like mortar)"},
    "mouvement": {"B1": "Noun (Masculine)", "n": "Movement; refers to an artistic school or the physical shifting/settling of a building's structure"},
    "monographie": {"B2": "Noun (Feminine)", "n": "Monograph; a comprehensive and detailed study of a single subject, such as a specific church or castle"},
    "étaient": {"A2": "Verb (Imperfect)", "n": "Were; the third-person plural imperfect of 'être'. Used in historical descriptions to establish past conditions"},
    "religieuse": {"A2": "Adjective (Feminine)", "n": "Religious; refers to art, architecture, or life pertaining to the church (e.g., 'architecture religieuse')"},
    "l'oevre": {"B2": "Noun (Masculine - Misspelling)", "n": "The work; a common typographical error for 'l'œuvre'. Refers to a specific artistic or literary creation"},
    "intréssant": {"A2": "Adjective (Misspelling)", "n": "Interesting; an archaic or misspelled variant of 'intéressant' (extra accent on the first 'e')"},
    "général": {"A2": "Adjective / Noun", "n": "General; used in broad surveys ('un aperçu général') or administrative titles"},
    "décorent": {"B1": "Verb (Present)", "n": "Decorate; refers to how specific ornaments or murals 'décorent' a wall or structure"},
    "critiques": {"B2": "Noun (Plural) / Adjective", "n": "Critiques / Critical; refers to analytical reviews or the 'critical' state of a monument's decay"},
    "cette": {"A1": "Determiner (Feminine)", "n": "This; used to specify a particular object (e.g., 'cette église')"},
    "Préface": {"B1": "Noun (Feminine)", "n": "Preface; the introductory section of a book, often written by the author to explain their intent"},
    "Prophètes": {"B1": "Noun (Masculine Plural)", "n": "Prophets; common iconographic subjects in church murals (the 'Profeternas' mentioned in your Swedish list)"},
    "Prix": {"A2": "Noun (Masculine)", "n": "Price / Prize; can refer to the cost of materials or an award (e.g., 'Prix de Rome')"},
    "Poésie": {"B1": "Noun (Feminine)", "n": "Poetry; in art history, often used metaphorically to describe the 'soul' or aesthetic power of a ruin"},
    "Pourquoi": {"A1": "Adverb / Conjunction", "n": "Why; used in investigative or polemical titles (e.g., 'Pourquoi restaurer?')"},
    "planches": {"B1": "Noun (Feminine Plural)", "n": "Plates; the individual printed illustrations or engravings in a 'Recueil' or 'planschverk'"},
    "physiologie": {"C1": "Noun (Feminine)", "n": "Physiology; 19th-century usage often applied to the 'nature' or 'functioning' of a city or social class"},
    "philosophie": {"B1": "Noun (Feminine)", "n": "Philosophy; the underlying theory behind a method of restoration (e.g., 'philosophie de la restauration')"},
    "Petits": {"A1": "Adjective (Masculine Plural)", "n": "Small / Little; often used in series titles (e.g., 'Petits guides')"},
    "Novelles": {"C1": "Noun (Feminine Plural - Archaic)", "n": "Novellas / New laws; an older spelling of 'Nouvelles' or a reference to Roman 'Novellae' (new laws)"},
    "Nouvelles": {"A2": "Noun (Feminine Plural) / Adjective", "n": "News / New; used in titles of recent journals or accounts (e.g., 'Nouvelles annales')"},
    "Notices": {"B1": "Noun (Feminine Plural)", "n": "Notices / Brief accounts; short descriptive entries in a catalog or bibliographic list"},
    "pratiques": {"B1": "Noun (Plural) / Adjective", "n": "Practices; the actual application or use of a profession (e.g., 'arts pratiques' - practical arts)"},
    "ornements": {"A2": "Noun (Masculine Plural)", "n": "Ornaments; decorative elements used in architecture and design, often a central theme in 19th-century stylistic surveys"},
    "chez": {"A1": "Preposition", "n": "At/Among; often used in titles to denote a publisher or a specific cultural context (e.g., 'Chez Firmin-Didot')"},
    "Réflexions": {"B1": "Noun (Feminine Plural)", "n": "Reflections; a common title for analytical or philosophical essays (e.g., 'Réflexions sur la peinture')"},
    "Romanesques": {"B1": "Adjective (Plural)", "n": "Romanesque; in an architectural context, it refers to the style preceding Gothic. In a literary context, it means 'romantic' or 'fictional'"},
    "Revué": {"B2": "Verb (Past Participle - Archaic Accent)", "n": "Reviewed / Revised; often found on title pages as 'Revué et augmentée' (Revised and expanded)"},
    "Retour": {"A2": "Noun (Masculine)", "n": "Return; often used in the sense of a 'retour à l'antique' (return to the classical style)"},
    "Restaurer": {"B1": "Verb (Infinitive)", "n": "To restore; the act of repairing or returning an object to a previous state"},
    "Renouveau": {"B2": "Noun (Masculine)", "n": "Renewal / Revival; a resurgence of interest in a particular style or movement"},
    "Reflexions": {"B1": "Noun (Feminine Plural - Variant)", "n": "Reflections; alternative spelling of 'Réflexions,' common in older texts or where diacritics were omitted"},
    "Recueil": {"B2": "Noun (Masculine)", "n": "Collection / Compendium; a curated set of plates, drawings, or essays published together"},
    "Rassembler": {"B1": "Verb (Infinitive)", "n": "To gather / To reassemble; used in conservation for the re-joining of broken fragments"},
    "Quand": {"A1": "Conjunction / Adverb", "n": "When; used to establish a temporal context in historical narratives"},
    "Pénétrer": {"B2": "Verb (Infinitive)", "n": "To penetrate / To permeate; often used in discussions of how light or moisture enters a building or how a style spreads"},
    "rentoiler": {"C1": "Verb (Infinitive)", "n": "To reline; the process of attaching a new supporting canvas to the back of an original, weakened canvas painting using an adhesive (historically glue-paste or wax-resin)"},
    "ans": {"A1": "Noun (Masculine Plural)", "n": "Years; used to denote a span of time (e.g., 'pendant dix ans' - for ten years)"},
    "d'authenticité": {"C1": "Phrase (de + noun)", "n": "Of authenticity; relating to the original, genuine nature of a work of art or historical document"},
    "manière": {"B1": "Noun (Feminine)", "n": "Manner / Style; refers to the specific technique or artistic approach of a creator"},
    "antiquaires": {"B2": "Noun (Plural)", "n": "Antiquarians / Antique dealers; historically, scholars interested in the study of artifacts and monuments"},
    "autres": {"A1": "Adjective / Pronoun (Plural)", "n": "Others / Other"},
    "maniére": {"B1": "Noun (Feminine / Historical Orthography)", "n": "Manner / Style; the specific technique or artistic approach (often spelled with an acute accent 'é' in older French texts where modern French uses the grave 'è')"},
    "Scandinaves": {"A2": "Noun / Adjective (Plural)", "n": "Scandinavians; people or things originating from Scandinavia"},
    "Société": {"A2": "Noun (Feminine)", "n": "Society / Company / Association; often used in the names of historical or scholarly organizations"},
    "manière": {"B1": "Noun (Feminine)", "n": "Manner / Way / Style; (Standard: manière)"},
    "nue": {"B1": "Adjective (Feminine) / Noun", "n": "Naked / Bare / Nude; in architecture, refers to a plain surface (le nu du mur) or a cloud (la nue)"},
    "polychrome": {"B2": "Adjective", "n": "Polychrome; multicolored, specifically referring to the painted decoration of architectural elements or sculptures (Standard: polychrome)"},
    "polychrôme": {"C2": "Adjective (Historical Orthography)", "n": "Polychrome; multicolored. In 19th-century texts like Hittorff's, used to argue that Greek architecture was originally painted in vibrant colors"},
    "sauvegarde": {"B2": "Noun (Feminine)", "n": "Safeguarding / Preservation; the act of protecting cultural heritage or data"},
    "sept": {"A1": "Numeral", "n": "Seven"},
    "Suéde": {"A1": "Proper Noun", "n": "Sweden"}, # archaic or incorrect
    "Suède": {"A1": "Proper Noun", "n": "Sweden"},
    "m'enforcer": {"B2": "Verb (Reflexive - Typo/Archaic)", "n": "To push myself further / To sink in; likely 'm'enfoncer' (to sink/delve) or 'm'efforcer' (to strive)"},
    "meilleure": {"A2": "Adjective (Feminine)", "n": "Better / Best; the feminine form of 'meilleur'"},
    "rationaliste": {"C1": "Adjective / Noun", "n": "Rationalist; relating to the architectural style that emphasizes logic, function, and geometric clarity"},
    "restera": {"A2": "Verb (Future)", "n": "Will remain / Will stay; third-person singular future of 'rester'"},
    "souvent": {"A1": "Adverb", "n": "Often / Frequently"},
    "elle": {"A1": "Pronoun (Feminine)", "n": "She / It (referring to a feminine noun)"},
    "traité": {"B1": "Noun (Masculine)", "n": "Treaty / Treatise; a formal agreement or a written work dealing formally with a subject (e.g., an architectural treatise)"},
    "travaux": {"A2": "Noun (Plural, corrected)", "n": "Works / Labors / Construction"},
    "trop": {"A1": "Adverb", "n": "Too / Too much / Excessively"},
    "vais-je": {"A2": "Verb + Pronoun (Inverted)", "n": "Shall I / Am I going; the inverted form of 'je vais' used for questions"},
    "Ve": {"C1": "Noun (Proper)", "n": "The 5th (abbreviation for 'Cinquième'); often used for the 'Ve République' or the 'Ve Arrondissement' in Paris."},
    "attendre": {"A2": "Verb", "n": "To wait / To expect."},
    "combien": {"A1": "Adverb / Pronoun", "n": "How much / How many."},
    "humaine": {"A2": "Adjective (Feminine)", "n": "Human; relating to mankind or characterized by human emotion/scale."},
    "Vienne": {"B2": "Proper Noun", "n": "Vienna; the French name for the Austrian capital, Wien"},
    "l'imitation": {"B1": "Noun (Feminine)", "n": "The imitation; in art history, the act of copying a style or nature (mimesis)"},
    "aujourd'hui": {"A1": "Adverb", "n": "Today / Nowadays / In the present day"},
    "conservera": {"B2": "Verb (Future)", "n": "Will preserve / Will keep / Will maintain"},
    "notre": {"A1": "Possessive Adjective", "n": "Our"},
    "peintres": {"A2": "Noun (Masculine Plural)", "n": "Painters; artists who apply pigment to a surface"},
    "rapetisse": {"C1": "Verb (Present)", "n": "Shrinks / Minimizes / Makes smaller / Belittles"},
    "sert": {"A2": "Verb (Present)", "n": "Serves / Is used for / Is useful for (from 'servir')"},
    "édifice": {"B1": "Noun (Masculine)", "n": "Buildings / Edifices; typically refers to large, significant, or public structures"},
    "édifices": {"B1": "Noun (Masculine Plural)", "n": "Buildings / Edifices; typically refers to large, significant, or public structures"},
    "époque": {"B1": "Noun (Feminine)", "n": "Era / Period / Age / Epoch"},
    "a-t-il": {"A1": "Phrase", "n": "Has he / Does he have (inverted question)"},
    "actualité": {"B1": "Noun (Feminine)", "n": "Current events / News / Reality"},
    "anciennes": {"A2": "Adjective (Feminine Plural)", "n": "Ancient / Old / Former"},
    "appliquée": {"B2": "Adjective / Participle (Feminine)", "n": "Applied (as in 'art appliqué')"},
    "aquarelle": {"B1": "Noun (Feminine)", "n": "Watercolor"},
    "archéologique": {"B1": "Adjective", "n": "Archaeological"},
    "artiste": {"A1": "Noun", "n": "Artist"},
    "choses": {"A1": "Noun (Feminine Plural)", "n": "Things"},
    "décoratifs": {"B1": "Adjective (Masculine Plural)", "n": "Decorative"},
    "département": {"B1": "Noun (Masculine)", "n": "Department / Administrative region"},
    "françaises": {"A1": "Adjective (Feminine Plural)", "n": "French"},
    "l'architecte": {"A2": "Noun (Masculine/Feminine)", "n": "The architect"},
    "moisissures": {"C1": "Noun (Feminine Plural)", "n": "Molds / Fungi (relevant in conservation)"},
    "mondes": {"B1": "Noun (Masculine Plural)", "n": "Worlds"},
    "moyen": {"A1": "Adjective / Noun", "n": "Middle / Mean / Medium"},
    "peint": {"A2": "Adjective / Participle", "n": "Painted"},
    "peut": {"A1": "Verb (Present)", "n": "Can / May (from 'pouvoir')"},
    "suédois": {"A1": "Adjective / Noun (Masculine)", "n": "Swedish / Swede"},
    "âge": {"A1": "Noun (Masculine)", "n": "Age (often 'Moyen Âge' for Middle Ages)"},
    "arriver": {"B2": "Verb", "n": "To arrive / To occur (Swedish: anlända)."},
    "documentaire": {"B1": "Adjective", "n": "Documentary"},
    "horreurerna": {"C1": "Noun (Definite Plural)", "n": "The horrors"},

    "café": {"A1": "Noun (Masculine)", "n": "Coffee / Café"},
    "capitale": {"A1": "Noun (Feminine)", "n": "Capital city"},
    "caractère": {"B1": "Noun (Masculine)", "n": "Character / Nature"},
    "catholique": {"A2": "Adjective", "n": "Catholic"},
    "cathédrales": {"B1": "Noun (Feminine Plural)", "n": "Cathedrals"},
    "ce": {"A1": "Pronoun/Determiner", "n": "This / That"},
    "choses": {"A1": "Noun (Feminine Plural)", "n": "Things"},
    "classe": {"A1": "Noun (Feminine)", "n": "Class / Category"},
    "comparée": {"B2": "Adjective (Feminine)", "n": "Comparative (e.g., 'littérature comparée')"},
    "complet": {"A2": "Adjective (Masculine)", "n": "Complete"},
    "composé": {"B1": "Adjective / Participle", "n": "Composed / Mixed"},
    "comprends": {"A1": "Verb", "n": "Understand"},
    "conciergerie": {"B2": "Noun (Feminine)", "n": "Conciergerie; historically a prison/palace, now a major monument in Paris"},
    "conditionné": {"B2": "Adjective / Participle", "n": "Conditioned / Packaged"},
    "conservatoire": {"B1": "Noun (Masculine)", "n": "Conservatory / Academy / Preservation institution"},
    "conséquence": {"B1": "Noun (Feminine)", "n": "Consequence"},
    "contre": {"A1": "Preposition", "n": "Against"},
    "couleurs": {"A1": "Noun (Feminine Plural)", "n": "Colors"},
    "creda": {"-": "Etymology", "n": "Relating to 'credo' or belief systems (Archaic/Latinate)"},
    "credita": {"-": "Etymology", "n": "Relating to credit or belief"},
    "crois": {"A1": "Verb", "n": "Believe / Think"},
    "création": {"B1": "Noun (Feminine)", "n": "Creation / Work of art"},
    "curieux": {"B1": "Adjective (Masculine)", "n": "Curious"},
    "d'Agincourt": {"C1": "Phrase", "n": "Of Agincourt (likely Seroux d'Agincourt, pioneer of art history)"},
    "d'Art Mural": {"B2": "Phrase", "n": "Of Mural Art"},
    "d'Aujourd'hui": {"A1": "Phrase", "n": "Of Today (Title or proper noun)"},
    "d'Empédocle": {"C2": "Phrase", "n": "Of Empedocles (Pre-Socratic philosopher)"},
    "d'Europe": {"A2": "Phrase", "n": "Of Europe"},
    "d'Ingres": {"C1": "Phrase", "n": "Of Ingres (referring to the painter Jean-Auguste-Dominique Ingres)"},
    "d'Objects": {"B1": "Phrase", "n": "Of objects (Standard: d'objets)"},
    "d'Yperman": {"C2": "Phrase", "n": "Of Yperman (likely referring to the medieval medical/surgical author Jan Yperman)"},
    "d'art": {"A2": "Phrase", "n": "Of art / Artistic"},
    "d'artistes": {"B1": "Phrase", "n": "Of artists"},
    "d'aujourd'hui": {"A1": "Phrase", "n": "Of today / Modern"},
    "d'un": {"A1": "Phrase", "n": "Of a / From one"},
    "d'études": {"B1": "Phrase", "n": "Of studies / Research-related"},
    "deux": {"A1": "Number", "n": "Two"},
    "deuxième": {"A1": "Ordinal Number", "n": "Second"},
    "dis": {"A1": "Verb", "n": "Say / Speak"},
    "durée": {"B1": "Noun (Feminine)", "n": "Duration / Period of time"},
    "décadence": {"B2": "Noun (Feminine)", "n": "Decadence / Decline"},
    "décor": {"B1": "Noun (Masculine)", "n": "Decor / Scenery / Setting"},
    "décoratif": {"B1": "Adjective (Masculine)", "n": "Decorative"},
    "décoration": {"B1": "Noun (Feminine)", "n": "Decoration"},
    "décorative": {"B1": "Adjective (Feminine)", "n": "Decorative"},
    "démolisseurs": {"B2": "Noun (Masculine Plural)", "n": "Demolishers / Those who tear down buildings"},
    "dévoilement": {"C1": "Noun (Masculine)", "n": "Unveiling / Disclosure (often of a restored work)"},
    "dʹhistoire": {"A2": "Phrase", "n": "Of history"},
    "feu": {"A2": "Noun (Masculine)", "n": "Fire / The late (when preceding a name)"},
    "christianisme": {"B2": "Noun", "n": "Christianity"},
    "culturelle": {"B1": "Adjective", "n": "Cultural"},
    "dessins": {"B2": "Noun (Plural)", "n": "Designs / Patterns / Drawings"},
    "encadrée": {"B1": "Adjective, Participle (Feminine)", "n": "Framed / Supervised; physically set in a frame or contextually managed within a framework"},
    "entre": {"A1": "Preposition", "n": "Between / Among; indicating a position in the middle of two or more points"},
    "hôpital": {"A2": "Noun (Masculine)", "n": "Hospital; an institution for medical treatment, often a significant building type in urban history"},
    "l'eau": {"A1": "Noun (Feminine)", "n": "The water; a primary factor in both the life and the decay of historical materials"},
    "l'espace": {"B1": "Noun (Masculine)", "n": "The space; referring to both physical volume in architecture and the conceptual area of a site"},
    "outils": {"A2": "Noun (Masculine Plural)", "n": "Tools; instruments used to perform a manual task or a professional craft"},
    "guerre": {"B1": "Noun", "n": "War"},
    "effets": {"B1": "Noun", "n": "Effects"},
    "exemple": {"A1": "Noun", "n": "Example (Modern: exempel)"},
    "faire": {"A1": "Verb", "n": "To do / To make"},
    "finde-siecle": {"C1": "Adjective/Noun", "n": "Fin-de-siècle; relating to the end of the 19th century, often characterized by cynicism and artistic refinement"},
    "fresque": {"B1": "Noun (Feminine)", "n": "Fresco; a mural painting technique on wet lime plaster"},
    "fresques": {"B1": "Noun (Plural)", "n": "Frescoes; multiple mural paintings"},
    "guériront": {"B2": "Verb (Future)", "n": "Will heal / Will cure (from the verb 'guérir')"},
    "homme": {"A1": "Noun (Masculine)", "n": "Man / Mankind"},
    "l'Integration": {"B2": "Noun", "n": "The integration; in restoration, the process of making a loss or 'lacuna' whole again"},
    "l'Orangerie": {"B2": "Proper Noun", "n": "The Orangerie; specifically referring to the Musée de l'Orangerie in Paris, famous for Monet's Water Lilies"},
    "mis": {"A2": "Verb (Past Participle)", "n": "Put / Placed (from the verb 'mettre')"},
    "museés": {"A1": "Noun (Plural)", "n": "Museums (Note: Standard modern spelling is 'musées')"},
    "méchaniques": {"B1": "Adjective (Plural)", "n": "Mechanical (Note: Standard modern spelling is 'mécaniques')"},
    "qu'il": {"A1": "Contraction", "n": "That he / That it"},
    "relatifs": {"B1": "Adjective (Plural)", "n": "Relative / Related"},
    "tyrannie": {"B2": "Noun (Feminine)", "n": "Tyranny"},
    "industriels": {"B2": "Adjective", "n": "Industrial (Modern: industriell)"},
    "noveau": {"B2": "Adjective", "n": "New (as in 'Art Nouveau')"},
    "goût": {"B1": "Noun", "n": "Taste"},
    "inachevé": {"B2": "Adjective", "n": "Unfinished / Incomplete"},
    "l'Artisanat": {"B2": "Noun", "n": "Craftsmanship / The crafts"},
    "l'Esprit": {"B2": "Noun", "n": "The Spirit / The Mind"},
    "l'Exposition": {"B1": "Noun", "n": "The Exhibition / The Exposition"},
    "l'Institut": {"B1": "Noun", "n": "The Institute"},
    "l'Unesco": {"B1": "Proper Noun", "n": "UNESCO"},
    "l'architecture": {"A2": "Noun", "n": "The architecture"},
    "l'histoire": {"A1": "Noun", "n": "The history"},
    "l'homme": {"A1": "Noun", "n": "The man / Mankind"},
    "l'iconoclasme": {"C1": "Noun", "n": "Iconoclasm (the destruction of religious icons/images)"},
    "l'institut": {"B1": "Noun", "n": "The institute"},
    "l'èglise": {"A2": "Noun", "n": "The church (Standard: l'église)"},
    "libérant": {"B2": "Participle", "n": "Liberating / Releasing"},
    "libéraux": {"B2": "Adjective / Noun (Plural)", "n": "Liberal (e.g., 'arts libéraux')"},
    "lithographiés": {"C1": "Adjective / Participle (Plural)", "n": "Lithographed; printed using a stone or metal plate"},
    "malades": {"A2": "Noun / Adjective (Plural)", "n": "Sick / Patients"},
    "manuel": {"B1": "Adjective / Noun", "n": "Manual / Handbook"},
    "manuscrit": {"B1": "Noun", "n": "Manuscript"},
    "matière": {"B2": "Noun", "n": "Matter / Material / Substance"},
    "mise": {"B1": "Noun / Participle", "n": "Placing / Putting (e.g., 'mise en scène')"},
    "moi": {"A1": "Pronoun", "n": "Me / I"},
    "mots": {"A1": "Noun (Plural)", "n": "Words"},
    "murale": {"B1": "Adjective / Noun", "n": "Mural / Wall-mounted"},
    "musei-": {"B1": "Prefix", "n": "Museum-related"},
    "musée": {"A1": "Noun", "n": "Museum"},
    "musées": {"A1": "Noun (Plural)", "n": "Museums"},
    "mécaniques": {"B1": "Adjective / Noun (Plural)", "n": "Mechanical"},
    "mémoire": {"B1": "Noun", "n": "Memory"},
    "mêlant": {"B2": "Participle", "n": "Mixing / Blending"},
    "n'est": {"A1": "Contraction", "n": "Is not"},
    "ou": {"A1": "Conjunction", "n": "Or"},
    "probleme": {"A1": "Noun", "n": "Problem (Standard: problème)"},
    "projet": {"A2": "Noun", "n": "Project / Plan"},
    "qu'apparent": {"B2": "Phrase", "n": "Only apparent / Seemingly"},
    "qu'elle": {"A1": "Contraction", "n": "That she / That it (feminine)"},
    "reviendra": {"B1": "Verb (Future)", "n": "Will return / Will come back (e.g., 'la question reviendra' - the question will return)"},
    "intellectuelle": {"B1": "Adjective (Feminine)", "n": "Intellectual; (e.g., 'propriété intellectuelle' - intellectual property; 'démarche intellectuelle' - intellectual approach)."},

    "historique": {"B1": "Adjective (French)", "n": "Historical"},
    "historiques": {"B1": "Adjective", "n": "Historics"},
    "politique": {"B1": "Noun, Adjective", "n": "Policy / Politics / Political; (e.g., 'politique culturelle' - cultural policy)"},
    "lacunes": {"B2": "Noun (Plural)", "n": "Losses / Gaps / Lacunae; missing areas in a painting, fresco, or manuscript"},
    "les": {"A1": "Article, Pronoun (Plural)", "n": "The / Them"},
    "lieux": {"A2": "Noun (Plural)", "n": "Places / Sites / Locations (e.g., 'lieux de mémoire' - sites of memory)"},

    "humaines": {"C1": "Adjective (French)", "n": "Human / Humanities (often appearing in citations like 'sciences humaines')"},
    "humaniste": {"B2": "Noun (French/Archaic)", "n": "Humanist"},

    "Accueil": {"A1": "Noun", 'n': "Reception / Home; the welcoming area or the homepage of a publication"},
    "Africaine": {"B1": "Adjective"},
    "Age": {"A1": "Noun", 'n': "Age; era / period"},
    "Agence": {"B1": "Noun"},
    "Almanach": {"B1": "Noun", 'n': "Almanac; an annual publication containing calendars and thematic data"},
    "Alpes": {"A1": "Proper Noun", 'n': "Alps"},
    "Annales": {"B2": "Noun (Plural)", 'n': "Annals; a common title for academic journals publishing chronological research (e.g., 'Annales du Midi')"},
    "Appliqué": {"B1": "Noun", "B2": "Adjective"},
    "Art sacré": {"C1": "Noun", 'n': 'French: Sacred Art; a specific theological and aesthetic movement regarding modern religious art'},
    "Artistique": {"A2": "Adjective", 'n': "Artistic"},
    "Arts": {"A1": "Noun (Plural)", 'n': "Arts"},
    "Atmosphérique": {"B1": "Adjective"},
    "Beaux-Arts": {"B1": "Noun (Plural)", 'n': "Fine Arts; disciplines such as painting, sculpture, and architecture focused on aesthetics"},
    "Belgique": {"A1": "Proper Noun", 'n': "Belgium"},
    "Berzé": {"B2": "Proper Noun", 'n': "Berzé-la-Ville; a site famous for its high-quality Cluniac Romanesque murals"},
    "Besoins": {"A2": "Noun (plural)"},
    "Biologie": {"B1": "Adjective"},
    "Biosphère": {"B1": "Noun"},
    "Bourgogne": {"B1": "Proper Noun", 'n': "Burgundy; a French region famous for Cluniac and Cistercian Romanesque architecture"},
    "Centre": {"A1": "Noun"},
    "Chemins": {"A2": "Noun"},
    "Chimie": {"B1": "Noun"},
    "Comité": {"B1": "Noun", 'n': "Committee; often the 'Comité des monuments historiques'"},
    "Comitéinternational": {"B1": "Noun"},
    "Commerce": {"A2": "Noun", 'n': "Commerce / Trade; also used in titles of professional or historical journals"},
    "Commissariat": {"B2": "Noun"},
    "Communauté": {"B1": "Noun"},
    "Composent": {"B1": "Verb"},
    "Condensée": {"B1": "Adjective"},
    "Congrès": {"B1": "Noun", 'n': "Congress / Conference; a formal assembly of experts (e.g., the International Congress of the History of Art)"},
    "Dictionnaire raisonné": {"C1": "Noun Phrase", 'n': "Reasoned Dictionary; specifically Viollet-le-Duc's monumental work on French architecture from the 11th to 16th centuries"},
    "Draps": {"B1": "Noun (Plural)", 'n': "Sheets / Cloth / Drapery"},
    "Décoratif": {"B1": "Adjective", 'n': "Decorative"},
    "Décret": {"B1": "Noun"},
    "Ecole": {"A1": "Noun"},
    "Economie": {"B1": "Noun"},
    "Electricite": {"B1": "Noun"},
    "Electricité": {"B1": "Noun"},
    "Electriques": {"B1": "Noun (plural)"},
    "Etudes": {"B1": "Noun (plural)"},
    "Expression": {"B2": "Noun"},
    "Financière": {"B2": "Noun"},
    "Fluides": {"A2": "Noun"},
    "Fonctionnement": {"B2": "Noun"},
    "France": {"A1": "Proper Noun", 'n': "France; a central country in the history of restoration theory (e.g., Viollet-le-Duc)"},
    "Goéland": {"B2": "Noun"},
    "Halles": {"B2": "Noun (Plural)", 'n': "Market halls; central covered markets"},
    "Identification": {"B2": "Noun"},
    "Institute": {"A2": "Noun"},
    "Internationale": {"B1": "Adjective (Feminine)", 'n': "International"},
    "Italie": {"A1": "Proper Noun", 'n': "Italy"},
    "Laboratoire": {"B1": "Noun", 'n': "Laboratory"},
    "Matière": {"B1": "Noun"},
    "Montrealais": {"C1": "Noun"},
    "Montréalais": {"C1": "Noun"},
    "Monuments historiques": {"B1": "Noun Phrase", 'n': "Historical Monuments; the French national designation for protected heritage sites"},
    "Monuments": {"A1": "Noun (Plural)", 'n': "Monuments; structures of historical or aesthetic significance"},
    "Moyen Age": {"A2": "Noun Phrase", 'n': "Middle Ages (Medieval period)"},
    "Moyen Age": {"A2": "Noun Phrase", 'n': "Middle Ages (Medieval period)"},
    "Moyen": {"B1": "Noun / Adjective", 'n': "Middle / Average / Medium; (e.g., 'Moyen Âge' — Middle Ages)"},
    "Mécanique": {"B1": "Noun"},
    "Médithèque": {"B1": "Noun", 'n': "Media library; (Modern: Médiathèque)"},
    "Métiers": {"B1": "Noun (plural)"},
    "Nil": {"A1": "Proper Noun", 'n': "Nile; the central river for Egyptian archaeology"},
    "Notre Dame": {"A1": "Proper Noun", 'n': "Our Lady; common title for cathedrals (e.g., Notre-Dame de Paris)"},
    "Noveau": {"A2": "Adjective", 'n': "New; (Note: correctly spelled 'Nouveau' in standard French)"},
    "Nubie": {"B2": "Proper Noun", 'n': "Nubia; the region in southern Egypt and northern Sudan, famous for its monumental archaeological sites"},
    "Objectifs": {"B1": "Noun"},
    "Occident": {"B2": "Noun", 'n': "The West / The Western world"},
    "Paris": {"A1": "Proper Noun", 'n': "Paris; often referring to the location of major research institutes like the Sorbonne"},
    "Patrimoine": {"B1": "Noun", 'n': "Heritage; cultural or natural inheritance"},
    "Peintures murales": {"B1": "Noun Phrase", 'n': "Mural paintings / Wall paintings"},
    "Renaissance": {"A2": "Noun", 'n': "Renaissance; the cultural 'rebirth' period between the Middle Ages and Modernity"},
    "R´eseau": {"B2": "Noun"},
    "Réseau": {"B2": "Noun"},
    "Réseaux": {"B2": "Noun"},
    "Scientifique": {"B1": "Adjective", 'n': "Scientific"},
    "Soufflé": {"A2": "Noun"},
    "Spatiales": {"B2": "Adjective (plural)"},
    "St": {"A1": "Abbreviation", 'n': "Saint"},
    "Structurale": {"B1": "Noun"},
    "Suisse": {"B1": "Noun"},
    "Système": {"B1": "Noun"},
    "Systèmes": {"B1": "Noun"},
    "Sécurité": {"B2": "Noun"},
    "Tertiaire": {"B1": "Noun, Adjective"},
    "Turquet": {"C1": "Proper Noun", 'n': "Turquet de Mayerne; (Same as Mayerne)"},
    "Télédétection": {"B1": "Adjective"},
    "Viborg": {"N/A": "Proper Noun", 'n': "A city in Denmark / Russia; significant in medieval history"},
    "Ville": {"A1": "Noun", 'n': "City / Town"},
    "Vins": {"A1": "Noun (plural)"},
    "Viollet-le-Duc": {"C1": "Proper Noun", 'n': "Eugène Viollet-le-Duc; the influential 19th-century architect and theorist known for 'stylistic restoration'"},
    "Watervliet": {"N/A": "Proper Noun", 'n': "A town in Belgium/Netherlands; significant for the 'Master of Watervliet'"},
    "actes": {"B2": "Noun (Plural)", 'n': "Proceedings / Acts; the published record of papers and discussions from a scholarly meeting"},
    "alternatives": {"B1": "Noun (plural)"},
    "antique": {"A2": "Adjective", 'n': "Ancient / Antique"},
    "antiquitiés": {"B1": "Noun (Plural - variant)", 'n': "Antiquities; objects or monuments from ancient times (historical spelling variant)"},
    "après": {"A1": "Preposition", 'n': "After; often used to denote the period following a major event, such as 'après-guerre' (post-war)"},
    "archaéologiques": {"B2": "Adjective (Plural - variant)", 'n': "Archaeological; relating to the study of the past (historical spelling variant)"},
    "archéologie": {"A2": "Noun", 'n': "Archaeology; the study of human history through the excavation of sites and the analysis of artifacts"},
    "archéologie": {"B1": "Noun", 'n': "Archaeology"},
    "art sacré": {"C1": "Noun", 'n': 'French: Sacred Art; a specific theological and aesthetic movement regarding modern religious art'},
    "artistique": {"B1": "Adjective", 'n': "Artistic; often used in 19th-century Swedish texts to denote aesthetic quality"},
    "artistiques": {"B1": "Adjective (Plural)", 'n': "Artistic"},
    "atomique international": {'C1': 'Adjective phrase'},
    "atomique": {"B2": "Adjective"} ,
    "attaques": {"B2": "Noun (plural)"},
    "atéliers": {"B1": "Noun (Plural - variant)", 'n': "Workshops / Studios; places of artistic creation or restoration (historical spelling variant)"},
    "au": {"A1": "Contraction", 'n': "To the / In the; masculine singular (à + le)"},
    "aussi": {"A1": "Adverb", 'n': "Also / Too"},
    "authenticité": {"B2": "Noun", 'n': "Authenticity; a core concept in conservation regarding the truthfulness of a monument's material, form, and context"},
    "autour": {"A2": "Preposition", 'n': "Around / Concerning; often used as 'autour de' to describe a debate or theme"},
    "aux": {"A1": "Preposition, Contraction", 'n': "To the / At the (Plural)"},
    "avancé": {"B2": "Adjective"},
    "avec": {"A1": "Preposition", 'n': "With"},
    "beaucoup": {"A1": "Adverb", 'n': "Much / Many / A lot"},
    "bleue": {"A1": "Adjective", 'n': "Blue (Feminine); often referring to the 'manteau bleu' of the Virgin Mary in iconography"},
    "bords": {"A2": "Noun (Plural)", 'n': "Banks / Shores; often used in the context of 'bords du Nil' (banks of the Nile) in travelogues"},
    "carte": {"B2": "Noun"},
    "cathédrale": {"B1": "Noun", 'n': "Cathedral"},
    "ceinture": {"A2": "Noun", 'n': "Belt / Sash; a diagnostic garment detail in statues or portraits"},
    "chapeau": {"A1": "Noun", 'n': "Hat; can signify social status or a specific trade in genre paintings"},
    "chapelles": {"A2": "Noun (Plural)", 'n': "Chapels"},
    "chine": {"B1": "Noun"},
    "choisit": {"B1": "Verb", 'n': "Chooses / Selects; used in describing an artist's choice of composition or palette"},
    "compensation": {"B2": "Noun"},
    "composent": {"B1": "Verb (third-person plural present tense)"},
    "conformité": {"B2": "Noun"},
    "connaissance": {"B1": "Noun", 'n': "Knowledge"},
    "conservation": {"B1": "Noun", 'n': "Conservation"},
    "considéré": {"B1": "Adjective/Participle", 'n': "Considered"},
    "contrôle": {"B1": "Noun"},
    "copies": {"A2": "Noun (Plural)", 'n': "Copies; in conservation, often refers to physical or painted replicas of murals"},
    "couleur": {"A1": "Noun", 'n': "Color"},
    "croisière": {"B2": "Noun"},
    "crêpes": {"B2": "Noun (plural)"},
    "cubisme": {"B1": "Noun", 'n': "Cubism; the early 20th-century avant-garde art movement that revolutionized the perception of form and space"},
    "d'Electricité": {'B1': 'Noun (compound)'},
    "d'eglise": {"A2": "Phrase", 'n': "Of the church / Church-related"},
    "d'histoire": {"A2": "Noun Phrase", 'n': "Of history; as in 'd'histoire de l'art' (of art history)"},
    "d'information": {'B1': 'Noun (compound)'},
    "dans": {"A1": "Preposition", 'n': "In"},
    "de": {"A1": "Preposition", 'n': "Of / From; a fundamental connector for titles and descriptions"},
    "des": {"A1": "Article", 'n': "Of the / Some; plural contraction of 'de + les'"},
    "disposition": {"B2": "Noun", 'n': "Layout / Arrangement; the spatial organization of a building"},
    "droit de la déconnexion": {'B2': 'Noun phrase', 'C1': 'Noun phrase'}, # right to disconnect
    "droit à l'oubli": {'C1': 'Adjective phrase'}, # right to be forgotten
    "du": {"A1": "Contraction", 'n': "Of the (De + le); masculine singular"},
    "début": {"A1": "Noun", 'n': "Beginning / Start; often used to date the start of a style or century"},
    "déploration": {"B2": "Noun", 'n': "Lamentation; a specific iconographic scene depicting the mourning over the dead Christ"},
    "développement": {"B1": "Noun"},
    "d‘oevre": {"B2": "Noun Phrase", 'n': "Work; usually part of 'chef-d’œuvre' (masterpiece) or 'main-d'œuvre' (labor/workforce)"},
    "d’Acoustique": {'B1': 'Noun (compound)'},
    "d’Electricité": {"B2": "Noun (compound)"},
    "d’Etudes": {"B1": "Noun (plural)"},
    "d’art": {"A2": "Noun Phrase", 'n': "Of art; as in 'objets d’art' or 'histoire d’art'"},
    "elle-elle-aime": {"B2": "Phrase"},
    "en": {"A1": "Preposition", 'n': "In / To / Within; often used to denote a field of study or location"},
    "enquête": {"B2": "Noun"},
    "est": {"A1": "Verb", 'n': "Is; 3rd person singular of 'être'"},
    "et": {"A1": "Conjunction", 'n': "And"},
    "européens": {"A2": "Adjective (plural masculine)"},
    "faussé": {"C1": "Verb, Adjective", 'n': 'Distorted / falsified / warped; a diagnostic term used to describe how the true meaning or appearance of a monument has been compromised'},
    "faux": {'A2': 'Adjective', 'n': 'False / Fake'},
    "femme": {"A1": "Noun", 'n': "Woman"},
    "fer": {"A2": "Noun"},
    "français": {"A1": "Adjective, Noun, Demonym"}, # as a Noun (language/people)
    "fédérale": {"B2": "Adjective"}, # feminine form of the adjective "fédéral," which translates to "federal" in English
    "fédéraux": {"B2": "Adjective"},
    "grands-parents": {"A1": "Noun (plural)"}, # "grandparents"
    "hachures": {"C1": "Noun (Plural)", 'n': "Hatching; a retouching technique using fine, parallel lines to integrate a loss without deceiving the eye"},
    "histoire": {"A1": "Noun", 'n': "History; the chronological record of events or the study of the past"},
    "idéa": {"A2": "Noun"},
    "imitateurs": {"B2": "Noun", 'n': "Imitators; those who copy a style without the original mastery, often found in the context of 19th-century 'stylistic' restoration"},
    "inachevé": {"B2": "Adjective", 'n': "Unfinished / Incomplete"},
    "informatiques": {"B2": "Adjective"},
    "international": {"A1": "Adjective", 'n': "International; denoting the cross-border nature of 19th and 20th-century scholarly networks"},
    "inédits": {"B2": "Adjective, Noun (Plural)", 'n': "Unpublished / Inedit; documents or works never previously published"},
    "l'Energie": {'B1': 'Noun'},
    "l'art": {"A1": "Noun", 'n': "The art; as in the object of study or the practice itself"},
    "l'execution": {"B2": "Noun", 'n': "The execution; the technical act of creating the artwork"},
    "l'habitation": {"B1": "Noun", 'n': "The dwelling / Habitation; domestic architecture"},
    "l'église": {"A1": "Noun", 'n': "The church; referring to both the institution and the physical building"},
    "l'énergie": {'B1': 'Noun'},
    "la": {"A1": "Article", 'n': "The; feminine singular"},
    "le droit à l'oubli": {'C1': 'Noun phrase'}, # the right to be forgotten
    "le": {"A1": "Article (masculine singular)", 'n': 'The'},
    "l’Art": {"A1": "Noun", 'n': "The Art; the expression of human creativity"},
    "l’Unesco": {"B1": "Proper Noun", 'n': "UNESCO; the international body for world heritage"},
    "l’art sacré": {"B2": "Noun Phrase", 'n': "Sacred art; specifically refers to religious art intended for liturgical use or spiritual contemplation, a major theme in 20th-century French aesthetics."},
    "l’imitation": {"B1": "Noun", 'n': "The imitation"},
    "manœuvre": {"B2": "Noun"},
    "masse": {"B1": "Noun"},
    "mes": {"A1": "Determiner (Possessive Adjective)"}, # "my" (plural)
    "modernes": {"A2": "Adjective (Plural)", 'n': "Modern"},
    "monde": {"A1": "Noun", 'n': "World"},
    "montage": {"B2": "Noun"},
    "monumental": {"B1": "Adjective", 'n': "Monumental; relating to structures of great size or historical significance"},
    "monuments": {"A2": "Noun (Plural)", 'n': "Monuments; architectural structures of historical or memorial value"},
    "nationale": {"B1": "Noun"},
    "nettoyage": {"B1": "Noun", 'n': "Cleaning"},
    "nord": {"A1": "Noun", 'n': "North; often used in 'le Nord' to refer to Scandinavia or Northern Europe"},
    "nous": {"A1": "Pronoun", 'n': "We / Us"},
    "nouveau": {"A2": "Adjective"},
    "nouvelle": {"A1": "Adjective", 'n': "New"},
    "numérique": {"B1": "Noun"},
    "nécessaire": {'A2': 'Adjective', 'n': 'Necessary'},
    "optronique": {"C1": "Noun"},
    "origines": {"B1": "Noun (Plural)", 'n': "Origins"},
    "par": {"A1": "Preposition", 'n': 'By; indicating the agent of the distortion'},
    "paradoxe": {"B2": "Noun", 'n': "Paradox"},
    "parce": {"A1": "Conjunction", 'n': "Because; used as 'parce que'"},
    "passé": {'A2': 'Noun / Adjective', 'n': 'Past'},
    "patine": {"B2": "Noun", 'n': "Patina; the surface film produced by age and oxidation"},
    "patrimoine": {"B2": "Noun", 'n': "Heritage / Patrimony; the collective property, traditions, and artifacts inherited from the past"},
    "peintes": {"B2": "Adjective (French Plural)", 'n': "Painted; e.g., 'murailles peintes' (painted walls)"},
    "peintre": {"B1": "Noun (French)", 'n': "Painter"},
    "peinture": {"B1": "Noun (French)", 'n': "Painting / Paint"},
    "peintures": {"B1": "Noun (Plural)", 'n': "Paintings; often found in international charters like the Venice Charter or 'peintures murales'"},
    "perturbations": {"B2": "Noun (plural)"},
    "pigmenten": {"B1": "Noun (Swedish Definite Plural)", 'n': "The pigments; the coloring agents in the paint layer"},
    "pionnier": {"B2": "Noun", 'n': "Pioneer"},
    "plus": {'A1': 'Adverb', 'n': 'More'},
    "polychrome": {'C1': 'Adjective', 'n': 'Polychrome; decorated in several colors (common in sculpture/architecture)'},
    "polychromie": {"B2": "Noun", 'n': "Polychromy; the use of multiple colors in decoration, sculpture, or architecture"},
    "polychromy": {"B2": "Noun (Plural)", 'n': "Alternative spellings for polykromi used in international research"},
    "pondre": {"B1": "Verb", 'n': "Hen / To lay (an egg); often used metaphorically in French idioms (poule aux œufs d'or)"},
    "position": {"B1": "Noun", 'n': "Position / Stance"},
    "poule": {"B1": "Noun", 'n': "Hen / To lay (an egg); often used metaphorically in French idioms (poule aux œufs d'or)"},
    "pour": {"A1": "Preposition"},
    "première": {'A1': 'Adjective (Feminine)', 'n': 'First'},
    "principes": {"B1": "Noun (Plural)", 'n': "Principles"},
    "problème": {"B1": "Noun", 'n': "Problem"},
    "probléms": {"B1": "Noun (Plural)", 'n': "Problems"},
    "professionelle": {"B1": "Adjective", 'n': "Professional; relating to a specialized occupation requiring specific training"},
    "propos": {"B1": "Noun", 'n': "Subject / Remark; as in 'à propos' (with regard to)"},
    "publiée": {"B1": "Adjective/Participle", 'n': "Published"},
    "pâles": {"B2": "Adjective", 'n': "Pale / weak / lackluster; used metaphorically to describe poor-quality imitations that lack the 'soul' of the original"},
    "que": {'A1': 'Conjunction', 'n': 'That / Than'},
    "quelques": {"A1": "Determiner", 'n': "Some / A few"},
    "qui": {'A1': 'Pronoun', 'n': 'Who / Which'},
    "quotidienne": {"B1": "Adjective", 'n': "Daily; e.g., 'la vie quotidienne' (daily life)"},
    "qu’apparent": {"B2": "Phrase", 'n': "Only apparent; e.g., a paradox that is 'qu’apparent'"},
    "qu’elle": {"A1": "Contraction", 'n': "That she / That it"},
    "qu’il": {"A1": "Contraction", 'n': "That he / That it"},
    "radioélectriques": {"C1": "Adjective (plural)"},
    "raison": {"B1": "Noun"},
    "rapports": {'B1': 'Noun (Plural)', 'n': 'Reports / Relations / Connections'},
    "recherche": {'B1': 'Noun', 'n': 'Research'},
    "relevé": {"C1": "Noun", 'n': "Survey / Graphic record; a precise drawing or tracing of a mural's condition"},
    "relevés": {"C1": "Noun (Plural)", 'n': "Surveys / Tracings / Records"},
    "religieux": {"B1": "Adjective", 'n': "Religious"},
    "reseaux": {"B1": "Noun"},
    "restaurateurs": {"B2": "Noun (Plural)", 'n': "Restorers; professionals who perform the physical intervention on artworks"},
    "restauration": {"B1": "Noun", 'n': "Restoration; the act of returning an object or building to a known or perceived earlier state"},
    "restaurations": {"B1": "Noun (Plural)", 'n': "Restorations; the acts of returning objects to a previous state"},
    "resumé": {"B1": "Noun", 'n': "Summary; a brief overview of the conservation findings or treatment history"},
    "retouche": {"B2": "Noun", 'n': "Retouch; the localized restoration of a paint layer or surface defect"},
    "revue": {"B1": "Noun", 'n': "Journal / Review; a scholarly periodical"},
    "romantique": {'B1': 'Adjective / Noun', 'n': 'Romantic / Romanticist'},
    "rouge": {"A1": "Adjective", 'n': "Red; frequently associated with martyrs or the passion of Christ"},
    "réalise": {'B1': 'Verb', 'n': 'Realizes / Creates / Executes'},
    "réalisme": {'B1': 'Noun', 'n': 'Realism'},
    "réponse": {"B1": "Noun"},
    "réseaux": {"B1": "Noun (plural)"},
    "résurrections": {"C1": "Noun (Plural)", 'n': "Resurrections; metaphorically used in restoration to describe the 'bringing back to life' of a damaged or covered work of art."},
    "sa": {"A1": "Pronoun", 'n': "His / Her / Its (Feminine singular)"},
    "sacré": {"B1": "Adjective", 'n': "Sacred; relating to the divine or religious (e.g., 'art sacré' - sacred art)"},
    "saint-sulpicien": {'C2': 'Adjective', 'n': 'Saint-Sulpician; a style of 19th-century religious art often criticized as sentimental or mass-produced'},
    "scandinave": {"A2": "Adjective", 'n': "Scandinavian"},
    "sciences": {"A2": "Noun (Plural)", 'n': "Sciences"},
    "scientifique": {"B2": "Adjective", 'n': "Scientific / Scholarly"},
    "scientifiques": {"B2": "Adjective (Plural)", 'n': "Scientific / Scholarly"},
    "sculpture": {"A2": "Noun", 'n': "Sculpture"},
    "se": {'A2': 'Pronoun', 'n': 'Itself / Oneself'},
    "ses": {'A1': 'Determiner (Plural)', 'n': 'His / Her / Its'},
    "siècle": {"A1": "Noun", 'n': "Century; a fundamental unit of time in historical periodization"},
    "siècles": {'A2': 'Noun (Plural)', 'n': 'Centuries'},
    "socialiste": {'B1': 'Adjective / Noun', 'n': 'Socialist'},
    "son": {"A1": "Pronoun", 'n': "His / Her / Its (Masculine singular)"},
    "spatial": {"B2": 'Adjective (masculine form)', 'n': "Spatial; relating to space"},
    "spatiale": {"B2": 'Adjective (feminine form)', 'n': "Spatial; relating to space"},
    "spécial": {"B1": "Adjective"},
    "style": {'A2': 'Noun', 'n': 'Style'},
    "stylistiques": {'B2': 'Adjective (Plural)', 'n': 'Stylistic'},
    "suis": {'A1': 'Verb', 'n': "Am (from 'être' - to be)"},
    "suisses": {"B2": "Adjective (plural)"},
    "suivi": {"B2": "Noun/Participle", 'n': "Follow-up / Monitoring; e.g., the long-term monitoring of a site's climate"},
    "sur": {"A1": "Preposition", 'n': "On / Upon / About"},
    "sécurité": {"B1": "Noun"},
    "tableaux": {"B2": "Noun", 'n': "Tableaux; living pictures or organized visual scenes, common in 19th-century aesthetic theory"},
    "technique": {"B1": "Noun/Adjective", 'n': "Technique / Technical"},
    "technologiques": {"C1": "Adjective", 'n': "Technological; relating to the material science of art production"},
    "temps atomique international": {'C1': 'Noun phrase'}, # International Atomic Time
    "terrassier": {"B2": "Noun", 'n': "Navvy / Groundworker; a laborer involved in excavation or earthworks"},
    "textes": {"A1": "Noun (Plural)", 'n': "Texts; referring to the charters, laws, or manuscripts that define heritage practice"},
    "timides": {"B2": "Adjective", 'n': "Timid / Hesitant stylistic choices"},
    "traitement": {"B1": "Noun"},
    "tridimensionnels": {"B2": "Adjective (Plural)", 'n': "Three-dimensional"},
    "trimestrielle": {"B2": "Adjective", 'n': "Quarterly; published four times a year"},
    "triptyques": {"B1": "Noun (Plural)", 'n': "Triptychs; three-paneled paintings, common as medieval and Renaissance altarpieces"},
    "très": {"A1": "Adverb"},
    "un": {'A1': 'Article / Number', 'n': 'A / One (Masculine)'},
    "une": {"A1": "Article", 'n': "A / One; feminine singular"},
    "valeur": {'B1': 'Noun', 'n': 'Value'},
    "vie": {'A1': 'Noun', 'n': 'Life'},
    "vieilles": {"A2": "Adjective (Plural)", 'n': "Old"},
    "violà": {"A2": "Interjection"},
    "vite": {'A1': 'Adverb', 'n': 'Quickly'},
    "vrai": {'A2': 'Adjective', 'n': 'True'},
    "vélo": {"A1": "Noun (masculine)"}, # "bicycle," "bike"
    "vérité": {"B2": "Noun", 'n': "Truth; in restoration, often used in 'vérité historique' (historical truth)"},
    "À": {"A1": "Preposition"}, # "to," "at"
    "à": {"A1": "Preposition"},
    "âge": {'A1': 'Noun', 'n': 'Age / Era'},
    "école": {"A1": "Noun"},
    "écologique": {"B1": "Adjective", 'n': "Ecological"},
    "économique": {'B1': 'Adjective', 'n': 'Economic'},
    "éditions": {"B1": "Noun (Plural)", 'n': "Editions; refers to specific published versions of a text or a series of prints/reproductions"},
    "éducation": {"A2": "Noun", 'n': "Education; the process of receiving or giving systematic instruction, especially at a professional level"},
    "énergies": {"B1": "Noun (plural)"},
    "époque": {'B1': 'Noun', 'n': 'Epoch / Era / Period'},
    "éternelles": {"B2": "Adjective (Plural)", 'n': "Eternal; in art theory, often used to describe the 'timeless' or 'universal' qualities of a masterpiece."},
    "études": {"A2": "Noun (Plural)", 'n': "Studies; can refer to academic research papers or preliminary sketches made by an artist before the final work"},
    "été": {"A1": "Verb (Past participle)", 'n': "of 'être'; been; used here to establish a historical state"},

}
