#-*- coding: utf-8 -*-
# -*- mode: python; python-indent-offset: 4 -*-
#
# Some useful dict()s
#
# 2024-02-20
#
# G. Q. Maguire Jr.
#
# miss_spelled_to_correct_spelling is a dict where the key is the misspelling,
# and the value is a dict having the following possible keys:
#  'c':  a corrected version of the string  [mandatory]
#  's':  information about the source or sources
#          if multiple sources, they are placed in a list
#          Each source is typically of the form: 'diva2:ddddddd''
#  'n':  a note about this entry
#

miss_spelled_to_correct_spelling={
    'boilier': {'c': 'boiler', 's': 'diva2:724099'},
    'devel-opers': {'c': 'developers', 's': 'diva2:1864417'},
    'brow-ser': {'c': 'brow-ser', 's':'diva2:936265'},
    'Conflict-free': {'c': 'conflict-free'},
    'High-level': {'c': 'high-level'},
    'proof-ofconcept': {'c': 'proof-of-concept'},
    "􏰀 chemical modification􏰀": {'c': "chemical modification"},
    "work enviroment": {'c': "work environment"},
    "working enviroment": {'c': "working environment"},
    'database managment system': {'c': 'database management system'},
    'Edifact': {'c': 'EDIFACT', 'n': 'an acronym'},
    'En- semble LSTM': {'c': 'Ensemble LSTM'},
    'Swedish Institute for  Standards': {'c': 'Swedish Institute for Standards'},
    'Swedish Institute of Standards': {'Swedish Institute for Standards'},
    'machine learning personal- ization': {'c':'machine learning personalization'},
    'masspectrometry': {'c': 'mass spectrometry', 's': 'diva2:1455012', 'n': 'no full text'},
    'wheatstonebridge': {'c': 'Wheatstone bridge'},
    "ooyala iq": {'c': "Ooyala IQ"},
    'temperature profiles': {'c': 'temperature profiles'},
    'textbf{0.765': {'c': '\textbf{0.765}'},
    'textbf{0.867': {'c': '\textbf{0.867}'},
    'textbf{0.940': {'c': '\textbf{0.940}'},
    'genera-tion': {'c': 'generation'},
    'termooxidative': {'c': 'thermooxidative', 's': 'diva2:745531', 'n': 'no full text'},
    'timeresoluted': {'c': 'time resolved', 's': 'diva2:743504', 'n': 'no full text'},
    'proc-esses': {'c': 'processes'},
    'severley': {'c': 'severely', 's': 'diva2:826739'},
    'visuaualization': {'c': 'visualization'},
    'ver-sioned': {'c': 'versioned', 's': 'diva2:751697'},
    'utiliza­tion': {'c': 'utilization', 's': 'diva2:1117705'},
    'variatns': {'c': 'variants', 's': 'diva2:744712'},
    'us-age': {'c': 'usage', 's': 'diva2:724440'},
    'untransribed': {'c': 'untranscribed', 's': 'diva2:1876173'},
    'under­esti­ma­tion': {'c': 'under­estimation', 's': 'diva2:537187'},
    'unchaninging': {'c': 'unchanging', 's': 'diva2:855926', 'n': 'no full text'},
    'treat-ments': {'c': 'treatments', 's': 'diva2:826703'},
    'transdcution': {'c': 'transduction', 's': 'diva2:804978'},
    'transcirption': {'c': 'transcription', 's': 'diva2:853465'},
    'transcirptome': {'c': 'transcriptome', 's': 'diva2:852471'},
    'transcriptiase': {'c': 'transcriptase', 's': 'diva2:853465'},
    'ad-dress': {'c': 'address', 's': 'diva2:1864417'},
    'aduiovisual': {'c': 'audiovisual', 's': 'diva2:744704'},
    'affiboday':{'c': 'affibody', 's': 'diva2:744736'},
    'accomodate': {'c':  'accommodate', 's': 'diva2:1617682'},
    'aminoosy': {'c': 'aminooxy', 's': 'diva2:744733'},
    'ammount': {'c': 'amount', 's': 'diva2:1449212'},
    'arie': {'c': 'are', 's': 'diva2:854019', 'n': 'no full text'},
    'aqueuous': {'c': 'aqueous', 's': 'diva2:853705'},
    'articial': {'c': 'artificial', 's': 'diva2:949994'},
    'asssociated': {'c': 'associated', 's': 'diva2:744727'},
    'atleast': {'c': 'at least', 's': 'diva2:1593450'},
    'autofluorescense': {'c': 'autofluorescence', 's': ['diva2:1788558', 'diva2:1741440']},

    'age-dependant': {'c': 'age-dependent', 's': 'diva2:1568044'},
    'Zonemas-ter': {'c': 'Zonemaster', 's': 'diva2:1322207'},
    'air­craft':{'c': 'aircraft', 's': 'diva2:625004'},
    'al-ready': {'c': 'already', 's': ['diva2:819025', 'diva2:818785']},
    'asynchrounous': {'c': 'asynchronous', 's': 'diva2:1216721'},
    'as-sessment': {'c': 'as-sessment', 's': 'diva2:1331767'},
    'asmospheric': {'c': 'atmospheric', 's': 'diva2:854226', 'n': 'correct in original'},
    'assess­ment': {'c': 'assessment'},
    'assess­ments': {'c': 'assessments'},
    'assess­­ments': {'c': 'assessments'},
    'aza-Michael': {'c': 'Aza-Michael'},
    "a˙ected": {'c': 'affected', 's': 'diva2:1223867'},
    'biogasificaiton': {'c': 'biogasification'},
    'biomecha\xadnical': {'c': 'biomechanical'},
    'bacertial': {'c': 'bacterial'},
    'baisins': {'c': 'basins'},
    'barg': {'c': 'bars', 's': 'diva2:1708926'},
    'beeing': {'c': 'being', 's': ['diva2:862341', 'diva2:739841', 'diva2:1455922']},
    'bioaccumulativ': {'c': 'bioaccumulative'},
    'blo-sourced': {'c': 'bio-sourced', 's': 'diva2:855383'},
    'bomdomg': {'c': 'binding', 's': 'diva2:851740', 'n': 'no full text, in tyhis and other words the typist was off their key positions'},
    'branced': {'c': 'branched', 's': 'diva2:853640'},
    'brest': {'c': 'breast', 's': 'diva2:854686'},
    'brils': {'c':  'nanofibrils', 's': 'diva2:1150933'},
    'buisness': {'c': 'business', 's': 'diva2:935159'},
    'beome': {'c': 'become', 's': 'diva2:854047'},
    'benecial': {'c': 'beneficial', 's': ['diva2:1261155', 'diva2:949994'], 'n': 'missing ligature'},
    'charac\xadteristics': {'c': 'characteristics'},
    'chromotography': {'c': 'chromatography', 's': 'diva2:851740'},
    'com\\xadpared': {'c': 'compared', 's': 'diva2:537187'},
    'com\\xadparisons': {'c': 'comparisons', 's': 'diva2:1452049'},
    'con-nect': {'c': 'connect', 's': 'diva2:628440'},
    'con-tinue': {'c': 'continue', 's': 'diva2:724440'},
    'con-tribution': {'c': 'contribution', 's': 'diva2:1802066'},
    'concentraions': {'c': 'concentrations', 's': 'diva2:801776'},
    'concentrat': {'c': 'concentrate', 's': 'diva2:1096550'},
    'concetnrations': {'c': 'concentrations', 's': 'diva2:744706'},
    'concisted': {'c':  'consisted', 's': 'diva2:826713'},
    'conclussion': {'c': 'conclusion', 's': 'diva2:1119292'},
    'conclustion': {'c':  'conclusion', 's': 'diva2:893748'},
    'curli': {'c': 'curlior', 's': ' diva2:1597566'},
    'conversio': {'c': 'conversion', 's': 'diva2:1096550'},
    'coould': {'c': 'could', 's': 'diva2:801785', 'n': 'no full text'},
    'coplaxity': {'c': 'complexity', 's': 'diva2:801773', 'n': 'no full text'},
    'copolyerization': {'c': 'copolymerization', 's': 'diva2:730215', 'n': 'no full text'},
    'biofim': {'c': 'biofilm', 's': 'diva2:826642'},
    'biofule': {'c': 'biofule', 's': 'diva2:854656'},
    'bio­mecha­nical': {'c': 'biomechanical', 's': 'diva2:537187'},
    'com-plement': {'c': 'complement', 's': 'diva2:819109'},
    'com-plex': {'c': 'complex', 's': ['diva2:1864417', 'diva2:1802066']},
    'campherquinone': {'c': 'camphorquinone', 's': 'diva2:848249'},
    'celllular': {'c': 'cellular', 's': 'diva2:854845'},
    'ciruit': {'c': 'circuit', 's': 'diva2:1350183'},
    'cloride': {'c': 'chloride', 's': 'diva2:1273275'},
    'com\xadpared': {'c':  'compared', 's': 'diva2:537187'},
    'com\xadparisons': {'c': 'comparisons', 's': 'diva2:1452049'},
    'effciency': {'c': 'efficiency', 's': 'diva2:630125'},
    'emanuate': {'c':  'emanate', 's': 'diva2:1061386'},
    'enzyme-Linked': {'c': 'enzyme-linked', 's': 'diva2:1723025'},
    'epigentic': {'c': 'epigenetic', 's': 'diva2:1738587'},
    'erials': {'c': 'materials', 's': 'diva2:1136064', 'n': 'no full text'},
    'temperatur': {'c': 'temperature', 's': 'diva2:1520020'},
    'eand': {'c': 'and', 's': 'diva2:1520020'},
    'eciency': {'c': 'efficiency', 's': 'diva2:1260679', 'n': 'missing ligrature'},
    'ecient': {'c': 'efficient', 's': 'diva2:1260679', 'n': 'missing ligrature'},
    'ecpecially': {'c': 'especially', 's': 'diva2:854686', 'n': 'no full text'},
    'expecially': {'c': 'especially', 's': 'diva2:854686', 'n': 'no full text'},
    'eect': {'c': 'effect', 's': ['diva2:1344757', 'diva2:1229284'], 'n': 'missing ligature'},
    'eects': {'c': 'effects', 's': 'diva2:765822', 'n': 'missing ligature'},
    'effectives': {'c': 'effectiveness', 's': 'diva2:839241', 'n': 'no full text'},
    'egnineer': {'c': 'engineer', 's': 'diva2:744700', 'n': 'no full text'},
    'eliminiation': {'c': 'elimination', 's': 'diva2:852471', 'n': 'no full text'},
    'employes': {'c':  'employees', 's': 'diva2:932555', 'n': 'no full text'},
    'emuls': {'c': 'emulsifier', 's': 'diva2:1154619', 'n': 'no full text'},
    'en-ergy': {'c': 'energy', 's': 'diva2:1109225'},
    'enantioselectiviy': {'c': 'enantioselectivity', 's': 'diva2:893748', 'n': 'no full text'},
    'enatiomeric': {'c': 'enantiomeric', 's': 'diva2:765778'},
    'enatnioselectivity': {'c': 'enantioselectivity', 's': 'diva2:881652', 'n': 'no full text'},
    'enchancer': {'c': 'enhancer', 's': 'diva2:852471', 'n': 'no full text'},
    'envoirment': {'c': 'environment', 's': 'diva2:1218233', 'n': 'error in the original'},
    'enzymatoc': {'c': 'enzymatic', 's': 'diva2:801905', 'n': 'no full text'},
    'establis': {'c':  'establish', 's': 'diva2:1454477', 'n': 'error in the original'},
    'estalomer': {'c': 'elastomer', 's': 'diva2:1270990', 'n': 'error in original'},
    'esti\xadmates': {'c': 'estimates', 's': 'diva2:537187'},
    'eterogeneity': {'c': 'heterogeneity', 's': 'diva2:744723', 'n': 'no full text'},
    'evauate': {'c': 'evaluate', 's': 'diva2:1044163', 'n': 'no full text'},
    'ewquence': {'c': 'sequence', 's': 'diva2:744733', 'n': 'no full text'},
    'examplem': {'c': 'example', 's': 'diva2:854686', 'n': 'no full text'},
    'exibility': {'c': 'flexibility', 's': 'diva2:1519525', 'n': 'missing ligature'},
    'exifoliated': {'c': 'exfoliated', 's': 'diva2:1150933', 'n': 'no full text'},
    'exluded': {'c': 'excluded', 's': 'diva2:1129274', 'n': 'error in original'},
    'exo- with': {'c': 'polymerase Klenow exo-', 's': 'diva2:744724', 'n': 'no full text'},
    'experimentm': {'c': 'experiment', 's': 'diva2:744699', 'n': 'no full text'},
    'expermental': {'c': 'experimental', 's': 'diva2:801785', 'n': 'no full text'},
    'expresseion': {'c': 'expression', 's': 'diva2:853465', 'n': 'no full text'},
    'eluation': {'c': "elution", 's': 'diva2:1708920', 'n': 'error in original'},
    'de-velop': {'c': 'develop', 's': 'diva2:1802066'},
    'decreaasing': {'c': 'decreasing', 's': 'diva2:848199', 'n': 'no full text'},
    'dected': {'c': 'detected', 's': 'diva2:801916', 'n': 'no full text'},
    'dedictated': {'c': 'dedicated', 's': 'diva2:744716', 'n': 'no full text'},
    'deection': {'c': 'detection', 's': 'diva2:571303'}, 
    'dentitrificans': {'c': 'denitrificans', 's': 'diva2:459254', 'n': 'part of "Comamonas denitrificans" - error in the original'},
    'derstanding': {'c': 'understanding', 's': 'diva2:1242516', 'n': 'no full text'},
    'desinfection': {'c': 'disinfection', 's': 'diva2:952496', 'n': 'error in the original'},
    'destaching': {'c': 'detaching', 's': 'diva2:1571882'},
    'destilled': {'c': 'distilled', 's': 'diva2:744697', 'n': 'no full text'},
    'deve­lo­ping': {'c': 'developing', 's': 'diva2:537187'},
    'diallydimethylammoinium': {'c': 'diallyldimethylammonium', 's': 'diva2:1876747', 'n': 'error in original'},
    'dibenzocycllctyl': {'c': 'dibenzocyclooctyne',  's': 'diva2:744733', 'n': 'no full text'},
    'dichrosim': {'c':'dichroism', 's': 'diva2:1642418', 'n': 'error in original'},
    'dierence': {'c':  'difference', 's': 'diva2:787913', 'n': 'missing ligature, no full text'},
    'dierent': {'c':  'different', 's': 'diva2:787913', 'n': 'missing ligature, no full text'},
'dietser': {'c': 'diester', 's': 'diva2:802058', 'n': 'error in te original'},
    'diffculties': {'c': 'difficulties', 's': 'diva2:1561070', 'n': 'missing ffi ligature'},
    'differerentiation': {'c': 'differentiation', 's': 'diva2:855915', 'n': 'no full text'},
    'detectin': {'c':  'detecting', 's': 'diva2:853465', 'n': 'no full text'},
    'diffirent': {'c': 'different', 's': 'diva2:572719', 'n': 'correct in original'},
    'diffrent': {'c':  'different', 's': ['diva2:1186252', 'diva2:935159']},
    'dif‌f‌icult': {'c': 'difficult', 'n': 'there is a 0x200c hiding between the two fs'},
    'discribes': {'c': 'describes', 's': 'diva2:818853', 'n': 'error in original'},
    'diseasesis': {'c': 'disease', 's': 'diva2:1427280', 'n': 'correct in the original'},
    'distribtuion': {'c': 'distribution', 's': 'diva2:801742', 'n': 'no full text'},
    'doesent': {'c': "doesn't", 's': 'diva2:724099', 'n': 'error in original'},
    'dofferent': {'c': 'different', 's': 'diva2:442833', 'n': 'no full text'},
    'donut-shpaed': {'c': 'donut-shaped', 's': 'diva2:744719', 'n': 'no full text'},
    'dooncuted': {'c': 'conducted', 's': 'diva2:801916', 'n': 'no full text'},
    'dould': {'c': 'could', 's': 'diva2:744700', 'n': 'no full text'},
    'dryes': {'c': 'dries', 's': 'diva2:441389', 'n': 'error in original'},
    'dvelopment': {'c': 'development', 's': 'diva2:852274', 'n': 'no full text'},
    'dvelopments': {'c': 'developments', 's': 'diva2:855825', 'n': 'no full text'},
    "diagonsis'": {'c': "diagnoses'", 's': 'diva2:956243', 'n': 'error in original'},
    'diagonsis': {'c': "diagnoses'", 's': 'diva2:956243', 'n': 'error in original'},
    'diamin': {'c': 'diamine', 's': 'diva2:1357105'},
    'difficultires': {'c': 'difficulties', 's': 'diva2:854019', 'n': 'no full text'},
    'eptide': {'c': 'peptide', 's': 'diva2:1094126', 'n': 'no full text'},
    'elec­trolyte': {'c': 'electrolyte', 's': 'diva2:1117705'},
    'calcultions': {'c': 'calculations', 's': 'diva2:730237', 'n': 'error in original'},
    'calld': {'c': 'called', 's': 'diva2:801911', 'n': 'no full text'},
    'canalysis': {'c': 'analysis', 's': 'diva2:801776', 'n': 'no full text'},
    'cancerl': {'c': 'cancer', 's': 'diva2:801905', 'n': 'no full text'},
    'canidate': {'c': 'candidate', 's': 'diva2:1886090', 'n': 'error in original'},
    'carboxymethylated-periodate': {'c': 'carboxymethylated periodate', 's': 'diva2:1468587'},
    'carboxymethylation-periodate': {'c': 'carboxymethylation periodate', 's': 'diva2:1468587'},
    'carboxymetylated': {'c': 'carboxymethylated', 's': 'diva2:885112', 'n': 'error in original'},
    'ccours': {'c': 'occurs', 's': 'diva2:744722', 'n': 'no full text'},
    'ceaning': {'c': 'cleaning', 's': 'diva2:856313', 'n': 'no full text'},
    'cehmoselective': {'c': 'chemoselective', 's': 'diva2:744733'},
    'cetyltrimetylammonium': {'C': 'cetyltrimethylammonium', 's': 'diva2:418821', 'n': 'error in original'},
    'challengens': {'c': 'challenges', 's': 'diva2:744718', 'n': 'no full text'},
    'challengin': {'c': 'challenging', 's': 'diva2:854845', 'n': 'no full text - note additional error in title'},
    'charaterization': {'c': 'characterization', 's': 'diva2:853705', 'n': 'no full text'},
    'cient': {'c': 'efficient', 's': 'diva2:1240231', 'n': 'no full text'},
    'ciopolymer': {'c': 'copolymer', 's': 'diva2:744738', 'n': 'no full text'},
    'classiffcation': {'c': 'classification', 's': 'diva2:1235942', 'n': 'missing ligature'},
    'clincs': {'c': 'clinics', 's': 'diva2:855926', 'n': 'no full text'},
    'cmpared': {'c': 'compared', 's': 'diva2:854287', 'n': 'no full text'},
    'coee': {'c': 'coffee', 's': 'diva2:787913', 'n': 'no full text, missing ligatures in abstrat'},
    'coeffcient': {'c':  'coefficient', 's': 'diva2:1129274', 'n': 'error in handling the ligrature'},
    'coefficent': {'c':  'coefficient', 's': 'diva2:1326223', 'n': 'error in original'},
    'cofacor': {'c': 'cofactor', 's': 'diva2:845671', 'n': 'correct in original'},
    'cohorts11': {'c': 'cohorts', 's': 'diva2:1454856', 'n': 'the 11 was a superscript citation'},
    'strengths3-11': {'c': 'strengths', 's': 'diva2:1454856', 'n': 'the 3-11 was a superscript citation'},
    'conserning': {'c': 'concerning', 's': 'diva2:826701', 'n': 'error in original'},
    'consitute': {'c': 'constitute', 's': 'diva2:1217588', 'n': 'no full text'},
    'consluding': {'c': 'concluding', 's': 'diva2:854709', 'n': 'no full text'},
    'conslusive': {'c': 'conclusive', 's': 'diva2:882778', 'n': 'no full text'},
    'cont': {'c': 'contained', 's': 'diva2:1147570', 'n': 'no full text'},
    'containly': {'c': 'certain', 's': 'diva2:1384216'},
    'ophilized': {'c': 'lyophilized', 's': 'diva2:1384216'},
    'contect': {'c': 'context', 's': 'diva2:854686', 'n': 'no full text'},
    'contect': {'c': 'context', 's': 'diva2:854226', 'n': 'error in original'},
    'contitions': {'c': 'conditions', 's': 'diva2:744697', 'n': 'no full text'},
    'contr': {'c':  'controlled', 's': 'diva2:1136064', 'n': 'no full text'},
    'contral': {'c': 'control', 's': 'diva2:801776', 'n': 'no full text'},
    'contribiuted': {'c': 'contributed', 's': 'diva2:1763572', 'n': 'error in original'},
    'controll': {'c': 'control', 's': 'diva2:862366', 'n': 'error in original'},
    'con­centrations': {'c': 'concentrations', 's': 'diva2:625004'},
    'cristallization': {'c': 'crystallization', 's': 'diva2:1676935', 'n': 'error in original'},
    'cross-rection': {'c': 'cross-reaction', 's': 'diva2:801742', 'n': 'no full text'},
    'currenly': {'c': 'currently', 's': 'diva2:1412461', 'n': 'error in original'},
    'cytomtery': {'c': 'cytometry', 's': 'diva2:849460', 'n': 'error in original'},
    'cmedia': {'c': 'media', 's': 'diva2:1473146', 'n': 'error in original'},
    'organi': {'c': 'organic', 's': 'diva2:1473146', 'n': 'error in original'},
    'conlussions': {'c': 'conclusions', 's': 'diva2:1119292', 'n': 'correct in original'},
    'columes': {'c': 'columns', 's': 'diva2:855926', 'n': 'no full text'},
    'conditons': {'c': 'conditions', 's': 'diva2:646620', 'n': 'error in original'},
    'conditons': {'c': 'conditions', 's': 'diva2:635950', 'n': 'no full text'},
    'conjuction': {'c':  'conjunction', 's': 'diva2:1519525', 'n': 'error in original'},
    'flouresence': {'c': 'fluorescence', 's': 'diva2:730215', 'n': 'no full text'},
    'flourometer': {'c': 'fluorometer', 's': 'diva2:1617664', 'n': 'error in original'},
    'fluorphores': {'c': 'fluorophores', 's': 'diva2:851832', 'n': 'no full text'},
    'flurophores': {'c': 'fluorophores', 's': 'diva2:849460', 'n': 'error in original'},
    'forouabain': {'c': 'for ouabain', 's': 'diva2:1454420', 'n': 'correct in original'},
    'fossile': {'c': 'fossil', 's': 'diva2:1574756', 'n': 'error in original'},
    'factos': {'c':'factors', 's': 'diva2:856152', 'n': 'no full text'},
    'fiels': {'c': 'fields', 's': 'diva2:1685176', 'n': 'correct in the original'},
    'findins': {'c': 'findings', 's': 'diva2:801905', 'n': 'no full text'},
    'finterest': {'c': 'interest', 's': 'diva2:853705', 'n': 'no full text'},
    'firts': {'c':  'first', 's': 'diva2:801778', 'n': 'no full text'},
    'flakesen': {'c': 'flakes', 's': 'diva2:911592', 'n': 'error in original'},
    'flowwoed': {'c': 'followed', 's': 'diva2:853465', 'n': 'no full text'},
    'flyx': {'c': 'flux', 's': 'diva2:802022', 'n': 'correct in the original'},
    'frequens': {'c': 'frequent', 's': 'diva2:801739', 'n': 'correct in original'},
    'frquencies': {'c': 'frequencies', 's': 'diva2:852274', 'n': 'no full text'},
    'full-lengh': {'c': 'full-length', 's': 'diva2:1886090', 'n': 'error in original'},
    'full-lenth': {'c': 'full-length', 's': 'diva2:744727', 'n': 'no full text'},
    'fullfil': {'c': 'fulfill', 's': 'diva2:1574756', 'n': 'error in original'},
    'funcional': {'c': 'functional', 's': 'diva2:849460', 'n': 'correct in original'},
    'funcionality': {'c': 'functionality', 's': 'diva2:895964', 'n': 'no full text'},
    'functioinally': {'c':'functionally', 's': 'diva2:856188', 'n': 'no full text'},
    'furtherly': {'c': 'further', 's': 'diva2:1115012', 'n': 'error in original'},
    'gasfication': {'c': 'gasification', 's': 'diva2:1472049', 'n': 'correct in original'},
    'genereation': {'c': 'generation', 's': 'diva2:853640', 'n': 'no full text'},
    'glycol-initiatedco-oligomer': {'c':  'glycol-initiated co-oligomer', 's': 'diva2:1441893', 'n': 'correct in original'},
    'greates': {'c':  'greatest', 's': 'diva2:801916', 'n': 'no full text'},
    'grot': {'c':  'grenar och (träd)toppar', 's': 'diva2:1384503', 'n': 'an abbreviation for the Swedish "grenar och (träd)toppar in"'},
    'gsification': {'c':  'gasification', 's': 'diva2:854656', 'n': 'no full text'},
    'gool': {'c':  'goal', 's': 'diva2:1584720', 'n': 'error in original'},
    'heets': {'c': 'P-sheets', 's': 'diva2:1150933', 'n': 'no full text'},
    'hemlcellulose': {'c': 'hemicellulose', 's': 'diva2:855383', 'n': 'no full text'},
    'heterpdimer': {'c': 'heterdimer', 's': 'diva2:744727', 'n': 'no full text'},
    'hfb4jecorina': {'c': 'HFB4 jecorina', 's': 'diva2:744661', 'n': 'likely correction - no full text'},
    'hifh': {'c': 'high', 's': 'diva2:744727', 'n': 'no full text'}, 
    'high-througput': {'c': 'high-throughput', 's': 'diva2:744723', 'n': 'no full text'},
    'high-valuable': {'c': 'highly valuable', 's': 'diva2:1792332', 'n': 'error in original'},
    'highe': {'c': 'highest', 's': 'diva2:1096550', 'n': 'no full text'},
    'hight': {'c': 'high', 's': 'diva2:1787103', 'n': 'no full text'},
    'higy': {'c': 'highly', 's': 'diva2:744700', 'n': 'no full text'},
    'hostine': {'c': 'hostone'}, # 's': 'diva2:744727', 'n': 'error in original'
    'hygenization': {'c': 'hygienization', 's': 'diva2:827343', 'n': 'error in the original'},
    'hygro\xadscopic': {'c': 'hygroscopic', 's': 'diva2:460449'},
    'im-miscible': {'c': 'immiscible', 's': 'diva2:1170230', 'n': 'error in original, it should not have the hyphen'},
    'in-door': {'c': 'indoor', 's': 'diva2:819109'},
    'Sys-tem': {'c': 'Sys-tem', 's': 'diva2:819109'},
    'indi­vi­dual': {'c': 'individual', 's': 'diva2:537187'},
    'inspec­tors': {'c': 'inspectors', 's': 'diva2:537187'},
    'insuf-ficient': {'c': 'insufficient', 's': 'diva2:1451753'},
    'inten­si­ve': {'c': 'intensive', 's': 'diva2:537187'},
    'influecning': {'c': 'influencing', 's': 'diva2:853815', 'n': 'no full text'},
    'ing': {'c': 'compression moulding', 's': 'diva2:1136064', 'n': 'no full text'}, 
    'initiated-Ring': {'c': 'initiated - Ring', 's': 'diva2:1787126', 'n': 'part of " surface initiated-Ring Opening Polymerisation (SI-ROP)"'},
    'ickettii': {'c': 'pickettii', 's': 'diva2:744661', 'n': 'no full text'}, # part of "Ralstonia pickettii T1"
    'iden-tity': {'c': 'identity', 's': 'diva2:820958', 'n': 'hyphenation at the end of a line'},
    'ihibitors': {'c': 'inhibitors', 's': 'diva2:801899', 'n': 'no full text'}, 
    'ifie': {'c': 'emulsifier', 's': 'diva2:1154619', 'n': 'no full text'},
    'illustrtate': {'c': 'illustrate', 's': 'diva2:801894', 'n': 'no full text'},
    'immunogenicty': {'c': 'immunogenicity', 's': 'diva2:1357753', 'n': 'error in original'},
    'implats': {'c': 'implants', 's': 'diva2:1096539', 'n': 'error in original'},
    'importatnt': {'c': 'important', 's': 'diva2:801905', 'n': 'no full text'},
    'importtant': {'c': 'important', 's': 'diva2:773429', 'n': 'error in original'},
    'improtant': {'c': 'important', 's': 'diva2:757429', 'n': 'error in original'},
    'previ-ously': {'c': 'previously', 's': 'diva2:757429', 'n': 'hyphen at end of line'},
    'algo-rithms': {'c': 'algo-rithms', 's': 'diva2:757429', 'n': 'hyphen at end of line'},
    'incative': {'c': 'inactive', 's': 'diva2:1583834', 'n': 'the abstraqct in DiVA does not match the abstract in the thesis'},
    'industial': {'c': 'industrial', 's': 'diva2:826712', 'n': 'error in original'},
    'inevstigate': {'c': 'investigate', 's': 'diva2:849460', 'n': 'correct in original'},
    'inexpression': {'c': 'expression', 's': 'diva2:1455140', 'n': 'correct in original'},
    'infectivty': {'c': 'infectivity', 's': 'diva2:1624600', 'n': 'error in original'},
    'increasin': {'c': 'increasing' , 's': 'diva2:802022', 'n': 'correct in original'},
    'usally': {'c': 'usually', 's': 'diva2:854686', 'n': 'no full text'},
    'hogh': {'c': 'high', 's': 'diva2:801739', 'n': 'correct in the original'},
    'homorepats': {'c': 'homorepeats', 's': 'diva2:1723014', 'n': 'no full text'},
    'hree': {'c': 'Three', 's': 'diva2:853824', 'n': 'no full text'},
    'hylauronic': {'c': 'hyaluronic', 's': 'diva2:1438811'},
    'knockdoen': {'c': 'knockdown', 's': 'diva2:849535', 'n': 'correct in original'},
    'jalf-life': {'c': 'half-life', 's': 'diva2:744738', 'n': 'no full text'},
    'isomerade': {'c': 'isomerized', 's': 'diva2:756805', 'n': 'error in original'},
    'istribution': {'c': 'distribution', 's': 'diva2:934992', 'n': 'correct in original'},
    'irmetabolism': {'c': 'iron metabolism', 's': 'diva2:1094126', 'n': 'no full text'},
    'ironbase': {'c': 'iron base'},
    'ised': {'c': 'used', 's': 'diva2:801776', 'n': 'no full text'},
    'instuments': {'c': 'instruments', 's': 'diva2:1777698', 'n': 'error in original'},
    'intection': {'c': 'infection', 's': 'diva2:1454477', 'n': 'error in original'},
    'faciliate': {'c': 'facilitate', 's': 'diva2:1183490', 'n': 'error in original'},
    'facilites': {'c': 'facilties', 's': 'diva2:827149', 'n': 'error in original'},
    'inter-view': {'c': 'interview', 's': 'diva2:628440', 'n': 'hyphen at end of line'},
    'interst': {'c': 'interest', 's': 'diva2:801903'},
    'intresting': {'c': 'interesting', 's': 'diva2:801903', 'n': 'no full text'},
    'inuential': {'c': 'influential', 's': 'diva2:1519525', 'n': 'missing ligature'},
    'invesetigated': {'c': 'investigated', 's': 'diva2:845671', 'n': 'correct in original'},
    'in­spec­tors': {'c': 'inspectors', 's': 'diva2:537187'},
    'iquest': {'c': 'Iquest', 's': 'diva2:1764820'},
    'nsemiconductor': {'c': 'n-semiconductor', 's': 'diva2:1272696', 'n': 'correct in original'},
    'long\xadduration': {'c': 'long-duration', 's': 'diva2:1617578'},
    'lactide-Polyvinyl': {'c': 'lactide-polyvinyl', 's': 'diva2:720734'},
    'lactide-polyvinyl': {'c': 'lactide-polyvinyl', 's': 'diva2:720734'},
    'lar\xadgest': {'c': 'largest', 's': 'diva2:537187', 'n': 'correct in original'},
    'laballed': {'B2': 'Adjective', 's': 'diva2:1205231'}, # British spelling
    'leachables/extractbales': {'c': 'leachables/extractables', 's': 'diva2:826706', 'n': 'error in original'},
    'leching': {'c': 'leaching', 's': 'diva2:1723002', 'n': 'error in original'},
    'lycosomal': {'c': 'lysosomal', 's': 'diva2:744738', 'n': 'no full text'}, 
    'leache': {'c': 'leaches', 's': 'diva2:945315', 'n': 'correct in original'},
    'leding': {'c': 'leading', 's': 'diva2:852471', 'n': 'no full text'},
    'lenghts': {'c': 'lengths', 's': 'diva2:1777766', 'n': 'error in original'},
    'ligninfrom': {'c': 'lignin from' , 's': 'diva2:1044163', 'n': 'no full text'},
    'limiti': {'c': 'limiting', 's': 'diva2:1096550', 'n': 'no full text'},
    'linces': {'c': 'lines', 's': 'diva2:744703', 'n': 'no full text'},
    'linterplanetary': {'c': 'interplanetary', 's': 'diva2:1147592', 'n': 'The abstract does not match the thesis - it is completely different'},
    'potentia':  {'c': 'potential', 's': 'diva2:1147592', 'n': 'The abstract does not match the thesis - it is completely different'},
    'litterature': {'c': 'literature', 's': 'diva2:730237', 'n': 'error in original'}, 
    'lyophylization': {'c': 'lyophilization', 's': 'diva2:854656', 'n': 'no full text'},
    'lysosomalautophagy': {'c': 'lysosomal autophagy', 's': 'diva2:1586242', 'n': 'no full text'},
    'lupis': {'c': 'lupus', 's': 'diva2:1745402', 'n': 'correct in original, part of , Canis lupus familiaris'},
    'lution': {'c': 'solution', 's': 'diva2:1159711', 'n': 'correct in original'},
    'lutions': {'c': 'solutions', 's': 'diva2:1322863', 'n': 'correct in original, hyphen at end of line'}, 
    'lver': {'c': 'over', 's': 'diva2:744700', 'n': 'no full text'},
    'pG': {'c': 'pH', 's': 'diva2:744700', 'n': 'no full text'},
    'ltering': {'c': 'filtering', 's': 'diva2:1344757', 'n': 'missing ligature'},
    'logies': {'B2': 'technologies', 's': 'diva2:1159711', 'n': 'correct in original'},
    'lso': {'c': 'also', 's': 'diva2:1150933', 'n': 'no full text'},
    'loacted': {'c': 'located', 's': 'diva2:801911', 'n': 'no full text'},
    'lo': {'c': 'to', 's': 'diva2:1529843', 'n': 'error in original - the text does not make sense - "lo lead a healthy lifestyle" - I think should be "to participate in living a healthy lifestyle." to match the Swedish'},
    'ln\U0010123a\U00100732': {'c': '****UNKNOWN*** equation', 's': 'diva2:778828', 'n': 'no full text - part of some equation'},
    'lnker': {'c': 'linker', 's': 'diva2:744725', 'n': 'no full text'},
    'lled': {'c': 'filled', 's': 'diva2:1325213', 'n': 'missing ligature'},
    'mainte­nance': {'c': 'maintenance', 's': 'diva2:625004', 'n': 'hyphen at end of line in original'},
    'mehtod': {'c': 'method', 's': 'diva2:855825', 'n': 'no full text'},
    'millipn': {'c': 'millipn', 's': 'diva2:853705', 'n': 'no full text'},
    'pf': {'c': 'of', 's': 'diva2:853705', 'n': 'no full text'},
    'mnolecules': {'c': 'molecules', 's': 'diva2:801712', 'n': 'no full text'},
    'measurment': {'c': 'measurement', 's': 'diva2:952512', 'n': 'error in original'},
    'measurments': {'c': 'measurements', 's': ['diva2:848199', 'diva2:1679874'], 'n': 'no full text'},
    'mesophil': {'c': 'mesophilic', 's': 'diva2:459300', 'n': 'correct in original'},
    'mealloprotease': {'c': 'metalloprotease', 's': 'diva2:744736', 'n': 'no full text'},
    'metalo-proteinase': {'c': 'metalloproteinase', 's': 'diva2:744700', 'n': 'no full text'},
    'macroinititors': {'c': 'macroinitiators', 's': 'diva2:730215', 'n': 'no full text'},
    'metrices': {'c': 'metrics', 's': 'diva2:1591713', 'n': 'error in original'},
    'microaglia': {'c': 'microglia', 's': 'diva2:854845', 'n': 'no full text'},
    'mglmL': {'c': 'mg/mL', 's': 'diva2:1223497', 'n': 'correct in original'},
    'move\xadments': {'c': 'movements', 's': 'diva2:537187'},
    'muscel': {'c': 'muscle', 's': 'diva2:1119292', 'n': 'error in original'},
    'myeline': {'c': 'myelin', 's': 'diva2:1779762', 'n': 'error in original'},
    'machine-learning-asa-service': {'c':   'machine-learning-as-a-service', 's': 'diva2:1303137', 'n': 'hyphen at end of line in original'},
    'measure\xadments': {'c':  'measurements', 's': 'diva2:537187'},
    'mo-ment': {'c': 'moment', 's': 'diva2:1468986', 'n': 'correct in original'},
    'mainteance': {'c': 'maintenance', 's': 'diva2:1765032', 'n': 'correct in original'},
    'manageble': {'c': 'manageable', 's': 'diva2:1726251', 'n': 'error in original'},
    'managmenet': {'c': 'management', 's': 'diva2:851710', 'n': 'no full text'},
    'manuelly': {'c': 'manually', 's': 'diva2:1667517', 'n': 'error in original'},
    'matabolic': {'c': 'metabolic', 's': 'diva2:801733', 'n': 'no full text'},
    'mathe': {'c': 'mathematical model', 's': 'diva2:1096550', 'n': 'no full text'},
    'mathods': {'c': 'methods', 's': 'diva2:801911', 'n': 'no full text'},
    'matrice': {'c': 'matrix', 's': ':1474350', 'n': 'error in original'},
    'mbio': {'c': 'm<sub>bio</sub>', 's': 'diva2:827212'},
    'Mbio': {'c': 'M<sub>bio</sub>', 's': 'diva2:827212'},
    'mcroorganisms': {'c': 'microorganisms', 's': 'diva2:845671', 'n': 'correct in original'},
    'me-chanical': {'c': 'mechanical', 's': 'diva2:637933', 'n': 'hyphen at end of line in original'},
    'membrance': {'c': 'membrane', 's': 'diva2:801744', 'n': 'no full text'},
    'metabolis': {'c': 'metabolism', 's': 'diva2:801905', 'n': 'no full text'},
    'metabolix': {'c': 'metabolic', 's': 'diva2:802022'},
    'metastes': {'c': 'metastases', 's': 'diva2:853465', 'n': 'no full text'},
    'micromet': {'c': 'micrometer-sized' , 's': 'diva2:1095499', 'n': 'no full text'},
    'microscomicmucin': {'c': 'microscopic mucin'},
    'microspere-based': {'c': 'microsphere-based', 's': 'diva2:851710', 'n': 'no full text'},
    'midroarray': {'c': 'microarray', 's': 'diva2:845712', 'n': 'no full text'},
    'migh': {'c': 'might', 's': 'diva2:854845', 'n': 'no full text'},
    'missinged': {'c': 'missing', 's': 'diva2:738455', 'n': 'correct in original'},
    'molcule': {'c': 'molecule', 's': 'diva2:744725', 'n': 'no full text'},
    'molcules': {'c': 'molecules', 's': 'diva2:1674058'},
    'momen': {'c': 'moment', 's': 'diva2:744718', 'n': 'no full text'},
    'mong': {'c': 'among', 's': 'diva2:801742', 'n': 'no full text'},
    'monosaccharaides': {'c': 'monosaccharides', 's': 'diva2:1145272', 'n': 'no full text'},
    'mphiphilic': {'c': 'amphiphilic', 's': 'diva2:1094126', 'n': 'no full text'},
    'msolution': {'c': 'm<sub>olution</sub>', 's': 'diva2:827212', 'n': 'correct in original'}, 
    'mucleus': {'c': 'nucleus', 's': 'diva2:801785', 'n': 'no full text'},
    'mutli-TI': {'c': 'multi-TI', 's': 'diva2:734297', 'n': 'error in original'},
    'mycerlial': {'c': 'mycelial', 's': 'diva2:854692', 'n': 'no full text'},
    'myekosuppression': {'c': 'myelosuppression', 's': 'diva2:860338', 'n': 'no full text'},
    'myelosupression':  {'c': 'myelosuppression', 's': 'diva2:860338', 'n': 'no full text'},
    'myleosupression':  {'c': 'myelosuppression', 's': 'diva2:860338', 'n': 'no full text'},
    'nitrogren': {'c':  'nitrogen', 's': 'diva2:1170378', 'n': 'error in original'},
    'n-buytl': {'c': 'n-butyl', 's': 'diva2:1339368'},
    'n-buytlacrylate': {'c':  'n-butyl acrylate', 's': 'diva2:1339368'},
    'n-ctyl': {'c': 'n-octyl', 's': 'diva2:848199', 'n': 'no full text'},
    'nanboodies': {'c': 'nanobodies', 's': 'diva2:1711725', 'n': 'no full text'},
    'nanofi': {'c':  'nanofibrils', 's': 'diva2:1150933'},
    'naphtenic': {'c':'naphthenic', 's': 'diva2:506104', 'n': 'error in original'},
    'nderstand': {'c': 'understand', 's': 'diva2:801776', 'n': 'no full text'},
    'ndings': {'c':'findings', 's': 'diva2:731857', 'n': 'missing ligature'},
    'neurosergical': {'c': 'neurosurgical', 's': 'diva2:720785', 'n': 'error in original'},
    'sur-gical': {'c': 'surgical', 's': 'diva2:720785', 'n': 'error in original'},
    'neurprotective': {'c': 'neuroprotective', 's': 'diva2:744699', 'n': 'no full text'},
    'nolecule': {'c': 'molecule', 's': 'diva2:744722', 'n': 'no full text'},
    'nto': {'c': 'not to', 's': 'diva2:853640', 'n': 'no full text'},
    'ob-ject': {'c': 'object', 's': 'diva2:1561106', 'n': 'hyphen at end of line in original'},
    'ob­ser­va­tion': {'c': 'ob­ser­va­tion', 's': 'diva2:537187'},
    'organiza-tional': {'c': 'organiza-tional', 's': 'diva2:458457'},
    'os-cilloscopes': {'c': 'oscilloscopes', 's': 'diva2:1109332'},
    'overecpress': {'c': 'overexpress', 's': 'diva2:849535', 'n': 'correct in original'},
    'ot': {'c': 'of', 's': 'diva2:1473146', 'n': 'error in original'},
    'ot': {'c': 'not', 's': 'diva2:1676731', 'n': 'counld not at end of line, the not should be on the next line'},
    'multihpysics': {'c': 'multiphysics', 's': 'diva2:846119', 'n': 'no full text'},
    'mus­culo­skeletal': {'c': 'musculoskeletal', 's': 'diva2:537187'},
    'occational': {'c': 'occasional', 's': 'diva2:744734', 'n': 'error in original'},
    'occlustion': {'c': 'occlusion', 's': 'diva2:744699', 'n': 'no full text'},
    'occured': {'c': 'occurred', 's': 'diva2:789707', 'n': 'error in original'},
    'oces': {'c': 'offices', 's': 'diva2:826225', 'n': 'missing ligature'},
    'octaetylporphyrin': {'c': 'octaethylporphyrin', 's': 'diva2:1148715'},
    'oe': {'c': 'one', 's': 'diva2:744700', 'n': 'no full text'},
    'oligonucleotie': {'c': 'oligonucleotide', 's': 'diva2:853824', 'n': 'no full text'},
    'olled': {'c': 'controlled', 's': '<diva2:1136064', 'n': 'no full text'},
    'cus- tomers': {'c': 'customers', 's': 'diva2:1741341'},
    'on-slie': {'c': 'on-slide', 's': 'diva2:744724', 'n': 'no full text'},
    'ophtalmic': {'c': 'ophthalmic', 's': 'diva2:851832', 'n': 'no full text'},
    'oretical': {'c': 'theoretical', 's': 'diva2:1117705', 'n': 'no full text'},
    'organiszation': {'c': 'organization', 's': 'diva2:855915', 'n': 'no full text'},
    'o.3': {'c': '0.3', 's': 'diva2:745566', 'n': 'no full text'},
    'pastic': {'c': 'plastic', 's': 'diva2:1205231', 'n': 'error in original'},
    'peruorocarbon': {'c': 'perfluorocarbon', 's': 'diva2:1325213', 'n': 'missing ligature'},
    'per\xadceived': {'c': 'perceived', 's': 'diva2:537187'},
    'per\xadformed': {'c': 'performed', 's': 'diva2:1452049', 'n': 'hyphen at end of line in original'},
    'phophosribulokinase': {'c': 'phosphoribulokinase', 's': 'diva2:1823407', 'n': 'no full text'},
    'possibilty': {'c': 'possibility', 's': 'diva2:1667517'},
    'pre-cision': {'c': 'precision', 's': 'diva2:724705', 'n': 'hyphen at end of line in original'},
    'pre-sents': {'c': 'presents', 's': 'diva2:1217609', 'n': 'hyphen at end of line in original'},
    'powergenerated': {'c': 'power generated', 's': 'diva2:1216523', 'n': 'there was a newline between the words'},
    'preaheating': {'c': 'preheating', 's': 'diva2:441389', 'n': 'correct in original'},
    'parcticles': {'c': 'particles', 's': 'diva2:744719', 'n': 'no full text'},
    'parementers': {'c': 'parameters', 's': 'diva2:848249', 'n': 'no full text'},
    'partion': {'c': 'partition', 's': 'diva2:1843588', 'n': 'error in original'},
    'pases': {'c': 'phases', 's': 'diva2:801894', 'n': 'no full text'},
    'patiens': {'c': 'patients', 's': ['diva2:801778', 'diva2:852274'], 'n': 'no full text'},
    'pennationangle': {'c': 'pennation angle', 's': 'diva2:1553336', 'n': 'there was a new line between the words'},
    'perfomred': {'c': 'performed', 's': 'diva2:853465', 'n': 'no full text'},
    'pharaceutical': {'c': 'pharmaceutical', 's': 'diva2:744729', 'n': 'no full text'},
    'peptideLac': {'c': 'peptide-Lac', 's': 'diva2:1587325', 'n': 'appears as "peptide- Lac" in original'},
    'phenotapes': {'c': 'phenotypes', 's': 'diva2:845713', 'n': 'no full text'},
    'phenyl]borate': {'c': 'phenyl borate', 's': 'diva2:1690568', 'n': 'part of "Sodium tetrakis[3,5-bis(trifluoromethyl)phenyl]borate" - the split on the right bracket is wrong for a checmical name'},
    'phthahlic': {'c': 'phthalic', 's': 'diva2:1787126', 'n': 'error in original'},
    'physolological': {'c': 'physiological', 's': 'diva2:801899', 'n': 'no full text'},
    'plaer': {'c': 'player', 's': 'diva2:849535', 'n': 'correct in original'},
    'plastrics': {'c': 'plastics', 's': 'diva2:1243292', 'n': 'error in original'},
    'ploting': {'c': 'plotting', 's': 'diva2:971422', 'n': 'error in original'},
    'polyactic': {'c': 'polylactic', 's': 'diva2:801903', 'n': 'no full text'},
    'pos-sibility': {'c': 'possibility', 's': 'diva2:724440', 'n': 'correct in original'},
    'posibility': {'c': 'possibility', 's': 'diva2:1643935', 'n': 'error in original'},
    'potentiao': {'c': 'potential', 's': 'diva2:853465', 'n': 'no full text'},
    'potntial': {'c': 'potential', 's': 'diva2:801742', 'n': 'no full text'},
    'prbe': {'c': 'probe', 's': 'diva2:851774', 'n': 'correct in original'},
    'prepresent': {'c': 'represent', 's': 'diva2:744716', 'n': 'no full text'},
    'presdicted': {'c': 'predicted', 's': 'diva2:845713', 'n': 'no full text'},
    'presured': {'c': 'pressured', 's': ['diva2:787218', 'diva2:787188']},
    'pre\xadsentation': {'c': 'presentation', 's': 'diva2:1117705'},
    'profit\xadable': {'c': 'profitable', 's': 'diva2:460449', 'n': 'correct in original'},
    'prolesfor': {'c': 'profiles for', 's': 'diva2:1260679', 'n': 'missing ligature'},
    'protiens': {'c': 'proteins', 's': 'diva2:572719', 'n': 'correct in original'}, 
    'protit': {'c': 'profit', 's': 'diva2:1115384'},
    'prototpyes': {'c': 'prototypes', 's': 'diva2:854001', 'n': 'no full text'},
    'prototypeset': {'c': 'prototype set', 's': 'diva2:1451748', 'n': 'correct in original'},
    'purific': {'c': 'purifiction', 's': 'diva2:1876253', 'n': 'correct in original'},
    'puruvate': {'c': 'pyruvate', 's': 'diva2:1787103', 'n': 'no full text'},
    'pyrrolidone-Polycaprolactone': {'c': 'pyrrolidone-polycaprolactone', 's': 'diva2:720734', 'n': 'no full text'},
    'prostatespecific': {'c': 'prostate-specific', 's': 'diva2:1876708'}, # #"prostate- specific"
    'panol': {'c': '2-propanol', 's': 'diva2:1159711'},
    'pdc': {'c': 'H<sub>2</sub>pdc = 2,6-pyridinedicarboxylic acid', 's': 'diva2:855425'},
    'rscattering': {'c': 'scattering', 's': 'diva2:1677054', 'n': 'correct in original; the "r" comves from the end of the previous word "laser"'},
    'rsults': {'c': 'results', 's': 'diva2:854001', 'n': 'no full text'},
    'rotein': {'c': 'protein', 's': 'diva2:853815', 'n': 'no full text'},
    'rotts': {'c': 'roots', 's': 'diva2:856152', 'n': 'no full text'},
    'rigidus': {'c': 'hallux rigidus:', 's': ['diva2:635950', 'diva2:646620'],'n': 'diva2:635950 has no full text, while the version at diva2:646620 does; Latin for “stiff toe”'},
    'roduced': {'c': 'introduced', 's': 'diva2:1117705', 'n': 'no full text'},
    'revovery': {'c': 'recovery', 's': 'diva2:855825', 'n': 'no full text'},
    'revelaed': {'c': 'revealed', 's': 'diva2:801739', 'n': 'correct in original'},
    'responset': {'c': 'response to', 's': 'diva2:851774'},
    'resport': {'c': 'report', 's': 'diva2:855915', 'n': 'no full text'},
    'responisibility': {'c': 'responsibility', 's': 'diva2:1763572', 'n': 'correct in original'},
    'repoted': {'c': 'reported', 's': 'diva2:744724', 'n': 'no full text'},
    'requiered': {'c': 'required', 's': 'diva2:1454477', 'n': 'error in original'},
    'rabricated': {'c': 'fabricated', 's': 'diva2:854047', 'n': 'no full text'},
    'releaed': {'c': 'released', 's': 'diva2:1045583', 'n': 'error in original'},
    'radica': {'c': 'radicals', 's': 'diva2:1096550', 'n': 'no full text'}, 
    'reained': {'c': 'retained', 's': 'diva2:744733', 'n': 'no full text'},
    'ques': {'c': 'queues', 's': 'diva2:1686917', 'n': 'error in original'},
    'res\xadpective': {'c': 'respective', 's': 'diva2:537187'},
    'quantication': {'c': 'quantification', 's': 'diva2:787913', 'n': 'no full text'},
    'regene\xadration': {'c': 'regeneration', 's': 'diva2:460449'},
    'regene\xadrator': {'c': 'regenerator', 's': 'diva2:460449'},
    'regu-lation': {'c': 'regulation', 's': 'diva2:724746'},
    'rele-vant': {'c': 'relevant', 's': 'diva2:725219'},
    'reagarding': {'c': 'regarding', 's': 'diva2:744661', 'n': 'no full text'},
    'seperately': {'c': 'separately', 's': 'diva2:1183490', 'n': 'error in original'},
    'sythesis': {'c': 'synthesis', 's': 'diva2:853705', 'n': 'no full text'},
    'sythesis': {'c': 'synthesis', 's':  'diva2:802022', 'n': 'correct in original'},
    'sytometry': {'c': 'cytometry', 's': 'diva2:744736', 'n': 'no full text'},
    'suuport': {'c': 'support', 's': 'diva2:744725', 'n': 'no full text'},
    'switxhed': {'c': 'switched', 's': 'diva2:801733', 'n': 'no full text'},
    'synthesi&lt;ed': {'c': 'synthesized', 's': 'diva2:744730', 'n': 'no full text'},
    'sysstems': {'c':'systems', 's': 'diva2:801733', 'n': 'no full text'},
    'sufficinet': {'c': 'sufficient', 's': 'diva2:1640359', 'n': 'error in original'},
    'suporting': {'c': 'supporting', 's': 'diva2:801905', 'n': 'no full text'},
    'survery': {'c': 'survey', 's': 'diva2:1183490', 'n': 'error in original'},
    'sucient': {'c': 'sufficient', 's': 'diva2:731857', 'n': 'missing ligature'},
    'suffcient': {'c': 'sufficient', 's': 'diva2:1094051', 'n': 'missing ligature'},
    'su-peraggregate': {'c': 'superaggregate', 's': 'diva2:1264229', 'n': 'hyphen at end of line in original'},
    'subsequen': {'c': 'subsequent', 's': 'diva2:852471', 'n': 'no full text'},
    'structrual': {'c': 'structural', 's': 'diva2:1888328', 'n': 'error in original'},
    'styrene-butadien': {'c': 'styrene-butadiene', 's': 'diva2:1270990', 'n': 'error in original'},
    'strenght': {'c':  'strength', 's': 'diva2:1382135', 'n': 'correct in original'},
    'strenths': {'c': 'strengths', 's': 'diva2:855720', 'n': 'no full text'},
    'stickie': {'B2': 'Noun'}, # used in diva2:413406 - no full text
    'stickies': {'B2': 'Noun (plural)'}, # see diva2:413406 - no full text
    'stie': {'c': 'site', 's': 'diva2:744736', 'n': 'no full text'},
    'stets': {'c': 'sets', 's': 'diva2:1640359', 'n': 'error in original'},
    'st-g-PCL': {'c': 'st-g-PCL<sub>2</sub>', 's': 'diva2:745521', 'n': 'no full text'},
    'sstem': {'c': 'system', 's': 'diva2:851774', 'n': 'correct in original'},
    'sstems': {'c': 'systems', 's': 'diva2:801733', 'n': 'no full text'},
    'specic': {'c': 'specific', 's': ['diva2:1438504','diva2:949949'], 'n': 'missing ligature'},
    'sitaution': {'c': 'situation', 's': 'diva2:935159', 'n': 'error in original'},
    'somplex': {'c': 'complex', 's': 'diva2:744727', 'n': 'no full text'},
    'songle-cell': {'c': 'single-cell', 's': 'diva2:744723', 'n': 'no full text'},
    'showeds': {'c': 'showed', 's': 'diva2:826713', 'n': 'error in original'},
    'showedfthat': {'c': 'showed that', 's': 'diva2:1325213', 'n': 'correct in original'},
    'shotin': {'c': 'shot in', 's': 'diva2:1683604', 'n': 'correct in original - there words are separated by a newline'},
    'shold': {'c': 'should', 's': 'diva2:1296678', 'n': 'error in original'}, 
    'short-and': {'B1': 'short- and', 's': 'diva2:744701', 'n': 'no full text'},
    'settings—a': {'c': 'settings - a', 's': 'diva2:1883099', 'n': 'phen begins a parenthetical'},
    'serio': {'c': 'serious', 's': 'diva2:1159711', 'n': 'correct in original'},
    'sequenzed': {'c':  'sequenced', 's': 'diva2:801790', 'n': 'no full text'},
    'sequense': {'c': 'sequence', 's': 'diva2:853705', 'n': 'no full text'},
    'sdepending': {'c': 'depending', 's': 'diva2:1540188', 'n': 'the "s" is from the units of the previoous number - note there is a line break after "32 s" and before "depending"'},
    'scientificlly': {'c': 'scientifically', 's': 'diva2:853640', 'n': 'no full text'},
    'sare': {'c': 'are', 's': 'diva2:1703746', 'n': 'the "s" belongs with the previous word "tools"'},
    'sanc-tions': {'c': 'sanctions', 's': 'diva2:1217609', 'n': 'hyphen at end of line in original'},
    'salamnder': {'c': 'salamander', 's': 'diva2:852471', 'n': 'no full text'},
    'safetey': {'c': 'safety', 's': 'diva2:1060103', 'n': 'error in original'},
    'superaggre-gate': {'c': 'superaggregate', 's': 'diva2:1264229', 'n': 'correct in original'},
    'sub-national': {'c': 'subnational', 's': 'diva2:442651', 'n': 'hyphenated in original'},
    'sulfamethoxazol': {'c': 'sulfamethoxazole', 's': 'diva2:1218610', 'n': 'no full text'},
    'struc\xadture': {'c': 'structure', 's': 'diva2:537187'},
    'solidosty': {'c': 'solidosity', 's': 'diva2:1095506', 'n': 'error in original'},
    'singl-cell-sized': {'c': 'single-cell-sized', 's': 'diva2:860677', 'n': 'no full text'},
    'soilds': {'c': 'solids', 's': 'diva2:1430868', 'n': 'correct in original'},
    'sild': {'c': 'silk', 's': 'diva2:895964', 'n': 'no full text'},
    'serotenergic': {'c': 'serotonergic', 's': 'diva2:801785', 'n': 'no full text'},
    'withing': {'c': 'within', 's': 'diva2:1572413', 'n': 'error in original'},
    'wokrs': {'c': 'works', 's': 'diva2:1528033', 'n': 'error in original'},
    'wilde': {'c': 'wild', 's': 'diva2:1217588', 'n': 'no full text'},
    'where\xadof': {'c': 'whereof', 's': 'diva2:460449'},
    'whitch': {'c': 'which', 's': 'diva2:756805', 'n': 'error in original'},
    'whoch': {'c': 'which', 's': 'diva2:851740', 'n': 'no full text'},
    'vpr': {'C': 'Vpr', 's': 'diva2:804978', 'n': 'no full text'}, # Vpr is an HIV protein
    'weght': {'c': 'weight', 's': 'diva2:1382135', 'n': 'error in original'},
    'voe': {'c': 'volatile organic compound', 's': 'diva2:1096550', 'n': 'no full text'},
    'toether': {'c':  'together', 's': 'diva2:744730', 'n': 'no full text'},
    'togther': {'c': 'together', 's': 'diva2:801905', 'n': 'no full text'},
    'toerlance': {'c': 'tolerance', 's': 'diva2:855806', 'n': 'no full text'},
    'tje': {'c': 'the', 's': 'diva2:851740', 'n': 'no full text'},
    'tient': {'c': 'patient', 's': 'diva2:1621933', 'n': 'no full text'},
    'thsi': {'c': 'this', 's': 'diva2:744718', 'n': 'no full text'},
    'thta': {'c': 'that', 's': 'diva2:854043', 'n': 'no full text'},
    'thermoncompensated': {'c': 'thermocompensated', 's': 'odiva2:848988'},
    'thos': {'c': 'this', 's': 'diva2:744727', 'n': 'no full text'},
    'three-dimensopnal': {'c':  'three-dimensional', 's': 'diva2:855915', 'n': 'no full text'},
    'test-ing': {'c': 'testing', 's': 'diva2:557542', 'n': 'hyphen at end of line in original'},
    'tetraethyelene': {'c': 'tetraethylene', 's': 'diva2:852874', 'n': 'no full text'},
    'tha': {'c': 'the', 's': ['diva2:854709', 'diva2:744719']},
    'teh': {'c': 'the', 's': ['diva2:744699', 'diva2:801776']},
    'temerature': {'c': 'temperature', 's': 'diva2:744725', 'n': 'no full text'},
    'terget': {'c': 'target', 's': 'diva2:801905', 'n': 'no full text'},
    'teriolecta': {'c': 'tertiolecta', 's': 'diva2:854656'},
    'tareting': {'c': 'targeting', 's': 'diva2:853705', 'n': 'no full text'},
    'targetin': {'c': 'targeting', 's': 'diva2:851710', 'n': 'no full text'},
    'tRNApyl': {'c': 'tRNA<sup>pyl</sub>', 's': 'diva2:1038973'},
    't-peel': {'c': 'T-peel', 's': 'diva2:1540188'},
    'vaccinatin': {'c': 'vaccination', 's': 'diva2:801739', 'n': 'correct in original'},
    'veen': {'c': 'been', 's': 'diva2:845713', 'n': 'no full text'},
    'usedd': {'c': 'used', 's': 'diva2:854845', 'n': 'no full text'}, 
    'usign': {'c': 'using', 's': 'diva2:853640', 'n': 'no full text'},
    'uswed': {'c': 'used', 's': 'diva2:802022', 'n': 'correct in original'},
    'uidized': {'c': 'fluidized', 's': 'diva2:1229284', 'n': 'missing ligature'},
    'uing': {'c': 'using', 's': 'diva2:854287', 'n': 'no full text'},
    'uctuations': {'c': 'fluctuations', 's': 'diva2:1261155', 'n': 'missing ligature'},
    'ue': {'c': 'flue', 's': 'diva2:1229284', 'n': 'missing ligature'},
    'ucts': {'c': 'products', 's': 'diva2:1159711'},
    'triglycer': {'c': 'triglycerides', 's': 'diva2:1154619', 'n': 'no full text'},
    'tsted': {'c': 'tested', 's': 'diva2:744724', 'n': 'no full text'},
    'treatmen': {'c': 'treatment', 's': 'diva2:744706', 'n': 'no full text'},
    'tretments': {'c': 'treatments', 's': 'diva2:744736', 'n': 'no full text'},
    'totatl': {'c': 'total', 's': 'diva2:851774', 'n': 'error in original'},
    'towrads': {'c': 'towards', 's': 'diva2:801894', 'n': 'no full text'},
    'trapsIVwere': {'c': 'traps were', 's': 'diva2:1447055', 'n': 'The "IV" was from the page number!'},
    'threee-dimensional': {'c': 'three-dimensional', 's': 'diva2:854019', 'n': 'no full text'},
    'tighly-regulated': {'c': 'tightly-regulated', 's': 'diva2:1873267', 'n': 'no full text'},
    'tonCO': {'c': 'tonCO<sub>2</sub>', 's': 'diva2:1627230'},
    'texttt{kspaceFirstOrder': {'c': 'kspaceFirstOrder', 's': 'diva2:1790368', 'n': 'the LaTeX command "textt{}" to set the string in typerwrite font was not processed properly - the original is correct'},
    'themocellum': {'c': 'thermocellum', 's': 'diva2:1574726', 'n': 'no full text'},
    'tetrakis[3,5-bis': {'c': "tetrakis[3,5-bis(trifluoromethyl)phenyl]borate", 's': 'diva2:1690568'},
    'technially': {'c': 'technically', 's': 'diva2:854845', 'n': 'no full text'},
    'tech\xadnical': {'c': 'technical', 's': 'diva2:537187'},




}
