# This dictionary contains Mathematics Subject Classification (MSC) entries 
# expanded into single-concept keywords (by splitting compound terms).
# Each entry retains its Part of Speech (POS), CEFR level, and the original 
# top-level MSC code.

expanded_msc_keywords_with_code = {
    'General topics': { 'C1 (Specialized)': 'Noun Phrase', 'MSC': '00'},
    'Overarching topics': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '00'},
    'Collections': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '00'},
    'History': {'B2': 'Noun Phrase', 'MSC': '01'},
    'Biography': {'B2': 'Noun Phrase', 'MSC': '01'},
    'Mathematical logic': {'C2 (Specialized)': 'Noun Phrase', 'MSC': '03'},
    'Foundations of mathematics': {'C2 (Specialized)': 'Noun Phrase', 'MSC': '03'},
    'Combinatorics': {'B2': 'Noun', 'MSC': '05'},
    'Order theory': {'C2 (Specialized)': 'Noun Phrase', 'MSC': '06'},
    'Lattices': {'C2 (Specialized)': 'Noun Phrase', 'MSC': '06'},
    'Ordered algebraic structures': {'C2 (Specialized)': 'Noun Phrase', 'MSC': '06'},
    'General algebraic systems': {'C2 (Specialized)': 'Noun Phrase', 'MSC': '08'},
    'Number theory': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '11'},
    'Field theory': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '12'},
    'Polynomials': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '12'},
    'Commutative algebra': {'C2 (Specialized)': 'Noun Phrase', 'MSC': '13'},
    'Algebraic geometry': {'C2 (Specialized)': 'Noun Phrase', 'MSC': '14'},
    'Linear algebra': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '15'},
    'Multilinear algebra': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '15'},
    'Matrix theory': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '15'},
    'Associative rings': {'C2 (Specialized)': 'Noun Phrase', 'MSC': '16'},
    'Associative algebras': {'C2 (Specialized)': 'Noun Phrase', 'MSC': '16'},
    'Nonassociative rings': {'C2 (Specialized)': 'Noun Phrase', 'MSC': '17'},
    'Nonassociative algebras': {'C2 (Specialized)': 'Noun Phrase', 'MSC': '17'},
    'Category theory': {'C2 (Specialized)': 'Noun Phrase', 'MSC': '18'},
    'Homological algebra': {'C2 (Specialized)': 'Noun Phrase', 'MSC': '18'},
    'K-theory': {'C2 (Specialized)': 'Noun', 'MSC': '19'},
    'Group theory': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '20'},
    'Group generalizations': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '20'},
    'Topological groups': {'C2 (Specialized)': 'Noun Phrase', 'MSC': '22'},
    'Lie groups': {'C2 (Specialized)': 'Noun Phrase', 'MSC': '22'},
    'Real functions': {'B2': 'Noun Phrase', 'MSC': '26'},
    'Measure theory': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '28'},
    'Integration theory': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '28'},
    'Complex variables': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '30'},
    'Analytic functions': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '30'},
    'Potential theory': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '31'},
    'Several complex variables': {'C2 (Specialized)': 'Noun Phrase', 'MSC': '32'},
    'Analytic spaces': {'C2 (Specialized)': 'Noun Phrase', 'MSC': '32'},
    'Special functions': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '33'},
    'Ordinary differential equations': {'B2': 'Noun Phrase', 'MSC': '34'},
    'Partial differential equations': {'B2': 'Noun Phrase', 'MSC': '35'},
    'Dynamical systems': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '37'},
    'Ergodic theory': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '37'},
    'Difference equations': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '39'},
    'Functional equations': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '39'},
    'Sequences': {'C1 (Specialized)': 'Noun Phrase',  'MSC': '40'},
    'Series': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '40'},
    'Summability': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '40'},
    'Approximations': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '41'},
    'Expansions': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '41'},
    'Harmonic analysis': {'C2 (Specialized)': 'Noun Phrase', 'MSC': '42'},
    'Euclidean spaces': {'C2 (Specialized)': 'Noun Phrase', 'MSC': '42'},
    'Abstract harmonic analysis': {'C2 (Specialized)': 'Noun Phrase', 'MSC': '43'},
    'Integral transforms': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '44'},
    'Operational calculus': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '44'},
    'Integral equations': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '45'},
    'Functional analysis': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '46'},
    'Operator theory': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '47'},
    'Calculus of variations': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '49'},
    'Optimal control': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '49'},
    'Optimization': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '49'},
    'Geometry': {'B2': 'Noun', 'MSC': '51'},
    'Convex geometry': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '52'},
    'Discrete geometry': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '52'},
    'Differential geometry': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '53'},
    'General topology': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '54'},
    'Algebraic topology': {'C2 (Specialized)': 'Noun Phrase', 'MSC': '55'},
    'Manifolds': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '57'},
    'Cell complexes': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '57'},
    'Global analysis': {'C2 (Specialized)': 'Noun Phrase', 'MSC': '58'},
    'Analysis on manifolds': {'C2 (Specialized)': 'Noun Phrase', 'MSC': '58'},
    'Probability theory': {'B2': 'Noun Phrase', 'MSC': '60'},
    'Stochastic processes': {'B2': 'Noun Phrase', 'MSC': '60'},
    'Statistics': {'B1': 'Noun', 'MSC': '62'},
    'Numerical analysis': {'B2': 'Noun Phrase', 'MSC': '65'},
    'Computer science': {'A2': 'Noun Phrase', 'MSC': '68'},
    'Mechanics of particles': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '70'},
    'Mechanics of systems': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '70'},
    'Mechanics of deformable solids': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '74'},
    'Solid mechanics': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '74'},
    'Fluid mechanics': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '76'},
    'Optics': {'B2': 'Noun Phrase', 'MSC': '78'},
    'Electromagnetic theory': {'B2': 'Noun Phrase', 'MSC': '78'},
    'Classical thermodynamics': {'B2': 'Noun Phrase', 'MSC': '80'},
    'Heat transfer': {'B2': 'Noun Phrase', 'MSC': '80'},
    'Quantum theory': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '81'},
    'Statistical mechanics': {'C2 (Specialized)': 'Noun Phrase', 'MSC': '82'},
    'Structure of matter': {'C2 (Specialized)': 'Noun Phrase', 'MSC': '82'},
    'Relativity': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '83'},
    'Gravitational theory': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '83'},
    'Astronomy': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '85'},
    'Astrophysics': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '85'},
    'Geophysics': {'B2': 'Noun', 'MSC': '86'},
    'Operations research': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '90'},
    'Mathematical programming': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '90'},
    'Game theory': {'B2': 'Noun Phrase', 'MSC': '91'},
    'Economics': {'B2': 'Noun Phrase', 'MSC': '91'},
    'Social sciences': {'B2': 'Noun Phrase', 'MSC': '91'},
    'Behavioral sciences': {'B2': 'Noun Phrase', 'MSC': '91'},
    'Biology': {'B2': 'Noun Phrase', 'MSC': '92'},
    'Natural sciences': {'B2': 'Noun Phrase', 'MSC': '92'},
    'Systems theory': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '93'},
    'Control theory': {'C1 (Specialized)': 'Noun Phrase', 'MSC': '93'},
    'Information theory': {'B2': 'Noun Phrase', 'MSC': '94'},
    'Communication theory': { 'B2': 'Noun Phrase', 'MSC': '94'},
    'Circuits': {'B2': 'Noun Phrase', 'MSC': '94'},
    'Mathematics education': {'B1': 'Noun Phrase', 'MSC': '97'}
}
