#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# -*- mode: python; python-indent-offset: 4 -*-
#
# Zoom-chat-to-canvas-page-py -c course_id --transcript zoom_chat_file
#
# Example:
# ./Zoom-chat-to-canvas-page-py    -c 11 --transcript /z3/maguire/meeting_saved_chat-20210304.txt
# ./Zoom-chat-to-canvas-page-py -v -c 11 --transcript /z3/maguire/meeting_saved_chat-2020-12-10.txt
#
# based on by zeudonymize.py Daniel Bosk <dbosk@kth.se> - https://github.com/dbosk/recordy.git
# His program took in a Zoom chant and pseudo anonymized it.
# It can optionally take a file to map names - for example to preserve the teacher's name
#
# Example: ./zeudonymize.py --transcript /z3/maguire/meeting_saved_chat-20210304.txt
# Where the transcript is:
# 14:41:00	 From  Daniel Bosk, KTH : @Chip: I wrote a short script to pseudonymize Zoom chat transcripts.
# 14:41:48	 From  Gerald Q Maguire Jr  to  Daniel Bosk, KTH(Direct Message) : Great - send me a pointer to it.
# 14:42:15	 From  Daniel Bosk, KTH  to  Gerald Q Maguire Jr(Direct Message) : https://github.com/dbosk/recordy/tree/master/zeudonymize
#
# will generate:
#  meeting_saved_chat-20210304-pseudonymized.txt
#  meeting_saved_chat-20210304.nyms
# The later will contain:
# {
#   " Daniel Bosk, KTH": "Student 3",
#   " Gerald Q Maguire Jr ": "Student 4"
# }
#
# Changing the pseudonym file to meeting_saved_chat-20210304-teacher.nyms
# {
#   " Daniel Bosk, KTH": "Teacher",
#   " Gerald Q Maguire Jr ": "Student 4"
# }
# and running with
#  --nymfile /z3/maguire/meeting_saved_chat-20210304-teacher.nyms
# will apply the pseudonym for Daniel as "Teacher"
#
# on 2021-03-04 G. Q. Maguire Jr. extended this to use information from a Canvas course room to be able to
# make a wikipage from a chat transcript.
# Also as can be seen from the above, the names should have strip applied to them to remove the starting and trailng white space.
#
# With the option "-N" it does not use pseudonyms, but rather the real user's names
#
# After creating the HTML page
# 1. upload the created page and give it a title, in this case "Test page 3"
#    ./ccreate.py https://xxxx.instructure.com/courses/11/pages/test-page-3 "Test page 3"
#
# 2. Put the page into a module in the course by going to a module, clicking the plus symbol
#    then select the type of module to add as "Page" and then select the item in the scrolling list "Test page 3"
#
# Note that you need to refresh the "Modules" page to be able to see the new choice of page.
#
# Note that if your use the ccreate.py script multiple times, the page will have names of the form: "Test page 3-i", such as "Test page 3-6". 
#
# You can eliminate the uploaded page by using the page: https://xxxx.instructure.com/courses/11/pages
#    Click on the three vertical dots on the right and select "Delete"

#
import re
import sys

import json
import argparse
import os

import requests, time
import pprint

#############################
###### EDIT THIS STUFF ######
#############################

global baseUrl	# the base URL used for access to Canvas
global header	# the header for all HTML requests
global payload	# place to store additionally payload when needed for options to HTML requests

# Based upon the options to the program, initialize the variables used to access Canvas gia HTML requests
def initialize(args):
  global baseUrl, header, payload

  # styled based upon https://martin-thoma.com/configuration-files-in-python/
  config_file=args["config"]

  try:
    with open(config_file) as json_data_file:
      configuration = json.load(json_data_file)
      access_token=configuration["canvas"]["access_token"]
      if args["containers"]:
        baseUrl="http://"+configuration["canvas"]["host"]+"/api/v1"
        print("using HTTP for the container environment")
      else:
        baseUrl="https://"+configuration["canvas"]["host"]+"/api/v1"

      header = {'Authorization' : 'Bearer ' + access_token}
      payload = {}
  except:
    print("Unable to open configuration file named {}".format(config_file))
    print("Please create a suitable configuration file, the default name is config.json")
    sys.exit()

# Canvas related functions
def list_modules(course_id, module_name=None):
  modules_found_thus_far=[]
  # Use the Canvas API to get the list of modules for the course
  #GET /api/v1/courses/:course_id/modules

  url = "{0}/courses/{1}/modules".format(baseUrl, course_id)
  if Verbose_Flag:
    print("url: {}".format(url))

  # this will do a partial match against the module_name
  # This reducing the number of responses returned

  if module_name:
    payload = {'search_term': module_name} 
    r = requests.get(url, headers = header, data = payload)
  else:
    r = requests.get(url, headers = header)

  if Verbose_Flag:
    print("result of getting modules: {}".format(r.text))

  if r.status_code == requests.codes.ok:
    page_response=r.json()

    for p_response in page_response:  
      modules_found_thus_far.append(p_response)

    # the following is needed when the reponse has been paginated
    # i.e., when the response is split into pieces - each returning only some of the list of modules
    # see "Handling Pagination" - Discussion created by tyler.clair@usu.edu on Apr 27, 2015, https://community.canvaslms.com/thread/1500
    while r.links.get('next', False):
      r = requests.get(r.links['next']['url'], headers=header)  
      if Verbose_Flag:
        print("result of getting modules for a paginated response: {}".format(r.text))
      page_response = r.json()  
      for p_response in page_response:  
        modules_found_thus_far.append(p_response)

  return modules_found_thus_far

def create_module(course_id, module_name):
  module_id=None              # will contain the module's ID if it exists
  # Use the Canvas API to create a module in the course
  #POST /api/v1/courses/:course_id/modules
  url = "{0}/courses/{1}/modules".format(baseUrl, course_id,module_name)
  if Verbose_Flag:
    print("creating module for course_id={0} module_name={1}".format(course_id,module_name))
  payload = {'module[name]': module_name }
  r = requests.post(url, headers = header, data = payload)
  if Verbose_Flag:
    print("result of creating module: {}".format(r.text))

  if r.status_code == requests.codes.ok:
    modules_response=r.json()
    module_id=modules_response["id"]

  return  module_id

def create_module_page_item(course_id, module_id, page_id, item_name, page_url):
  module_id=None
  # Use the Canvas API to create a module item in the course and module
  #POST /api/v1/courses/:course_id/modules/:module_id/items
  url = "{0}/courses/{1}/modules/{2}/items".format(baseUrl, course_id, module_id)
  if Verbose_Flag:
    print("creating module assignment item for course_id={0} module_id={1} assignment_id={1}".format(course_id, module_id, page_id))
  payload = {'module_item':
             {
               'title': item_name,
               'type': 'Page',
               'content_id': page_id,
               'page_url': page_url
             }
             }

  r = requests.post(url, headers = header, json = payload)
  if Verbose_Flag:
    print("result of creating module page item: {}".format(r.text))

  if r.status_code == requests.codes.ok:
    modules_response=r.json()
    module_id=modules_response["id"]

  return  module_id



def list_pages(course_id, page_name=None):
  pages_found_thus_far=[]
  # Use the Canvas API to get the list of modules for the course
  #GET /api/v1/courses/:course_id/pages

  url = "{0}/courses/{1}/pages".format(baseUrl, course_id)
  if Verbose_Flag:
    print("url: {}".format(url))

  # this will do a partial match against the module_name
  # This reducing the number of responses returned

  if page_name:
    payload = {'search_term': page_name} 
    r = requests.get(url, headers = header, data = payload)
  else:
    r = requests.get(url, headers = header)

  if Verbose_Flag:
    print("result of getting pages: {}".format(r.text))

  if r.status_code == requests.codes.ok:
    page_response=r.json()

    for p_response in page_response:  
      pages_found_thus_far.append(p_response)

    # the following is needed when the reponse has been paginated
    # i.e., when the response is split into pieces - each returning only some of the list of modules
    # see "Handling Pagination" - Discussion created by tyler.clair@usu.edu on Apr 27, 2015, https://community.canvaslms.com/thread/1500
    while r.links.get('next', False):
      r = requests.get(r.links['next']['url'], headers=header)  
      if Verbose_Flag:
        print("result of getting modules for a paginated response: {}".format(r.text))
      page_response = r.json()  
      for p_response in page_response:  
        pages_found_thus_far.append(p_response)

  return pages_found_thus_far

def create_course_page(course_id, page_title, page_contents):
  #Create page WikiPagesApiController#create
  #POST /api/v1/courses/:course_id/pages

  url = "{0}/courses/{1}/pages".format(baseUrl,course_id)
  if Verbose_Flag:
    print("url: {}".format(url))

  payload={'wiki_page':
           {
             'title': page_title,
             'body': page_contents,
             'published': 'true'
           }
           }
  r = requests.post(url, headers = header, json=payload)

  if Verbose_Flag:
    print("result of creating a page: {}".format(r.text))

  if r.status_code == requests.codes.ok:
    page_response=r.json()
    return page_response

  return None


def delete_course_page(course_id, page_url):
  #delete a page
  #DELETE /api/v1/courses/:course_id/pages/:url

  url = "{0}/courses/{1}/pages/{2}".format(baseUrl,course_id, page_url)
  if Verbose_Flag:
    print("url: {}".format(url))

  r = requests.delete(url, headers = header)

  if Verbose_Flag:
    print("result of deleting a page: {}".format(r.text))

  if r.status_code == requests.codes.ok:
    page_response=r.json()
    return page_response

  return None



def create_module_page_item(course_id, module_id, page_id, item_name, page_url):
  # Use the Canvas API to create a module item in the course and module
  #POST /api/v1/courses/:course_id/modules/:module_id/items
  url = "{0}/courses/{1}/modules/{2}/items".format(baseUrl, course_id, module_id)
  if Verbose_Flag:
    print("creating module assignment item for course_id={0} module_id={1} assignment_id={1}".format(course_id, module_id, page_id))
  payload = {'module_item':
             {
               'title': item_name,
               'type': 'Page',
               'content_id': page_id,
               'page_url': page_url
             }
             }

  r = requests.post(url, headers = header, json = payload)
  if Verbose_Flag:
    print("result of creating module page item: {}".format(r.text))

  if r.status_code == requests.codes.ok:
    modules_response=r.json()
    module_id=modules_response["id"]
    return module_id
  return  module_id


# class and functions related to the Zoom chat items

class PseudonymFactory:
  def __init__(self, prefix, nym_map):
    self.__prefix = prefix
    self.__num = 0
    pattern = re.compile(f"{prefix} (\\d+)")
    for _, pseudonym in nym_map.items():
      match = pattern.match(pseudonym)
      if match:
        self.__num = max(self.__num, int(match.group(1)))

  def __str__(self):
    return f"{self.__prefix} {self.__num}"

  def next(self):
    self.__num += 1
    return str(self)

  def __next__(self):
    return self.next()

def main(argv):
  global Verbose_Flag
  
  timestamp_regex = r'(2[0-3]|[01][0-9]|[0-9]):([0-5][0-9]|[0-9]):([0-5][0-9]|[0-9])'

  argp = argparse.ArgumentParser(description="zeudonymize: Pseudonymizing Zoom chats")

  argp.add_argument("-t", "--transcript", required=True,
                    help="Filename of the chat transcript")
  argp.add_argument("-p", "--prefix", type=str, default="Student",
                    help="Pseudonym prefix for new pseudonyms")
  argp.add_argument("-n", "--nymfile", type=str,
                    help="Filename of the nym map")

  argp.add_argument('-v', '--verbose', required=False,
                    default=False,
                    action="store_true",
                    help="Print lots of output to stdout")
  argp.add_argument('-C', '--containers',
                    default=False,
                    action="store_true",
                    help="for the container enviroment in the virtual machine")
  argp.add_argument("--config", type=str, default='config.json',
                    help="read configuration from file")

  argp.add_argument("-c", "--canvas_course_id", type=int, required=True,
                    help="canvas course_id")

  argp.add_argument('-N', '--nonanonymous', required=False,
                    default=False,
                    action="store_true",
                    help="use the real names and not the pseudonyms")

  argp.add_argument('-M', '--module_name', required=False, type=str,
                    default='Zoom chat sessions',
                    help="Name of the module to put the HTML page into")

  argp.add_argument('-T', '--page_title', required=False, type=str,
                    default='',
                    help="Name of the page to use")

  argp.add_argument('-R', '--remove_existing_page', required=False,
                    default=False,
                    action="store_true",
                    help="remove an existing page")


  args = vars(argp.parse_args(argv))

  Verbose_Flag=args["verbose"]

  initialize(args)
  if Verbose_Flag:
    print("baseUrl={}".format(baseUrl))

  course_id=args["canvas_course_id"]
  print("course_id={}".format(course_id))

  in_filename = args["transcript"]
  prefix = args["prefix"]
  if args["nymfile"]:
    with open(args["nymfile"], "r") as nym_file:
      nym_map = json.loads(nym_file.read())
  else:
    nym_map = {}

  out_base, out_ext = os.path.splitext(in_filename)
  out_filename = out_base + "-pseudonymized" + out_ext
  out_pseudonyms = out_base + ".nyms"

  pseudonym = PseudonymFactory(prefix, nym_map) # initialize the factory to make pseudonyms
  from_kw = "[Ff]rom"
  # privateMsg="Privately" - currently not handled
  directMsg="(Direct Message)"
  
  list_of_chat_items=[]

  chat_item=dict()              # empty chat item to use
  
  if Verbose_Flag:
    print("About to start processing the transcript")
  
  try:
    with open(in_filename, "r") as in_file, open(out_filename, "w") as out_file:
      inputLines=in_file.readlines()
      for line in inputLines:
        # check for the start of a chat item
        # these have the form: dd:dd:dd\t From  <sender> : msg
        # or                   dd:dd:dd\t From  <nsender> to <recipient> (Direct Message) : msg
          m0=re.match(timestamp_regex,line)
          if m0:
            if m0.start() == 0:
              timestamp=m0.group()
              if Verbose_Flag:
                print("timestamp={0}, line={1}".format(timestamp, line))
              remainder_of_line=line[m0.end():].strip()

              chat_item=dict()              # empty chat item to use
              chat_item['timestamp']=timestamp

              # check for From keyword
              fromMatch=re.match(from_kw, remainder_of_line)
              if not fromMatch:
                print("From keyword not found in line=".format(remainder_of_line))
                continue

              # there must always be a sender
              senderMatch = re.match(f"{from_kw} *([^:]*)", remainder_of_line)
              if not senderMatch:              
                print("sender not found in line=".format(remainder_of_line))
                continue

              possibleSender=senderMatch.group(1).strip()
              # here sender can include a "to xxxx" portion
              # now look a possible recipient
              # print("looking for recipient in sender={0}".format(sender))

              # look for "[Tt]o" keyword
              toKeywordFound=False

              toIndex1=possibleSender.find(" to ")
              toIndex2=possibleSender.find(" TO ")
              if toIndex1 > 0:
                sender=possibleSender[0:toIndex1].strip()
                possibeRecipient=possibleSender[toIndex1+5:].strip()
                toKeywordFound=True
              elif toIndex2 > 0:
                sender=possibleSender[0:toIndex2].strip()
                possibeRecipient=possibleSender[toIndex2+5:].strip()
                toKeywordFound=True
              else:
                sender=possibleSender
                possibeRecipient=None

              if Verbose_Flag:
                print("toKeywordFound={0} sender={1} possibeRecipient={2}".format(toKeywordFound, sender, possibeRecipient))

              if sender not in nym_map: # if the sender is not know, add a pseudonym for them
                if Verbose_Flag:
                  print("sender '{0}' not in nym_map".format(sender))
                nym_map[sender] = pseudonym.next()

              if not toKeywordFound: #  there is just a sender
                sender_offset=remainder_of_line.find(sender)
                remainder_of_line = remainder_of_line[(sender_offset+len(sender)):].strip()
                if remainder_of_line[0] == ':':
                  remainder_of_line = remainder_of_line[1:].strip()
                output_line="{0}\t{1}:\t:{2}".format(timestamp, nym_map[sender], remainder_of_line)

                if args["nonanonymous"]:
                  chat_item['sender']=sender
                else:
                  chat_item['sender']=nym_map[sender]

                chat_item['msg']=remainder_of_line
                list_of_chat_items.append(chat_item)

                print(output_line, file=out_file)
                continue

              # now look for recipient
              directIndex=possibeRecipient.endswith(directMsg)
              recipient=possibeRecipient[:len(directMsg)]
              if Verbose_Flag:
                print("recipient={}".format(recipient))

              directIndex2=remainder_of_line.find(directMsg)
              if directIndex2 > 0:
                remainder_of_line = remainder_of_line[(directIndex2+len(directMsg)):].strip()
                if remainder_of_line[0] == ':':
                  remainder_of_line = remainder_of_line[1:].strip()
                  msg=remainder_of_line.strip()
              else:
                msg=""

              if recipient not in nym_map:
                if Verbose_Flag:
                  print("recipient '{0}' not in nym_map".format(recipient))
                nym_map[recipient] = pseudonym.next()

              output_line="{0}\t{1}:{2}:{3}".format(timestamp, nym_map[sender], nym_map[recipient], msg)
              if args["nonanonymous"]:
                chat_item['sender']=sender
              else:
                chat_item['sender']=nym_map[sender]

              if args["nonanonymous"]:
                chat_item['recipient']=recipient
              else:
                chat_item['recipient']=nym_map[recipient]

              chat_item['msg']=remainder_of_line
              list_of_chat_items.append(chat_item)

              print(output_line, file=out_file)
              continue

            else:               # timestamp not starting in column 0
              #output_line="\t\t\t{0}".format(line.strip())
              output_line="{0}".format(line.strip())
              existing_msg=chat_item.get('msg', "")
              chat_item['msg']=existing_msg+'<br>'+output_line
              print(output_line, file=out_file)

          else:                 # just output lines that do not start with a timestamp
            #output_line="\t\t\t{0}".format(line.strip())
            output_line="{0}".format(line.strip())
            existing_msg=chat_item.get('msg', "")
            chat_item['msg']=existing_msg+'<br>'+output_line

            print(output_line, file=out_file)

  except FileNotFoundError as err:
    print(f"file not found: {err}", file=sys.stderr)
    return -1

  with open(out_pseudonyms, "w") as nym_file:
    print(json.dumps(nym_map, indent=2), file=nym_file)

  if Verbose_Flag:
    print("number of chat_items={}".format(len(list_of_chat_items)))

  in_base, in_ext = os.path.splitext(os.path.basename(in_filename))
  new_file_name="{1}-chat_for_course-{0}.html".format(course_id, in_base)

  page='<h2><a id="Chat">{0}</h3>'.format(in_base)
  page=page+'<table style="width:100%">\n<tr><th  width=10%>Timestamp</th><th width=15%>Sender</th><th width=15%>[Recipient]</th><th>Message</th></tr>'

  for i in list_of_chat_items:
    if Verbose_Flag:
      print("item={}".format(i))
    timestamp=i['timestamp']
    sender=i['sender']
    recipient=i.get('recipient', False)
    msg=i['msg']

    if recipient:
      new_item="<tr><td>{0}</td><td>{1}</td><td>{2}</td><td><pre>{3}</pre></td></tr>".format(timestamp, sender, recipient, msg)
    else:
      new_item="<tr><td>{0}</td><td>{1}</td><td></td><td><pre>{2}</pre></td></tr>".format(timestamp, sender, msg)
    page=page+new_item

  page=page+'</table>'
  # write out body of response as a .html page

  with open(new_file_name, 'wb') as f:
    encoded_output = bytes(page, 'UTF-8')
    f.write(encoded_output)

  desired_module_name=args["module_name"]
  existing_modules=list_modules(course_id, desired_module_name)

  module_id=None
  for m in existing_modules:
    if m['name'] == desired_module_name:
      module_id=m['id']
      print("module with this name exists with id={}".format(module_id))

  if not module_id:
    create_module(course_id, desired_module_name)
  
  desired_page_title=args["page_title"]
  if len(desired_page_title) < 1:
    desired_page_title=in_base.replace('_', '-')
  print("desired_page_title={}".format(desired_page_title))
  existing_pages=list_pages(course_id, desired_page_title)
  for p in existing_pages:
    if p['title'] == desired_page_title:
      page_id=p['page_id']
      print("page with this title exists with p={}".format(p))
      if args["remove_existing_page"]:
        delete_course_page(course_id, p['url'])
        print("removed existing page")
      else:
        desired_page_title="{}-new".format(desired_page_title)

  page_info=create_course_page(course_id, desired_page_title, page)
  if Verbose_Flag:
    print("page_info={}".format(page_info))

  if page_info:
    m2=create_module_page_item(course_id, module_id, page_info['page_id'], page_info['title'], page_info['url'])
    if m2:
      print("created page in module={}".format(m2))

if __name__ == '__main__':
  sys.exit(main(sys.argv[1:]))
